### ISSUE TITLE
MToon 1.0: Backfaces have flipped normals when double sided.

### ISSUE THREAD

**Issue by lyuma** [vrm-c/UniVRM#1022]
## Describe the bug

In MToon 1.0, if I set "Double Sided" to On, the back faces are using the normals of the front face. (So a skirt appears as if lit from below.)

MToon should add code to use VFACE or SV_IsFrontFace to display backface normals properly.

This bug is new to MToon 1.0, because the old MToon shader had a hack to flip normals which was incorrect. See also: https://github.com/Santarh/MToon/issues/56

## To Reproduce

1. Open a project with UniVRM installed.
2. Edit `Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon.shader` and remove `Hidden/` from the shader name, so it can be selected on a VRM 0.0 model.
3. Add AliciaSolid to the scene.
4. Rotate the Directional Light to X=90 so the light comes directly from above. Turn Shadows Off on the light.
5. Disable the `cloth1` and `cloth2` objects inside mesh in the hierarchy. (Alicia has both layers of the skirt as separate objects: disabling these objects allows us to simulate a single sided mesh)
6. Open AliciaSolid_vrm-0.51.Materials folder, and shift click all the materials. Change the shader to `VRM10/vrmc_materials_mtoon`
7. Select the alicia_wear material. Change Double Sided to On, and set Shade Color to black.

It will show the same shade of lighting on both the topside and the underside of the character's skirt.

## Expected behavior

Ideally, the underside of the clothing will be darkened, and the topside will be lit, because the light comes from up.

## Screenshots

If you follow the process above:
![image](https://user-images.githubusercontent.com/39946030/121632712-4fc09d00-ca36-11eb-9e20-ab5dd77709e4.png)

Here is a custom version of Alicia I made in Blender, to illustrate the problem more clearly:
![MToon 1.0 - Cull Off has wrong normals](https://user-images.githubusercontent.com/39946030/121631048-3407c780-ca33-11eb-83c2-fe21da8cdb87.png)

## Environments (please complete the following information):

 - OS: Windows 10
 - Unity version: Unity-2018.4
 - UniVRM version: latest master: be9220cb6c58e6b46016ea9481718b3cd2caf263

## Additional context

See my comment on the original MToon issue here: https://github.com/Santarh/MToon/issues/56#issuecomment-859257322

**Comment by Santarh** [comment]
Thanks your report.

Yes, I know this issue because MToon1.0 is now WIP and has not been released.
At this stage, I prioritize the implementation of ideal specifications over Unity-specific behavior.

I will work on it.

**Comment by Santarh** [comment]
I consider this VFACE fix on Unity 2017.4.28f1, too.
Because now UniVRM supports only Unity 2019.4 LTS or later ! :smile: :smile: :smile: :smile:  

https://github.com/Santarh/MToon/issues/56#issuecomment-859257322

**Comment by Santarh** [comment]
Fixed with #1024
