### ISSUE TITLE
[Discussion] Injecting VRM extensions into GLB and exporting it as VRM

### ISSUE THREAD

**Issue by srcnalt** [vrm-c/UniVRM#1025]
Hello, this is not a bug report, but I could not find any other medium I could discuss this. I apologize for that.

I am planning to automate GBL to VRM conversion using UniVRM, and even go as far as removing Unity and dependency on using GameObjects in this process.

I am working on 3D human models of a defined structure, in which mesh, polycount, textures change however name, structure, count of textures, blend shapes, bones, meshes etc are all the same. Working on such models leads me the think the extensions part of the json structure of the model will be similar for all the models. So rather than iterating over the game object, recalculating humanoid properties of the models every time can be reduced into injecting this part of the json into the file once it is generated from a sample model.

So the process would follow as:
- Import GLB
- Inject GLB related extensions
- Regenerate binaries and export to VRM

![process](https://user-images.githubusercontent.com/3163281/121770495-463c4f80-cb72-11eb-99e6-738abce6b7ab.png)

During this process no game objects will be instantiated. Loaded GLTF object will be modified and exported back again.

I used UniVRM 0.66.0 for importing the GLB however it breaks the mesh due to some bone count issue. So I could not have any success setting up the set of operations I wanted to make. I used GLTFUtility for loading but it will require writing a lot of adaptors to convert the GLTF objects from this to UniGLTF version, so I decided to delay this and look for other possible options I might be missing.

I also tried going for this operation in blender. 
- I imported the model, 
- exported it as gltf + texture + bin, 
- edited the gltf manually, 
- imported it into blender, then exported as glb. 

However extensions were lost in the result, probably since extensions were not mentioned in the binary - don't really know.
I also do not know if, due to texture and mesh size differences (size, polycount) binaries are referencing extensions area differently which might actually render the idea of injecting common JSON part to all the models useless.

I would really like to hear your ideas on this, and would like to know if I am missing something.

**Comment by infosia** [comment]
> I used UniVRM 0.66.0 for importing the GLB however it breaks the mesh due to some bone count issue.

@srcnalt Sounds like it's somewhat related to #741. UniVRM 0.66 doesn't support `UNSIGNED_BYTE` for joints and ends up breaking meshes & reporting bone count issue that does not really make sense. I saw some more issues importing GLB ( #742 #821 ) that's all fixed in the latest release so I hope updating UniVRM works for you too.

**Comment by srcnalt** [comment]
Thank you for the reply. I tried the latest 0.76 however I fail to find the option to import GLB files. Am I missing something.
![image](https://user-images.githubusercontent.com/3163281/122266517-8d17a580-cee2-11eb-8c03-4ec4ce3d3df2.png)

**Comment by infosia** [comment]
Not sure why they removed it but I can see that drag & drop glb file directly onto Asset folder works for me 😮

**Comment by Santarh** [comment]
Please see vrm-1.0 specification discussions at https://github.com/vrm-c/vrm-specification
vrm-1.0 specification is easier to achieve this than vrm-0.x.
