### ISSUE TITLE
UniVRM GUI Flickers and can't export

### ISSUE THREAD

**Issue by DayDark288** [vrm-c/UniVRM#1026]
UniVRM's GUI Flickering when the cursor hovers in (sometimes randomly) and Unable to export model

Can't reproduce

## Expected behavior:

GUI Shouldn't flicker and can export

## Screenshots

![image](https://user-images.githubusercontent.com/70122416/121843646-4032a400-cd15-11eb-89b5-ba5f4af163ff.png)

 - OS: Windows 10
 - Unity version: Unity-2020.3.7f1
 - UniVRM version: 0.66.0`

## Additional context

NullReferenceException: Object reference not set to an instance of an object
ArgumentException: Getting control 0's position in a group with only 0 controls when doing repaint

**Comment by KanaFuyuko** [comment]
The way I fixed this was I went to the Blendshape animation component where you have the blendshape buttons, Select a blendshape, scroll down and select the second tab named "Blendshape List" and then click the plus button and then remove it and it would stop flickering with me. Sometimes you might get a message about the blinks which just check to make sure they are set properly and done.

**Comment by ousttrue** [comment]
Please report again when it is reproduced.
