### ISSUE TITLE
Head look at not work

### ISSUE THREAD

**Issue by orangeagain** [vrm-c/UniVRM#1035]
## Describe the bug

eye look at work.
head look at not work

## To Reproduce

use vrm view scene to open a vrm file, move looktarget, eye moved, head not move.

## Environments (please complete the following information):

VRM version 0.66 and 0.76

## Additional context
There two warrning below:
`The referenced script (Unknown) on this Behaviour is missing!`
`The referenced script on this Behaviour (Game Object 'LookAtTarget') is missing!`

**Comment by Santarh** [comment]
Thanks your issue.
In VRM, `VRMLookAtHead` component provides eye movement function.
It doesn't provide head bone movement function.
It may be a misleading name...

https://vrm.dev/en/docs/univrm/lookat/
