### ISSUE TITLE
Blendshape breaking lighting and material

### ISSUE THREAD

**Issue by MattoRyu** [vrm-c/UniVRM#1093]
When using blendshape, the lighting and materials change to a more shiny version. The shading becomes off. 

![image](https://user-images.githubusercontent.com/86881991/124356445-5d45fd00-dc59-11eb-9d2a-7c787d2a113a.png)
![image](https://user-images.githubusercontent.com/86881991/124356394-2a036e00-dc59-11eb-8897-59ab1263616c.png)
![image](https://user-images.githubusercontent.com/86881991/124356377-16580780-dc59-11eb-9704-da36a0e0b8ae.png)
![image](https://user-images.githubusercontent.com/86881991/124356431-4e5f4a80-dc59-11eb-8d17-bc899d928e3a.png)

**Comment by GreenCapComix** [comment]
I have seartched a lot about it, and the only temporary solution I´ve found is, in Blender, you scale the model 5 times, apply transform, and then you export the fbx file.
Why 5 times? I don´t know, but it works.

This is where I´ve found the solution.
[](https://forum.unity.com/threads/problem-artifacts-on-surface-of-character-model-when-blendshapes-via-blender-are-present.250279/)

**Comment by ousttrue** [comment]
Please check #828
