### ISSUE TITLE
インストールできない

### ISSUE THREAD

**Issue by YusukeMasuda36** [vrm-c/UniVRM#1097]
https://github.com/keijiro/KlakNDI
これにUniVRMをインストールすると失敗してしまいます。

対処法をご教授頂けないでしょうか

## 環境情報

 - OS: Windows 10
 - Unity version:Unity2019.4`]
 - UniVRM version: v0.78.0
 - https://github.com/keijiro/KlakNDI

**Comment by ousttrue** [comment]
ええと、もう少し詳しく。

Unity のコンソールを見て、そこにエラーがあるかどうかをご確認ください。

https://vrm.dev/docs/univrm/

その際に見つかったエラーメッセージを issue に添えてください。

**Comment by YusukeMasuda36** [comment]
このようなエラーが出ています

![スクリーンショット 2021-07-16 120515](https://user-images.githubusercontent.com/65877590/125885502-d4dad285-530c-4dec-9cc5-a86b90835122.png)

**Comment by ousttrue** [comment]
`UniVRMをインストールする` がうまくできていないと思われます。

まず、 `UniVRM` アンインストールした状態で赤いメッセージがコンソールに出ないことを確認してください。
https://vrm.dev/docs/univrm/install/univrm_uninstall/

そのあとで、
https://github.com/vrm-c/UniVRM/releases/download/v0.78.0/UniVRM-0.78.0_851b.unitypackage
を使ってインストールしてください。
