### ISSUE TITLE
VRChat用に設定したVRoidモデルを再度VRMに変換する時にエラーが出て失敗する

### ISSUE THREAD

**Issue by Velocity37564** [vrm-c/UniVRM#1100]
## バグについて

VRChat用に設定したVRoidモデルを再度VRMに変換する時にエラーが出て失敗する

## 再現方法

1.VRM0のExportUniVRMをクリック
2.必須項目を入力しExportをクリック
3.下記のエラーが出て失敗する

ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
VRMShaders.EditorTextureSerializer.CanExportAsEditorAssetFile (UnityEngine.Texture texture, VRMShaders.ColorSpace exportColorSpace) (at Assets/VRMShaders/GLTF/IO/Editor/EditorTextureSerializer.cs:46)
VRMShaders.TextureExporter.ExportAsSRgb (UnityEngine.Texture src) (at Assets/VRMShaders/GLTF/IO/Runtime/TextureExporter.cs:73)
UniGLTF.MaterialExporter.Export_Color (UnityEngine.Material m, VRMShaders.ITextureExporter textureManager, UniGLTF.glTFMaterial material) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/MaterialExporter.cs:41)
UniGLTF.MaterialExporter.ExportMaterial (UnityEngine.Material m, VRMShaders.ITextureExporter textureExporter) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/MaterialExporter.cs:24)
UniGLTF.gltfExporter+<>c__DisplayClass35_0.<Export>b__2 (UnityEngine.Material x) (at Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs:239)
System.Linq.Enumerable+SelectListIterator`2[TSource,TResult].ToList () (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
UniGLTF.gltfExporter.Export (UniGLTF.MeshExportSettings meshExportSettings, VRMShaders.ITextureSerializer textureSerializer) (at Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs:239)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings, System.Collections.Generic.List`1[T] destroy) (at Assets/VRM/Editor/Format/VRMEditorExporter.cs:229)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings) (at Assets/VRM/Editor/Format/VRMEditorExporter.cs:24)
VRM.VRMExporterWizard.ExportPath (System.String path) (at Assets/VRM/Editor/Format/VRMExporterWizard.cs:275)
UniGLTF.ExportDialogBase.EndGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:161)
UniGLTF.ExportDialogBase.OnGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:82)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <bd70c40e01f641bdb7d836e1e97755bc>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <bd70c40e01f641bdb7d836e1e97755bc>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <bd70c40e01f641bdb7d836e1e97755bc>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <bd70c40e01f641bdb7d836e1e97755bc>:0)
UnityEditor.DockArea.OldOnGUI () (at <bd70c40e01f641bdb7d836e1e97755bc>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <a6a8a08b59d34373858eada2d852ad38>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <023156577e4f4156adf0f4b3a3fedf85>:0)

## 期待する動作

VRM出力の成功

## 環境情報

 - OS: [`Windows 10`]
 - Unity version: [`Unity-2018.4` `Unity-2019.4`]
 - UniVRM version: [`0.70.0` `0.78.0`]

## 追加の状況・背景

1.服やアクセサリーなどを着せ替え用のツールで着せています。
名前が重複しているボーンはHips_Jucketのように名前を変更しています。
2.Unityプロジェクト内のテクスチャファイルを直接CLIP STUDIOで編集し、上書き保存をしています。
同じ手順を踏んだモデルで成功するものと失敗するものがあります。

**Comment by ousttrue** [comment]
https://github.com/vrm-c/UniVRM/blob/master/Assets/VRMShaders/GLTF/IO/Editor/EditorTextureSerializer.cs#L46

**Comment by ousttrue** [comment]
失敗するモデルのマテリアルに未対応のテクスチャーが設定されているようです。

![textureType](https://user-images.githubusercontent.com/68057/125745481-7888cd25-a4f0-4ae6-973b-22af28e53a94.jpg)

該当するものが分かれば Default に設定して再度エクスポートしてみてください。

**Comment by ousttrue** [comment]
TODO: エクスポートが失敗するのではなく、未対応テクスチャが有るのでエクスポートできないというメッセージを出す

**Comment by Velocity37564** [comment]
ありがとうございます、無事出力できました。

**Comment by ousttrue** [comment]
#1102 でメッセージ追加
