### ISSUE TITLE
Namespace "VRM" can't be found by any other script.

### ISSUE THREAD

**Issue by LucaBGt** [vrm-c/UniVRM#1103]
## バグについて

Using the namespace or trying to add a script to the namespace "VRM" results in an error about that the namespace "can not be found".

## 再現方法

例: 動作の再現させる手順:

1. Create a new script or import a scirpt (I did the VFS_SDK)
2. See the error: _Assets/[...]: error CS0246: The type or namespace name 'VRM' could not be found (are you missing a using directive or an assembly reference?)_

動作を再現できる最小の例(モデルファイルなど)がある場合は、このissueに添付してください。

I don't know why the namespace isn't visible to some scripts and not to others. I can't think about any reason this shouldn't work.

期待する動作を明確かつ簡潔に記述してください。

## スクリーンショット

-

## 環境情報

Mac OSX Big Sur 11.2.3
Unity 2020.3.5f1, also tried in 2019.4.1f1
UniVRM version 0.78.0_58b

## 追加の状況・背景

This issue came up while trying to use the **VSF_SDK**, but no script outside of the UniVRM scripts could access the namespace.

**Comment by yahagi-day** [comment]
VRM/Runtime/VRM(Assembly Definition Asset)のAutoReferencedにチェックを入れると解決します。
私はadfについて詳しくないためこの方法が最善であるかはわかりません。
@ousttrue 

![image](https://user-images.githubusercontent.com/32870950/126061675-80085f8e-1773-4668-b2c4-8379b6b3cfde.png)

**Comment by yahagi-day** [comment]
多くの場合Assembly-CSharpから参照するのでAuto Referencedはデフォルトでtrueであるべきに見えます

**Comment by LucaBGt** [comment]
Thank you!
This was the correct solution.
The setting was not automatically enabled, though.

**Comment by Santarh** [comment]
Some asmdef files has been set `Auto Referenced`` true` since v0.79.0 !
