### ISSUE TITLE
Make asmdef's `Auto Referenced` `true` .

### ISSUE THREAD

**Issue by Santarh** [vrm-c/UniVRM#1107]
Pre-Release にもかかわらず、想定していたよりも多くのユーザが asmdef の設定に関して躓いていたので asmdef を厳格に管理しない方向に倒す。

https://github.com/vrm-c/UniVRM/issues/993
https://github.com/vrm-c/UniVRM/issues/1103

**Comment by ousttrue** [comment]
`Assets/VRM.Samples/VRM.Samples.asmdef` 消してもコンパイルが通った(AutoReferenceが効いている)
