### ISSUE TITLE
editor export VRM is different from runtime export VRM

### ISSUE THREAD

**Issue by marcusx2** [vrm-c/UniVRM#1112]
I was having a problem that the skinned mesh renderers were clipping through the model using the runtime export method for VRM. However, I wasn't having the problem when exporting with the editor. I solved the issue by basically replacing the runtime code with the editortime code to have the same code running, and it worked. Now, I am not a specialist or anything, I can't give more details than this. It's something I think you guys should investigate. Thank you for the asset by the way, it works wonders!

**Comment by ousttrue** [comment]
I've added an example of performing model normalization to the Runtime export sample.

https://github.com/vrm-c/UniVRM/pull/1119/files#diff-fdea351931d90d1e57fd9ae008ea2e49c5a5359a41fa8f5290c4cd66afdf7c8eR113-R127

**Comment by Santarh** [comment]
Please see vrm-1.0 specification discussions at https://github.com/vrm-c/vrm-specification
vrm-1.0 specification is easier to achieve this than vrm-0.x.
