### ISSUE TITLE
export VRM with animation clip at runtime

### ISSUE THREAD

**Issue by marcusx2** [vrm-c/UniVRM#1113]
Is this possible? It seems that the model is exported to VRM without the animation clip attached to the animator. I found some code that deals with AnimationClip at gltfExporter.cs, but only at editortime, not runtime. So exporting VRM at runtime with animation clips is not supported? Will it ever be? Thank you for your time.

**Comment by Santarh** [comment]
Thanks your issue.
Unfortunately, no, we can't export `AnimationClip` at runtime.
Because Unity doesn't provide the TRS information in `AnimationClip` at runtime.

> Unity internally combines position curves, scale curves, and rotation curves.
https://docs.unity3d.com/ScriptReference/AnimationUtility.GetEditorCurve.html
