### ISSUE TITLE
[0.77]AsyncでランタイムロードしたモデルのScaleを1以上にするとSpringBoneの動作が怪しくなる

### ISSUE THREAD

**Issue by Yukakiri0213** [vrm-c/UniVRM#1115]
## バグについて

こちら(https://vrm.dev/docs/univrm/programming/runtime_import/) のページを参考にランタイムロードを行わせていただいているのですが、非同期ロードである RuntimeGltfInstance instance = await context.LoadAsync(); を利用してロードを行ったモデルのScaleを1以上にするとSpringBoneが破綻します。

利用したスクリプト：
[LoadVRM.txt](https://github.com/vrm-c/UniVRM/files/6875234/LoadVRM.txt)
利用モデル：(https://3d.nicovideo.jp/works/td32797)

## 期待する動作

AsyncでランタイムロードしたモデルのScaleを1以上にしてもSpringBoneが怪しい動きをしなくなると助かります。
もし私のミスやおま環でしたら申し訳ありません。

## スクリーンショット

上の画像が同期ロード時(正常)、下の画像が非同期ロード時の画像です。どちらもScaleは5.0にしてあります。

<img width="1440" alt="スクリーンショット 2021-07-26 11 38 03" src="https://user-images.githubusercontent.com/52926422/126925612-9c0a0094-1065-4639-a090-8fcc5efbb8b6.png">
<img width="1440" alt="スクリーンショット 2021-07-26 11 38 33" src="https://user-images.githubusercontent.com/52926422/126925616-ea888db1-f271-4417-b3da-5c94a6c8a570.png">

## 環境情報

 - OS: MacOS11.4、Windows 10(どちらの環境でも確認)
 - Unity version: Unity-2019.4.28
 - UniVRM version: 0.77.0

**Comment by ousttrue** [comment]
SpringBone の初期化が `Start` や `Awake` によるからと思われる(AddComponent直後)。
LoadAsync が終わってスケールの適用が終わるまで SpringBone の初期化を阻止する必要がありそう。

* `StartSpringBone` 関数を追加する
* or `ShowMeshes`  に SpringBone 開始機能を入れちゃう？
* or `LoadSpringBone` 関数を分離する

**Comment by ousttrue** [comment]
実験した結果、prefab を シーンに展開してスケールを 5 にした場合もうまく行かないことがわかりました。

原因は、 `async` ではなくスケールの取り扱いロジックの方にありそうです。
別の方法を調査。

**Comment by ousttrue** [comment]
原因は、 `VrmSpringBone.Awake` で初期化しているのでスケールが後から変わることに対応できないことでした。

スケール変更後に以下のコードで再初期化をお試しください。
```cs
foreach (var spring in root.GetComponentsInChildren<VRMSpringBone>())
{
    spring.Setup();
}
```

**Comment by ousttrue** [comment]
いったんクローズします。上記の対応では不十分で、初期化方法の変更が必要な場合はリオープンしてください。

* 初期化タイミングを `Awakeより後ろ` かつ `T-Pose 以外のモーションが投入される前` にする必要があり、迂闊に変えると既存のアプリの挙動に影響が出る可能性があるかもしれない
