### ISSUE TITLE
URPサンプルプロジェクトへのインポート時にビルドエラーが出る

### ISSUE THREAD

**Issue by tsujimaru99** [vrm-c/UniVRM#1137]
## バグについて

URPのプロジェクトテンプレートにUniVRMをImportするとビルドエラーとなりビルドができません。メッセージは下記の通りです。

> Error building Player: Shader error in 'VRM10/MToon10': undeclared identifier 'i' at Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_forward_fragment.hlsl(48) (on d3d11)

※上記メッセージはUnity 2019.4.29 × UniVRM 0.79の組み合わせのものです。
※vrmc_materials_mtoon_forward_fragment.hlsl　48行目の記述内容は以下です。

> UNITY_APPLY_FOG(i.fogCoord, col);　

## 再現方法

1. UnityHubよりプロジェクトテンプレート「URP」を選択してサンプルシーンを生成
2. unitypackageにてUniVRMをインポート
3. ビルドする
4. エラーメッセージ表示

## 期待する動作

URPでのUniVRMの利用
→プロジェクト側で回避すべき問題であればご指摘ください。

## スクリーンショット

![bugreport_uniVRM_20210809](https://user-images.githubusercontent.com/88624900/128638000-e542d07d-02bd-4b78-8d7a-29ea822d8f82.png)

## 環境情報

 - OS: [`Windows 10`]
 - Unity version: [`Unity-2019.4.29` / `Unity-2020.3.14f1`]
 - UniVRM version: [`0.66` / `0.78` / `0.79`]

## 追加の状況・背景

vrmc_materials_mtoon_forward_fragment.hlsl
の該当箇所を見てみましたが、自力での解決が不可能でした・・

**Comment by ousttrue** [comment]
#368

**Comment by tsujimaru99** [comment]
ビルドするまでは問題なく動いていたので、UniVRMがURP未対応と気付きませんでした。検索が足らず失礼しました、、
