### ISSUE TITLE
What difference between "UniVRM0X" and "UniVRM10" unitypackage? 「UniVRM0X」と「UniVRM10」のユニティパッケージの違いは何ですか？

### ISSUE THREAD

**Issue by orangeagain** [vrm-c/UniVRM#1152]
Which one I should use, can anyone explanin this?
Thanks first.

どちらを使うべきですか、誰かがこれを説明できますか？
前もって感謝します

**Comment by ousttrue** [comment]
Add unitypackage contents table.
https://github.com/vrm-c/UniVRM/releases/tag/v0.80.0

`UniVRM0X-*.unitypackage` is basic package.
