### ISSUE TITLE
no import menu

### ISSUE THREAD

**Issue by takutosama** [vrm-c/UniVRM#1162]
## Environments (please complete the following information):

 - UniVRM version: 0.80.0
 - Unity version: Unity-2020.2.7f1
 - OS:WIndows 10 64bit

![image](https://user-images.githubusercontent.com/53239913/130246075-9a8e1553-79bc-41e8-afd3-78867f6db69e.png)

i was importing the univrm pack and after its imported,
the import menu didn't pop up and this shows up in the console

**Comment by ousttrue** [comment]
Thank you for your report.
The yellow message is a warning and the installation was successful.

Please try dropping the file onto the asset for import.

**Comment by ousttrue** [comment]
Restored gltf import menu. `v0.84.0`
