### ISSUE TITLE
MToon shader not supporting single pass VR rendering

### ISSUE THREAD

**Issue by smitdylan2001** [vrm-c/UniVRM#1163]
## Environments (please complete the following information):

 - UniVRM version: 0.63
 - Unity version: Unity 2020.3.15f2
 - OS: Windows 10

## Describe the bug

* A clear and concise description of what the bug is.
MToon shader/material does not work in VR using single pass/multiview. 
It renders on one eye and does not render on the other. This can be fixed within the shader for Unity

* Reproduction procedure
- Start VR project
- Import UniVRM
- Put VR rendering at single pass/multiview
- Put in a model

* File that causes an error (those that can be pasted here)
MToon shaders/materials

**Comment by Santarh** [comment]
This issue was fixed in v0.77.0 and later.
