### ISSUE TITLE
Runtime Exporter Sample

### ISSUE THREAD

**Issue by bhehy001xamk** [vrm-c/UniVRM#1185]
Hi,
the samples link in the read.me file does not work. 

The program works well, but I would like to get a script that could, for example, press a button in runtime mode to export an object. Is this possible?

**Comment by ousttrue** [comment]
Runtime Exporter sample is there.

<https://github.com/vrm-c/UniVRM/tree/master/Assets/VRM/Samples/RuntimeExporterSample>

I will update documentaion.

**Comment by ousttrue** [comment]
`Assets/VRM_Samples/RuntimeExporterSample/VRMRuntimeExporter.cs` is runtime export sample.

https://vrm-c.github.io/UniVRM/en/vrm0/sample/RuntimeExporterSample.html
