### ISSUE TITLE
Download question for version 0.82.1

### ISSUE THREAD

**Issue by Caldoric** [vrm-c/UniVRM#1208]
so, i see that the listing for the latest downloadable public version of this has three main unity package files available for download, but it only says to download two of them. what's the purpose of the third listed package?

the third package in question is listed as "VRM-0.82.1_1413.unitypackage", for clarification.

**Comment by breadnone** [comment]
That is if you want to convert it to URP

**Comment by ousttrue** [comment]
VRM pacakge is `vrm-1.0beta`.

Added the contents of each package.
https://github.com/vrm-c/UniVRM/releases/tag/v0.83.0

**Comment by ousttrue** [comment]
Currently, the latest release page has the following table.

<table>
<tr><th>unitypackage</th><th>folder</th><th>contents</th></tr>
<tr>
    <td rowspan="2">UniGLTF_VRMShaders</td>
    <td>Assets/VRMShaders</td>
    <td>UniUnlit, MToon, MToon10, MaterialTexture Import/Export etc</td>
</tr>
<tr>
    <td>Assets/UniGLTF</td>
    <td>UniGLTF<br>(require VRMShaders)</td>
</tr>
<tr>
    <td>UniVRM</td>
    <td>Assets/VRM</td>
    <td>UniVRM<br>(require UniGLTF_VRMShaders)</td>
</tr>
<tr>
    <td>VRM</td>
    <td>Assets/VRM10</td>
    <td>VRM-1.0beta<br>(require UniGLTF_VRMShaders)</td>
</tr>
</table>
