### ISSUE TITLE
Extracting Materials from VRM1 (URP) Will Spawn Unwanted Prefab

### ISSUE THREAD

**Issue by breadnone** [vrm-c/UniVRM#1210]
## 環境情報

 - UniVRM version: `0.82.1`
 - Unity version: `Unity-2020 LTS
 - OS: `Windows 10`

Extracting materials resulted in re-spawning unwanted prefab 

![image](https://user-images.githubusercontent.com/64100867/132747762-b2445b90-eff8-4016-9c48-a72899759f4a.png)

**Comment by ousttrue** [comment]
Thank you for reporting.
Processing may be interrupted due to an error during import.
# 1232 may be related.
If you get this error in the latest version, please submit the console log.

**Comment by Santarh** [comment]
The discussion has stopped for a long time, so I will close it.
If you have any problems, please comment again.
