### ISSUE TITLE
URP implementation status

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/UniVRM#1214]
# Import

| GLTF material | runtime import         | editor import          |
|---------------|------------------------|------------------------|
| default PBR   | OK `v0.82.1`           | OK `v0.82.1`           |
| unlit         | OK `v0.82.1`           | OK `v0.82.1`           |
| MToon         | not | not                    |
| MToon10       | WIP. `v0.112` | WIP. fallback to unlit |

VRM-0.X のモデルで URP MToon を利用したい場合は、
VRM-1.0 として Migration Import することで代替できる予定です。

## TODO:

* [ ] how to load user-defined shader

https://github.com/simplestargame/ShaderGraphsMToonForURPVR

# export
No plans for now

**Comment by breadnone** [comment]
The default implementation for https://github.com/simplestargame/ShaderGraphsMToonForURPVR is double-sided, which most of the time, won't be needed in pre-generated models in vroid. Perhaps, exposing the option for end-users to toggle it off?

Also, as I've mentioned here https://github.com/vrm-c/UniVRM/issues/368 it doesn't have a proper custom lightings to negate the exposure of lights, which very important to achieve the stylized toon style, the models will be very bright and the accuracy of the colors will be lost.

Thank you and appreciated for your hard work

**Comment by ousttrue** [comment]
There is no active task, so close it.
