### ISSUE TITLE
it might not be a bug but i can't import the package

### ISSUE THREAD

**Issue by NamiAthena** [vrm-c/UniVRM#1238]
Hello there, i've used UniVRM before with no problems at all, after changing computers and downloading the new version of UniVRM, i wasn't able to use the package because of the following errors;

![image](https://user-images.githubusercontent.com/91122766/134145753-82ff5cbf-970c-406e-92b4-0945f2730970.png)

i tried everything in my knowledge to find whats wrong, i tried different unity verisons, different univrm versions but i couldn't fix the issue

Unity version 2019.4.30f1
UniVRM verison 0.83
Windows 10

**Comment by ousttrue** [comment]
Thank you for reporting.
The UniGLTF_VRMShaders unitypackage may not be installed.
Recent versions require two Unity packages.

Please see https://github.com/vrm-c/UniVRM/releases

**Comment by NamiAthena** [comment]
I wasn't trying to use the UniGLTF_VRMShaders unitypackage, I was trying to
install UniVRM itself, i tried the 0.70.0 Version (i saw another threat by
someone who had the same problem with me and someone said they should try
to use the 0.70.0 version and they said it worked so i gave it a try) and
it actually worked out just fine!

ousttrue ***@***.***>, 24 Eyl 2021 Cum, 13:35 tarihinde şunu
yazdı:

**Comment by ousttrue** [comment]
It is divided into two packages from `v0.81`. When you make a new one, please install two.
