### ISSUE TITLE
GLTF Exporter window OnGUI lockup with big models

### ISSUE THREAD

**Issue by TheXRMonk** [vrm-c/UniVRM#1240]
## Environments (please complete the following information):

 - UniVRM version: `0.81.0`
 - Unity version: `Unity-2020.3.11f1`
 - OS: `Windows 10`

## Describe the bug

Trying to export a big model (~2 million polys) makes the window very unresponsive. You can still press export and the process works fine, it just takes a very long time, and there's no progression feedback other than the time passed since ongui.mouseup locked the editor.

**Comment by ousttrue** [comment]
Thank you for reporting.
Consider implementing progressive feedback.

**Comment by ousttrue** [comment]
`v0.94.0`
