### ISSUE TITLE
Unity 2021.1へUPMで導入するとコンソールへ警告が表示される

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#1245]
## 環境情報

 - UniVRM version: `0.84.0`
 - Unity version: `Unity-2021.1.22f1`
 - OS: `Windows 10`

## バグについて

* バグの内容  
   Unity 2021.1.22f1へUPMで導入すると、コンソールへ複数の警告が表示される
* ConsoleLog (1つ目)  
   > Script 'Packages/com.vrmc.gltf/Samples/ScreenSpace/ScaleOffset.cs' will not be compiled because it exists outside the Assets folder and does not to belong to any assembly definition file.
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline (UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,string[])
* スクリーンショット  
  ![image](https://user-images.githubusercontent.com/3625160/134763599-27cb187e-595a-4137-93b7-216a81a3c3c7.png)
* 再現方法
  1. Unity 2021.1.22f1で新規プロジェクトを作成する
  2. Packages/manifest.jsonのdependenciesへ以下を挿入
     > "com.vrmc.vrmshaders": "https://github.com/vrm-c/UniVRM.git?path=/Assets/VRMShaders#v0.84.0",
     > "com.vrmc.gltf": "https://github.com/vrm-c/UniVRM.git?path=/Assets/UniGLTF#v0.84.0",
     >"com.vrmc.univrm": "https://github.com/vrm-c/UniVRM.git?path=/Assets/VRM#v0.84.0",

**Comment by ousttrue** [comment]
報告ありがとうございます。
`Samples` フォルダの挙動が変わったかもしれないです。

**Comment by ousttrue** [comment]
各 Sample に asmdef を追加。

**Comment by ousttrue** [comment]
`v0.85.0`

**Comment by esperecyan** [comment]
@ousttrue 対応ありがとうございます。v0.85.0で上記の警告は出なくなりましたが、代わりに下記の警告が出るようになりました。

> A meta data file (.meta) exists but its folder 'Packages/com.vrmc.univrm/Samples/SpringBone' can't be found, and has been created. Empty directories cannot be stored in version control, so it's assumed that the meta data file is for an empty directory in version control. When moving or deleting folders outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.

![](https://user-images.githubusercontent.com/3625160/135392375-322ac514-73dd-4916-831b-fad5e0a076ec.png)
