### ISSUE TITLE
スタンドアロン版や3DCGソフト向けのエクスポーターの制作予定は？

### ISSUE THREAD

**Issue by Bancho29** [vrm-c/UniVRM#128]
ゲームやツールを制作するような人はともかく、わざわざVRM形式を出力するため「だけ」にUnityをインストールするのは気が引けるので、スタンドアロン版のUniVRMを公開できないでしょうか?

また、「Blender」「メタセコイア」「xismo」とか言った3DCGソフトのユーザーが1からVRMデータを制作できるように、公式のエクスポータープラグインも公開できないでしょうか?
（現に「MAYA」用のエクスポータープラグインが公開されています。
（ https://kashika.co.jp/product/vrmexporter/index.html ）
また、Blender用のVRM_IMPORTER（ https://github.com/iCyP/VRM_IMPORTER ）でもエクスポート機能がありますが、現状は不安定です）

要望を言いっぱなしで申し訳ありません。

**Comment by hiroj** [comment]
今のところありません、spec-1.0が確定した後に改めて検討致します。

**Comment by FujiSunflower** [comment]
こちらOpenの方が良いのでは。
