### ISSUE TITLE
Error I get when trying to export my model.

### ISSUE THREAD

**Issue by ItsFoxxxy** [vrm-c/UniVRM#1304]
## Environments (please complete the following information):

 - UniVRM version: `0.86.1`
 - Unity version: `Unity-2020.3`
 - OS: `Windows 10`

## Describe the bug
Everything seems fine until this point, any help appreciated. (Only the first error)
![Screenshot_2](https://user-images.githubusercontent.com/92508364/137266382-abdabd34-8fad-4129-8e98-0465c68bd8f1.png)

**Comment by Santarh** [comment]
The discussion has stopped for a long time, so I will close it.
If you have any problems, please comment again.
