### ISSUE TITLE
VRM Tab not showing Error

### ISSUE THREAD

**Issue by Philippinetizen** [vrm-c/UniVRM#1329]
don't know the main cause but it says the following

1.) Assets\VRM\Runtime\FastSpringBone\Blittables\BlittableTransform.cs(54,39): error CS1061: 'TransformAccess' does not contain a definition for 'localToWorldMatrix' and no accessible extension method 'localToWorldMatrix' accepting a first argument of type 'TransformAccess' could be found (are you missing a using directive or an assembly reference?)

2.) Assets\UniGLTF\Samples\ScreenSpace\ScaleOffset.cs(20,18): warning CS0649: Field 'ScaleOffset.Gltf' is never assigned to, and will always have its default value null

3.) Assets\UniGLTF\Samples\ScreenSpace\ScaleOffset.cs(17,18): warning CS0649: Field 'ScaleOffset.Unity' is never assigned to, and will always have its default value null

Unity version: 2019.27f2
UniVRM version: UniVRM-0.87.0_9425

**Comment by Santarh** [comment]
The discussion has stopped for a long time, so I will close it.
If you have any problems, please comment again.
