### ISSUE TITLE
Blend shape normals broken after VRM export

### ISSUE THREAD

**Issue by KatiKnitt** [vrm-c/UniVRM#1354]
## Environments

 - UniVRM version: `0.87.0`
 - Unity version: `Unity-2019.4.31f1`
 - OS: `Windows 10`

## Describe the bug

Hi, I wanted to bring up an already mentioned bug again, since it is still an issue. https://github.com/vrm-c/UniVRM/issues/597 https://github.com/vrm-c/UniVRM/issues/415

Normals on blendshapes are wrong whenever I export to VRM. However, [the main fix provided](https://vrm.dev/en/docs/univrm/blendshape/check_blendshape_normal/#fix-blendshape-normal) , ticking the box for `Legacy Blend Shape Normals` does not solve the issue.

I tried out all combinations for normals too, setting it to import or calculate and exported to fbx from blender with different settings. I also used the MToon shader. There's always some kind of normal error on the shapekeys, even if it looks right in Unity before and `Legacy Blend Shape Normals` is ticked.

With some settings the blendshapes just use the normals of the resting position of the mesh, with only the most extreme shape keys looking wrong as a result.
![Normal Shapekeys some corrupted](https://user-images.githubusercontent.com/26291274/139280689-4d8bddea-b5f2-44a9-8ca4-e2aaa7dd8f47.jpg)
In this case the error already exists in Unity before export. The imported fbx has no smoothing groups and the normals are set to `Import` and `Legacy Blend Shape Normals`. I get an ImportFBX Warning stating `Can't generate normals for blendshape on mesh 'Wallace_Head', mesh has no smoothing groups.`

Some settings will destroy the blendshapes for every shape key. 
![Normal Shapekeys all corrupted](https://user-images.githubusercontent.com/26291274/139280846-95fee482-a1fd-40b0-8b2b-5bbce8043ebe.jpg)
In my latest settings, the fbx does have smoothing groups, the normals are set to `Import` and `Legacy Blend Shape Normals`. I get no ImportFBX Warning and the normals on the imported fbx look right in Unity. They look wrong on every blendshape after I export to VRM.

Here's a link to both fbx files. They are exported from blender. 
[fbx without smoothing groups](https://drive.google.com/file/d/1sZ0jYoMKdBqOFL6PTPHccXDnw0VZu5ov/view?usp=sharing)
[fbx with smoothing groups](https://drive.google.com/file/d/1AFmFaFMto3-95JuJyMSi8XJIN7RVJsPf/view?usp=sharing)

**Comment by ousttrue** [comment]
Will be fixed in `v0.89`
