### ISSUE TITLE
Unity 2021.2 Invisible Model (VRM 1)

### ISSUE THREAD

**Issue by breadnone** [vrm-c/UniVRM#1359]
## 環境情報

 - UniVRM version: `0.88.0`
 - Unity version: `Unity-2021.2`
 - OS: `Windows 10`

The imported model becomes invisible after VRM 1 Migration in Unity 2021.2 and no error/warning logs shown. This issue does not appear in Unity 2020.  

The invisibility issue also appears in the newly created project in Unity 2021.2.  

![image](https://user-images.githubusercontent.com/64100867/140292069-1c06df79-f781-46a0-a605-a23078e8809f.png)

**Comment by ousttrue** [comment]
Thank you for reporting.
An exception may have occurred before showMesh.

**Comment by ousttrue** [comment]
The problem could not be reproduced.
Is the model loaded by Runtime or Editor (Asset)?
For Runtime, check the `instance.ShowMeshes ()` call.

**Comment by breadnone** [comment]
Turns out, the model was corrupted when exported from Vroid (vroid v1.0). Newly created model fixed the issue.

Closing this
