### ISSUE TITLE
VRMAvatar not showing in prefab after import (Following new Vroid update)

### ISSUE THREAD

**Issue by Sunflowerskies** [vrm-c/UniVRM#1367]
## Environments (please complete the following information):

 - UniVRM version: `0.53.0_6b07`
 - Unity version: `Unity-2020.3.21f1`
 - OS: `Windows 10`

## Describe the bug

* ConsoleLog alerts there there is no Animator.Avatar but in does not provide the option for VRMAvatar in prefab data. 

![model newnovrmavatar](https://user-images.githubusercontent.com/83678988/140823882-e7bd73c6-4471-4ef1-8edc-8e3dafe8875e.PNG)
![oldmodelvrmavatar](https://user-images.githubusercontent.com/83678988/140823895-e7534fe8-84d6-4513-bc3a-572922fbc96a.PNG)

This seems to have started occurring after the new Vroid update. I have imported and old and new project. The old project seems to have the VRMAvatar but the new only seems to contain Meta. 
I'd like to note that the new model is newly updated with the new VRoid software and has been modified. The old model has not be modified in the slightest. 

Most likely seems to be caused by the new Vroid update.

**Comment by ousttrue** [comment]
Thank you for reporting.

There may be some exceptions.
Paste the console log here.

Use a newer version as much as possible.
<https://vrm-c.github.io/UniVRM/en/release/index.html>

**Comment by Santarh** [comment]
The discussion has stopped for a long time, so I will close it.
If you have any problems, please comment again.
