### ISSUE TITLE
What differences between VRM & VRM10? VRM＆VRM 10の違いは？

### ISSUE THREAD

**Issue by orangeagain** [vrm-c/UniVRM#1377]
Which one has better compatibility? Which one can be used in production?
どちらが互換性が良いですか？どちらが生産で使用できますか？

**Comment by ousttrue** [comment]
Thank you for reporting.

Please see <https://vrm.dev/en/docs/vrm1/>.

**Comment by Santarh** [comment]
The discussion has stopped for a long time, so I will close it.
If you have any problems, please comment again.
