### ISSUE TITLE
Model won't export

### ISSUE THREAD

**Issue by XenoDragoness** [vrm-c/UniVRM#1378]
## Environments (please complete the following information):

 - UniVRM version: `0.81.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## Describe the bug

Exporting not working:
In 'VRM Exporter' the options for 'Meta, Mesh, BlendShape, ExportSettings' do not appear, meaning I cannot input title, version, or author, and the Export button is remaining greyed out and unusable.

I have gone through all the regular process of setting up my model for VRM export and nothing has worked, I have also tried avrious different versions of both Unity and UniVRM and neither have offered a solution to this problem.

It also continues to tell me to face my model towards positive X axis, it always says this no matter what direction I pose my model in.

![help](https://user-images.githubusercontent.com/94468349/142026730-51000749-3623-483a-8ebb-3f5295291971.PNG)

**Comment by ousttrue** [comment]
Thank you for reporting.

Determines whether the model faces Z+ at the leftUpperLeg and RightUpperLeg positions.
Is the upper left leg on the left and the upper right leg to the right ?

Please check humaniod avatar bone assignment.

`Humanoid` component may be helpful.
![humanoid](https://user-images.githubusercontent.com/68057/142825382-dbbc9316-8514-4af7-9f70-a001c31a5ed2.jpg)

**Comment by Santarh** [comment]
The discussion has stopped for a long time, so I will close it.
If you have any problems, please comment again.
