### ISSUE TITLE
テクスチャの最大サイズが4096×4096から2048x2048に変更される

### ISSUE THREAD

**Issue by Smabro56** [vrm-c/UniVRM#1379]
## 環境情報

 - UniVRM version: `0.81.0`
 - Unity version: `Unity-2019.4.31f1`
 - OS: `Windows 10`

## バグについて

* バグの内容
入出力時のどちらかで、テクスチャの最大サイズが4096×4096から2048x2048に強制的に変更される。

* ConsoleLog
なにも出力されない

* スクリーンショット
![キャプチャ](https://user-images.githubusercontent.com/69447268/142170844-7e1a55b5-08ab-4a2e-9e4a-96908c61ca89.PNG)
![キャプチャ2](https://user-images.githubusercontent.com/69447268/142170895-77d71ecf-f11c-4aae-9bf6-57f772aa1c34.PNG)
![キャプチャ3](https://user-images.githubusercontent.com/69447268/142170901-93943bca-d920-49c0-b315-1ac48a1be019.PNG)

* 再現方法
1. 適当なVRMファイルを用意する
2. （解像度が4096のテクスチャが含まれていない場合）任意のテクスチャ画像を解像度が4096x4096のものに差し替える
3. テクスチャの最大解像度を4096x4096に変更する
4. UniVRMを用いてVRMをエクスポート
5. エクスポートしたVRMをインポート
6. テクスチャ最大解像度が2048x2048になっている

* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)
[test.zip](https://github.com/vrm-c/UniVRM/files/7553274/test.zip)
(VRoidStudio v1.0.3で新規作成を選び、服装をテクスチャ解像度がわかりやすいプリセットに変更し、マテリアル数を2に変更してエクスポートすることで作成したVRMファイル)

**Comment by ousttrue** [comment]
報告ありがとうございます。

現象を確認しました。
以下のような動きです。

* vrm インポート時に png をフォルダに書き出します
* unity がこれをアセットとして import します
* unity が TextureImporter の `MaxSize` を 2048 に設定します
(vrm ではなくて png 単体をアセットフォルダに投入することでも再現しました)

![maxsize](https://user-images.githubusercontent.com/68057/142846989-7c31389e-947b-4818-82d3-a1081945d121.jpg)

* texture がロードされるときに MaxSize の影響を受けます
* UniVRM はロードされたテクスチャーエクスポートします(asset ではなく scene をエクスポートしています)

とりあえず、TextureImporter の `MaxSize` 設定値を 4096 に手動で操作することで回避できます。

UniVRMがどのように振る舞うべきか検討。

* EditorImport: TextureImporter の MaxSize を変更すべきか
* Export時にオリジナルの png 等をサーチするべきか

**Comment by ousttrue** [comment]
https://github.com/vrm-c/UniVRM/blob/master/Assets/VRMShaders/GLTF/IO/Editor/Texture/Exporter/EditorTextureSerializer.cs#L24

**Comment by esperecyan** [comment]
@ousttrue インポート時のテクスチャサイズ反映はUniVRM-0.54.0で実装されました https://github.com/vrm-c/UniVRM/issues/291 が、最近のUniVRMでは動作しなくなっているようです。

**Comment by Santarh** [comment]
https://github.com/vrm-c/UniVRM/pull/1402
上記 PullRequest にて修正しましたので、次の UniVRM リリースで修正される予定です。

**Comment by ousttrue** [comment]
`v0.91.0`
