### ISSUE TITLE
Expressions are broken when exporting as VRM 1.0 model.

### ISSUE THREAD

**Issue by Santarh** [vrm-c/UniVRM#1380]
Unity Editor から VRM 1.0 モデルをエクスポートすると、口パクなどの Expression が大きく開きすぎたり、色々壊れる。

UniVRM 0.89.0

**Comment by ousttrue** [comment]
![expression](https://user-images.githubusercontent.com/68057/143224382-a2545c72-88e3-45e3-841f-908fa0c0dd44.jpg)

weight の値域 0-1 のバグ。
Unity の値域 0-100 がそのまま入っている。
