### ISSUE TITLE
 gltf urp materials do not work well in unity 2020 lts.

### ISSUE THREAD

**Issue by Personuo** [vrm-c/UniVRM#1382]
Unity seems to be changing the criteria for LIT materials,?
Some parameters do not work immediately in 2020 lts.

**Comment by ousttrue** [comment]
Thank you for reporting.
URP support is limited and incomplete.
MToon falls back to Unlit.
This is because the URP version of MToon has not been implemented yet.
I will write a document about customizing the Material loader.

**Comment by Santarh** [comment]
Duplicated
https://github.com/vrm-c/UniVRM/issues/1214
