### ISSUE TITLE
ovelay texture on body mesh in unity.

### ISSUE THREAD

**Issue by papitosan** [vrm-c/UniVRM#1384]
Is it possible to  export multiple vroid skin overlays and make the layering in unity on the body mesh? (for now it's one texture, i cannot start from nude and  add bra and panties for instance)
 would this be difficult to make?

Thanks a lot,

Kind regards

**Comment by Santarh** [comment]
The discussion has stopped for a long time, so I will close it.
If you have any problems, please comment again.
