### ISSUE TITLE
[1.0] Unable to find "Pose Freeze" in Settings

### ISSUE THREAD

**Issue by infosia** [vrm-c/UniVRM#1388]
## Environments

 - UniVRM version: `VRM-0.89.0_9470.unitypackage`
 - Unity version: `Unity-2019.4.29f1`
 - OS: `Windows 10`

## Describe the bug

Unable to find "Pose Freeze" in ExportSettings when exporting VRM 1.0 despite of `Settings の PoseFreeze を有効にしてください`.

![Capture](https://user-images.githubusercontent.com/1661068/143381182-b89f5434-86b2-44c1-8304-80a2dce27197.PNG)

* Reproduction procedure

1. Import [kaya.fbx](https://github.com/infosia/themachinery-issues/blob/master/0011/kaya.fbx)
2. Place the fbx into the scene
3. `VRM1` -> `Export VRM 1.0`

* File that causes an error (those that can be pasted here)

https://github.com/infosia/themachinery-issues/blob/master/0011/kaya.fbx

**Comment by Santarh** [comment]
In the vrm-1.0 specification, we decided not to do transform normalization.
Therefore, the assumption has changed and we will close it.
