### ISSUE TITLE
Best way to update?

### ISSUE THREAD

**Issue by Applepiee** [vrm-c/UniVRM#1401]
Hi,

We are on univrm 0.63. What's the best way to update? Should we update version one by one? Or just replace with newest version?

**Comment by ousttrue** [comment]
Thank you reporting.
We recommend the latest version.

| Unity  | UniVRM |
|--------|--------|
| 5.6    | v0.55  |
| 2018.4 | v0.66  |
| 2019.4 | latest |

https://vrm-c.github.io/UniVRM/en/release/index.html

**Comment by Santarh** [comment]
The discussion has stopped for a long time, so I will close it.
If you have any problems, please comment again.
