### ISSUE TITLE
When the model is deleted, Meta.Thumbnail still resides in memory

### ISSUE THREAD

**Issue by Personuo** [vrm-c/UniVRM#1408]
If a model loaded from vrm file or sdk,
When I deleted the model, I found Meta.Thumbnail still resides in memory

univrm version 0.89.0_9470

**Comment by ousttrue** [comment]
Thank you for reporting.
When I tried it, it was released normally.
This is the current loading procedure.

* https://github.com/vrm-c/UniVRM/blob/master/Assets/VRM_Samples/SimpleViewer/ViewerUI.cs#L459
* https://vrm-c.github.io/UniVRM/en/vrm0/0_87_runtime_import.html

Please tell me the simple steps to cause the problem.

**Comment by Santarh** [comment]
The discussion has stopped for a long time, so I will close it.
If you have any problems, please comment again.
