### ISSUE TITLE
VRMMetaコンポーネントインスタンスに値を保存する

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#1421]
現在、VRMMetaコンポーネントはVRMBlendShapeProxyコンポーネントと同じように、固有のアセットにデータを保存して参照するようになっています。プレハブバリアントを作成してもメタデータが共用状態になり、Title等を書き替えると元のプレハブも書き換わった状態になり、細かいバリエーション違いのVRMを管理するのが難しくなっています。

VRMFirstPersonコンポーネントなどのように、コンポーネントインスタンスに値を保存するように変更できないでしょうか。

**Comment by ousttrue** [comment]
報告ありがとうございます。

動作を確認したところ、meta object の置き換えが意図したとおりに動作していせんでした。 #1423 にて修正しました。
![meta_prop](https://user-images.githubusercontent.com/68057/145945043-0f487b6c-8209-483a-a997-8486b727cb2e.gif)

希望に沿う形でコンポーネントにはできないのですが、
バリエーション毎に  VRMMeta オブジェクトを複製(Ctrl-D)することどできるようになります。

`v0.92.0` から動くようになります。

## 細かい説明

VRM の editor import で生成された prefab は通常の prefab というようりは、
元になった VRM の反映という意図があります。
なので、基本的になるべく不変(prefabが不変。instanceはシーンで変更可)であるようにデザインしていて、
変わるのは元の VRM が変更されて reimport されたときのみになることを意図しています。
(VRM-0 は Unity assetPostProecessor を使っているため不完全)。

この意図を前進させる ScriptedImporter という機能がありまして、
glb, vrm-1 はこれを使って fbx 風の動作をするようにしています。
(fbx の prefab は変更できない。instance は変更できる)

Unity の asset 管理をシンプルに保つため、なんらかのファイルから生成される prefab は変更不可(readonly でオリジナルの glb, vrm-1 や fbx の反映)という設計です。

**Comment by esperecyan** [comment]
つまり、現行のUniVRMは不完全であるためにプレハブバリアント同士で値が共有状態になっている (VRMMetaアセットの付け替えはv0.92.0で出来る) が、UniVRM1からはFBXのようにバリアントごとに別の値が設定可能になる、ということですね。
説明ありがとうございます。
