### ISSUE TITLE
Blendshape smoothing not being exported correctly from FBX to VRM

### ISSUE THREAD

**Issue by mistyskye** [vrm-c/UniVRM#1427]
## Environments:

 - UniVRM version: `0.61.1` &  `0.91.0`
 - Unity version: `Unity-2019.4.29`
 - OS: `Windows 10`

## Description:
  
I am exporting a model from Blender as an FBX. I am aware of the issue with normals so when I import it in Unity, I make sure to check the box "Legacy Blend Shape Normals" or set Blend Shape Normals to import. However, there seems to be another issue related to smoothing. 
When I view the FBX blendshapes in the Scene view, they look exactly like they do in Blender (nice and smooth). However, after I export the FBX to VRM, when I view the blendshapes they are broken and not smooth. (see screenshots)
Somewhere along the line UniVRM is ignoring the smoothing from Blender.

The following screenshots show the combination of jawOpen and mouthSmileLeft and mouthSmileRight blendshapes. It happens with other symmetrical blendshapes too.
FBX:
![image](https://user-images.githubusercontent.com/49554363/145979758-d07181ee-9ba1-4ee6-b99c-1a5f6f9c3d73.png)

VRM:
![image](https://user-images.githubusercontent.com/49554363/145979707-62654625-969f-4b5d-9579-d21d384d81a5.png)

I am not comfortable with sharing the original file as it is for a paid commission.

**Comment by Santarh** [comment]
Please make this option disabled.

![image](https://user-images.githubusercontent.com/328204/175480037-b2b8d063-e585-4819-822f-6405344d5459.png)
