### ISSUE TITLE
[1.0] The tail joint of SpringBone cannot be imported when hitRadius is not set

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/UniVRM#1441]
## 環境情報

 - UniVRM version: `0.92.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## バグについて

* バグの内容

SpringBoneの仕様上、末端JointにはhitRadius等のオプショナルな値は無くても良いことになっていたはずですが、無いと動かないようです。
恐らくhitRadiusだけでなく、他の値も同等の問題を発生させると思います。

* ConsoleLog

```
InvalidOperationException: Nullable object must have a value.
System.Nullable`1[T].get_Value () (at <9577ac7a62ef43179789031239ba8798>:0)
UniVRM10.Vrm10Importer+<LoadSpringBoneAsync>d__17.MoveNext () (at Library/PackageCache/com.vrmc.vrm@2487dd5fdd/Runtime/IO/Vrm10Importer.cs:578)
```

該当行: https://github.com/vrm-c/UniVRM/blob/2487dd5fdd48ad02c59ad5ff15bc10d7ded9d2d3/Assets/VRM10/Runtime/IO/Vrm10Importer.cs#L578

* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

[three-vrm-girl-1.0-beta.zip](https://github.com/vrm-c/UniVRM/files/7767108/three-vrm-girl-1.0-beta.zip)

VRM1.0-beta版のthree-vrm-girlです。

**Comment by 0b5vr** [comment]
シンプルに、該当箇所をこうすれば解決するものと思います:

```cs
if (!(gltfJoint.HitRadius is null)) {
    joint.m_jointRadius = gltfJoint.HitRadius.Value;
}
if (!(gltfJoint.DragForce is null)) {
    joint.m_dragForce = gltfJoint.DragForce.Value;
}
if (!(gltfJoint.GravityDir is null)) {
    joint.m_gravityDir = Vector3InvertX(gltfJoint.GravityDir);
}
if (!(gltfJoint.GravityPower is null)) {
    joint.m_gravityPower = gltfJoint.GravityPower.Value;
}
if (!(gltfJoint.Stiffness is null)) {
    joint.m_stiffnessForce = gltfJoint.Stiffness.Value;
}
```

C#に不慣れなもので、もしより良いsyntaxがあればご教示ください。
このままで良ければ、これでPR作ってしまいます。

**Comment by ousttrue** [comment]
報告ありがとうございます。
非末端は、警告にしてエラーにはしない方向でやってみます。

**Comment by ousttrue** [comment]
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_springBone-1.0-beta/schema/VRMC_springBone.joint.schema.json
に基づいて、愚直にデフォルト値を割り当てることにしました。
問題があってから対応しようと思います。

**Comment by ousttrue** [comment]
`v0.93.0` 年始予定です。
