### ISSUE TITLE
Wrong metallic&smoothness texture assignment after exporting (standard shader)

### ISSUE THREAD

**Issue by PrettyFireNOI7** [vrm-c/UniVRM#1447]
## Environments (please complete the following information):

 - UniVRM version: `0.92.0`
 - Unity version: `Unity-2019.4.34f1c1`
 - OS: `Windows 10`

## Describe the bug

* After exporting (like the first export from FBX to VRM), the texture used for metallic&smoothness is wrong assigned.
* Sorry that I don't know how to get the ConsoleLog.

* Reproduction procedure:
Here is an FBX file exported from Blender:
[TestFBX.zip](https://github.com/vrm-c/UniVRM/files/7793708/TestFBX.zip)

![I1](https://user-images.githubusercontent.com/81634162/147769541-80795bb5-9f0a-45b6-9abf-ed5d67843e3d.png)
In the pic, there are two planes skinned to the head bone of the Armature. The green one and pink one are two different materials and two textures are used to map the smoothness value ( in Blender it is called "roughness" ). The texture for the green one has a "false" mark and the texture for the pink one has a "check" mark.
If you open the FBX with WIN10 3D viewer you should get this:
![I2](https://user-images.githubusercontent.com/81634162/147772496-e9a6eae9-2427-41bd-97af-727f14dcd0e5.png)

Start a Unity project with UniVRM installed and import the FBX. Drag the prefab into the scene.
Extract the materials.
The texture for metallic&smoothness would need to be set manually (automatically there might be no texture in the metallic&smoothness slot). Then they should look like this:
![I3](https://user-images.githubusercontent.com/81634162/147773157-b0c94e39-fb1f-49d6-8156-4e4e79217f59.png)

Next, set Humanoid and export it to VRM.

Drag the exported VRM into the scene.And it should look like this:
![I4](https://user-images.githubusercontent.com/81634162/147773353-5a337bb7-0a05-4faa-a644-8f5f6a8265a1.png)
As the pic above, the left model is the exported VRM and the "false" mark on the green plane becomes "check". The texture is incorrectly assigned.
This problem still occurs after re-assigning the texture on the VRM model and do the second time export.

**Comment by PrettyFireNOI7** [comment]
Tested with 0.93. I think this bug is fixed, thought I found the Rendering Mode of Standard material would be reset from Transparent to Fade. I would do a another bug report.

**Comment by Santarh** [comment]
Fixed with https://github.com/vrm-c/UniVRM/pull/1437
