### ISSUE TITLE
Weird skinning deformation

### ISSUE THREAD

**Issue by PrettyFireNOI7** [vrm-c/UniVRM#1448]
## Environments (please complete the following information):

 - UniVRM version: `0.92.0`
 - Unity version: `Unity-2019.4.34f1c1`
 - OS: `Windows 10`

## Describe the bug

* Some mesh deformation is weird, as in the picture below, the joint of upper arm and shoulder has unexpected deformation in VRM format :
![I2](https://user-images.githubusercontent.com/81634162/147827326-4aa6a273-97b1-4b4e-912d-cf9f9bca8f5f.png)
The left model is the result of the first export (become VRM format) from the right FBX model. When exporting, the right model is in T-pose. In the picture their upper arm bone had been rotated to show the different deformation. I think I should have made the weight on the original model is normalized.

* ConsoleLog : Sorry again, I have no idea about how to extract the console logs.

* Reproduction procedure :
Here is a file than contains the previous shoulder mesh's Blender file and FBX file (the FBX file is exported from the Blender file) :
[VRM BugReport.zip](https://github.com/vrm-c/UniVRM/files/7796389/VRM.BugReport.zip)
![I1](https://user-images.githubusercontent.com/81634162/147826608-7627e494-b253-4865-9548-7c47115b1fb1.png)
Import the FBX into a Unity project with VRM installed, then set humanoid and exported it using VRM. (I did not extract the material since I think this step wouldn't affect the final deformation in this case.) 
Import the exported VRM file.
Put both of them (the FBX and VRM prefab) into the scene and rotate their upper arm and then the different deformation should be noticeable.
![I2](https://user-images.githubusercontent.com/81634162/147827591-95ed1499-38a2-426d-a25e-e241c3535cc1.png)

**Comment by ousttrue** [comment]
Thank you for reporting.
I will check if the total weights for the bones in the exporter are 1.

**Comment by ousttrue** [comment]
The total weight of all vertices was 1.
When baked, it may shift due to the effect of linear interpolation.
I'm not sure.
Therefore, it cannot be fixed.

**Comment by Santarh** [comment]
The discussion has stopped for a long time, so I will close it.
If you have any problems, please comment again.
