### ISSUE TITLE
animator.avatar is not humanoid when animator.avatar is humanoid

### ISSUE THREAD

**Issue by goodone0513** [vrm-c/UniVRM#1450]
## Environments (please complete the following information):

 - UniVRM version: `0.92.0 & 1.0`
 - Unity version: `Unity-2021.2.7f1`
 - OS: `Windows 11 22523`

## Describe the bug

* I am experiencing a bug where the program states "animator.avatar is not humanoid" even after when I checked it was humanoid.
* -
* ![image](https://user-images.githubusercontent.com/64828505/147842007-d244c23e-c4f0-47d1-8109-73b8307da60f.png)
* Set avatar to "humanoid" > select avatar in "assets" section > run "VRM0" or "VRM1"
* Not Known

**Comment by ousttrue** [comment]
Thank you for reporting.

![avatar](https://user-images.githubusercontent.com/68057/148036779-2f7f4508-57f1-4c05-b265-ae8659b42c21.jpg)

When I select humanoid and apply it, I find that the event does not come to the GUI for some reason. I don't know how to fix it. As a workaround, close the export window and reopen it.

**Comment by ousttrue** [comment]
Since there is no reaction, it will be closed. If anything, please report it again.
