### ISSUE TITLE
Cannot Export as VRM or see the option for "Export as Humanoid." 

### ISSUE THREAD

**Issue by rinkasahara** [vrm-c/UniVRM#1451]
## Environments (please complete the following information):

 - UniVRM version: `0.81.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## Describe the bug

* A clear and concise description of what the bug is.
* ConsoleLog
* ScreenShot
* Reproduction procedure
* File that causes an error (those that can be pasted here)
![error](https://user-images.githubusercontent.com/96962908/147863387-564f401b-ecbf-4dbb-83d2-df66c62687dc.png)

**Comment by ousttrue** [comment]
Thank you for reporting.
You cannot export unless you resolve the error message (red). 
Make sure that the materials in one of the Renderers are not null. 
The message is unfriendly, so I'll improve it.
