### ISSUE TITLE
Standard shader rendering mode is reseted from Transparent to Fade after exporting

### ISSUE THREAD

**Issue by PrettyFireNOI7** [vrm-c/UniVRM#1454]
## Environments (please complete the following information):

 - UniVRM version: `0.93.0`
 - Unity version: `Unity-2019.4.34f1c1`
 - OS: `Windows 10`

## Describe the bug

* After exporting, if the rendering mode in standard shader is Transparent, the mode will be reset to Fade.

* ConsoleLog
Sorry I don't know how to get the console logs.

* ScreenShot:
![I3](https://user-images.githubusercontent.com/81634162/148641731-912c6701-71cb-4cba-a522-0fe415bb83dc.png)

* Reproduction procedure:
Export a model with standard shader whose rendering mode is set to Transparent. Then import the exported one, the rendering mode should be reset to Fade (bug).

* File that causes an error:
This is the FBX model in the said picture, which should be quick for setting a standard transparent material and test the bug.
[BugTest.zip](https://github.com/vrm-c/UniVRM/files/7833096/BugTest.zip)

**Comment by ousttrue** [comment]
Thank you for reporting.
I confirmed the reproduction of the bug.
The materials exported to glb are:
```js
    {
      "alphaMode": "BLEND",
      "doubleSided": false,
      "name": "Material",
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          0.6038274,
          0.6038274,
          0.6038274,
          0.4
        ],
        "metallicFactor": 0,
        "roughnessFactor": 1
      }
    }
```
Maybe an importer's problem.

**Comment by ousttrue** [comment]
https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/material.schema.json#L44
The gltf blend mode feature is opaque, masked, or transparent.
When you export, the difference between fade and transparency is lost.
When importing, gltf's AlphaMode.Blend will be Unity's Fade.

**Comment by ousttrue** [comment]
Since it is a specification, we will continue as it is.

**Comment by PrettyFireNOI7** [comment]
Thanks for the elaboration.
