### ISSUE TITLE
Export won't work

### ISSUE THREAD

**Issue by sadilyy** [vrm-c/UniVRM#1455]
## Environments (please complete the following information):

 - UniVRM version: `0.93.0`
 - Unity version: `Unity-2019.4.29f1`
 - OS: `Windows 10`

## Describe the bug
When trying to export a vrchat model from a unitypackage to a vrm model, I get these errors and I am unsure how to fix it or if there is a fix.
![image](https://user-images.githubusercontent.com/97390881/148682746-959c43a4-e590-4b46-a8c0-2d641b91f5a0.png)

**Comment by ousttrue** [comment]
Thank you for reporting.
This seems to happen when a renderer other than MeshRenderer or SkinnedMeshRenderer is attached.
For example, LineRenderer or ParticleSystemRenderer.
If anything other than `MeshRenderer` or` SkinnedMeshRenderer` is found, change it to skip.

**Comment by ousttrue** [comment]
`v0.96.0`
