### ISSUE TITLE
[1.0] MToon の Shade 色の効き方が違う？

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/UniVRM#1464]
## 環境情報

 - UniVRM version: `0.93.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## バグについて

白い Shade 色が指定された時の挙動が 0.x と 1.0 で違うようです。

![white_shade](https://user-images.githubusercontent.com/68057/149708695-1ad5fad2-c790-4a76-a370-98a604cbc0fa.gif)

シェーダーの修正もしくは、マイグレーションの修正が必用でしょうか。

[white_shade_materials.unitypackage.zip](https://github.com/vrm-c/UniVRM/files/7879010/white_shade_materials.unitypackage.zip)
リネームして `.zip` を取り除いてお試しください(github の貼り付け拡張子の制限)

**Comment by Santarh** [comment]
VRM 1.0 では明確に、`dot(N, L)` の値に応じて `LitColor` `ShadeColor` が混合されるという仕様になりましたので、実装としては合っています。
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_materials_mtoon-1.0-beta/README.ja.md#shade-color

またマイグレーションで良い感じに解決できるものではないので、残念ながらこれは仕様としたいです。

「 `LitColor` よりも明るい `ShadeColor` の指定」という明らかに現実的ではない値が与えられた時の挙動ですので
0.x のように「外れ値のパラメタでもなんとなく忖度してなんとなくいい感じに色を出す」ではなく
1.0 のように「直感的な計算定義にのみ従い、外れ値のパラメタは外れ値が出る」としたほうが
素直かなと感じます。
