### ISSUE TITLE
Can you update a VRM model without changing GUIDs (seems to create new GUIDs per import)

### ISSUE THREAD

**Issue by alankent** [vrm-c/UniVRM#1468]
Is it possible to import a VRM file, make further changes in VRoid studio, then reimport (update) keeping the old GUIDs? I want to update the VRM file without changing the GUIDs in Unity. (It seems to create a new version (_1 appended) when I import the second time.

(Reason: I am animating in Unity - all the Cinemachine timelines use the GUIDs so it is a big job to redo all the animation if the VRoid character is updated.)

**Comment by ousttrue** [comment]
Thank you for reporting.
The code around here seems to be relevant.
Do you have any opinions on this?

https://github.com/vrm-c/UniVRM/blob/master/Assets/VRM/Editor/Format/VRMEditorImporterContext.cs#L148

```cs
            // Create or update Main Asset
            if (m_prefabPath.IsFileExists)
            {
                Debug.LogFormat("replace prefab: {0}", m_prefabPath);
                var prefab = m_prefabPath.LoadAsset<GameObject>();
                PrefabUtility.SaveAsPrefabAssetAndConnect(root, m_prefabPath.Value, InteractionMode.AutomatedAction);
            }
            else
            {
                Debug.LogFormat("create prefab: {0}", m_prefabPath);
                PrefabUtility.SaveAsPrefabAssetAndConnect(root, m_prefabPath.Value, InteractionMode.AutomatedAction);
            }
```

`InteractionMode.AutomatedAction` I don't really understand.

**Comment by alankent** [comment]
Ahhhh! I will experiment a bit more. I was dragging and dropping VRM files into a folder. If it is already there, then it changes the name to have a unique number after it (so "Sam", "Sam 1", "Sam 2", etc). However I forgot there is an "Import" menu option as well. When I use the "import" menu option I get the "replace prefab" message you point out!

So maybe this is already supported, I just have to use the menu import instead. I will experiment and report back. Thanks for pointing this out!

**Comment by alankent** [comment]
Hmmm. Been trying a few different tests. It does seem to update the current character. It loses any added components (not surprising I guess), but shortly after doing an import Unity locks up. I have to kill the process to recover.

**Comment by andreiagmu** [comment]
@alankent To make the updated character not lose components you add on it, maybe you could create a prefab variant of the original prefab generated by VRM importer, and add your components on that variant? (instead of adding directly on the original prefab)

I think that way you can update your character, keeping your components safe on the prefab variant (which will also be updated with the new version of the character).

**Comment by ousttrue** [comment]
Since there is no reaction, it will be closed. If anything, please report it again.
