### ISSUE TITLE
Is exported VRM's skin weight is limited to 4 skin weights?

### ISSUE THREAD

**Issue by leztusi** [vrm-c/UniVRM#1476]
## Environments (please complete the following information):

 - UniVRM version: `0.91.0`
 - Unity version: `Unity-2021.1.15`
 - OS: `Windows 10`

## Describe the bug

* A clear and concise description of what the bug is.
limited skin weights cause bad deformation.
Before exporting, I made sure the model's skin weights on the import settings is set to highest, as well as setting the project setting's skin weight to unlimited.
But the skin weight error still happens after exporting.
I tried to emulate the same error on blender by setting a skin weight limit to 4, and looks the same as when I exported my model to VRM.

* ScreenShot
![image](https://user-images.githubusercontent.com/20206492/150074023-724d301d-ffed-406c-a64f-f5747eca1d9a.png)

* Reproduction procedure
export a model with rig that has skin weights larger than 4 weights.
export to vrm
compare the before and after.

**Comment by ousttrue** [comment]
Thank you for reporting.
4weight is a gltf specification.
vrm cannot record more than 4 weights.
It seems better to reduce it to 4 in blender before exporting.

**Comment by fire** [comment]
gltf 2.0 can support any multiple of 4 weights.

**Comment by leztusi** [comment]
glTF devs also told me the same thing. I don't know how univrm/vrm use glTF as the base, but if it's possible to update this somehow, it will improve exported univrm models a lot.
