### ISSUE TITLE
FastSpringBone

### ISSUE THREAD

**Issue by LievreAI** [vrm-c/UniVRM#1480]
## Environments (please complete the following information):

UniVRM v0.87.0
Unity 2019.2.0f1
Windows

## Describe the bug

you cannot descirb as i belive those releases not even tested each release that i test
the same error each version bring endless errors
the latest version error : `Assets\VRM\Runtime\FastSpringBone\Blittables\BlittableTransform.cs(54,39): error CS1061: 'TransformAccess' does not contain a definition for 'localToWorldMatrix' and no accessible extension method 'localToWorldMatrix' accepting a first argument of type 'TransformAccess' could be found (are you missing a using directive or an assembly reference?)`

we speaking on a new simple project that bring those errors once i import it
so you cannot said its error with your project as this is clean project i did just for the plugin test and seems i have the same error with the same project i have both  of them sharing  the same error

**Comment by ousttrue** [comment]
Thank you for reporting.
Minimum unity version is `2019.4` from `UniVRM-0.80`.

https://vrm-c.github.io/UniVRM/en/release/index.html
