### ISSUE TITLE
[1.0] Neutral 反映

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/UniVRM#1482]
https://github.com/vrm-c/vrm-specification/pull/346

**Comment by DominikCGI** [comment]
Expressions won't work if they share the Name "A" "E" "I" "O" "U" "Fun" Sorrow" "Joy" "Surprised"... Even so they all are present at runtime. I can only change "Extra" (a new made expression) with proxy.ImmediatelySetValue("Extra", 1.0f);)

If I use any other blendspace than that new one, it won't set the values. i guess that the stuff is somehow hardcoded in japanese.
