### ISSUE TITLE
[1.0] Constraints, the behavior of freeze axes are opposite from spec

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/UniVRM#1490]
## 環境情報

 - UniVRM version: `0.94.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## バグについて

UniVRMのVRM10 Rotation Constraintですが、仕様で定めたfreezeAxesの挙動とUniVRMの挙動が真逆になっていると思います。

freezeAxesで指定した軸がコンストレイントによって制約されないのではなく、制約される挙動が正しいと想定して仕様を組んでおりました。

https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_node_constraint-1.0_draft#freeze-axes

**Comment by ousttrue** [comment]
？
true になった軸の回転が 0 になると思うんだけど。

**Comment by 0b5vr** [comment]
trueになった軸の回転がconstraintによって制約され、falseの軸に対してはconstraintは作用しない、という仕様になっています。

freezeという名前がややこしいという意見は社内からは上がりました……

**Comment by ousttrue** [comment]
有効な軸を指定するのであれば名前変えたいです。
`Axis` だけとか `ActiveAxis` とか。
`Freeze` という名前なら `効かない方を指定する` という意味になるんじゃないだろうか・・・

**Comment by 0b5vr** [comment]
Unityを参照してそうしたのですが、かえって分かりづらくなってしまいました……。ごめんなさい。

`axis` で良さそうですね。PR作ります。
