### ISSUE TITLE
[1.0] VRM10Object from project context menu

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/UniVRM#1491]
UniVRM version: `0.94.0`

### Description

VRM1の吐き出しに `VRM10Object` というオブジェクトが必要となりますが、これをProjectのコンテキストメニューから新規作成できてもよいのかなと思いました。

例えば、以下の変更を加えれば実現可能ですが、いかがでしょうか。

https://github.com/0b5vr/UniVRM/commit/efecb656bff004c7e5d16e69f032c6172a78f911#diff-9d00e2dfcc4da8a7e318653c92dfae15a2c6feb83d3750d1ef12ea9bef984599R19-R21

### Context

Blenderからモデルを読み込んでUniVRM上でセットアップをしようと、VRM10Instanceコンポーネントをモデルルートに追加したのですが、PlayするとLookAtまわりでエラーが発生してしまいました。
VRM10Objectを追加してからPlayモードに入ったところ、正常に動作しました。

**Comment by ousttrue** [comment]
Component 手動貼り付け時の動作を確認します。

**Comment by 0b5vr** [comment]
右クリックとは若干ずれますが、たとえばこのようなダイアログがあるとセットアップが簡単になるかと思いました。

![image](https://user-images.githubusercontent.com/7824814/153127906-36e01bbd-d893-4d9d-a7b0-0348187bb1fb.png)

荒削りな実装ですが、一応ブランチを私のフォークにpushしてあります（初めてUnityのEditorGUI触りました……）:

https://github.com/0b5vr/UniVRM/pull/1

**Comment by ousttrue** [comment]
`Create new VRM10Object` ボタンをいただいて初期設定できるボタンを追加しました。

**Comment by ousttrue** [comment]
`v0.96.0`
