### ISSUE TITLE
[1.0] Bounds are not set to mesh primitives properly

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/UniVRM#1492]
## 環境情報

 - UniVRM version: `0.94.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## バグについて

#1389 より引き継ぎ。
infosiaさんが貼っていた以下のモデルを私の手元でも改めて読み込んでみましたが、 `MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS` については引き続きエラーが発生していました。
`accessor.min` および `accessor.max` がmeshに対して割り当てられていない場合があると思います。

https://github.com/infosia/themachinery-issues/blob/master/0011/kaya.fbx

**Comment by ousttrue** [comment]
`v0.95.0`
