### ISSUE TITLE
[1.0] Exported VRMC_node_constraint extensions do not have specVersion

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/UniVRM#1493]
## 環境情報

 - UniVRM version: `0.94.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## バグについて

- UniVRMから吐き出したモデルについて、 `VRMC_node_constraint` に `specVersion` が抜けていると思います。
現状のバージョンは `1.0-draft` なので、これの追加が必要です。

現状の出力結果:

![image](https://user-images.githubusercontent.com/7824814/152134738-c669f0eb-f3a5-45b9-a7ff-135061896678.png)

**Comment by ousttrue** [comment]
修正します。

**Comment by 0b5vr** [comment]
これ、すぐできそうだったので私の方でやってみます。
