### ISSUE TITLE
"The model needs to face the positive Z-axis"

### ISSUE THREAD

**Issue by Xwilarg** [vrm-c/UniVRM#1507]
## Environments (please complete the following information):

 - UniVRM version: `0.94.0`
 - Unity version: `Unity-2021.2.9f1`
 - OS: `Windows 11 Pro Insider Preview Build 22543.rs_prerelease.220122-2315`

## Describe the bug

Hey,
I'm trying to import a MMD model in Unity and then export it to VRM, I managed to generate a prefab but when trying to export it I have the following error:
```
The model needs to face the positive Z-axis
```
However I don't really get what the issue is since my model is already facing the Z axis
![image](https://user-images.githubusercontent.com/20053454/152647988-01c4828f-0cc9-4376-b4e9-239bf333d961.png)

**Comment by ousttrue** [comment]
Thank you for reporting.
In UniVRM, The forward is confirmed from HumanBodyBones.LeftUpperLeg and HumanBodyBones.RightUpperLeg.
Check out HumanBodyBones.LeftUpperLeg and HumanBodyBones.RightUpperLeg.
For example, they are swapping.

**Comment by ousttrue** [comment]
The behavior of prefab has changed from Unity-2021.3, and it may have failed to get the coordinates.
Try instantiating the prefab into your scene and then exporting it.

**Comment by ousttrue** [comment]
Since there is no reaction, it will be closed. If anything, please report it again.
