### ISSUE TITLE
VRMSpringBoneのGizmo表示のデフォルト有効化とEditモードでの表示

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#1508]
VRM設定を簡単、かつ解りやすくするため、VRMSpringBoneのGizmo表示を、VRMSpringBoneColliderGroupなどと同様の表示へ変更できないでしょうか。
- デフォルトで有効
- Editモード/プレハブで表示 (Playモード以外でも表示)

各Gizmoはビューの設定から一括して表示非表示を切り替えられるので、邪魔になることは無いのではないかと思います。

**Comment by ousttrue** [comment]
なるほど。
ちょっと調べます。
Start時に情報を集めて SpringBone の内容を確定させているのですが、
ある程度割り切った Editor 表示を作ればよいかもしれません。

**Comment by ousttrue** [comment]
現状。

|class|method|comment|
|-|-|-|
|VRMSpringBoneColliderGroup|OnDrawGizmosSelected||
|VRMSpringBone|OnDrawGizmos|m_drawGizmo でスイッチ, m_verlet(LateUpdateかFixedUpdateで更新)を描画。Playするまで描画されない |

**Comment by ousttrue** [comment]
変更。

|class|method|comment|
|-|-|-|
|VRMSpringBoneColliderGroup|OnDrawGizmosSelected||
|VRMSpringBone|OnDrawGizmosSelected|Application.isPlaying で描画ロジックをスイッチ|

**Comment by ousttrue** [comment]
`v0.96.0`
