### ISSUE TITLE
[UniGLTF] MeshUtility.SeparationProcessing() でアセット・シーンに干渉しないオプションが欲しい

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#1509]
`UniGLTF.MeshUtility.MeshUtility.SeparationProcessing()` を実行すると、指定したオブジェクトに対して `Object.Instantiate()`、分割されたメッシュに対して `AssetDatabase.CreateAsset()` が実行されます。VRM作成時の前処理として利用できるように、それらの処理を行わないようにするパラメータ等を用意できないでしょうか。

https://github.com/vrm-c/UniVRM/blob/fd3324494baa04b4011dc0a1746334db68474816/Assets/UniGLTF/Editor/MeshUtility/MeshUtility.cs#L31-L32
https://github.com/vrm-c/UniVRM/blob/fd3324494baa04b4011dc0a1746334db68474816/Assets/UniGLTF/Editor/MeshUtility/MeshUtility.cs#L236-L249

**Comment by ousttrue** [comment]
なるほど。
調べてみます。

**Comment by ousttrue** [comment]
`GameObject.Instantiate(go)` しているのはオリジナルを保全するためにコピーに対して処理する意図があります。
コピーするのをやめると、オリジナルが変更されるだけでなく`ctrl-Z`  したときに `undo` が自然にふるまうように配慮するなどの追加の工数がかかります。コピー化オリジナルの不要な方を削除してください。

`AssetDatabase.CreateAsset()` はやらないと、Unity を再起動したときに MIssing になります。
これも不要であれば処理後に削除してください。

`VRM作成時の前処理` というのがいかなる状況なのかわからないので、なんとも言えないのですが、
エディタ時(not play)の処理としては妥当だと判断しました。

**Comment by esperecyan** [comment]
検討有り難うございます。

具体的には、https://github.com/vrm-c/UniVRM/issues/1515 と同じことを実現するための、カスタムのVRMエクスポート処理を行うエディタ拡張において、インスタンスなメッシュを改変する一連の処理の一部として利用したいです。
https://github.com/esperecyan/VRMConverterForVRChat/blob/eb29156d1732f4df5c5d980373d6c21666cea7b8/Editor/VRChatToVRM/VRChatToVRMConverter.cs#L116-L122
現在は同クラスのv0.53.0時点のコードを改造したものを利用していますが、中身を理解できていないので、できればMeshUtility側の公開APIを直接利用して、MeshUtility側でアップデートが行われた際にも追従できればと考えています。
https://github.com/esperecyan/VRMConverterForVRChat/blob/v32.0.0/CombineMeshesAndSubMeshes/Editor/CombineMeshesAndSubMeshes.cs#L298-L709

> `GameObject.Instantiate(go)` しているのはオリジナルを保全するためにコピーに対して処理する意図があります。
> コピーするのをやめると、オリジナルが変更されるだけでなく`ctrl-Z` したときに `undo` が自然にふるまうように配慮するなどの追加の工数がかかります。コピー化オリジナルの不要な方を削除してください。

一連の処理の一部として利用したいため、すでにコピー済みのインスタンスに対して処理するので、できればスクリプト向けのAPIとしてはそういった処理向けのオプションがあれば便利だと考えていました。

> `AssetDatabase.CreateAsset()` はやらないと、Unity を再起動したときに MIssing になります。
> これも不要であれば処理後に削除してください。

Unityエディタでアセットへメッシュを新規作成する処理には時間がかかるので、できれば作って消すというのは避けたいです。

**Comment by ousttrue** [comment]
MeshUtility.SeparationProcessing の仕様を変更し、

* コピーしない(呼び出し側で、必要に応じてコピーする)
* MeshをAsset化しない
* Meshのリストをreturnする(呼び出し側で、必要に応じてAsset化したりDestroyする)

です。
これで、うまく行くと思います。

**Comment by ousttrue** [comment]
`v0.97.0`

**Comment by esperecyan** [comment]
期待した通りの挙動で、問題なくツールへ組み込むことが出来ました。ありがとうございます！
