### ISSUE TITLE
VRMのExportSettingsで、メッシュ分割を最適化するオプションを追加

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#1515]
VRMのExportSettingsで、メッシュ分割をランタイムでの読み込み向けに最適化する、以下のようなオプションを提供できないでしょうか。

1. FirstPersonFlagごとにメッシュを統合
1. FirstPersonFlagがAutoになっているメッシュを、BothとThirdPersonOnly(head)へ分割し、それぞれFirstPersonFlagを設定し直す
1. 各メッシュをシェイプキーの有無で分割

**Comment by ousttrue** [comment]
検討します。
込み入った処理(処理や条件が複雑 や 説明するのが大変)の場合は、Export する前にシーンで解決してもらう方針です。

**Comment by ousttrue** [comment]
`v0.116` で統合リストを明示する方式を導入します。
vrm ではデフォルトで FirstPerson 毎に統合グループが設定されます。
