### ISSUE TITLE
cannot import VRM when texture name have InvalidFileNameChars.

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#152]
https://docs.microsoft.com/ja-jp/dotnet/api/system.io.path.getinvalidfilenamechars?view=netframework-4.7.2
ﾃｸｽﾁｬnameに上記に示されるような文字(0x00~0x31等)が入っている場合、VRMファイルがインポートできません。

**Comment by hiroj** [comment]
#152 こちらと一緒に修正致します。

**Comment by PoChang007** [comment]
インポート時に制御文字のエスケープを追加した。
