### ISSUE TITLE
特定のアセットとの併用でVector3の定義の重複エラー

### ISSUE THREAD

**Issue by meganeroppy** [vrm-c/UniVRM#1521]
Unity2021.2にて、
UniVRM 0.94とUnity Asset Store のStreamingSpeechRecognition
(https://assetstore.unity.com/packages/add-ons/machinelearning/streaming-speech-recognition-using-google-cloud-vr-ar-mobile-des-115172)
というアセットと一緒に使おうとすると、以下のような競合エラーが発生し、解消することができません。

error CS0433: The type 'Vector3' exists in both 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

同様のエラーコードを含む投稿は既にあるようですが、解決策が分からないまま閉じられてしまっていたので新たに投稿させていただきました。

**Comment by ousttrue** [comment]
報告ありがとうございます。
`'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`
と
`'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`
の両方に、`System.Numerics.Vector3` が入っているというエラーのようです。
> error CS0433: The type 'Vector3' exists in both 'System.Numerics.Vectors

たぶん、`UniVRM` 関係無いと思われます。
Unity から `System.Numerics.Vector3` を取り除くのは無理なので、
StreamingSpeechRecognition？から `System.Numerics.Vector3` を取り除けばなおるかもしれません。

Unity のバージョン等は関係あるかもしれません。
昔のバージョンは、`System.Numerics` が無いです。

**Comment by meganeroppy** [comment]
ご回答ありがとうございます。

StreamingSpeechRecofnition（以下SSR）がインポートされているプロジェクトにUniVRM0.94をインポートすると前述のエラーとなるのは何度も試しているので間違いありません。
仰る通りSystem.Numerics.Vector3はUnityにデフォルトでも入っているものなので、UniVRMを入れた時にこのエラーになる理屈はよくわかっておりません。
SSRの方のSystem.Numerics.Vector3を削除するとエラーは消え、ひとまず問題なく動作します。
ただこの変更によって追々挙動に支障が起きることを懸念し、念のため他に解消方法が無いか知りたくここに投稿した次第です。

一旦SSRの方のSystem.Numerics.Vector3を削除する対応でしばらくしのごうかと思います。

コメントありがとうございました！
