### ISSUE TITLE
VRMファイルへシェイプキーのアニメーションが出力される

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#1522]
Animatorにシェイプキーのアニメーションが含まれている場合、これがVRMファイルへ出力されますが、これは仕様でしょうか。

unitypackageと出力後のVRMファイル
[VRM Animation Test.zip](https://github.com/vrm-c/UniVRM/files/8046356/VRM.Animation.Test.zip)

また、空のアニメーションクリップが含まれている場合、animationsにnameプロパティのみが含まれる壊れたファイルが出力されます。

## 環境情報

 - UniVRM version: `0.95.1`
 - Unity version: `Unity-2021.2.10f1`
 - OS: `Windows 10`

**Comment by ousttrue** [comment]
報告ありがごうございます。
VRMで、Animation のエクスポートをスキップするように修正します。

**Comment by ousttrue** [comment]
`v0.96.0`
