### ISSUE TITLE
Issues with Baked Blendshapes and Proxies

### ISSUE THREAD

**Issue by DissonantAU** [vrm-c/UniVRM#1526]
## Environments (please complete the following information):

 - UniVRM version: `0.66.0` & `0.92.0`
 - Unity version: `Unity-2019.4.31f1`
 - OS: `Windows 10`

## Describe the bug

I'm having an issue with Blendshapes not being handled properly when baked on a model
As per: https://vrm.dev/en/docs/univrm/blendshape/univrm_bake_blendshape/

For example: The model has Eyebrows as Blendshapes to toggle on/off (Off by default)

- If I set them On (100%) for the Neutral Expression and Apply it in Exporter (Apply selected BlendshapeClip) or set it manually on the model under Blendshapes, after exporting it seems random BlenshapeProxies Break - EG in VSeeFace, and Re-importing to Unity, some expressions revert to default Blendshapes (0%/Off)
- Even setting the shapes manually doesn't work.
- Looking at the reimported blendshapes shows no eyebrows: the blendshape seems to have been inversely linked to another slider (Eg Sad Eyes Blendshape being on makes the eyebrows disappear, and they reappear if I set Sad Eyes to 0% - I can even see the eyebrows shrink as though I'm moving their slider)
- If I disable Eyebrows (0%) and reexport, the eyebrows work correctly - baking them on just seems to break something
- I'd rather not leave them off, since that causes other issues (Eg in VSF changing animation causes the eyebrows to flash on/off)

No Eyebrows Baked:
![image](https://user-images.githubusercontent.com/33020221/153864853-f7d389af-dbae-41a4-b561-c21ef67a62ec.png)
Sorrow Blendshape (Eyebrows show correctly
![image](https://user-images.githubusercontent.com/33020221/153864812-fff09b04-1d63-4e5f-acf6-28855ec360ba.png)

Eyebrows baked:
![image](https://user-images.githubusercontent.com/33020221/153865063-223ed550-777e-4f38-a410-908b814b6eaa.png)
Sorrow BlendshapeProxy (Eyebrows missing!)
![image](https://user-images.githubusercontent.com/33020221/153865181-26313e7a-319a-417f-852f-599d92b0e6d1.png)
Slider is at 100%
![image](https://user-images.githubusercontent.com/33020221/153865206-6ea0239e-e693-4617-ab89-67d59e689cd7.png)
Different Blendshape set to 0=eyebrows back!
![image](https://user-images.githubusercontent.com/33020221/153865348-9e7a2e86-7818-4a84-8781-768f5e05910b.png)
Set to 6.5, Eyebrows start coming back - can confirm the other blendshape isn't covering the eyebrows, they are actually shrinking
![image](https://user-images.githubusercontent.com/33020221/153865402-6ea57b5f-25c7-412c-aae2-faa99f9f98dc.png)
Note - eyebrows blendshape being set to 0 or 100% has NO effect anymore! (Below set to 0% Sad Eyes, also no longer effects Neutral also no longer but I suppose that's expected with it being baked)
![image](https://user-images.githubusercontent.com/33020221/153865538-2bc5ba50-bb55-4d2a-b73a-5e2510661367.png)

I'm assuming there's a bug with how the baking interacts with proxies?

To reproduce:
Unfortunately I don't know when/how models are effected, in this case a blendshape is baked, then other blend shapes in a similar area seem to 'link'?
1) Export model with a blendshape on, Pose Freeze enabled and Blendshape Proxies effecting other Blendshapes in area (with the prior blendshape unaffected
2) Import Model - check Blendshape Proxy, and Enabled

Unfortunately I can't share the model due to licensing (Winterpaw's VRChat Canine Feminine Expanded Version)
I'm playing with converting another (Free/Open) VRC model to VRM, I'll post it here if I have the same issue

As an aside: 
It would be nice if there was a way to set 'default' blendshape values across all proxies and have them being shown correctly in Programs like VSeeFace (ie the preview before load) *without* baking them in, allowing more flexible proxies that won't work with baked models

Assistance would be appreciated

**Comment by lithiumfox** [comment]
Also experiencing this issue (or at least something similar) as well in other applications like Virtual Motion Capture (even when importing back to unity it can cause odd issues with the textures/shape/etc) 

Example before and after baking body examples:

![image](https://user-images.githubusercontent.com/4545555/156869649-ff0ed728-036e-40f9-92fc-ccaa66a086e2.png)

In this instace, what I was trying to do was use modifiers built into the FBX that allow for re-shaping of the model, such as shortening hair, decreasing size of body parts (meaning no need to use transparent textures to prevent clipping) etc.

**Comment by ousttrue** [comment]
blendshape bake changes the state when all values ​​are 0. If side effects occur due to the combination, I'm sorry I can't find out without specific data, so I don't know.

**Comment by ousttrue** [comment]
#1870
