### ISSUE TITLE
cannot import VRM when texture name too long.

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#153]
texture name が長すぎるとVRMファイルがインポートできません。
windowsのファイルパスにはデフォルトで長さ制限があります。
https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation

**Comment by hiroj** [comment]
Export時に長すぎるファイル名に対して警告するよにします。

**Comment by PoChang007** [comment]
テクスチャ名前の長さ制限は６４に設定しています。
