### ISSUE TITLE
Cannot Import .VRM model

### ISSUE THREAD

**Issue by Yi-Jiahe** [vrm-c/UniVRM#1537]
## Environments (please complete the following information):

 - UniVRM version: `0.95.1`
 - Unity version: `Unity-2020.3.28f1`
 - OS: `Windows 10`

## Describe the bug

Importing the .VRM by dragging and dropping as described in https://vrm.dev/en/docs/univrm/import/univrm_import/ doesn't do anything; all I get in the folder is the .VRM file.

![image](https://user-images.githubusercontent.com/47210363/154827828-ead7b139-1ce1-412b-a9bb-2a9ef5a82e3f.png)

Using VRM0 > Import from VRM 0.x creates a a bunch of folders and a prefab 
![image](https://user-images.githubusercontent.com/47210363/154827805-47576e6f-6471-41c2-9fe7-91839c7ba2db.png)

But trying to open the Prefab gives 
```
Opening Prefab Mode failed: The Prefab at 'Assets/StreamingAssets/Fluffy/Fluffly.prefab' is broken.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

The .VRM was exported from VRoid Studio and opens in OpenSeeFace.
[Fluffly.zip](https://github.com/vrm-c/UniVRM/files/8103403/Fluffly.zip)

**Comment by ousttrue** [comment]
Thank you for your report.
`StreamingAssets` is special folder.
Try it in another folder.

**Comment by ousttrue** [comment]
`StreamingAssets` trouble. not bug.
