### ISSUE TITLE
Obsolete link shown in Meta inspector GUI

### ISSUE THREAD

**Issue by infosia** [vrm-c/UniVRM#1538]
Severity: Low

Obsolete link `https://github.com/dwango/UniVRM/releases` shown in Meta inspector GUI. `https://github.com/vrm-c/UniVRM/releases` might be better I guess.

![Capture](https://user-images.githubusercontent.com/1661068/154834655-d98232c9-73a9-47c0-8b45-143c0a273c36.PNG)

https://github.com/vrm-c/UniVRM/blob/8303fea05e9622d14614cca6ee0e70acde508bcd/Assets/VRM/Editor/Meta/VRMMetaObjectEditor.cs#L179

**Comment by ousttrue** [comment]
報告ありがとうございます。
`dwango` を `vrm-c` に修正しました。

**Comment by ousttrue** [comment]
`v0.97.0`
