### ISSUE TITLE
UniVRM Prefered Import Type to work in URP/HDRP 

### ISSUE THREAD

**Issue by breadnone** [vrm-c/UniVRM#1539]
Hi, I'm in the middle of making open source Visual Novel engine called [VF-Roid](https://github.com/breadnone/VF-Roid) for VRoid in Unity3D and will integrate file formats that UniVRM supported.

My question is, what are the preferred file types when importing VRoid model into Unity3D via UniVRM for both URP/HDRP? I've used UniVRM before for test projects, and it imported into .vrm format. Is .vrm the preferred format in the future?

EDIT: Title correction

**Comment by ousttrue** [comment]
The file type (extension) of vrm will be `.vrm` for now.
With glb, the application can open the file and then determine its contents.
