### ISSUE TITLE
BlendShpae import bug `0.96.0`, `0.96.1`

### ISSUE THREAD

**Issue by Nocifia** [vrm-c/UniVRM#1554]
## Environments (please complete the following information):

 - UniVRM version: `0.86.0`
 - Unity version: `Unity-2019.4.31f1`
 - OS: `Windows 10`

## Describe the bug
Hello,

The blendshape work on the fbx but after the export to VRM , on the prefab none of the blenshape works
fbx version :
![fbx](https://user-images.githubusercontent.com/100374380/155578351-eba145ac-6618-4675-87ce-a82dc90fbc2e.PNG)

vrm version : 
![VRM](https://user-images.githubusercontent.com/100374380/155578435-1509e086-a49b-4d2f-baf5-235340657d51.PNG)

both have the same blendshape active : 
![blendshape](https://user-images.githubusercontent.com/100374380/155578518-1b1b24be-802b-47b3-ab93-1a9b1de97d7e.PNG)

the export restult from fbx that created the vrm one : 
![export1](https://user-images.githubusercontent.com/100374380/155578773-f0e94b8f-3e8a-4b88-aec9-a821c887aea7.PNG)

and the warning message if pose frezze is uncheck : 
![export2](https://user-images.githubusercontent.com/100374380/155578831-960b7328-3dfb-4736-a26a-cf40a7d22f71.PNG)

i look into a lot of blendshape issues here and on other forum but none got all blendshape not working after export.
So if you got an idea of what cause that issue, thank you.

**Comment by TigerHix** [comment]
Exact same issue here. Also on v0.96.0, Unity 2021.1.21f1. The blend shape list is correctly preserved when exporting to VRM, but none of the blend shapes _actually_ does anything.

**Comment by TigerHix** [comment]
Can confirm rolling back to v0.95.1 fixed this issue.

**Comment by esperecyan** [comment]
@ousttrue  UniVRM-0.96.0以降、Unityエディタ上でシェイプキーが完全にインポートされなくなっています。

以下のVRMファイルでも確認できます。
https://github.com/vrm-c/UniVRM/blob/c55edd80109f6b7589293123e5b0f8a1ea79e167/Tests/Models/Alicia_vrm-0.51/AliciaSolid_vrm-0.51.vrm

**Comment by ousttrue** [comment]
Thank you for reporting.
This issue is caused by #1535.
`v0.96.0` and `v0.96.1` has this problem.

**Comment by ousttrue** [comment]
Fixed this bug by #1571.
I am working on `v0.96.2`.

**Comment by NekoStudios** [comment]
unfortunately I have the same problem, I use the version UniVRM-0.96.2_b978 and it’s the same avatar when doing that these blendshape no longer works

**Comment by esperecyan** [comment]
I have confirmed that shape keys are imported successfully in UniVRM-0.96.2.

Also, after importing the following VRM, exporting and importing again worked correctly.

https://github.com/vrm-c/UniVRM/blob/c55edd80109f6b7589293123e5b0f8a1ea79e167/Tests/Models/Alicia_vrm-0.51/AliciaSolid_vrm-0.51.vrm

**Comment by NekoStudios** [comment]
I think there’s confusion, I’m speaking for another model not this one

**Comment by ousttrue** [comment]
@NekoStudios 

The bug is caused in import.

```
base model --> export(`v0.96.0` `v0.96.1`) --> exported.vrm <= this is OK.
                                                                                    |
                                                                                    | import(`v0.96.0`, `v0.96.1`)
                                                                                   v
                                                                         exported.prefab <= this has bug
```

Please reimport, after `v0.96.2` installed.

**Comment by ousttrue** [comment]
![context_menu](https://user-images.githubusercontent.com/68057/156728040-d61631f4-5b17-4e7d-ab8d-98126575ce2c.jpg)
right click `vrm file` and execute `reimport`
