### ISSUE TITLE
VRMエクスポート時のウィンドウが正常に表示されない

### ISSUE THREAD

**Issue by Rikurus** [vrm-c/UniVRM#1556]
## 環境情報

 - UniVRM version: `0.96.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## バグについて

* バグの内容
パーティクルシステムを入れた状態でVRMエクスポートを行おうとすると、
VRMエクスポートのウィンドウが正常に表示されなくなる。
※VRMではパーティクルシステムが非対応であることは存じております

* ConsoleLog
[Editor.log](https://github.com/vrm-c/UniVRM/files/8142745/Editor.log)

* スクリーンショット
![image](https://user-images.githubusercontent.com/51016253/155752932-e17594af-a0cb-49f2-a82d-0d2aa7a3eab8.png)

* 再現方法
パーティクルシステムをVRMアバター化したいアバターに設定し、
その状態でVRMエクスポートを実行する。

**Comment by ousttrue** [comment]
報告ありがとうございます。
調査します。

**Comment by ousttrue** [comment]
MeshRenderer と SkinnedMeshRenderer 以外の Renderer (ParticleSystemRenderer など)でエラーにならないように修正しました。

**Comment by ousttrue** [comment]
`v0.96.1`
