### ISSUE TITLE
UniVRM-0.96.0でビルドエラーが起きるようになった: 'AnimationExporter' does not contain a definition for 'GetAnimationClips'

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#1557]
## 環境情報

 - UniVRM version: `0.96.0`
 - Unity version: `Unity-2021.2.13f1`
 - OS: `Windows 10`

## バグについて

* バグの内容  
  ビルドエラーが発生する。
* ConsoleLog  
  > Assets\UniGLTF\Runtime\UniGLTF\IO\gltfExporter.cs(249,43): error CS0117: 'AnimationExporter' does not contain a definition for 'GetAnimationClips'
  > Assets\UniGLTF\Runtime\UniGLTF\IO\gltfExporter.cs(253,43): error CS0117: 'AnimationExporter' does not contain a definition for 'GetAnimationClips'
  > Assets\UniGLTF\Runtime\UniGLTF\IO\gltfExporter.cs(274,60): error CS0117: 'AnimationExporter' does not contain a definition for 'Export'
* スクリーンショット  
  ![](https://user-images.githubusercontent.com/3625160/155836218-b6ecff78-8643-422c-936f-314f0594a78e.png)
* 再現方法
  1. Unity 2021.2.13f1で新規プロジェクトを作成
  2. [UniVRM-0.96.0_9693.unitypackage](https://github.com/vrm-c/UniVRM/releases/download/v0.96.0/UniVRM-0.96.0_9693.unitypackage)をインポート
  3. ビルドして実行

**Comment by ousttrue** [comment]
報告ありがとうございます。
調査します。
#1543 で `#if UNITY_EDITOR` をやめたのが関係ありそうです。

**Comment by ousttrue** [comment]
AnimationClip Export 処理の Editor でしか動かない部分を editor の asmdef に移動し、ビルドでエラーが出ないことを確認しました。

**Comment by ousttrue** [comment]
`v0.96.1`

**Comment by esperecyan** [comment]
確認しました。ありがとうございます。
