### ISSUE TITLE
Support for EXT_meshopt_compression of GLTF. or KHR_mesh_quantization 

### ISSUE THREAD

**Issue by butaixianran** [vrm-c/UniVRM#1558]
Hi, I'm using this greate project for importing gltf/glb into Unity.   

But a problem with gltf format is file size and data performance, when with shape keys. So, I open an issue to gltf team, and they told me, for game engine, I could use a gltf compress tool called: [gltfpack] 
 (https://github.com/zeux/meshoptimizer/tree/master/gltf)  

I checked the tool gltfpack, it is pretty good for game engine.   

But to read its output .glb file, gltf importer need to support gltf extension: KHR_mesh_quantization  

And that's level 1.   

To do a further compression, which can take a 50mb glb file down to 23mb.  

Gltf importer need to support "EXT_meshopt_compression" extension to read it.  
There is an official Unity package for this format:  
[https://docs.unity3d.com/Packages/com.unity.meshopt.decompress@0.1/manual/index.html](https://docs.unity3d.com/Packages/com.unity.meshopt.decompress@0.1/manual/index.html)  

So, it will be very good if this project would like to support EXT_meshopt_compression.   

Or, al least support KHR_mesh_quantization will be fine.  

Thanks.

**Comment by ousttrue** [comment]
Thank you for reporting.
It seems easier than draco, so I'd like to implement importer someday.

https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_mesh_quantization

**Comment by ousttrue** [comment]
KHR_mesh_quantization `v0.99`.
I'm sorry, but I don't plan to implement EXT_meshopt_compression.

**Comment by butaixianran** [comment]
KHR_mesh_quantization is good enough. thanks
