### ISSUE TITLE
colorspaceをgammaに設定するとLinearに設定変更を促すダイアログが表示され閉じることができなくなる

### ISSUE THREAD

**Issue by KazukiKuriyama** [vrm-c/UniVRM#1559]
## 環境情報
 - UniVRM version: `0.96.0`
 - Unity version: `Unity-2020.3`
 - OS: `Windows 11`

## バグについて
* バグの内容
WebGL 1.0 はColorSpaceのLinear設定に非対応のため、gammaに設定する必要があるが、gammaに設定するとLinearに設定変更を促すダイアログが表示され閉じることができなくなる。
この状態だとマテリアルやテクスチャの選択時にポップアップされる他のモーダルが表示されなくなる。

* なぜWebGL1.0を使用するか？
スマートフォンブラウザでのWebGLアプリの表示はWebGL1への切り替えが必須のため
https://qiita.com/yuji_yasuhara/items/237a571b9ba8be3d0cbd

* スクリーンショット
![image](https://user-images.githubusercontent.com/64897247/155912164-c6b6edae-9c22-4c3b-b847-271994db2594.png)

* 再現方法
1. プラットフォームをWebGLに変更する。
2. PlayerSettings>Player>OtherSettingsからcolorspaceをgammaに変更する
3. WebGL1.0を追加し、WebGL2.0を削除する。
4. Linearに変更を促すダイアログが表示される
5. ダイアログの✕ボタンを押す。
→本事象が発生し、再度ダイアログが表示され閉じることができなくなる。

* 関連issuu
https://github.com/vrm-c/UniVRM/issues/466

**Comment by ousttrue** [comment]
報告ありがとうございます。
C# symbol など、回避手段を作ります。
