### ISSUE TITLE
Convert other materials automatically

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/UniVRM#1566]
### Description

技術委員会で話題に挙げさせていただいた内容です。

FBXやglbなどからモデルをインポートした際に、マテリアルがStandard MaterialあるいはUnlitになってインポートされる場合が多いと思います。
それらのマテリアルを自動的に良い感じのパラメタへ変換するユーティリティ・ウィザード等があると便利かと思いました。

### Possible Solution

- Color TextureやAlbedo (`_MainTex`) をShade Color Textureにコピー
- Shade Colorをいい感じに変換
- AlphaModeを適切に変更
- doubleSidedを適切に変更
- などなど。抜け漏れまだありそうな気がします

**Comment by ousttrue** [comment]
Standard/Unlit から MToon にアップグレード？してついでにデフォルト値を設定するという感じでしょうか。

* Color TextureやAlbedo (_MainTex) をShade Color Textureにコピー。これはプロパティ名が同じなのでシェーダーを切り替えた時点で何もしなくても動作しそう
* Shade Colorをいい感じに変換。ピンクっぽいデフォルト色を他の色に変えることはできますが、`いい感じ` になるかどうか
* AlphaModeを適切に変更。これは元を引き継ぐ？
* doubleSidedを適切に変更。これも元を引き継ぐ。Standard になった時点でわからなくなりそう

という感じで、Standard/Unilt になった時点で元の適切な値というのが、コンピューターには分からないんでないかと思うのです。Unity では元の値、つまり fbx なり glb になる前のマテリアルにはアクセスできないので・・・。
