### ISSUE TITLE
Access To Face Expressions from code

### ISSUE THREAD

**Issue by breadnone** [vrm-c/UniVRM#1574]
How can I access all these properties from code?   
![image](https://user-images.githubusercontent.com/64100867/156351516-716bc77a-8849-490f-a283-ce1564365db6.png)  

Most of these attributes/functions in UniVRM are not well documented, if any.

**Comment by ousttrue** [comment]
In UniVRM, SkinnedMeshRenderer's BlendShape is operated via VRMBlendShapeProxy.
I think you can work with SkinnedMeshRenderer's BlendShape after every frame VRMBlendShapeProxy, but it's not supposed.
Modifications to control the processing order may be required.
