### ISSUE TITLE
In URP, imported gltf's material's shader is Standard, which should be URP Lit.

### ISSUE THREAD

**Issue by butaixianran** [vrm-c/UniVRM#1575]
## Environments:

 - UniVRM version: `0.96.2`
 - Unity version: `Unity-2021.2.13`
 - OS: `Windows 11`

## Describe the issue
In URP, importing a gltf file, every material's shader type is Standard(which should be URP/Lit), so none of those materials works.  
![](https://raw.githubusercontent.com/butaixianran/lib-links/master/img/urp_gltf_shader_issue_standard.jpg)  

If I just convert it to URP/Lit, then I lose all Base Color Textures. Because URP Lit Shader uses a different name for base color.  
![](https://raw.githubusercontent.com/butaixianran/lib-links/master/img/urp_gltf_shader_issue_urplit.jpg)

**Comment by ousttrue** [comment]
Thank you for reporting.

Well I do not know.
What is your gltf material?

**Comment by butaixianran** [comment]
I don't understand, what you mean "what is your gltf material".

I export a model from blender into glft file, then import it into a URP project of Unity.

Any material with color texture should get the same result.

**Comment by ousttrue** [comment]
The recent version has improved URP, so please try it.
