### ISSUE TITLE
Improve glTF plugin compatibility with newer ScriptedImporterAttribute syntax

### ISSUE THREAD

**Issue by bitinn** [vrm-c/UniVRM#1576]
**Is your feature request related to a problem? Please describe.**

I am testing interoperability across various glTF plugins for Unity, and run into an issue between multiple ScriptedImporter declaring itself as default importer for `glb` or `gltf` file type.

Unity will disable all importers for `glb` and `gltf` files upon seeing this, and [an error will be logged](https://github.com/Unity-Technologies/UnityCsReference/blob/master/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs#L116):

> Multiple scripted importers are targeting the extension 'glb' and have all been rejected: ...

**Describe the solution you'd like**

[This fork of UnityGLTF](https://github.com/prefrontalcortex/UnityGLTF) is the only plugin that doesn't conflict with other glTF importer via the use of `overrideExts` in ScriptedImporterAttribute (an added feature since 2020.2).

https://docs.unity3d.com/2022.2/Documentation/ScriptReference/AssetImporters.ScriptedImporterAttribute.html
https://github.com/prefrontalcortex/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Editor/Scripts/GLTFImporter.cs#L24

**Describe alternatives you've considered**

N/a

**Additional context**

I have tested this change to work:

![Screenshot 2022-03-04 145217](https://user-images.githubusercontent.com/1484279/156717886-f64ac773-8c8e-4751-821f-1e02cc01d027.jpg)

Note: there is however a current problem that cause Importer dropdown to not show up, we are waiting for Unity to address this issue or provide workaround:

https://forum.unity.com/threads/scriptedimporterattribute-handling-blocks-multiple-importers-for-the-same-file-type.1248427/
https://github.com/prefrontalcortex/UnityGLTF/issues/37

**Comment by bitinn** [comment]
Side note: these are the compatibility of GLB file across various popular glTF plugins.

![Export-Table](https://user-images.githubusercontent.com/1484279/156728714-733d82b1-2289-4bdb-bb6e-575f3955c0e2.jpg)

**Comment by ousttrue** [comment]
Thank you for reporting.
`overrideExts` looks good.

The orientation of the model is affected when converting gltf (right handed) and unity (left handed).
UniGLTF has historically used z-axis inversion for both import and export.
UniGLTF can change the axis to invert.

- import https://vrm.dev/en/gltf/glb_import#reverseaxis
- export https://vrm.dev/en/gltf/glb_export.html

The model `indices` exported by glTFast appear to be failing.
Perhaps `UniGLTF` does not have an implementation of the` unsigned byte` type.

**Comment by ousttrue** [comment]
overrideExts  will be in `v0.100.0`
