### ISSUE TITLE
CanExportAsEditorAssetFile (ArgumentOutOfRangeException)

### ISSUE THREAD

**Issue by VibuTV** [vrm-c/UniVRM#1583]
Thats the error thing i get and ive been fucking with this for 3 hours and i cant find a fix or anything

Specified argument was out of the range of valid values
ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
VRMShaders.EditorTextureSerializer.CanExportAsEditorAssetFile (UnityEngine.Texture texture, VRMShaders.ColorSpace exportColorSpace) (at Assets/VRMShaders/GLTF/IO/Editor/Texture/Exporter/EditorTextureSerializer.cs:45)
VRMShaders.TextureExporter.ConvertTextureSimple (UnityEngine.Texture src, System.Boolean needsAlpha, VRMShaders.ColorSpace exportColorSpace) (at Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/TextureExporter.cs:149)
VRMShaders.TextureExporter+<>c__DisplayClass7_0.<RegisterExportingSimple>b__0 () (at Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/TextureExporter.cs:61)
VRMShaders.TextureExporter.Export () (at Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/TextureExporter.cs:34)
UniGLTF.gltfExporter.Export (VRMShaders.ITextureSerializer textureSerializer) (at Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs:345)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings, System.Collections.Generic.List`1[T] destroy) (at Assets/VRM/Editor/Format/VRMEditorExporter.cs:229)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings) (at Assets/VRM/Editor/Format/VRMEditorExporter.cs:24)
VRM.VRMExporterWizard.ExportPath (System.String path) (at Assets/VRM/Editor/Format/VRMExporterWizard.cs:299)
UniGLTF.ExportDialogBase.EndGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:161)
UniGLTF.ExportDialogBase.OnGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:82)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.DockArea.OldOnGUI () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <344226e341014466b33f0c0fa34fcef5>:0)

**Comment by ousttrue** [comment]
Thank you for reporting.

There are texture types that are not supported in the export model. The texture is included by Unknown Material. Replace the unIVRM-supported materials (standard, no lights, MToon) and try again.

I might be able to make it display an easy-to-understand error message.

**Comment by ousttrue** [comment]
`v0.99` update error message
