### ISSUE TITLE
[UniGLTF] MeshIntegrator Wizard、MeshIntegratorUtilityで全メッシュを統合したい

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#1590]
MeshProcessing WizardのMeshIntegator、およびパブリックAPIの MeshIntegratorUtility.Integrate() メソッドで、シェイプキーのあるメッシュ・ないメッシュを分けずに統合するオプションを用意できないでしょうか。

https://github.com/vrm-c/UniVRM/blob/v0.97.0/Assets/UniGLTF/Runtime/MeshUtility/MeshIntegratorUtility.cs

![](https://user-images.githubusercontent.com/3625160/158589563-a8eaca32-a8d8-49c6-93cc-a9e926876d00.png)

**Comment by ousttrue** [comment]
`v0.99.0` で更新されます。
