### ISSUE TITLE
unable to export due to whitespace

### ISSUE THREAD

**Issue by SurvivalR** [vrm-c/UniVRM#1591]
## Environments (please complete the following information):

 - UniVRM version: `0.97.0`
 - Unity version: `Unity-2019.4.31f`
 - OS: `Windows 11`

when attempting to export the author section does not have a type box and an error says "all authors is whitespace"
![image_2022-03-18_034203](https://user-images.githubusercontent.com/101864139/158966262-04cb80b1-9295-42b8-8b09-1dc7b2f1d9a6.png)

**Comment by walbermr** [comment]
Hi, could you please give a hint on how to solve this issue?
