### ISSUE TITLE
Update When Offscreenが無効なため、アバターの部位が消えることがある => rootBone を推定して設定するオプションを追加する

### ISSUE THREAD

**Issue by FujiSunflower** [vrm-c/UniVRM#1595]
## 環境情報

 - UniVRM version: `0.89.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## 不具合の内容
VRMアバターのSkinned Mesh RendererのUpdate When Offscreenが無効の状態でインポートされるため、VRoidの顔の部位などが消えることがある。

## 不具合の再現方法
Animatorでアニメーションさせた状態で部位分けされているVRMをカメラで撮影する。

## スクリーンショット
![image](https://user-images.githubusercontent.com/20571538/160361010-0c7de00e-8087-40e2-b277-a7185ba15436.png)
![image](https://user-images.githubusercontent.com/20571538/160361053-8c32590e-5684-4d18-9f60-20138e05847b.png)

**Comment by saturday06** [comment]
本事象では髪が消えて胴体が残っています。Unityはバウンディングボックス計算にアニメーション情報を用いるらしいので、Humanoidアニメーションが有効な胴体のメッシュのバウンディングボックスが大きく計算され、アニメーションの無い髪は小さく計算されていて、その大きさの違いによりカメラを近づけると髪が先に消えるけど顔と胴体は残る、という事象に思えます。

**Comment by ousttrue** [comment]
とりあえず、すべての SkinnedMeshRenderer の Update When Offscreen を有効にするのが回避策で
まとめて設定する関数があります。
- https://vrm-c.github.io/UniVRM/ja/api/0_77_runtime_import.html?highlight=offscreen
などを参考にしてください(UniVRMのバージョンにより関数の生えている場所が変わっている)

問題は、`SkinnedMeshRenderer` を設定せずに適切にカリングされるようにすることで
メッシュの構成によっては起こります。

下のスクリーンショットの白い箱が `SkinnedMeshRenderer` が OFF のときの可視判定です。

<img width=300 src=https://user-images.githubusercontent.com/68057/162668486-197b9a56-2e60-4e17-a637-feaddbce10be.jpg>

これは初期化したときに Mesh の BoundBox + `SkinnedMeshRenderer.rootBone` で作られて、
以降フレームが進んで Mesh が変形しても形は追随しません。位置は回転は追随します。
で、間違った SkinnedMeshRenderer.rootBone を設定すると下のようになります。

<img width-300 src=https://user-images.githubusercontent.com/68057/162668922-3bcf4d3a-7669-4f85-bea6-860aedba968a.jpg>

当たり判定と、メッシュの場所が一致しない可能性があります。
例えば、SkinnedMeshRenderer.rootBone に root 位置の transform が指定されていると
足元にカリング判定のボックスが出るかもしれない。

SkinnedMeshRenderer.rootBone には、gltf.skin.skeleton を対応させている(いた？)のですが、
これは gltf と unity とで意味合いの異なる別の概念なのでよろしくない。

https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#schema-reference-skin

ちなみに rootBone を null にするとバウンディングボックスが足元に行きました。この状態になっていそうな気がします。
<img width=300 src=https://user-images.githubusercontent.com/68057/162670146-e2e3de36-8df5-49a8-9688-b8f141368f44.jpg>

Unity においては、SkinnedMeshRenderer.rootBone に SkinnedMeshRenderer.bones から一番根元になるボーンを選ぶのが妥当なような気がしているので
、そのようなインポートオプションを追加しようかと思いました。
デフォルトの動作を変えると、今までうまくいっていたのが逆にうまくいかなくなる場合もあり得るので、
オプションで明示したときのインポート動作を変えれるようにしてみます。

`SkinnedMeshRenderer.rootBone` がややこしくて、

* boundingBox の基準位置の変更
* boneWeight 無い頂点の bone になる？(顔などモーフのために SkinndMeshRendererを使う場合にある)

の２つの機能が兼用で、エッジケースがあります。

**Comment by FujiSunflower** [comment]
ランタイムインポートした際にアプリ開発者側で調整を加えないといけないのが**VRMの理念とずれている気がします。**  
対策法が複数あるのは小さい話題です。
[「人型のキャラクターや3Dアバター」において細かいモデルデータの差違を吸収・統一しアプリケーション側の取り扱いを簡単にする](https://vrm-consortium.org/)

**Comment by FujiSunflower** [comment]
v0.95で実装されたVrmUtilityによりアプリ開発者側での調整が減ったと思われるのでCloseとします。
https://vrm-c.github.io/UniVRM/ja/api/0_95_highlevel.html
