### ISSUE TITLE
about VRM runtime export 

### ISSUE THREAD

**Issue by tomtomtong** [vrm-c/UniVRM#1596]
Hello. I am making an animal generator software by Unity.
https://www.youtube.com/watch?v=77crJW8fqkM

But I meet one issue. The VRM exported does not link the blendshape clips.
Would I do it with script? 

Thank for any reply.

**Comment by ousttrue** [comment]
Thank you for reporting.

I will add a clip manipulation to sample.

**Comment by ousttrue** [comment]
Added sample code to RuntimeExporterSample.

https://github.com/vrm-c/UniVRM/blob/309d13b66219c0d2b6c441f64680a1c09a9a869b/Assets/VRM_Samples/RuntimeExporterSample/VRMRuntimeExporter.cs#L62

`v0.99.0`
