### ISSUE TITLE
Automatic creation of Perfect Sync Visemes

### ISSUE THREAD

**Issue by hikaruAi** [vrm-c/UniVRM#1606]
A QOL feature i will love is function to automatic create the 52 Blendshapes files for Perfect Sync, so i just need to manually assign the model blendshapes
![image](https://user-images.githubusercontent.com/6921914/162854957-1a25e8b8-419f-47b0-b060-cf85a11d9126.png)

References https://malaybaku.github.io/VMagicMirror/en/tips/perfect_sync

**Comment by ousttrue** [comment]
Thank you for reporting.
As a bonus feature to the sample to create and assign BlendShape assets.

**Comment by ousttrue** [comment]
Added a sample automatic BlendShapeClips creation menu.
It is included in `UniVRM_Samples-0.99.0_xxxx.unitypackage`.
