### ISSUE TITLE
Unity 2021.3でPackageManagerからUniGLTFをImportした時にcom.vrmc.gltf/Samples/以下にassembly definitionがないと警告がでる

### ISSUE THREAD

**Issue by yahagi-day** [vrm-c/UniVRM#1627]
## 環境情報

 - UniVRM version: `0.98.0`
 - Unity version: `Unity-2021.3`
 - OS: `Windows 10`

## バグについて
![image](https://user-images.githubusercontent.com/32870950/164627122-43e61d2e-bdc1-4aa2-b4cd-618b55172448.png)

SSIA

**Comment by ousttrue** [comment]
報告ありがとうございます。
調査します。

**Comment by zzxiang** [comment]
これらの警告を消すには[HumanBuilderTest.cs](https://github.com/vrm-c/UniVRM/blob/master/Assets/UniGLTF/Samples/UniHumanoid/HumanBuilderTest.cs)と[RuntimeBvhLoader.cs](https://github.com/vrm-c/UniVRM/blob/a5165a1d2a764bfa78e3ea028be6a5d42b3690f2/Assets/UniGLTF/Samples/UniHumanoid/RuntimeBvhLoader.cs)をどこかのAssembly Definition（asmdefファイル）に追加しないといけないようです。

**Comment by ousttrue** [comment]
`v0.106`
