### ISSUE TITLE
Does not support exporting texture types other than Default and NormalMap

### ISSUE THREAD

**Issue by rackgaming** [vrm-c/UniVRM#1646]
Screenshot: https://prnt.sc/1r0LQmqegNYI
[Editor.log](https://github.com/vrm-c/UniVRM/files/8692951/Editor.log)

UniVRM 0.98

Unity 2021.3.2f1 Personal

Had to change some of the sprites and make them the default channel because UniVRM doesn't know what a 2D sprite is(idk)

Either way, it is not exporting and has been giving me the same error over and over after changing it. Yes it is on linear and not Gamma. Pls help.

**Comment by ousttrue** [comment]
This error is the same as # 1583.
It's a matter of setting the texture importer, not the color space.
UniVRM exporters only support default or normal map texture types.

![TextureType](https://user-images.githubusercontent.com/68057/169011855-e2ce7c6e-67e1-4eca-afd7-db270baea390.jpg)

**Comment by rackgaming** [comment]
Damn that sucks because it makes the model look ugly

**Comment by rackgaming** [comment]
But I also tried going into the different sprites and changing them to default and didn't fix it so idk
