### ISSUE TITLE
MeshIntegratorWizardでExcludesのチェックボックスが反応しない

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#1678]
## 環境情報

 - UniVRM version: `0.99.0`
 - Unity version: `Unity-2022.1.3f1`
 - OS: `Windows 10`

## バグについて

* バグの内容  
 VRM0→MeshIntegratorWizardで、OptionsのExcludesで、「除く」チェックボックスをクリックしてもチェックが入らない。
* ConsoleLog  
  なし
* スクリーンショット  
  ![](https://user-images.githubusercontent.com/3625160/172077208-2565993d-3e9f-4d2e-bfff-a716d5dbace1.png)
* 再現方法
    1. [AliciaSolid_vrm-0.51.vrm](https://github.com/vrm-c/UniVRM/blob/v0.99.0/Tests/Models/Alicia_vrm-0.51/AliciaSolid_vrm-0.51.vrm)をダウンロードして、Unityエディタへインポートする
    2. メニュー「VRM0」→「MeshIntegratorWizard」
    3. 「ルート」で `AliciaSolid_vrm-0.51.prefab` を選択
    4. OptionsのExcludesを展開
    5. いずれかの要素を展開
    6. メッシュの「除く」チェックボックスをクリック
* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)  
  https://github.com/vrm-c/UniVRM/blob/v0.99.0/Tests/Models/Alicia_vrm-0.51/AliciaSolid_vrm-0.51.vrm

**Comment by ousttrue** [comment]
報告ありがとうございます。
修正します。

**Comment by ousttrue** [comment]
`v0.100`
