### ISSUE TITLE
UniVRMでのライセンスの保護

### ISSUE THREAD

**Issue by m-sigepon** [vrm-c/UniVRM#168]
現在、UniVRMではオリジナル製作者がライセンスを設定してVRMとして書き出すと、その後UniVRMで読み込むと誰でも好きなように書き換えることができてしまいます。
これは、ライセンスを設定しても基本的にユーザーの善意に任せている状態でVRMというものを安全に運用するためにはライセンスの設定によって、UniVRMでVRMをインポートした際に特定の項目は編集不能にするためグレーアウトするなどの対策が必要かと思われます。

例えば、VRoid Hubではサービス上アップロード時にモデル製作者さん自身にVRoid Hub向けのライセンスの再設定を行ってもらうという形でサービスを行っています。
しかし、そこにUniVRMで書き換えられたデータをアップロードされるとVRoid Hub側では何がオリジナルのデータなのか判別することが出来ません。
その為、最初にVRMのファイルを作成した時にユーザーが設定した一部の項目は編集不能のフラグが立つようにしUniVRMでも編集できないし、それをVRMが扱うサービスでも参照して尊重する仕組みが必要かと思われます。

VRoid Hubで、Other  License Urlが書き換わることが問題というような声を頂いていますが、これはあくまでも製作者本人がサービス規約に同意した上で自身で設定するという形になっています。しかし、Other License Urlを第三者が変更できないフラグを用意することでこのフラグが立っているVRMファイルは「このVRMは、サービス側では扱うことができません」というようなライセンスの意志を尊重するような処理が可能です。

個別のライセンス項目に、何が足りてなくて何が必要かは今後VRMコンソーシアムの技術会議で話し合っていければと思います。

**Comment by walf443** [comment]
> ・UniVRMでのライセンスの保護
> 現在、UniVRMではオリジナル製作者がライセンスを設定してVRMとして書き出すと、その後UniVRMで読み込むと誰でも好きなように書き換えることができてしまいます。

UniVRM側で二次利用なのかどうか、を判断するのはVRM内の情報だけではできないので、もしこれを機能として禁止してしまうと、作者が自分のライセンスをあとから変更して再度配布したい、といったことができなくなってしまうのもそれはそれでどうなんだという気がします。( 作者であればオリジナルデータは別の形でも持っているだろう、ということは現状ではありそうではありますが。

既にライセンスが設定されているもののデータを書きかえることは、技術上それほど難しいことではなく、他のツールが普及したりするのは防げないので、こういう対応の仕方はあまり建設的ではないかなという印象です。

作者がvrmファイルに電子署名をしたりする方法みたいな方法があると、別の人が署名したときに使った秘密鍵を持っている人でないと改竄すると不正なファイルになる、といったことが実現できるかもしれません。

**Comment by m-sigepon** [comment]
>UniVRM側で二次利用なのかどうか、を判断するのはVRM内の情報だけではできないので、もしこれを機能として禁止してしまうと、作者が自分のライセンスをあとから変更して再度配布したい、といったことができなくなってしまうのもそれはそれでどうなんだという気がします。( 作者であればオリジナルデータは別の形でも持っているだろう、ということは現状ではありそうではありますが。

これについては、ライセンス情報の保護を行うかどうかはモデル製作者が最終的に行う形になるので編集途中としてのVRMはそのままで、最終出力時にそういった保護をするかどうかエクスポーターで指定するというのを想定しています。

**Comment by ousttrue** [comment]
タイトルで内容がわかるようにして、話題もひとつでお願いします・・・🙇

**Comment by m-sigepon** [comment]
了解です分岐します。

**Comment by iCyP** [comment]
下記要約：
結論：vrmのﾗｲｾﾝｽ･ならびにﾓﾃﾞﾙﾃﾞｰﾀの保護は不要と考えます。
理由：そもそも生vrmをやりとりするのが間違っています。hubｻｰﾋﾞｽ<->ｸﾗｲｱﾝﾄｱﾌﾟﾘの中でﾓﾃﾞﾙ･ﾗｲｾﾝｽを保護・管理すべきです。Ｖカツ(ﾕｰｻﾞ)->ﾆｺﾆｺ立体->ﾊﾞｰﾁｬﾙｷｬｽﾄのような形ですね。

　hubサービスより先にファイルフォーマットが出てしまったので(先の文化を考慮して)ファイル自体にライセンス属性を付けたのでしょうが、hubサービスが充実すれば、vrmファイル自体のライセンス自体は不要だと思います。
　hubサービスの登場により、vrmファイル自体の重要な役目は商用利用可能な扱いやすい仕様のモデルフォーマットである所になると思います。よってライセンス・データ保護はhubｻｰﾋﾞｽ側で行うべきです。vrmフォーマット自体には不要であり、vrmファイルとして悪意の者に対する対策をするとすれば無用の労力をvrmユーザ・仕様開発者・hub,ｸﾗｲｱﾝﾄ開発者それぞれが共に負うことになる考えます。それはとても不幸でしょう。
　保護の必要があるならそもそも制作者が生VRMファイルを配布・一般公開しないべきです。(もちろんhubｻｰﾋﾞｽ上で表示する際にも非可逆変換を加えたうえで、というか車屋HPのようにﾌﾟﾘﾚﾝﾀﾞ360度画像にでもすべき)
　ユーザーは、vrmファイルを(改変共有目的でないならば)hubサービスにアップロードする際にのみ使用し、hubサービス提供側はそれを（gltfにこだわらず、むしろ全く違う別の）独自(大抵ろくなことにならないがないより"まし")形式に変換、暗号化するなりして保護し、SDKとしてアプリ開発者にその形式を簡単に扱えるように提供するのが妥当だと思います、そんなコストも脆弱性を作りこむリスクも形式の安全性を担保する責任も各社各人負いたくないでしょうけどね。　
　vrmファイル自体を秘密鍵なりでのﾓﾃﾞﾙﾃﾞｰﾀ暗号化管理などは拡張として出来るとは思いますが、鍵を持っている人しか見れないので無意味でしょう、GLTF互換もｸｿくらえですね。人に見られたくて作ったデータを自分の貸し金庫の中に入れますか？それを見せたいからと言ってコピーし放題のカギを他人に渡しますか？

**Comment by m-sigepon** [comment]
この意見は、実際にモデルを制作されている方から出た意見を元にしております。
iCyPさんの言っている、hubサービス側で管理するというのは勿論として事実この世にVRMというフォーマットを作ったのは、モデルデータにライセンスを持たせてモデルデータがMMDの時のようなオレオレライセンスが溢れるのを防ぐことが目的だったと思われます。
サービス単位で、独自フォーマットを作っていくのを無くし各環境で共通フォーマットを扱うことで、3D創作とそれを活用し保護するためにライセンスを持たせるというのが目的というのが自分のVRMに対する認識です。

hub側でのデータ保護は勿論行っているので、自分自身モデル製作者としても設定したライセンスが再度UniVRMで読み込んでライセンス情報が簡単に編集可能なのは、ライセンス情報を扱う環境として根本的な欠陥と感じています。

**Comment by kusano** [comment]
OSSである以上、このフラグを無視するようにUniVRMを改造することはできます。
電子署名を掛けたところで、元の制作者の名前（秘密鍵）のままライセンスを書き換えることはできなくても、他人が新たに電子署名をすることはできます。
UniVRMでライセンスを書き換えるか、UniVRMを改造して（もしくは、誰かが改造したUniVRMを探して）ライセンスを書き換えるかという違いでしかなく、結局はユーザーの善意に任せることになると思います。
書き換えのハードルを上げるメリットが、仕様の複雑化のデメリットに見合うのか疑問です。

> VRoid Hubで、Other License Urlが書き換わることが問題というような声を頂いていますが、これはあくまでも製作者本人がサービス規約に同意した上で自身で設定するという形になっています。しかし、Other License Urlを第三者が変更できないフラグを用意することでこのフラグが立っているVRMファイルは「このVRMは、サービス側では扱うことができません」というようなライセンスの意志を尊重するような処理が可能です。

製作者本人が（VRoid Hubを使って）Other License Urlを書き換えるという形なのに、「 **第三者が** 変更できないフラグ」が立っていると書き換えられないようになるのですか？
やはり、複雑で分かりづらくなるのではないかと……。

**Comment by iCyP** [comment]
繰り返しますが、ライセンス・モデル保護の環境・仕組みはvrmのup先であるhubｻｰﾋﾞｽが担うべきであって、ただの出力ファイルフォーマットであるvrmに担わせるにはあまりにも荷が重すぎ、解決できない問題であると思います。（DRMの類はいずれ邪悪に破られる星の下生まれる可哀そうな子です）
　私はVRMは最終出力ﾌｫｰﾏｯﾄとしての立ち位置であると認識しており、そこから任意でない他人が編集に戻れるような状態にvrmファイルが置かれている事が間違っている、と思います（DCC向けimporter作者が何言うですが)。　vrmを作ったらhubにﾎﾟﾝであとはhubｸﾗｲｱﾝﾄから変換暗号化なりがされたものが返ってきて、それで楽しむというのがVRMが将来描いている所だと感じています。

以下ポエム
　まず、VRMﾌｫｰﾏｯﾄの持つライセンスそのものの意義について。
(VRMは、第一に、触れたくはないが、その前一般向けに流通したフォーマットとその編集ツール周りに商用利用の上で問題があったため作られたフォーマットであり、ﾗｲｾﾝｽはそのﾌｫｰﾏｯﾄでの不十分と指摘されていた部分を整えることで移行を勧めやすくするためと捉えているところで、前提を違えているので論じるべきではないが)
　過去のオリジナルライセンスの問題については、法専門外の方のカバー不足な・また明文化されないルールに問題があったと考えている。
　その解決のため、難解なオリジナルライセンスの防止には、VRMの”仕様登場時点”ではVRMのmetaにはせめてこれだけは2択で明確にしておけ、という分で効果があったとは思う（古い実装の出力結果や実態はともかく)。
　しかし、hub->ｸﾗｲｱﾝﾄを介すことによりhubがその利用用途を管理し、ユーザーが他者のVRMファイル自体に直接触れず、そのライセンスを直接見ることがなくなる将来が来るだろう。その時、vrm所有者(権利者)は、そのhubのにアップロードする際にhubのライセンス体系に従ったものを設定することになると考えている。今のVRoid hubのように。そこから、hubがライセンスを表示・利用用途の設定によってｸﾗｲｱﾝﾄｱﾌﾟﾘの利用権限に応じてのﾓﾃﾞﾙの提供の可否を管理するようになり、利用者は、vrmは完成品をhubに上げ、ｸﾗｲｱﾝﾄｱﾌﾟﾘというﾌﾟﾛｷｼを通してﾓﾃﾞﾙを利用する、という文化になった時点でファイル自体がﾗｲｾﾝｽを持つ意味が無くなる情報と考えている。ユーザーの2次改変を認める配布VRMの場合はその限りではないが、配布ファイルを悪意から保護することは不可能なので、考えるべきでない。着せ替え遊びを(権利者にとって)安全にさせたいならhubｸﾗｲｱﾝﾄにｱｾｯﾄを入れてその中で選べるような仕組みの中にhubからﾊﾞｲﾅﾘをDLできるようにするべきだ。MMOゲームのように。

つぎに、vrmファイル自体ののライセンス・モデル保護について。
　コンシューマ向け、ネット向けそれぞれゲームの一体となった最適化され難解な独自バイナリからのモデルデータの物故抜きが防げないのに、それをファイル単一のしくみで防げるのだろうか？それが防げる仕組みがあったとして一般ユーザーが簡単に管理するするのは難しいだろう。BD(AACS)のようなハードウェア的保護(それも不十分なようだが)を謎の半導体企業らに求めるか？　それに繰り返すが、vrmで(不可能だが)割れ対策を持てたとして、割られたときは関係4者全員が対応しないといけなくなる。
　hub側で保護すればそれが割られてもhub以下の枝の対応で済む。それにｳｲﾙｽと同じで的は小さいほうが狙われにくい。(今時が一概に、だが)
　悪意に正面対決するほど、時間の無駄な事はそうそうない。
ここでvrmを扱うにあたりﾓﾃﾞﾙを悪意から回避したいﾕｰｻﾞｰができる策は、まずネットにupしない、どうしてもkawaiiしたいというならprivate uploadなり一般非公開登録で、自撮りSSをあげるなりにすべきである。他者に一切アクセスさせないという極論以外に割れを防ぐ術はない。**ネットにデータを見れる形で公開しながら絶対に割られないというのは絶対にあり得ない。** 某ｱﾊﾞﾀｰﾁｬｯﾄもまた最近ﾓﾃﾞﾙが割られていると聞く。
　悪意に正義のパワーで捻じ伏せる、というのは現実には甚だしく労力を費やす上に賽の河原に他ならない。我々は魔法少女ではないし、悪ボスは砂の数よりも多い。君子危うきに近寄らずともいうが、悪意に触れられたくないのであれば、悪意のない場所にいる、隠すのができるのであれば一番簡単で低コストだ(社会の諸々の問題一般について述べているわけではない)。インターネットというお立ち台に立つならおひねりもトロールも一緒に集まってくる覚悟をすべきだ。
長文駄文失礼。
