### ISSUE TITLE
[Material:SetVector] Cant import previously exported vrm models into prefab

### ISSUE THREAD

**Issue by MelaniesRats** [vrm-c/UniVRM#1680]
## Environments:

 - UniVRM version: `0.81.0`
 - Unity version: `Unity-2020.3.4f1`
 - OS: `Windows 10`

## Describe the bug

Cant import previously exported vrm models

Property _BumpMap already exists in the property sheet with a different type: 5
UnityEngine.Material:SetVector (string,UnityEngine.Vector4)
VRMShaders.MaterialFactory/<LoadAsync>d__11:MoveNext () (at Assets/VRMShaders/GLTF/IO/Runtime/Material/Importer/MaterialFactory.cs:152)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<UnityEngine.Material>:Start<VRMShaders.MaterialFactory/<LoadAsync>d__11> (VRMShaders.MaterialFactory/<LoadAsync>d__11&)
VRMShaders.MaterialFactory:LoadAsync (VRMShaders.MaterialDescriptor,VRMShaders.GetTextureAsyncFunc,VRMShaders.IAwaitCaller)
UniGLTF.ImporterContext/<LoadMaterialsAsync>d__33:MoveNext () (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:282)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<UniGLTF.ImporterContext/<LoadMaterialsAsync>d__33> (UniGLTF.ImporterContext/<LoadMaterialsAsync>d__33&)
UniGLTF.ImporterContext:LoadMaterialsAsync (VRMShaders.IAwaitCaller)
VRM.VRMEditorImporterContext:ConvertAndExtractImages (System.Action`1<System.Collections.Generic.IEnumerable`1<UniGLTF.UnityPath>>) (at Assets/VRM/Editor/Format/VRMEditorImporterContext.cs:78)
VRM.vrmAssetPostprocessor:ImportVrmAndCreatePrefab (string,UniGLTF.UnityPath) (at Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs:96)
VRM.vrmAssetPostprocessor:ImportVrm (UniGLTF.UnityPath) (at Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs:51)
VRM.vrmAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs:31)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Put an vrm file that was exported whit univrm into univrm

**Comment by ousttrue** [comment]
Thank you for reporting.

I have confirmed that this error message occurs.
`Unity-2021.3`

However, the import was successful. Did the prefab generation fail or look corrupted?

Make corrections to prevent this message.

**Comment by MelaniesRats** [comment]
there was no prefab generation

**Comment by ousttrue** [comment]
`v0.100`
