### ISSUE TITLE
Animations not saved to VRM export

### ISSUE THREAD

**Issue by GuWoSch** [vrm-c/UniVRM#1682]
I recently discovered that animations are not exported to my VRM files. I am animating game characters and usually the only thing I use animations for are eye blink.
Everything works in Unity but when I export the character in VRM format, the animations are not playing. To troubleshoot I re-import the VRM file back into Unity and see that the Controller is set back to 'none..'.
I am using uniVRM-0.98.0, but not sure if it is a problem with that version, although this started around the time I updated to it..

**Comment by ousttrue** [comment]
Because we can't know the meaning of the animation contained in the unknown vrm.
Since VRM does not use animation, it does not export animation from `v0.96.0`.
It is possible to add options to export the animation. Do you need it?

**Comment by ousttrue** [comment]
OK.

But,
If you're doing both an animation clip and a VRMBlendShape, keep in mind that the one that worked later will overwrite the SkinnedMeshRenderer's blendShape.

**Comment by ousttrue** [comment]
`v0.101`

- add export option
- add loadAnimation argument to VRM LoadAsync https://github.com/vrm-c/UniVRM/pull/1719/files#diff-d311db0b786e6c9209cabf11e15200caec4dd1546ff80316949cbc8e1b30d6f1R18
