### ISSUE TITLE
VRM10 の MonoBehaviour の C# 側の命名規則を統一し、また、Inspector での見え方も別に統一する

### ISSUE THREAD

**Issue by Santarh** [vrm-c/UniVRM#1699]
class 名は C# 命名規則になるべく準じた形で統一する。
Inspector での見え方は `VRM10/~~~` となるように AddComponentMenuAttribute で統一する。

また Sample の class 名がそれらに紛れないようにする。

**Comment by ousttrue** [comment]
ある程度やった。たぶん
