### ISSUE TITLE
glTF形式の、アバターでないオブジェクトデータなどにもライセンスデータを持たせたい

### ISSUE THREAD

**Issue by m-sigepon** [vrm-c/UniVRM#170]
例えば、キャラクターに読み込ませるアクセサリや、背景などにもライセンスデータを持ったglTFベースのフォーマットが必要かと思われます。

**Comment by vyv03354** [comment]
独自拡張を乱立させるより、[KHR_XMP拡張](https://github.com/KhronosGroup/glTF/pull/1553)を採用したほうがいいと思います。時期的な理由で(たとえばTHE SEED ONLINEのリリースまでにVRM 1.0仕様を固めなければならないとか)現時点での採用が不可能だとしても、せめて移行パスをあらかじめ想定した規定にしてほしいです。

**Comment by m-sigepon** [comment]
KHR_XMP拡張で対応できるならそれがよさそうですね。

**Comment by vyv03354** [comment]
もし現時点で対応できないなら、議論に参加して必要な機能を入れてもらうまであると思っています。
