### ISSUE TITLE
RuntimeでBlendShapeAvatarを編集できるように対応していただきたい

### ISSUE THREAD

**Issue by wakapippi** [vrm-c/UniVRM#1710]
VRMの表情を設定できるようなアプリケーションをUniVRMで開発しています。
RuntimeでBlendShapeAvatarのClipの追加を行っても、そのClipをアバターに反映できない状況でして、こちらを機能追加で対応いただきたいと考えています。

具体的には、BlendShapeAvatarのClipの追加はできるのですが、VRMBlendShapeProxy#Start内で生成している

`BlendShapeMerger m_merger`

が、初期化時のクリップ情報をキャッシュしている挙動のために、追加したClipに対してImmediatelySetValueなどを呼び出しても反映されません。

クリップ追加時にm_mergerを強制的に再生成することで問題が解決できることを確認していますが、もし公式で対応いただけそうでしたら、お願いしたい所存です。

**Comment by ousttrue** [comment]
報告ありがとうございます。

BlendShapeAvatar は Asset であるため play 中に変化することを避けていました。
`VRMの表情を設定できるようなアプリケーション` で使いたいという需要を了解しました。
明示的に再初期化する API などを検討します。

**Comment by ousttrue** [comment]
`v0.101`
