### ISSUE TITLE
MToon: We need descriptions about these materialProperties

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/UniVRM#172]
おそらく、MToonとそれのVRM出力の間には、UniVRMが噛んでいると思われますので、
こちらでissueを建てさせていただきます。

`VRM.materialProperties[i].floatProperties._BlendMode` に `0` (Opaque) 、
`VRM.materialProperties[i].tagMap.RenderType` に `"Opaque"` が入っているにもかかわらず、
`VRM.materialProperties[i].keywordMap` に `_ALPHATEST_ON` が存在する場合には
UniVRMではCutoutとして処理されてしまったのですが、
これは仕様でしょうか？

現状、Unityでの "Rendering Type" パラメータに該当すると思われるキーが
上記のように複数存在するため、
このうちどれを解釈するのが正しい挙動かがわかりませんでした。

これらの `materialProperties` がマテリアル上でどのように反映されるかを示した、
ドキュメントのようなものがありますとたいへん助かります。

Related issue: https://github.com/dwango/UniVRM/issues/69

**Comment by iCyP** [comment]
現状materialPropatiesを特にverify無しにそのままデシリアライズ、そのパラメータをシェーダに送ってﾚﾝﾀﾞﾘﾝｸﾞしてしまっています。#69 の通りですが、という所で、MToon自体の内部パラメータのﾄﾞｷｭﾒﾝﾄは多分出てこない（その前にｼｪｰﾀﾞｰﾌﾟﾛｷｼ #169 のような仕様にラップされたのが出てくるのでは）と思います。
そこでですが、現状は
https://github.com/Santarh/MToon/blob/95d383bbdb0da00981181e5ccf3d2d8dd89848f8/MToon/Scripts/Utils.cs#L154
あたり(他validate~~ﾒｿｯﾄﾞ)で、あるEnum(UIに上がってくる値)の時、本来期待するそれぞれパラメータが記載されているので、個人的にはそのswitch-case文の条件を基準にその子のパラメータを上書きするのがベタなのかなぁと思います。ちなみに私はこの場合、_BlendModeを優先します。

**Comment by hiroj** [comment]
https://github.com/Santarh/MToon/blob/95d383bbdb0da00981181e5ccf3d2d8dd89848f8/MToon/Scripts/Utils.cs#L154
現状このコードが仕様になります。
