### ISSUE TITLE
Dynamically created Avatar on runtime imported model has twisted shoulders

### ISSUE THREAD

**Issue by cpetry** [vrm-c/UniVRM#1726]
## Environments (please complete the following information):

 - UniVRM version: `0.101.0`
 - Unity version: `Unity-2022.1.1`
 - OS: `Windows 10`

## Describe the bug

I have a rigged human model from [Renderpeople.com](https://renderpeople.com/de/)
![image](https://user-images.githubusercontent.com/3867700/176420106-febdaa9e-0f9a-4708-b236-f5a7e6092c34.png)

Trying to import the model in runtime as a glb/gtlf and dynamically creating an avatar worked before using [TriLib](https://assetstore.unity.com/packages/tools/modeling/trilib-2-model-loading-package-157548) (older version 0.92 or so).
When using UniVRM for importing the model and applying the same avatar creation method as before I get twisted shoulders:
![image](https://user-images.githubusercontent.com/3867700/176419923-6521aef1-a48d-4731-85a7-4a311bc084e6.png).
Not sure what exactly the problem is but it seems the model behaves differently when exported by UniVRM.

I can confirm though that the model gets imported correctly in T-pose as expected. Something 

Sorry but I can't post the model here cause of it's license

**Comment by ousttrue** [comment]
Thank you for reporting.
Please refer to the sample for runtime export.
https://vrm-c.github.io/UniVRM/en/api/sample/RuntimeExporterSample.html

`vrm-0.x` requires normalization before exporting.
Normalization removes rotations and scales from the hierarchy and bake mesh.

**Comment by cpetry** [comment]
Ah sorry I didn't mean runtime export. I meant runtime import!
Imagine the model being somewhere on the web being loaded from within an webgl application for example.

**Comment by TigerHix** [comment]
It's the same. You need to write your own version of VRMNormalizer.Normalize (without all the VRM dependencies) to normalize the bones.
