### ISSUE TITLE
How do I load an EXT_meshopt_compression compressed model

### ISSUE THREAD

**Issue by wxxewx** [vrm-c/UniVRM#1727]

**Comment by ousttrue** [comment]
Thank you for reporting.
`EXT_meshopt_compression` is not implemented.

From `v0.99` `KHR_mesh_quantization` import is imprlemented.
- https://vrm-c.github.io/UniVRM/en/release/079/v0.99.0.html

**Comment by ousttrue** [comment]
I'm sorry, we don't plan to implement `EXT_meshopt_compression` .
