### ISSUE TITLE
一部のVRM1 Betaモデルのアニメーションのどこかが上下反転しているように見える

### ISSUE THREAD

**Issue by saturday06** [vrm-c/UniVRM#1729]
## 環境情報

 - UniVRM version: `0.101.0`
 - Unity version: `Unity-2021.3.5f1`
 - OS: `Windows 11 Pro 21H2 22000.675`

## バグについて

* バグの内容

https://github.com/vrm-c/UniVRM/pull/1719 で、エディターではアニメーションをインポートするようになったとのことですが、[特定のVRM1.0モデル](https://github.com/vrm-c/UniVRM/files/9035098/CesiumMan.vrm.zip)をエディタインポートしてアニメーションを再生すると、アニメーションのどこかが上下反転しているように見えます。

* ConsoleLog

Consoleにログは出力されませんでした。

* スクリーンショット

<img width="400" src="https://user-images.githubusercontent.com/532872/177047549-3d8d17a6-cd95-458f-80cb-2ebbe503c0dc.gif">

左が再現ファイルをそのままエディタインポートしたモデルです。右が、再現ファイルの拡張子を.glbに変更してからエディタインポートしたモデルです。ワイヤーフレーム表示にしています。拡張子を変更しないまま、右のようにアニメーションが再生される状態が期待される動作です。

* 再現方法

[再現ファイル](https://github.com/vrm-c/UniVRM/files/9035098/CesiumMan.vrm.zip) をエディタインポートし、エディタのPlayモードを開始します。

* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

glTF 2.0サンプルモデルのCesiumMan.glbにVRM 1.0のエクステンションを追加したモデルです。
[CesiumMan.vrm.zip](https://github.com/vrm-c/UniVRM/files/9035098/CesiumMan.vrm.zip)

**Comment by ousttrue** [comment]
報告ありがとうございます。

おそらく、 skin.skeleton と animation の組み合わせが未実装であることが原因です。
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/CesiumMan/glTF/CesiumMan.gltf#L1191

このあたりが関連するかもしれない。

* SkinnedMeshRenderer.rootBone と gltf.skin.skeleton の切り離し https://github.com/vrm-c/UniVRM/issues/1675
* https://github.com/vrm-c/UniVRM/issues/1475

dcc からどうやって作られるのか。
例えば、blender の Armature を 他の Object の child にするなど？でこうなるのか？

**Comment by saturday06** [comment]
これそういえばVRMアニメーションの実装に影響があるかもですね
