### ISSUE TITLE
The imported glTF model surface is not smooth

### ISSUE THREAD

**Issue by RuyeRuye** [vrm-c/UniVRM#1740]
## Environments (please complete the following information):

 - UniVRM version: `0.101.0`
 - Unity version: `Unity-2021.3`
 - OS: `Mac OS`

## Describe the bug
Using the older version(0.92.0) in the same environment, the glTF 2.0 model surface is smooth.Both URP and Built-in have this problem.
![image](https://user-images.githubusercontent.com/88803076/178463507-fc3658ff-40d2-4317-9f54-834c46e0069a.png)
![image](https://user-images.githubusercontent.com/88803076/178463641-222bb007-1a1b-4c13-8e91-c1044573ef36.png)

**Comment by ousttrue** [comment]
Thank you for reporting.
May be related to RecalculateNormals.

Relevant
`v0.95` https://github.com/vrm-c/UniVRM/pull/1686/files
