### ISSUE TITLE
VRM NO vertex normals

### ISSUE THREAD

**Issue by HwangDongJu** [vrm-c/UniVRM#1747]
## Environments (please complete the following information):

 - UniVRM version: `0.101.0`
 - Unity version: `Unity-2021.3.5`
 - OS: `Windows 11`

When exporting the work of vertex normals in fbx to vrm, vertex normals are not applied.

**Comment by ousttrue** [comment]
Thank you for reporting.
This may be related to #1740 .
`v0.102` is fixed This problem.
Try it with `v0.102.0`

**Comment by HwangDongJu** [comment]
I tested it and it works!
thank you~
