### ISSUE TITLE
UniJson JasonNode freeze 

### ISSUE THREAD

**Issue by michaellu88** [vrm-c/UniVRM#1754]
Hi,

I found out that this UniJson package freeze and shutter my scene from .parsetojson, any other Json package i can replace for running WEBGL runtime import VRM.

thanks

**Comment by michaellu88** [comment]
I have try to use unitask async await, no more freeze, but it took like 2 mins for the parsing. Anyone have more efficient way to do this? Tq

**Comment by ousttrue** [comment]
Thank you for your report.
It's monolithic, so it's impossible to separate Json parsing on the browser side.
Updated VRM_Samples/SimpleViewer to build with WebGL.
See next version `v0.103`.
