### ISSUE TITLE
No animation controller

### ISSUE THREAD

**Issue by Vic-Raiden** [vrm-c/UniVRM#1755]
## Environments (please complete the following information):

 - UniVRM version: `0.102.0`
 - Unity version: `Unity-2021.3.3f1`
 - OS: `Windows 10`

## Describe the bug

* There is no animation controller attached to the models imported, which implies there's something missing in the UniVRM package. Models are defined correctly as animated avatars, though.
* The error isn't shown on the console.
* 
![image](https://user-images.githubusercontent.com/109981974/180837017-808c0f78-ead6-43bc-9193-d9bc9dd58296.png)
* Any model I import shows without the animation controller file.

**Comment by ousttrue** [comment]
Thank you for your report.
UniVRM does not use Animator Controller.
I only use Animator's Humanoid avatar.
