### ISSUE TITLE
GL_INVALID_OPERATION: Active draw buffers with missing fragment shader outputs.

### ISSUE THREAD

**Issue by michaellu88** [vrm-c/UniVRM#1758]
Hi, i have this warning [.WebGL-0x110099cb800] GL_INVALID_OPERATION: Active draw buffers with missing fragment shader outputs. after loading vrm model at runtime webgl. I don't know it is related to my vrm model or unity bug. pls help tq

**Comment by ousttrue** [comment]
Thank you for your report.
I don't know how it will happen. I can't fix it.
