### ISSUE TITLE
Exposing Shape Keys of the Body

### ISSUE THREAD

**Issue by breadnone** [vrm-c/UniVRM#1770]
Would you consider, exposing shape keys for the body so they can be used in Unity to further customize the character as needed. Which also opens a possibility for developers to make a proper tooling for their game, such as ;

1. In-game character creator.
2. In-game effects (e.g: When gets hit by objects)
3. Dynamic character customization for both Edit and Play mode in Unity.

Thanks for your hard work and the beautiful plugin!

**Comment by ousttrue** [comment]
I interpreted it as a proposal to add ShapeKeys other than facial expressions.
Proposals for specifications can be made to the consortium.
<https://github.com/vrm-c/vrm-specification>
It may be added if it is specific and widespread (e.g. `suprised` in `1.0`)

**Comment by breadnone** [comment]
Yes, exactly, other than facial expression. Perhaps expose it through an API? So we developers can have much freedoms to expand it for out customEditors, plugins etc.

Thanks for the reply!
