### ISSUE TITLE
Native array leak

### ISSUE THREAD

**Issue by quantum-craft** [vrm-c/UniVRM#1772]
## Environments (please complete the following information):

 - UniVRM version: `v0.99.f`
 - Unity version: `Unity-2020.3`
 - OS: `Windows 10`

## Describe the bug

The Dispose() of GltfData in ImporterContext.cs (in UniGLTF) is never called.
This will cause native array leak because the NativeArraryManger's Dispose is called
in GltfData.Dispose().

Proposed fix:

Add "Data.Dispose();" in the end of ImporterContext's Dispose() method.

**Comment by ousttrue** [comment]
Thank you for your report.
ImporterContext doesn't own GltfData, so it doesn't Dispose arbitrarily.

Please refer to the code around here and SimpleViewer.
https://vrm-c.github.io/UniVRM/en/api/0_95_dispose.html

**Comment by quantum-craft** [comment]
@ousttrue
Thank you for your explaination.
Then this is not a bug.
