### ISSUE TITLE
TortoiseSVNにて、VRMデータが作り直されてしまう。

### ISSUE THREAD

**Issue by Nekohatsuden** [vrm-c/UniVRM#1784]
## 環境情報
TortoiseSVNにて、VRMデータが作り直されてしまう。

バグなのかは不明であったので、こちらに書かせていただきました。

-Import VRM : Unity 2019.3.4f1
-Unity version: Unity-2019.4.20f1
-OS:Windows 10

## バグについて
・Unityのプロジェクトにて、TortoiseSVN(1.14.3, Build 29387 - 64 Bit )を利用しています。

* 再現方法

a・クラウド上にあるVRMデータの入ったUnityプロジェクトを、空のフォルダに新規チェックアウトにてＤＬします。
b・その後、Unityを起動すると、VRMデータが作り直されてしまい、以前のVRMデータが上書き(プレハブの設定が初期化)されてしまいます。

これは何か対策はあるでしょうか？

よろしくお願い申し上げますm(_ _)m

**Comment by Nekohatsuden** [comment]
対策として、インポートした後のVRMファイルを削除、もしくは拡張子を変更することで解決しました。
おさがわせいたしましたm(_ _)m

**Comment by ousttrue** [comment]
違うかもしれませんが、
`svn` に `.meta` ファイルを記録されてますでしょうか。
Unity により `Hoge.vrm` に対して `Hoge.meta` が生成されます。
おそらく `Hoge.meta` が存在しないと editor import が発動します。

**Comment by Nekohatsuden** [comment]
返信ありがとうございましたm(_ _)m
metaは一緒にコミットしているので問題ないかと思います。
Aポイントで新しいVRMデータを追加・meta含めてコミットし、BポイントでPull(更新)すると、必ずデータを作りなおしてしまう様子です。拡張子VRMはインポートすると不要になると思いますので回避は可能ですが、できれば更新されないほうが良いと感じています。よろしくお願い申し上げますm(_ _)m

![image](https://user-images.githubusercontent.com/86540292/191415878-60592b89-f673-4779-8b80-a393335e5ef5.png)

**Comment by ousttrue** [comment]
よく読み直したところ、
`vrm-0.x` の仕様ぽいです。

* prefab を複製する
* シーンで変更して、シーンを保存する
* reimport されて上書きされても大丈夫なように vrm をエクスポートしなおす

など運用で回避してください。

prefab を変更不能にしたかったのですが、`Unity-5.6` の頃は良い手段がありませんでした。
`vrm-1.0` や `glb` の実装は、`ScriptedImporter` を使うことによって変更不可になっています(fbx のように)。
svn と言われたので固有の問題という先入観がありましたが、 git などでも同様かと思われます。

**Comment by Nekohatsuden** [comment]
ご確認をありがとうございましたm(_ _)m

最新バージョンでは回避できているのですね。どこかのタイミングでアップデートしたいと思います。
（UnityEditor 2020以上にアップいるとフレームがかなり落ちるので待っている状況です）

現在は、VRMファイルが起動して上書きしないよう、"vrm"ファイルの拡張子を　"_vrm"に書き換えて運営しています。

今のところ本対策で問題は出ていません。

今後ともよろしくお願い申し上げますm(_ _)m
