### ISSUE TITLE
missing parts of the model when converting to vrm

### ISSUE THREAD

**Issue by pandoraingri** [vrm-c/UniVRM#1797]
## Environments (please complete the following information):

 - UniVRM version: `0.86.0`
 - Unity version: `Unity-2019.4.31f1
 - OS: `Windows 10 64bit

## Describe the bug

when converting to vrm, one eye disappears, or rather it is there, but something with the material is possible. The material on both eyes is the same. The blend shape normals are off, also the normals are not turned inside out, the eyes are attached to the bone of the head and in the humanoid rig the heads are indicated correctly (also if they are not indicated at all - the same problem)
![with head](https://user-images.githubusercontent.com/88170900/190066367-900f9c3a-9eb0-479f-b23d-3d422a337f95.png)
![without head](https://user-images.githubusercontent.com/88170900/190066341-48ec34a5-96c4-48af-bbf7-0f80c9460623.png)
![back side](https://user-images.githubusercontent.com/88170900/190066389-1c546dca-55f9-44a2-b0b0-cace0cdeb1c5.png)

**Comment by ousttrue** [comment]
Thank you for your report.
But I can't check without the reproduction file.
#1870
