### ISSUE TITLE
Animations bound to child gameobject not saved to VRM export 

### ISSUE THREAD

**Issue by LangInteger** [vrm-c/UniVRM#1805]
## Environments (please complete the following information):

 - UniVRM version: `0.103.2`
 - Unity version: `Unity-2019.4`
 - OS: `macOS Monterey`

## Describe the bug

Guided by [this issue](https://github.com/vrm-c/UniVRM/issues/1682), I tried to store animation bound to one child prefab when exporting to vrm.

![IxYrLzJWlu](https://user-images.githubusercontent.com/17768055/190635957-aa338047-b138-45b8-826a-794a149aaeff.jpg)

![Y7IgpP3Pqz](https://user-images.githubusercontent.com/17768055/190635971-a2cb649b-41fd-4e51-bb36-ffe8387eeea2.jpg)

But when I reimport the vrm to unity, the animation controller is gone.

![IIIoJBrzOM](https://user-images.githubusercontent.com/17768055/190636019-6b68d0a9-b033-4dfc-b4bb-17087b8075b8.jpg)

![JELZlB0ziJ](https://user-images.githubusercontent.com/17768055/190636031-c337495e-b134-4cd0-9248-1db428eadc1b.jpg)
 
Do I miss something here?

**Comment by ousttrue** [comment]
UniVRM only supports Animation attached to Root.
gltf is like animating a scene.
There is a document here.

https://vrm.dev/en/gltf/animation_exporter
