### ISSUE TITLE
【VRM1】Unity実行中にVRM10 Spring Boneの重力設定の変更をリアルタイムに画面に反映したい

### ISSUE THREAD

**Issue by initialK-0001** [vrm-c/UniVRM#1829]
Unity2020.3.39f1 / VRM-0.104.0_c466.unitypackage を使って、VRM1.0ファイルを読み込んで表示してスクリーンショットを撮るアプリケーションを作成しようとしています。
縦長の画像にするためにVRMモデルをZ方向にマイナス90度回転させると元々Y方向に重力を設定している装飾品が傾いてしまうため、VRM10 Spring Bone Jointの設定で重力の方向をX方向へ変更するようにしたいです。

VRM0の時はUnityが実行状態であっても重力設定の変更がリアルタイムで画面表示に反映できていたのですが、VRM1では予め重力設定を施してからUnityを実行状態にしないと重力設定が画面表示に反映されないようです。
VRM1.0ではUnityの実行中にVRM10 Spring Boneの重力設定の変更をリアルタイムに画面に反映できるようにできないのでしょうか。
OSはWindows11 Home(バージョン21H2)です。

「Unity実行中にVRM10 Spring Boneの設定変更をリアルタイムに画面に反映しないこと」は仕様である可能性もあると考えたので、機能追加要望として投稿させて頂きました。（個人的にはVRM0で出来ていたことがVRM1で出来なくなったのでバグではないかと思っていますが。。）

2022/9/25 18:51修正 : 最初の投稿時にはUnity2019.4.31f1と表記していましたが、Unity2020.3.39f1の誤りでした。

**Comment by notargs** [comment]
VRM1.0のSpringBoneでは、あらかじめ設定項目類を含めたバッファを構築しておき、それを用いて並列演算することで処理を高速に行っています。

Vrm10Runtime.ReconstructSpringBone()を呼ぶことで、明示的にこのバッファの再構築処理を走らせることができるため、
重力方向を変更したいタイミングで、こちらを明示的に呼び出してください。

**Comment by initialK-0001** [comment]
御回答頂き、ありがとうございます。
試してみましたが、NullReferenceExceptionエラーで止まってしまいました。
例示頂いた「vrmRootGameObject」は当該揺れもののGameObjectを指すのだろうと考えていたのですが、違うのでしょうか？

＜コード＞
using UnityEngine;
using UniVRM10;

public class NewBehaviourScript1 : MonoBehaviour
{
    public void OnClickButton1()
    {
        var mimikazari01 = GameObject.FindWithTag("mimikazari1");
        var mimikazari02 = GameObject.FindWithTag("mimikazari2");
        Debug.Log(mimikazari01);
        Debug.Log(mimikazari02);
        mimikazari01.GetComponent<Vrm10Instance>().Runtime.ReconstructSpringBone();　←これが16行目
        mimikazari02.GetComponent<Vrm10Instance>().Runtime.ReconstructSpringBone();
    }
}

![2022-09-26](https://user-images.githubusercontent.com/114328165/192295382-6eb5135a-02d0-4a53-8730-ba58f71871d6.png)

**Comment by notargs** [comment]
GameObject名からの推察になりますが、恐らく `Karen_20220831_2_2_vrm1` に `Vrm10Instance` コンポーネントがついているかと思います。
検索バーに `t:Vrm10Instance` と入力するなどして該当のコンポーネントを探し、そこを対象として上記のコードを実行してください。

**Comment by initialK-0001** [comment]
御対応頂き、ありがとうございました。解決できました！クローズさせて頂きます。
後から見る方のために、最短シンプルと思われるコード例を記載しておきます。
＜コード＞
using UnityEngine;
using UniVRM10;

public class NewBehaviourScript1 : MonoBehaviour
{
    void Update()
    {
        GameObject Target = GameObject.Find("Karen_20220831_2_2_vrm1");
        Target.gameObject.GetComponent<Vrm10Instance>().Runtime.ReconstructSpringBone();
    }
}
![2022-09-27 (2)](https://user-images.githubusercontent.com/114328165/192534624-aa88dab6-15fb-4334-8a82-439051ac79d7.png)
