### ISSUE TITLE
GitLFSの帯域のクォータを超過しており、UniVRMをCloneできない

### ISSUE THREAD

**Issue by mkc1370** [vrm-c/UniVRM#1832]
## 環境情報

 - UniVRM version: `0.104.1`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`
 - Git: `git version 2.37.3.windows.1`

## バグについて

* バグの内容
UniVRMをCloneしようとすると、GitLFSのQuotaを超過しておりCloneできないという旨のエラーが発生します。

* ConsoleLog
```
Cloning into 'UniVRM'...
remote: Enumerating objects: 52566, done.
remote: Counting objects: 100% (1340/1340), done.
remote: Compressing objects: 100% (446/446), done.
remote: Total 52566 (delta 977), reused 1229 (delta 890), pack-reused 51226Receiving objects: 100% (52566/52566), 52.08 Receiving objects: 100% (52566/52566), 53.55 MiB | 15.06 MiB/s, done.

Resolving deltas: 100% (42536/42536), done.
Updating files: 100% (2629/2629), done.
Downloading Assets/UniGLTF/Editor/UniGLTF/Gizmo/Models/Bone.fbx (15 KB)
Error downloading object: Assets/UniGLTF/Editor/UniGLTF/Gizmo/Models/Bone.fbx (92d388e): Smudge error: Error downloading Assets/UniGLTF/Editor/UniGLTF/Gizmo/Models/Bone.fbx (92d388e892e7c7c9519e70f90c091b1e18eb1219b2685e55f74da0bb531b93eb): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to 'C:\Users\mkc1370\src\unity\UniVRM\.git\lfs\logs\20220928T154523.4883573.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Assets/UniGLTF/Editor/UniGLTF/Gizmo/Models/Bone.fbx: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
* スクリーンショット

* 再現方法
cmdで`git clone https://github.com/vrm-c/UniVRM.git`を入力

* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

**Comment by mkc1370** [comment]
同様にupm（manifest.jsonに以下の内容を追記）からUniVRMを導入する場合もLFS管理下にあるファイルを取得することができません。
ですが、LFS管理下でないファイルは取得でき、LFS管理下のファイルもUniVRMを動かすことに必須という訳でも無いので単にUnityで使うだけであれば何とかなりそうです。

``` json
    "com.vrmc.vrmshaders": "https://github.com/vrm-c/UniVRM.git?path=/Assets/VRMShaders#v0.104.1",
    "com.vrmc.gltf": "https://github.com/vrm-c/UniVRM.git?path=/Assets/UniGLTF#v0.104.1",
    "com.vrmc.univrm": "https://github.com/vrm-c/UniVRM.git?path=/Assets/VRM#v0.104.1",
    "com.vrmc.vrm": "https://github.com/vrm-c/UniVRM.git?path=/Assets/VRM10#v0.104.1"
```

![](https://user-images.githubusercontent.com/40651807/192715253-70ea3e08-8b5a-444f-9187-78b304456799.png)
![](https://user-images.githubusercontent.com/40651807/192715264-cceb4f93-6c2a-41f6-934a-08c1149600ea.png)

**Comment by Santarh** [comment]
報告ありがとうございます。

organization での quota 課金も選択肢のひとつとして考えましたが
色々調査して回った結果、GitHub の課金体系と OSS の相性が悪すぎるので
不特定多数のユーザが clone するリポジトリは LFS を使うべきではなさそうです。

**Comment by mkc1370** [comment]
返信ありがとうございます。

僕もリポジトリ全体で1GB（又は5GB）を超えるのがまだ先になりそうでかつ、100MB以上のファイルを扱うことが無いのであればLFSを使わない方が良いと思います。
S3等にLFSサーバーを立てる方法もありますが、保守が面倒なので…

**Comment by ousttrue** [comment]
`v0.104.2` で修正されました。
`v0.104.0` と `v0.104.1` が問題の発生するバージョンです。

また、vrm-specification でも同様の問題が発生していました。
こちらも lfs の仕様を取りやめました。

https://github.com/vrm-c/vrm-specification/tree/master/samples

**Comment by mkc1370** [comment]
ありがとうございます！
LFSを使用していたコミットに移動しない限り、LFSのダウンロードが走らない状態になっていたので問題無さそうです。
