### ISSUE TITLE
CS1525: Invalid expression term '='

### ISSUE THREAD

**Issue by ImperialTazer** [vrm-c/UniVRM#1840]
## Environments (please complete the following information):

 - UniVRM version: `0.81.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## Describe the bug

Assets\UniGLTF\Runtime\UniGLTF\IO\TextureIO\GltfTextureImporter.cs(154,31): error CS1525: Invalid expression term '='
 Happens when Import UniVRM, doesnt show up at top

**Comment by FaxMac** [comment]
Having same Issue!

**Comment by BlastBolt5** [comment]
Also having the issue

**Comment by ousttrue** [comment]
If your Unity version is 2018 or earlier, the new C# syntax will cause compilation errors.
Please use Unity version 2019 or later, or use UniVRM `v0.99.4` or earlier.

**Comment by ousttrue** [comment]
`0.81.0` ?? 🤔

**Comment by ousttrue** [comment]
https://github.com/vrm-c/UniVRM/blob/v0.104.2/Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfTextureImporter.cs#L154

`??=` expression cause this error in Unity-2019 .
But, this is from `v0.103.1` .

**Comment by BlastBolt5** [comment]
v0.99.4 fixed the issue for me, I was on v0.104.2, thanks

**Comment by ousttrue** [comment]
Rewriting `??=` in one place worked in Unity-2019. We will fix it in the next version.
