### ISSUE TITLE
can export because it says "all authors is white space" but I cant even edit the authors because nothing is there???

### ISSUE THREAD

**Issue by rarelambo21** [vrm-c/UniVRM#1845]
## 環境情報

 - UniVRM version: `0.81.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## バグについて

* バグの内容
* ConsoleLog
* スクリーンショット
* 再現方法
* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

**Comment by ousttrue** [comment]
You need to enter some text for authors to export.

**Comment by Sunz-CNKK** [comment]
Yeah, getting the same, it's displaying as "Element0" and the field next to Author is not there. 
![image](https://user-images.githubusercontent.com/56906693/196571397-b3b22cc2-7790-4e5b-903c-0e3b360305f2.png)

**Comment by Liferocka** [comment]
Same here any fix?

**Comment by Liferocka** [comment]
Oh put the "Author" in the Elements aria.
