### ISSUE TITLE
IVrm10Constraint.cs error CS0106: The modifier 'internal' is not valid for this item

### ISSUE THREAD

**Issue by VRArt1** [vrm-c/UniVRM#1852]
## Environments

 - UniVRM version: `0.104.1_4a9b`
 - Unity version: `Unity-2019.4.29f1`
 - OS: `Windows 11`

## Describe the bug

I tried to install the latest version of the univrm sdk but am receiving this error.

"Assets\VRM10\Runtime\Components\Constraint\IVrm10Constraint.cs(7,23): error CS0106: The modifier 'internal' is not valid for this item"

**Comment by GlowPon3** [comment]
Fixed with updating unity to 2020.3.41f1
