### ISSUE TITLE
リリースページ　v0.104.1　部分のリリースノートリンクが存在しないURL

### ISSUE THREAD

**Issue by TakaseFuga** [vrm-c/UniVRM#1855]
リリースページ
[https://github.com/vrm-c/UniVRM/releases](https://github.com/vrm-c/UniVRM/releases)
においてリンク切れの報告です。

[v0.104.1](https://github.com/vrm-c/UniVRM/releases/tag/v0.104.1)
リリースノートへのリンクが存在しないURLになっております。

**Comment by ousttrue** [comment]
報告ありがとうございます。

問題が２つありました。
* `v0.100.0` 以降のフォルダを `079` から `100` に移動していた。
* `vMajor.Minor.Patch` で `Patch` のリリースノートは生成していない。

とりあえず `v0.104.0` に向けて修正しました。
`v0.100.0` 以降の他のリンクも順次修正します。

**Comment by ousttrue** [comment]
なおしました。
