### ISSUE TITLE
SkinedMeshRendererのBlendShapesで動かないシェイプがある

### ISSUE THREAD

**Issue by nishlumi** [vrm-c/UniVRM#1857]
## 環境情報

 - UniVRM version: `VRM-0.104.0_c466`
 - Unity version: `Unity-2021-3.10f1`
 - OS: `Windows 10`

## バグについて

* バグの内容
SkinnedMeshRendererに含まれるBlendShapesが値の変更が反映されるものとされないものがある。

試したVRM： 
1, VRoidStudio製のVRM(0.x製のモデル、1.xコンバート済みのモデル）
2, それ以外の独自モデル（VRoidHubから。構成を見たところ非VRoidStudio製）

再現方法：
1, Unity Editor上でインスペクターの、SkinedMeshRendererのBlendShapesの各シェイプのスライダーから
2, 自作のアプリケーションから（プログラムから： SkinedMeshRenderer.SetBlendShapeWeight）

現象：　動くシェイプと動かないシェイプがある。
例（VRoidStudio製VRMの場合）：
動かない：Fcl_ALL_AngryなどFcl_ALL系すべて、Fcl_EYE_Natural、Fcl_EYE_Close系すべて、Fcl_MTH_A～O

Fcl_ALLであれば複数の箇所が動くことになるため、もしかすると複数の箇所のメッシュが内部で動くシェイプは仕様変更で動かなくなったのか？と思いましたが、Fcl_MTH_Aなど口だけ動くものでも動くものと動かないものが入り交じることから、疑問に思いました。
そしてUnity Editor上だけで動かないのかと想定しましたが、自作のアプリケーションのプログラム上でも同じシェイプが動かなかった結果から、環境関係なくこの問題が起きるのかと考えました。

なお、VRM10RuntimeExpressionのSetWeightのほうのシェイプはいずれも全て動きました。

一時的な対応策：
・VRM10InstanceのUpdateTypeを Vrm10Instance.UpdateTypes.None にする

NoneにすることでBlendShapesは全て動くようになりました。しかしその後None以外にするとSkinedMeshRendererのBlendShapesはすべて0に戻り、再び動かなくなるシェイプが発生します。

その他確認：
UniVRM 0.xを使用した自作アプリケーション上では、今回動かなかったシェイプは全て動いたことを確認。

これがバグなのか、VRM1.0になっての仕様変更の影響、あるいは別の設定が必要になるものなのかわからないため、ご確認をお願いいたします。

* ConsoleLog
* スクリーンショット
* 再現方法
* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

**Comment by ousttrue** [comment]
報告ありがとうございます。

VRM は `0.x` も `1.0` も両方とも `SkinedMeshRenderer.SetBlendShapeWeight` をVRMを通さずに直接呼ぶのを想定していない実装になっています。
順番的にそのフレームで後ろになったものが上書きして勝ちそうな気がします。

VRM より後に関数を呼び出したいという需要がありそうです。
VRM-1.0 の `Runtime.Process()` の後にコールバックを登録したり、なんらかのイベントシステムを追加できそうです。

**Comment by ousttrue** [comment]
#1869

**Comment by ousttrue** [comment]
1. `Vrm10Instance.UpdateTypes.None` を使う
2. `Vrm10Instance.Runtime.Process()` を手動で呼び出す
3. その後で SkinnedMeshRenderer を操作する

など、順番を制御することで解決できないかお試しください。

**Comment by nishlumi** [comment]
アドバイスいただいた方法を試してみました。

1. `UpdateTypes.None`
すでに試したことがあるのですが、確かに動かなかったブレンドシェイプが動くようになります。
その代わり、FinalIKなどのIKシステムでVRMが動かなくなりました。
さらに、再びLastUpdateにすると、Noneにする直前のブレンドシェイプ（つまり最初のLastUpdate時の）が復元され、Noneの間にセットしたブレンドシェイプがすべて上書きされました。

(例: 最初のLastUpdate時、Fcl_EYE_Close=100。None時、Fcl_ALL_Fun=100。LastUpdateに戻す=Fcl_EYE_Close=100、Fcl_ALL_Fun=0。）


2. `Runtime.Process()`
 
試した実装パターン
a. Update()内で常に実行した場合
b. SetBlendShapeWeight()の直後のみ

a、b両方とも、Noneにすれば動くようになるSkinnedMeshRendererのブレンドシェイプは
None/LastUpdate/Updateのいずれの場合でもUnity EditorのスライダーUIすら動かなくなりました。

FinalIKなどのIKも1と同様で、UpdateTypes.Noneでは動かなくなります。
（Update/LastUpdateにすれば動きます）

3. 1および2、これらの組み合わせの後で `SkinnedMeshRenderer` を操作する

```
VRM10Instance.Runtime.Process();
SkinnedMeshRenderer.SetBlendShapeWeight(index, value);
```
などとし、次の2パターンで試してみました。
UpdateTypes.LastUpdate時・・・一切動かず
UpdateTypes.None時・・・ブレンドシェイプは動きますがやはりIKが動かず

症状としては1、2と変わらずでした。


0.106が公開されたとのことなので、試していた0.104から入れ替えて再確認しましたが、いずれのケースも
今回の症状は発生しました。

1と2がうまく噛み合えば解決できそうなのでしょうが、引き続き試してみます。

**Comment by nishlumi** [comment]
諸々検証してようやく理解できました。下記の状態でした。

**Blendshapeで動かないシェイプ＝Expressionで実装され、競合しているシェイプ**

競合していないシェイプは動くことから、自前のアプリの対応方法としては
Blendshape側で動かないシェイプはExpression側で動くので問題なし（＋個別シェイプは動くのでさらに問題なし）とすることで解決に至りそうです。

バグではなくあくまでも仕様という理解しましたので、本issueは閉じていただいても大丈夫です。

## 検証

UpdateType=LastUpdate（デフォルト）　＋　VRoidStudio製VRMの場合：

| Expression | Blendshapeの一括シェイプ | Blendshapeの個別シェイプ |
| - | - | - |
happy | ALL_Joy | BRW_Joy, EYE_Joy, MTH_Joy |
| 動く | 動かない | すべて動く|

上記のように確認できました。
喜怒哀楽とaiueoはExpression側に同意味のものとして存在するため、Blendshape側の同意味のシェイプは動かなかったとしても問題ないと判断できました。

ご教授いただいた UpdateTypeは、それぞれRuntime.Process()がどこで実行されるかを制御するためのものだったのですね。
それならばUpdateType=NoneはRuntime.Process()が実行されないため、ボーンが一切動かなくなるのも理解できました。
（VRM1.x側の自動的な反映がなくなり、Unityや他の処理がそのまま活きるようになる。あくまで自分で挙動を制御するため？）

自分の不勉強で長文のissueを投稿してご迷惑をおかけしてしまい、申し訳ございませんでした。
