### ISSUE TITLE
no export options in vrm exporter

### ISSUE THREAD

**Issue by frostproto** [vrm-c/UniVRM#1862]
## Environments (please complete the following information):

 - UniVRM version: `0.81.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 11`

## Describe the bug

* When using the vrm exporter, no options appear.
* ConsoleLog
* 
![image](https://user-images.githubusercontent.com/115624841/195306173-1ce2fef8-1bae-43fe-8e99-a5ff28553c0a.png)

* import model, export, import prefab, export and no options appear
* File that causes an error (those that can be pasted here)

**Comment by ousttrue** [comment]
Thank you for reporting.
Are there any error messages in the console?
