### ISSUE TITLE
[1.0] Cannot export due to All Authors is whitespace

### ISSUE THREAD

**Issue by WizecatZA** [vrm-c/UniVRM#1880]
- VRM  0.105.0_cd48
 - Unity 2020.3.41f1
 - OS: `Windows 10`

When attempting to export a model the author field does not appear. I have tried clean installs of every vrm 1.0 version and unity versions 2020.3.41f1 and 2021.3.11f1. 
![VRM Broken](https://user-images.githubusercontent.com/116459361/197358650-71f7f1ad-5ba3-4b88-aa28-7b35bdbd5b31.png)

**Comment by BalthiBoom** [comment]
Had the same issue, here's a fix. For some reason the "Element0" field is the "Author" field.
https://github.com/vrm-c/UniVRM/issues/1845#issuecomment-1283192946
