### ISSUE TITLE
assets.generator が空になっている

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/UniVRM#1896]
## 環境情報

 - UniVRM version: `0.106.0`
 - Unity version: `Unity-2020.3`
 - OS: `Windows 11`

## バグについて

- VRM-1.0 をエクスポートすると assets.generator が空欄になっている

**Comment by ousttrue** [comment]
`vrm-0.x` と `glb` のエクスポートは `UniGLTF-2.42.0` になっていることを確認した。

**Comment by Santarh** [comment]
現状のリポジトリとパッケージの構成名の関係から、どうするのが望ましいのかちょっと考えてからレビューをする

- UniVRM（リポジトリ名・開発名）
    - UniGLTF ( `com.vrmc.gltf` )
    - VRM ( `com.vrmc.univrm` )
    - VRM10 ( `com.vrmc.vrm` )
