### ISSUE TITLE
VRM1として出力されたデータのGLBとしての互換性について

### ISSUE THREAD

**Issue by m-sigepon** [vrm-c/UniVRM#1906]
## 環境情報

 - UniVRM version: `v0.106.0`
 - Unity version: `Unity-2021.3.11f1`
 - OS: `Windows 11`

## バグについて

* バグの内容
一部環境で、.VRMとして出力したVRM1のデータを.GLBとリネームしGLBインポート環境で読み込んだところ正しくブレンドシェイプが読めずフェイシャル分変化がない表情がインポートされます。
同ツールの、同バージョンで0.xで過去にエクスポートした.VRMファイルを.GLBとしてリネームしてインポートすると正常にブレンドシェイプもインポートできます。（つまり過去バージョンで生成したVRMはGLBとの互換性が保てています）

また、VRM1同梱のGLBエクスポーターで、GLBとしてエクスポートするとブレンドシェイプが正しくインポートされました。

確認事項として、VRMの中身はGLBがベースでありVRMはあくまでextension情報として保持されていると思うのですがGLBとしてエクスポートされるデータと、VRMとしてエクスポートされるデータで0.x時代とGLB部分の読み込みが異なる状態になっていたりするでしょうか？
少なくとも、確認したソフトでは異なる状態でインポートされてしまうようです。

VRM1になっても、GLBとしての互換性が保たれているという前提であるならば.VRMファイルを.GLBとリネームした状態でも、GLB対応環境で正常に読めるようになってほしいです。（これが意図していない挙動であるならば）

**VRMをGLBにリネームして正常に読め込めないツール**
- [Metasequoia v4.8.4](https://www.metaseq.net/jp/download/)というモデリングソフトで発生、またVRMをGLBにリネームしたデータをインポートするとクラッシュが頻発
（[TinyGLTF](https://github.com/syoyo/tinygltf)を使用しているようです）

- [khronos公式のglTFサンプルビューアー](https://github.khronos.org/glTF-Sample-Viewer-Release/)
（エラーメッセージ出力、Message: Uncaught TypeError: Cannot read properties of undefined (reading 'subarray') - URL: https://github.khronos.org/glTF-Sample-Viewer-Release/GltfSVApp.js - Line: 20442 - Column: 30 - Error object: {}）
- Windows標準の、3Dビューアー
（読み込むとクラッシュ）

**VRMをGLBにリネームして正常に読み込めるツール**
- [Blender v3.3.1](https://www.blender.org/download/)標準のGLBインポーターで問題なくブレンドシェイプをインポート

* スクリーンショット
VRM1のサンプルデータを、.vrmから.glbにリネームしてインポート。ブレンドシェイプが正常に読めていない
![image](https://user-images.githubusercontent.com/26161297/199830946-703ddb7c-2e68-46f8-b48a-51a8c0724efd.png)
VRM1のサンプルデータを、Unity上のVRMプラグインのUniGLTFからエクスポートしインポート。ブレンドシェイプが正常に読まれる
![image](https://user-images.githubusercontent.com/26161297/199834633-775ed22d-833a-4253-ac1d-121f8051254e.png)

* 再現方法
VRM1のサンプルモデルをダウンロードし、.vrmから.glbにリネームし各種GLB2.0対応環境でインポート
https://github.com/vrm-c/vrm-specification/tree/master/samples

[Seed-san](https://github.com/vrm-c/vrm-specification/blob/master/samples/Seed-san)
[VRM1_Constraint_Twist_Sample](https://github.com/vrm-c/vrm-specification/blob/master/samples/VRM1_Constraint_Twist_Sample)

**Comment by saturday06** [comment]
UniVRMのVRM 0.xエクスポートでsparse accessorを有効にすると、今回の現象と同様にWindowsのビューワーがクラッシュし、glTF-Sample-Viewerでエラーが出ました。

<img src="https://user-images.githubusercontent.com/532872/199854617-aff4252a-7924-4690-b605-a04c5336f472.png" width="400">

たぶん、VRMのバージョンに関係なく、現象が再現するツールではsparse accessorに対応してないんだと思います。今回の現象を再現させたVRM0モデルを添付します。 [three-vrm-girl-vrm0-sparse-accessor.zip](https://github.com/vrm-c/UniVRM/files/9933673/three-vrm-girl-vrm0-sparse-accessor.zip)

**Comment by saturday06** [comment]
でも、Khronos公式のビューワーとかMicrosoft公式のビューワーとかが正常動作しないのならば、確かに何か見落としとかあるのかもですね。

glTF Validator的にはエラーは無かったんですが、ousttrueさんが以前glTF Validatorのsparse accessorのチェックは微妙だったって仰ってたと思うのでこの点は完全に依存はできない。

**Comment by m-sigepon** [comment]
sparse accessor今回の問題に関連してそうですね、sparse accessorがいつ頃実装されて現在のKhronos公式ビューアーとMicrosoft公式ビューアーが対応してない可能性があるのかな？
TinyGLTFは、v2.6.0でsparse accessorのシリアライズに対応とあるのでMetasequoiaの方に対応を問い合わせてみたいと思います。

**Comment by m-sigepon** [comment]
UniGLTFでUse Sparse accessor ForのありとなしをVRM1のv0.106.0で出力してみました。
VRMとしてエクスポートされたデータとまた異なるブレンドシェイプの壊れ方をしてました。
glTF-Validatorではどちらのデータも問題なしですが、khronos公式のglTFサンプルビューアーでエラーとWindows標準の3Dビューアーではクラッシュは同じでどちらも非対応？っぽいようです。

UniGLTFでUse Sparse accessor For チェック無し
![image](https://user-images.githubusercontent.com/26161297/199865017-515152d3-df3d-412f-aeda-f40ca733d121.png)
UniGLTFでUse Sparse accessor For チェック有り
![image](https://user-images.githubusercontent.com/26161297/199865315-0ce15992-4ee0-44e6-87ff-a6fd3a9c8c00.png)
サンプルファイル
[GLB_sparse accessor_testzip.zip](https://github.com/vrm-c/UniVRM/files/9934212/GLB_sparse.accessor_testzip.zip)

**Comment by ousttrue** [comment]
space は拡張じゃないので、それで落ちるのは仕方が無いと思います。
vrm-1.0 ではデフォルトで sparse を使うかつ、sparse を off にする UI が無かったので、
あとで追加しておきます。

**Comment by ousttrue** [comment]
#1913

**Comment by m-sigepon** [comment]
ブレンドシェイプの容量肥大化には対処したいので、デフォルトで有効なのは問題無いと思います。
UI側でのオンオフ対応承知しました。
