### ISSUE TITLE
UnityPathとPathObjectの統合について

### ISSUE THREAD

**Issue by mkc1370** [vrm-c/UniVRM#1927]
#1905 でUnityPathでPackages以下のファイルを扱えるようになりましたが、FBXがPackages以下にある状態で`Create new VRM10Object and default Expressions. select target folder`を選択するとPathObjectの処理が走るため以下のようなエラーが出ます。

<details>
<summary>エラー全文</summary>

```
ArgumentException: {Packages以下のFBXのパス}.asset is not under UnityAssetPath
VRMShaders.PathObject.get_UnityAssetPath () (at C:/Users/mkc1370/src/unity/Sample/UniVRM/Assets/VRMShaders/GLTF/IO/Runtime/PathObject.cs:47)
UniVRM10.Vrm10InstanceEditor.GetSaveName (UniVRM10.Vrm10Instance instance) (at C:/Users/mkc1370/src/unity/Sample/UniVRM/Assets/VRM10/Editor/Vrm10InstanceEditor.cs:131)
UniVRM10.Vrm10InstanceEditor.SetupVRM10Object (UniVRM10.Vrm10Instance instance) (at C:/Users/mkc1370/src/unity/Sample/UniVRM/Assets/VRM10/Editor/Vrm10InstanceEditor.cs:155)
UniVRM10.Vrm10InstanceEditor.OnInspectorGUI () (at C:/Users/mkc1370/src/unity/Sample/UniVRM/Assets/VRM10/Editor/Vrm10InstanceEditor.cs:189)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <49d9ebdb7a214103a5464220bdb1d1c3>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```
</details>

PathObjectも #1905 のような対応をすることは可能ですが、今後修正が二度手間になってしまうのでUnityPathの機能の一部（又は全部）をPathObjectできたら良いかと思いました。

**Comment by ousttrue** [comment]
`UnityPath` が UnityProject 外のパスを扱えない問題に対処するために、代替品として `PathObject` 後から追加しました。
必要な場所だけ `PathObject` に置き換えていく方針です。

UnityPath は外のパスが扱えない(変なところにAssetを作ろうとして失敗するのを防止)、UnityEditor 向け(Runtime向けの機能をはしょっている)にすることで、わりと安全側に倒してあるのです。
UnityPath 自体はあまり変化しないだろうとの見通しでした。
UnityPath は使っているところが多いので一度に置き換えると大変なので・・・

PathObject の責務を見直した方が良いかもしれない(Editor系の機能はやめる。必要に応じて UnityPath に変換するなど)。
