### ISSUE TITLE
(How to)Is there a way to import .fbx or other formats and convert that into vrm format in runtime?

### ISSUE THREAD

**Issue by ArivazhaganDeeploop** [vrm-c/UniVRM#1929]
Importing a .fbx file in runtime and convert it into .vrm format at runtime.

**Comment by Santarh** [comment]
Hi, you need to implement own codes or introduce third-party assets to import fbx files.
Unity and UniVRM don't provide the feature to import fbx files at runtime.

**Comment by ArivazhaganDeeploop** [comment]
Hello, if i did implement to import fbx in runtime is there a way to convert the file into .vrm in runtime using univrm?

**Comment by Santarh** [comment]
Yes, UniVRM can export the GameObject instance that satisfies the following conditions as VRM files.

- Root GameObject has `Animator` and that contains the human avatar.
- Transforms is in T-Pose.
- Human avatar contains the bones that required from the vrm specificaton.
- Materials contain only VRM supported shaders.
- VRM components is added to the root GameObject and setup completely.

Some published applications seem to export models using UniVRM at runtime.
https://twitter.com/cecilproject
https://vroid.com/studio

**Comment by ArivazhaganDeeploop** [comment]
Okay Thank you.
