### ISSUE TITLE
Cannot import glb File Asset

### ISSUE THREAD

**Issue by abo3skr2019** [vrm-c/UniVRM#1930]
## Environments (please complete the following information):

 - UniVRM version: `0.107.0`
 - Unity version: `Unity-2020.20f1`
 - OS: `Windows 10`

## Describe the bug

* A clear and concise description of what the bug is.
* upon importing a glb file i get a runnable file but cannot get into unity engine
* seems to be connected to the size of the file
* ConsoleLog
* Asset import failed, "Assets/AskarAvatarWInt.glb" > InvalidOperationException: Types System.Byte (array length 6204) and UnityEngine.Vector4 cannot be aliased due to size constraints. The size of the types and lengths involved must line up.
Unity.Collections.NativeArray`1[T].CheckReinterpretSize[U] (System.Int64 tSize, System.Int64 uSize, System.Int32 expectedTypeSize, System.Int64 byteLen, System.Int64 uLen) (at <ad3eaa0878d94cbe8e45f9c494d71647>:0)
Unity.Collections.NativeArray`1[T].Reinterpret[U] (System.Int32 expectedTypeSize) (at <ad3eaa0878d94cbe8e45f9c494d71647>:0)
UniGLTF.GltfData.GetTypedFromAccessor[T] (UniGLTF.glTFAccessor accessor, UniGLTF.glTFBufferView view) (at Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs:169)
UniGLTF.GltfData.GetArrayFromAccessor[T] (System.Int32 accessorIndex) (at Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs:221)
UniGLTF.WeightsAccessor.GetAccessor (UniGLTF.GltfData data, System.Int32 accessorIndex) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/WeightsAccessor.cs:44)
UniGLTF.PrimitiveExtensions.GetWeights (UniGLTF.glTFPrimitives primitives, UniGLTF.GltfData data, System.Int32 positionsLength) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/PrimitiveExtensions.cs:204)
UniGLTF.SkinningInfo.Create (UniGLTF.GltfData data, UniGLTF.glTFMesh mesh, UniGLTF.glTFPrimitives primitives) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/SkinningInfo.cs:32)
UniGLTF.MeshData.ImportMeshSharingVertexBuffer (UniGLTF.GltfData data, UniGLTF.glTFMesh gltfMesh, UniGLTF.IAxisInverter inverter) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshData.cs:449)
UniGLTF.MeshData.LoadFromGltf (UniGLTF.GltfData data, System.Int32 meshIndex, UniGLTF.IAxisInverter inverter) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshData.cs:112)
UniGLTF.ImporterContext+<>c__DisplayClass35_1.<LoadGeometryAsync>b__0 () (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:196)
VRMShaders.ImmediateCaller.Run (System.Action action) (at Assets/VRMShaders/GLTF/IO/Runtime/AwaitCaller/ImmediateCaller.cs:18)
UniGLTF.ImporterContext+<LoadGeometryAsync>d__35.MoveNext () (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:196)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
UniGLTF.ImporterContext+<LoadAsync>d__32.MoveNext () (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:116)
Rethrow as AggregateException: One or more errors occurred.
Rethrow as AggregateException: One or more errors occurred.
UniGLTF.ImporterContextExtensions.Load (UniGLTF.ImporterContext self) (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContextExtensions.cs:30)
UniGLTF.GltfScriptedImporterBase.Import (UnityEditor.AssetImporters.ScriptedImporter scriptedImporter, UnityEditor.AssetImporters.AssetImportContext context, UniGLTF.Axes reverseAxis, UniGLTF.RenderPipelineTypes renderPipeline) (at Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterBase.cs:86)
UniGLTF.GlbScriptedImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GlbScriptedImporter.cs:23)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <83a38f5397d94e36a22efa3369c82390>:0)
UnityEditor.AssetDatabase:ImportAsset(String)
UniGLTF.UnityPath:ImportAsset() (at Assets/UniGLTF/Runtime/UniGLTF/IO/UnityPath.cs:437)
UniGLTF.TopMenuImplementation:ImportGltfFileToGameObject() (at Assets/UniGLTF/Editor/TopMenuImplementation.cs:97)
UniGLTF.TopMenu:ImportGltfFile() (at Assets/UniGLTF/Editor/TopMenu.cs:26)

UnityEditor.AssetDatabase:ImportAsset (string)
UniGLTF.UnityPath:ImportAsset () (at Assets/UniGLTF/Runtime/UniGLTF/IO/UnityPath.cs:437)
UniGLTF.TopMenuImplementation:ImportGltfFileToGameObject () (at Assets/UniGLTF/Editor/TopMenuImplementation.cs:97)
UniGLTF.TopMenu:ImportGltfFile () (at Assets/UniGLTF/Editor/TopMenu.cs:26)

* ScreenShot
* 
![image](https://user-images.githubusercontent.com/68832286/203375854-17a8de36-0418-4346-9d2d-61d489ef281d.png)

![image](https://user-images.githubusercontent.com/68832286/203375884-808ae0c0-8072-478f-bd67-741a024063e7.png)

* Reproduction procedure
* importing an approximately 3.4mb glb file
* File that causes an error (those that can be pasted here)
https://drive.google.com/file/d/1RQm7qQWOrv5RPUvVR3FT2_5ux5AtHQ8L/view?usp=share_link

**Comment by ousttrue** [comment]
Thank you for your report.
Only Planar layout was implemented. I will now implement an interleaved layout.
This model has an interleaved vertex layout with a stride of 52 bytes.
