### ISSUE TITLE
GLB import with HTTP request?

### ISSUE THREAD

**Issue by badjano** [vrm-c/UniVRM#1931]
It looks like it's possible, maybe first loading the bytes from the url and then parsing it as a glb, but I can't find an example anywhere

**Comment by ArivazhaganDeeploop** [comment]
I tried doing that using uwr getting error as "A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details."

**Comment by ArivazhaganDeeploop** [comment]
What u can do is download the glb as file and u can load that in runtime by choosing path that's one way to do. if others have any methods to do this thing I'm happy to explore that too.

**Comment by badjano** [comment]
> download the glb as file and u can load that in runtime

unfortunately my project is in webgl :(

**Comment by ousttrue** [comment]
https://github.com/vrm-c/UniVRM/blob/master/Assets/VRM_Samples/SimpleViewer/ViewerUI.cs#L254

Here is webgl loading sample.
Get glb bytes from `UnityEngine.Networking.UnityWebRequest`.

See also
https://vrm-c.github.io/UniVRM/en/api/0_82_glb_import.html
