### ISSUE TITLE
IndexOutofRangeException: index was outside the bounds of the array 

### ISSUE THREAD

**Issue by wifininja** [vrm-c/UniVRM#1932]
Attempted to export to vrm 
Model was using Silent Cel Shader but changed all materials to VRM/Mtoon

Error : 
IndexOutOfRangeException: Index was outside the bounds of the array.
UniGLTF.MeshExporter_SharedVertexBuffer.Export (UniGLTF.ExportingGltfData data, UniGLTF.MeshExportInfo unityMesh, System.Collections.Generic.List`1[T] unityMaterials, UniGLTF.IAxisInverter axisInverter, UniGLTF.GltfExportSettings settings) (at Library/PackageCache/com.vrmc.gltf@1e8a6b35bd/Runtime/UniGLTF/IO/MeshIO/MeshExporter_SharedVertexBuffer.cs:129)
UniGLTF.gltfExporter.Export (VRMShaders.ITextureSerializer textureSerializer) (at Library/PackageCache/com.vrmc.gltf@1e8a6b35bd/Runtime/UniGLTF/IO/gltfExporter.cs:259)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings, System.Collections.Generic.List`1[T] destroy) (at Library/PackageCache/com.vrmc.univrm@1e8a6b35bd/Editor/Format/VRMEditorExporter.cs:237)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings) (at Library/PackageCache/com.vrmc.univrm@1e8a6b35bd/Editor/Format/VRMEditorExporter.cs:25)
VRM.VRMExporterWizard.ExportPath (System.String path) (at Library/PackageCache/com.vrmc.univrm@1e8a6b35bd/Editor/Format/VRMExporterWizard.cs:263)
UniGLTF.ExportDialogBase.EndGUI () (at Library/PackageCache/com.vrmc.gltf@1e8a6b35bd/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:161)
UniGLTF.ExportDialogBase.OnGUI () (at Library/PackageCache/com.vrmc.gltf@1e8a6b35bd/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:82)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect dockAreaRect) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.DockArea.OldOnGUI () (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <171d8a8f3bd84fa7b9eb1f330018a789>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <3eb17ad1b1ca496fb8c17fd74f372d76>:0)

**Comment by ousttrue** [comment]
Thank you for reporting.

**Comment by ousttrue** [comment]
Error is happening here.

https://github.com/vrm-c/UniVRM/blob/v0.108.0/Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExporter_SharedVertexBuffer.cs#L128

It seems to be due to a special submesh structure.
For example, the length of index is not a multiple of 3.

I don't know much more without the model data.
