### ISSUE TITLE
DnD to unity assets folder did not fix issue. (Assets/直下で import が Exceptionになる)

### ISSUE THREAD

**Issue by rhoelli** [vrm-c/UniVRM#1935]
Dnd to unity assets folder did not fix methode not implemented. Also reimporting all caused disallow import from folder under assets

**Comment by ousttrue** [comment]
Thank you for your report.
This problem is fixed at #1941 .

Dragging and dropping directly into the Assets folder will throw an exception.

Workaround: Create a folder and dnd there.

**Comment by ousttrue** [comment]
fixed `v0.108.0`
