### ISSUE TITLE
Imported VRM straight from VRoid Studio has thumb bones pointing in wrong direction

### ISSUE THREAD

**Issue by flarn2006** [vrm-c/UniVRM#1936]
## Environments (please complete the following information):

 - UniVRM version: VRM 0.107.0
 - Unity version: 2021.3.12f1
 - OS: Arch Linux

## Describe the bug

When I import a VRM model exported from VRoid Studio v1.17.0 (Steam version) the thumb bones are pointing in the wrong direction; as a result I have been having significant difficulties getting it to work with finger tracking in the game I'm developing. This issue appears in Blender as well, which suggests a problem with VRoid Studio rather than UniVRC, though I have been advised to post an issue here as apparently there have been issues like this in the past.

![Screenshot](https://user-images.githubusercontent.com/687313/204447898-e57cc204-7d63-491e-a134-2f9f6575c56b.png)

Note that while I am running VRoid Studio through Proton (which I'm aware is likely an unsupported configuration) I've also run it on my Mac (which is officially supported) and the same issue occurs with models exported from there.

**Comment by Santarh** [comment]
What plugin do you use for importing the vrm file in Blender?
You'll should get a answer by contacting supports of the plugin and VRoid Studio, or finding knowledges of Blender community.

Typically, "Bones" are implemented in a variant ways.
Especially Blender is quite different from other 3D softwares.
Therefore, solving this issue requires a special implementation in the plugin.

--- 
Technical appendix:
The VRoid model satisfy the vrm-0.x specification and the spec requires that the bone transform is normalized.
The latest vrm-1.0 spec does not require bone normalization.
If VRoid Studio conforms to VRM 1.0 specification, this situation will improve.

**Comment by slnfox** [comment]
Hello @flarn2006, did you find any solutions?
I'm also having this issue when using [AliciaSolid_vrm-0.51.vrm](https://github.com/vrm-c/UniVRM/blob/master/Tests/Models/Alicia_vrm-0.51/AliciaSolid_vrm-0.51.vrm) from this repo.

![image](https://github.com/user-attachments/assets/d01ec5e9-ee87-4d49-a827-b5e3cc7ec57d)
