### ISSUE TITLE
FR: Is there a workaround so someone doesn't need a complete humanoid rig?

### ISSUE THREAD

**Issue by rickyManalo** [vrm-c/UniVRM#1940]
Because of laziness and just and the fact that it's unnecessary work on my use case, for now, I want to know if there is a way to not need a full humanoid rig. And if there isn't a way, request for such feature.

**Comment by Santarh** [comment]
Am I correct in that you are trying to import a VRM 1.0 model without a `ControlRig` at runtime?

You can import a VRM 1.0 model without a `ControlRig` with the code below.

```csharp
async void Start()
{
    await Vrm10.LoadPathAsync("pathToVrmFile", controlRigGenerationOption: ControlRigGenerationOption.None);
}
```

**Comment by rickyManalo** [comment]
Where do I add that code though? Also, I don't know what a `ControlRig` is. If it's the armature/bones/rig, then that was what I meant earlier.

**Comment by rickyManalo** [comment]
Yes. Ah, too bad.
