### ISSUE TITLE
Blendshapes breaks after exporting FBX to VRM

### ISSUE THREAD

**Issue by Krieghor** [vrm-c/UniVRM#1961]
## Environments

 - UniVRM version: `0.107.0`
 - Unity version: `Unity-2021.3.14f1`
 - OS: `Windows 10`

## Describe the bug

I import my FBX file into Unity with no problem and the Blendshapes of the skinned mesh render works flawlessly, but when I export the model via UniVRM and load the .vrm in the scene, the blendshapes are kinda broken. They are not gone or totally broken, but some of them are different, like some vertex go wild. These blendshapes also look bad in VSeeface.

![blendshapeserror](https://user-images.githubusercontent.com/41807891/208267672-ea8964fc-56ee-4bbd-acae-82bf9aa8b7d2.jpg)

**Comment by Krieghor** [comment]
Ok I figured it out something. If I check "Legacy Blendshapes" at the FBX import, the **exactly same issue** is now present in the FBX. It's like the UniVRM export forces Legacy Blendshapes anyways.

**Comment by Krieghor** [comment]
I found a workaround. If I use Blender VRM addon to export the VRM, the blendshapes work just fine. Then I can import the VRM from Blender into Unity using UniVRM and the blendshapes are ok. I can even export again with Univrm with no problem.

**Comment by Sylvie44444** [comment]
do I need to install blender for this workaround to work?

**Comment by ousttrue** [comment]
Thank you for reporting.
#1870
