### ISSUE TITLE
Assets\VRM10\Runtime\Components\Constraint\IVrm10Constraint.cs(7,23): error CS0106: The modifier 'internal' is not valid for this item

### ISSUE THREAD

**Issue by Wuschllama** [vrm-c/UniVRM#1963]
## 環境情報

 - VRM: `0.108.0_e16d`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## バグについて

* バグの内容
* ConsoleLog
* スクリーンショット
* 再現方法
* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

**Comment by KryssSierr** [comment]
I have the same problem with the latest version.
