### ISSUE TITLE
Need help with a weird use case

### ISSUE THREAD

**Issue by gigglelier** [vrm-c/UniVRM#1968]
## 環境情報 (Environmental information)

 - UniVRM version: `0.108.0`
 - Unity version: `Unity-2020.3.42f1`
 - OS: `Windows 10`

## バグについて (About bugs)
  I have a weird use-case where I'm trying to make a character with detached pieces and extra limbs. And I found some issue after converting it to VRM using the library.

* バグの内容 (Content of the bug)
  At first glance, the eyes is gone. And on further inspection, for some reason, the eyes are all scaled to 100 as well. But only X is 100, but Y and Z are both 99.99997. And further more, all the pieces have this 100 scale. Another issue is the materials reverted to the Standard.

* ConsoleLog
  
* スクリーンショット (Screenshot)
  Hierarchy
  ![image](https://drive.google.com/uc?export=view&id=1qWwaosRbhqxEZKsPzqvB9yD3QKmB_kbu)
  
  Original material looks like
  ![image](https://drive.google.com/uc?export=view&id=1NfXq5AAN7LrBkmmF1bnv_61VznZHVW4r)
  
  Material after export
  ![material after export](https://drive.google.com/uc?export=view&id=1TTEVemI1001jcG2ODFhbPL3GaMG5Fzv5)
  
  Character looks like originally
  ![character](https://drive.google.com/uc?export=view&id=1HS4mNq2fT2RBfbpkpWcly0MpJYArOmgS)
  
  Character looks after export
  ![character after export](https://drive.google.com/uc?export=view&id=1Jfmyas0wzKLCShOxoCW_6jhfQmrQ54Id)

* 再現方法 (How to reproduce)
  Well, I guess the only way to reproduce this is sharing the fbx file. I hope it stays here. The guide on https://vrm.dev/en seems very outdated, so I might have made some mistake on the exporting. So maybe you guys can make the correct export. [blend file](https://drive.google.com/file/d/1rqm_pkRcc36mK_kAK8LkUqoqt0St4qfW/view?usp=share_link)

* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの) (The file where the error occurs (you can paste it here if you like))

**Comment by ousttrue** [comment]
Thank you for reporting.

I tried to export this model as vrm-0.x.
Here are the steps:

- import fbx.
    - fbx `AnimationType` to humanoid
    - fbx configure to fix humanoid avatar setting(assign DEF-spine.006 to head)
    - fbx extract materials
- all materials to MToon
    - setup materials. color, outline.
- Export vrm 0.x
    - input title, version, author
- done

I was able to successfully export the vrm.

Try to move the bones and check the weight paint before vrm. hips, spine...etc

![mtoon](https://user-images.githubusercontent.com/68057/223069343-6349e259-572e-4cec-adb5-5e33a037f6b7.jpg)
