### ISSUE TITLE
Cannot export with errors! Please HELP!!

### ISSUE THREAD

**Issue by MlNE-SWEEPER** [vrm-c/UniVRM#1969]
Export button is available but it stops with no error messeage and then this 2 console errors appear.

![image](https://user-images.githubusercontent.com/82304011/212936969-a1006019-72b7-42a1-89a6-d894e576f364.png)

AvatarBuilder 'VRM': Found duplicate human bone 'Hips' with transform '' and 'Hips'
UnityEngine.AvatarBuilder:BuildHumanAvatar (UnityEngine.GameObject,UnityEngine.HumanDescription)
UniHumanoid.AvatarDescription:CreateAvatar (UnityEngine.Transform) (at Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs:128)
VRM.VRMImporterContext:LoadHumanoid () (at Assets/VRM/Runtime/IO/VRMImporterContext.cs:260)
VRM.VRMImporterContext/<OnLoadHierarchy>d__4:MoveNext () (at Assets/VRM/Runtime/IO/VRMImporterContext.cs:50)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<VRM.VRMImporterContext/<OnLoadHierarchy>d__4> (VRM.VRMImporterContext/<OnLoadHierarchy>d__4&)
VRM.VRMImporterContext:OnLoadHierarchy (VRMShaders.IAwaitCaller,System.Func`2<string, System.IDisposable>)
UniGLTF.ImporterContext/<LoadAsync>d__32:MoveNext () (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:127)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<UniGLTF.RuntimeGltfInstance>:Start<UniGLTF.ImporterContext/<LoadAsync>d__32> (UniGLTF.ImporterContext/<LoadAsync>d__32&)
UniGLTF.ImporterContext:LoadAsync (VRMShaders.IAwaitCaller,System.Func`2<string, System.IDisposable>)
UniGLTF.ImporterContextExtensions:Load (UniGLTF.ImporterContext) (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContextExtensions.cs:15)
VRM.vrmAssetPostprocessor/<>c__DisplayClass2_0:<ImportVrmAndCreatePrefab>b__0 (System.Collections.Generic.IEnumerable`1<UniGLTF.UnityPath>) (at Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs:85)
UniGLTF.TextureExtractor/<>c__DisplayClass12_0:<ExtractTextures>b__0 () (at Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/TextureExtractor.cs:103)
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()

Exception: fail to create avatar
VRM.VRMImporterContext.LoadHumanoid () (at Assets/VRM/Runtime/IO/VRMImporterContext.cs:263)
VRM.VRMImporterContext+<OnLoadHierarchy>d__4.MoveNext () (at Assets/VRM/Runtime/IO/VRMImporterContext.cs:50)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UniGLTF.ImporterContext+<LoadAsync>d__32.MoveNext () (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:127)
Rethrow as AggregateException: One or more errors occurred.
Rethrow as AggregateException: One or more errors occurred.
UniGLTF.ImporterContextExtensions.Load (UniGLTF.ImporterContext self) (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContextExtensions.cs:22)
VRM.vrmAssetPostprocessor+<>c__DisplayClass2_0.<ImportVrmAndCreatePrefab>b__0 (System.Collections.Generic.IEnumerable`1[T] texturePaths) (at Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs:85)
UniGLTF.TextureExtractor+<>c__DisplayClass12_0.<ExtractTextures>b__0 () (at Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/TextureExtractor.cs:103)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at <a259d3c004024353a2c217da97495055>:0)

**Comment by ousttrue** [comment]
Thank you for reporting.
The next version will contain the fix.

`v0.109`

**Comment by ousttrue** [comment]
#2005
