### ISSUE TITLE
UniVRM  タイムライン…プレイモードとエデットモードで挙動が異なる

### ISSUE THREAD

**Issue by Nekohatsuden** [vrm-c/UniVRM#1971]
## 環境情報

 - UniVRM version: `2.43.2` / VRM1.0　
 - Unity version: `Unity-2020.3.36f1`
 - OS: `Windows 10`

## バグについて

<やっていること>
・タイムラインで、VRM本体のアニメ動作と、口パクをアニメ動作を分けて再生している。

<症状>
・旧バージョンでは、本体のアニメ動作と口パクが両方正常に動作していた。
・新バージョンでは、本体のアニメ動作と口パクが、エデットのプレビュー再生では正常に動作する。
　しかし、プレイモードで再生すると、動かなくなる。
・エラーはありません。警告は本件に関わるものはありません。

<注意点>
・本体のアニメと口パクが別々のアニメであること。
・表情はタイムライン上でオーバーライド、２ラインで再生している（１ラインに絞っても動作はしませんので関係ないかと思います）

<手順>
・VRM10のFBXをプレハブバリアントにする。
・バリアントをシーンのヒエラルキーに配置（FBXでも結果は変わりませんでした）
・タイムラインに、本体とFaceを別々にセット
・プレビューでは動作しますが、プレイモードでは動作しません。

申し訳ありません。非常に単純なことなのですが、解決方法がわかりませんでした。
よろしくお願い申し上げますm(_ _)m

![image](https://user-images.githubusercontent.com/86540292/213845356-8da59a68-8ebc-4d3f-80b4-80841e08af0e.png)

**Comment by Nekohatsuden** [comment]
バージョン追記しましたm(_ _)m

**Comment by Nekohatsuden** [comment]
１．バージョンについて

＞旧バージョン 新バージョン とありますが、以下についてお教え願えますでしょうか？
＞期待した動作が得られた Unity と UniVRM のバージョンの組み合わせ
＞今期待した動作が得られていない Unity と UniVRM のバージョンの組み合わせ

勘違いが起きるような報告にて申し訳ござませんm(_ _)m
当方が、UniGLTF と　UniVRM　の違いを正確に認識していませんでした。

確認した内容は下記の通りです。

<動作正常>
UniGLTF  2.43.2 / UniVRM　0.107．2  ←旧バージョン
Unity version: Unity-2019.4.35f1

<今回の不良？としていた動作>
UniVRM   2.43.2 / VRM1.0　 ←新バージョン
Unity version: Unity-2020.3.36f1



２.表情上書きの対策について
>つまり Timeline を使って Blendshape weight を操作しても、 VrmInstance によって上書きされてしまうということです。

Vrm10Instance　だけの問題だったのですね。助かりましたー＞＜
結論としては、３つ目の選択にて対応しますが、１点気になるところがありました。

<状況>
Vrm10Instance最初からコンポーネントにから外すと、髪揺れなどスプリングボーン系も完全に死んだままですが、
一度　Vrm10Instanceを動作させて、あとからスクリプトをenableすると、表情を入れても髪揺れがそのまま挙動するようです。

<念のための質問>
上記の挙動は正常でしょうか。(これがバクだったら、大変困るのですが)


口パクは最終的にシグナルによるリップシンクを使う予定ですが、表情だけはwavを見ながら手で後付しないと現状どうにもならなず、今回の動かなくなって　表情もタイムラインのシグナルなどを使うべきかどうか、日汗をかいておりました。
VRMキャラが50程いますと、タイムラインでのアニメ作業作成の作業効率にかなり響きます。


とりあえず、Vrm10Instanceを最初だけ起動し、enableすれば 揺れ物も動作し、表情も使えるという認識で進める予定です。
まずは対策が見つかりかつ簡単に対策できるため助かりました。

ありがとうございました。

**Comment by Santarh** [comment]
ありがとうございます。

> 一度　Vrm10Instanceを動作させて、あとからスクリプトをenableすると、表情を入れても髪揺れがそのまま挙動するようです

こちらに関しては、髪揺れ (SpringBone) の制御は最適化の都合上全モデルで ON/OFF をするインタフェースのみ現状提供しているため `FastSpringBoneService.Instance.UpdateType` を操作することで ON/OFF が可能です。
