### ISSUE TITLE
バージョンアップした後の、処理負荷の軽減について

### ISSUE THREAD

**Issue by Nekohatsuden** [vrm-c/UniVRM#1974]
要望です。

unity2019でのVRM0とunity2020でのVRM10 では、同じVRMデータを同じ条件で表示させても、写真のとおりかなりの差が出ます(アナリティクスでは、やはりレンダー負荷が大きいです)

![image](https://user-images.githubusercontent.com/86540292/213968733-e37482b1-897b-4c3e-bd4e-2091634f2d55.png)

Vroid Habでは最適化がされるようですが、ブラウザ上のみで利用はできないようです。
ついては、

・最適化されたデータを利用できる方法、コンバーターのリリース
・処理速度を速めるノウハウなどを記載したページ

などをご検討いただければ、ゲーム制作者としてはとても助かります。

週末に一気に試したため連続投稿になってしまい大変申し訳ありませんが、
何卒よろしくお願い申し上げますm(_ _)m

![image](https://user-images.githubusercontent.com/86540292/213966815-679835f9-a5b8-48e7-8fa9-ee3192cb37cd.png)

**Comment by Nekohatsuden** [comment]
検証結果追加しました。

**Comment by Santarh** [comment]
報告ありがとうございます。

バージョン別の描画フレームレート検証結果までありがとうございます！

パフォーマンス改善は常時の課題として認識しています。
しかしながら開発リソースの関係上、負荷が大きく目立つところから優先度をつけて対処せざるを得ません。
具体的に「こういう使用例でこのメソッドが Profiler 上で大きな負荷を示していて困っている」などを挙げていただければ助かります。

随時行っていきますので、この Issue 自体は閉じさせていただきます……！
