### ISSUE TITLE
i cant add authors 

### ISSUE THREAD

**Issue by Tsx1234** [vrm-c/UniVRM#1981]
## Environments (please complete the following information):

 - UniVRM version: `0.81.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## Describe the bug

* A clear and concise description of what the bug is.
* ConsoleLog
* ScreenShot
* Reproduction procedure
* File that causes an error (those that can be pasted here)
![image](https://user-images.githubusercontent.com/28224883/215262880-2bce02e4-dde3-4fe9-a127-a14537248740.png)

**Comment by GamerPi** [comment]
I am also having this issue. I am trying to convert a vrchat avatar...
