### ISSUE TITLE
having some weird problems 

### ISSUE THREAD

**Issue by Pg12313** [vrm-c/UniVRM#1995]
## 環境情報

 - UniVRM version: `0.81.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## バグについて

* バグの内容
* ConsoleLog
* スクリーンショット
* 再現方法
* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

**Comment by Pg12313** [comment]
![github issue](https://user-images.githubusercontent.com/25317919/221493115-8bcdcc48-c933-4408-9e79-50f9c27a0e4e.PNG)

**Comment by thedigitalcowbo** [comment]
Same here, I've tried with VRM1 and VRM0
Tried an older version of VRM, tried editing the script with the error by changing 0 to 1, tried commenting out the exception in hopes it would just skip so I could export the VRM. Same errors. Just stuck here and can't export my avatar

![Screenshot 2023-03-05 114156](https://user-images.githubusercontent.com/127046222/222976930-70e60974-14b1-475b-90d9-e320ac911113.png)
![Screenshot 2023-03-05 114538](https://user-images.githubusercontent.com/127046222/222976946-f15ee75b-504e-4dff-a641-9225b259dbdc.png)

**Comment by ousttrue** [comment]
# First

`ArgumentException: Getting COntrol 0's position ina group with only 0 controls when doing repaint.`

is not vrm error message.
But, If the exception remains, C# will not work properly (red message).

# Second

Including other than meshrenderer and skinnedmeshrenderer may cause an error  #2007
