### ISSUE TITLE
Finger Bones not Included on Export

### ISSUE THREAD

**Issue by V1perN3st** [vrm-c/UniVRM#1997]
## Environments (please complete the following information):

 - UniVRM version: `UniVRM-0.108.0_e16d`
 - Unity version: `Unity-2019.4.31f1`
 - OS: `Windows 10`

## Describe the bug

The Exported VRM seems to be missing the finger bones that was included in the FBX. The FBX was originally made for VRChat, but it was imported into a project with UniVRM. After adding SpringBones and making necessary adjustments, I exported the model to VRM and imported it into LIV for use with VR. I have a Valve Index, so it can track my fingers. According to the LIV group, if the model supports finger tracking it will move the individual fingers. I am not sure if there is a place to see where the finger bones are or if there is something special I need to do to enable/remap this.

**Comment by ousttrue** [comment]
Check Humanoid Mapping https://vrm.dev/univrm/humanoid/meshutility_humanoid.html
