### ISSUE TITLE
Assets\VRM10\Runtime\Components\Constraint\IVrm10Constraint.cs(7,23): error CS0106: The modifier 'internal' is not valid for this item

### ISSUE THREAD

**Issue by venop** [vrm-c/UniVRM#2001]
## 環境情報

 - UniVRM version: `0.108.0`
 - Unity version: `Unity-2019.4` 👈 `v0.108` require Unity-2020.4. https://vrm-c.github.io/UniVRM/
 - OS: `Windows 10`

## バグについて

* バグの内容 
* ConsoleLog : 
 Assets\VRM10\Runtime\Components\Constraint\IVrm10Constraint.cs(7,23): error CS0106: The modifier 'internal' is not valid for this item
* スクリーンショット
![image](https://user-images.githubusercontent.com/127037320/222969595-bb9cc5bb-c347-4152-a0c8-836c6a88e13b.png)

* 再現方法 :
VRM-0.108.0_e16d export

* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)
: VRM-0.108.0_e16d

**Comment by yahagi-day** [comment]
UniVRMの推奨環境は2020.3LTS以降です。
https://github.com/vrm-c/UniVRM#supported-environments
