### ISSUE TITLE
[頂点カラー][float以外未実装]頂点カラー付きのモデルをインポートしようとするとエラーが出る

### ISSUE THREAD

**Issue by tommy-tommy** [vrm-c/UniVRM#2018]
## 環境情報

 - UniVRM version: `v0.109.0`
 - Unity version: `Unity-2020.3.24`
 - OS: `Windows 11`

## バグについて

* **バグの内容**
blenderで頂点カラーを付けたglbモデルを書き出し、それをUnityプロジェクトへインポートしようとするとエラーが発生します。

* **エラーログ**
```
Exception: different length
UniGLTF.PrimitiveExtensions.GetColors (UniGLTF.glTFPrimitives primitives, UniGLTF.GltfData data, System.Int32 positionsLength) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/PrimitiveExtensions.cs:176)
UniGLTF.MeshData.ImportMeshSharingVertexBuffer (UniGLTF.GltfData data, UniGLTF.glTFMesh gltfMesh, UniGLTF.IAxisInverter inverter) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshData.cs:448)
UniGLTF.MeshData.LoadFromGltf (UniGLTF.GltfData data, System.Int32 meshIndex, UniGLTF.IAxisInverter inverter) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshData.cs:112)
UniGLTF.ImporterContext+<>c__DisplayClass35_2.<LoadGeometryAsync>b__0 () (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:193)
VRMShaders.ImmediateCaller.Run (System.Action action) (at Assets/VRMShaders/GLTF/IO/Runtime/AwaitCaller/ImmediateCaller.cs:18)
UniGLTF.ImporterContext+<LoadGeometryAsync>d__35.MoveNext () (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:193)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
UniGLTF.ImporterContext+<LoadAsync>d__32.MoveNext () (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:116)
Rethrow as AggregateException: One or more errors occurred.
Rethrow as AggregateException: One or more errors occurred.
UniGLTF.ImporterContextExtensions.Load (UniGLTF.ImporterContext self) (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContextExtensions.cs:22)
UniGLTF.GltfScriptedImporterBase.Import (UnityEditor.AssetImporters.ScriptedImporter scriptedImporter, UnityEditor.AssetImporters.AssetImportContext context, UniGLTF.Axes reverseAxis, UniGLTF.RenderPipelineTypes renderPipeline) (at Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterBase.cs:86)
UniGLTF.GlbScriptedImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GlbScriptedImporter.cs:23)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <bbfbd5a71eea45d1a1354233c800516b>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

* **再現方法**

1. blenderを使い、頂点カラー付きのモデルを作成
2. glb形式で書き出し
3. Windowsの3Dモデルビューワーでは表示されていることを確認（頂点カラーの位置がおかしいですがここは一旦無視）
4. glbファイルをUnityプロジェクトへ追加すると、「different length」というエラーが発生

* **スクリーンショット**
![image](https://user-images.githubusercontent.com/49640196/225893143-3827659a-5afb-46a9-9df6-88de96c8fa61.png)
![image](https://user-images.githubusercontent.com/49640196/225893170-fb1ca5da-f4bd-4a55-8a83-666a9b38731d.png)
![image](https://user-images.githubusercontent.com/49640196/225893155-306d1d9b-c8d1-4d0d-894b-21ddf114919c.png)
![image](https://user-images.githubusercontent.com/49640196/225893187-90afacc2-13ed-47a1-adde-d81731488e8b.png)

* **エラーの発生するファイル**
[vertex_col_test_cube.zip](https://github.com/vrm-c/UniVRM/files/11000870/vertex_col_test_cube.zip)

---

今回、頂点カラーはどうしても必要なため、頂点カラー情報は削除せずにインポートしたいと思っております。

こちら、バグなのか仕様なのかというところも不明なのですが、
対処法等、何か情報ご存じでしたらご助力いただければと思います。

よろしくお願いいたします。

**Comment by ousttrue** [comment]
報告ありがとうございます。
貼付モデルを確認させていただきました。
調べたところ Color の型が float3 または float4 の場合しか対応していませんでした。

glTF の仕様上は、

* unsigned byte normalized
* unsigned short normalized

も可能であるとのことなので次で impot 時に float に変換できるようにします。

**Comment by ousttrue** [comment]
blender のエクスポーターで頂点カラーに float3 か float4 を選択出来れば回避できそうです。

**Comment by ousttrue** [comment]
誤って UShort4 を Float4 として解釈してしまう。
本来 24 であるべき Count が 12 になってしまうために `different length`

**Comment by tommy-tommy** [comment]
@ousttrue 

> 報告ありがとうございます。 貼付モデルを確認させていただきました。 調べたところ Color の型が float3 または float4 の場合しか対応していませんでした。
> 
> glTF の仕様上は、
> 
> * unsigned byte normalized
> * unsigned short normalized
> 
> も可能であるとのことなので次で impot 時に float に変換できるようにします。

ご確認ありがとうございます。

次回バージョンにてご対応いただけるとのこと、承知致しました。
引き続き、よろしくお願い致します。

**Comment by tommy-tommy** [comment]
@ousttrue 
すいません、誤ってcloseとしてしまいました

**Comment by ousttrue** [comment]
![ushort_vcolor](https://user-images.githubusercontent.com/68057/230539033-61ed1a47-8564-43f9-a607-b5156126adf4.jpg)

#2031 で実装しました。

ひとつ注意点がありまして、 `UniVRM` で頂点カラーに対応しているマテリアルは `unlit` を import したときに使用される `UniUnlit` シェーダーのみです。
glTF の PBR シェーダーと Unity の Standard シェーダーは互換性が無い部分があり、
、 Unity の Standard シェーダーに頂点カラー能力が無いためです。
PBR 表現と頂点カラーを併用したい場合は、改造シェーダーを用意してマテリアルローダー
でスイッチさせるように拡張する必要があります。
