### ISSUE TITLE
VRM10RuntimeExportSamples_Error_Ambiguous Transform

### ISSUE THREAD

**Issue by kuni-0930** [vrm-c/UniVRM#2019]
## 環境情報

 - UniVRM version: `0.109.0`
 - Unity version: `Unity-2020.3.13f1`
 - OS: `Windows 10`

## バグについて
VRM10_SamplesのRuntimeExporterSample(scene)を使ってexportしたvrmを読み込むとAvatarBuilder 'VRM1': Ambiguous Transformのエラーが出ます。
ボーン関連の出力が上手く機能していないように見えます。
ご確認をよろしくお願いします。

* ConsoleLog
AvatarBuilder 'VRM1': Ambiguous Transform 'Runtime Control Rig/Vrm10ControlBone:Hips' and 'Runtime Control Rig/Vrm10ControlBone:Hips' found in hierarchy for human bone 'Hips'. Transform name mapped to a human bone must be unique.
UnityEngine.AvatarBuilder:BuildHumanAvatar (UnityEngine.GameObject,UnityEngine.HumanDescription)
UniHumanoid.HumanoidLoader:LoadHumanoidAvatar (UnityEngine.Transform,System.Collections.Generic.IEnumerable`1<System.ValueTuple`2<UnityEngine.Transform, UnityEngine.HumanBodyBones>>) (at Assets/UniGLTF/Runtime/UniHumanoid/HumanoidLoader.cs:37)
UniVRM10.Vrm10RuntimeControlRig:.ctor (UniHumanoid.Humanoid,UnityEngine.Transform) (at Assets/VRM10/Runtime/Components/Vrm10Runtime/ControlRig/Vrm10RuntimeControlRig.cs:41)
UniVRM10.Vrm10Runtime:.ctor (UniVRM10.Vrm10Instance,bool) (at Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs:68)
UniVRM10.Vrm10Instance:get_Runtime () (at Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs:98)
UniVRM10.Vrm10Instance:Start () (at Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs:120)

**Comment by hahaCrazy** [comment]
I also ran into this problem. My idea is that before importing again, the code needs to judge whether the bones of "Runtime Control Rig" already exist. If so, there is no need to regenerate the bones, but I don't know how to modify the source code

**Comment by ousttrue** [comment]
報告ありがとうございます。
調査します。

**Comment by ousttrue** [comment]
AvatarBuilder.BuildHumanAvatar 前にTransform名を強制的に unique になるように修正しました。
UniVRM 内に AvatarBuilder.BuildHumanAvatar は２カ所あって、片方は `v0.109` で対処されました。
２カ所目を同じ処理で修正。

**Comment by ousttrue** [comment]
> `Runtime Control Rig/Vrm10ControlBone:Hips' and 'Runtime Control Rig/Vrm10ControlBone:Hips'

`Runtime Control Rig/Vrm10ControlBone` is component name. `Hips` is Transform.name.
Component name has no effect. Uniqueness of Transform names is required.
