### ISSUE TITLE
Error: No animator in Exportroot

### ISSUE THREAD

**Issue by OmegaDrone0800** [vrm-c/UniVRM#2020]
## Environments (please complete the following information):

 - UniVRM version: `0.99.0`
 - Unity version: `Unity-21.3.21`
 - OS: `Windows 10`

## Describe the bug

* When I try to export this model to VRM format it tells me that "no animator in Exportroot", I don't know what it means but it has already happened in previous projects, what should I do?
 just in case the model is in blender format, which was exported to FBX and put in unity

[Lilly_2.zip](https://github.com/vrm-c/UniVRM/files/11009466/Lilly_2.zip)
![imagen_2023-03-18_165438981](https://user-images.githubusercontent.com/125789520/226134826-dd6a5ac0-7620-4561-8a67-f903c6f3c509.png)

**Comment by ousttrue** [comment]
Thank you for reporting.
Before doing vrm export, you need to Humanoid in Unity. This will attach the Animator to root.
It is possible from the fbx importer.
