### ISSUE TITLE
Cannot export my avatar as VRM.

### ISSUE THREAD

**Issue by ht51566** [vrm-c/UniVRM#2022]
## Environments (please complete the following information):

 - UniVRM version: `0.109.0`
 - Unity version: `Unity-2019.4.31f`
 - OS: `Windows 10`

## Describe the bug

I keep trying making my avatar to VRM but it won't work with this error on console.

Please, help me what can i do for.

![image](https://user-images.githubusercontent.com/5137095/226429308-d6193950-123f-405d-9314-7d694bbfa6ab.png)

Error: Could not load signature of VRC.Dynamics.MathUtil:DistancePointToPlane due to: Could not load file or assembly 'Unity.Mathematics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:Unity.Mathematics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>

AvatarBuilder 'VRM': Found duplicate human bone 'Hips' with transform '' and 'Hips'
UnityEngine.AvatarBuilder:BuildHumanAvatar (UnityEngine.GameObject,UnityEngine.HumanDescription)
UniHumanoid.AvatarDescription:CreateAvatar (UnityEngine.Transform) (at Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs:187)
VRM.VRMImporterContext:LoadHumanoid () (at Assets/VRM/Runtime/IO/VRMImporterContext.cs:260)
VRM.VRMImporterContext/<OnLoadHierarchy>d__4:MoveNext () (at Assets/VRM/Runtime/IO/VRMImporterContext.cs:50)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<VRM.VRMImporterContext/<OnLoadHierarchy>d__4> (VRM.VRMImporterContext/<OnLoadHierarchy>d__4&)
VRM.VRMImporterContext:OnLoadHierarchy (VRMShaders.IAwaitCaller,System.Func`2<string, System.IDisposable>)
UniGLTF.ImporterContext/<LoadAsync>d__32:MoveNext () (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:127)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<UniGLTF.RuntimeGltfInstance>:Start<UniGLTF.ImporterContext/<LoadAsync>d__32> (UniGLTF.ImporterContext/<LoadAsync>d__32&)
UniGLTF.ImporterContext:LoadAsync (VRMShaders.IAwaitCaller,System.Func`2<string, System.IDisposable>)
UniGLTF.ImporterContextExtensions:Load (UniGLTF.ImporterContext) (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContextExtensions.cs:15)
VRM.vrmAssetPostprocessor/<>c__DisplayClass2_0:<ImportVrmAndCreatePrefab>b__0 (System.Collections.Generic.IEnumerable`1<UniGLTF.UnityPath>) (at Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs:91)
UniGLTF.TextureExtractor/<>c__DisplayClass12_0:<ExtractTextures>b__0 () (at Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/TextureExtractor.cs:103)
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()

Exception: fail to create avatar
VRM.VRMImporterContext.LoadHumanoid () (at Assets/VRM/Runtime/IO/VRMImporterContext.cs:263)
VRM.VRMImporterContext+<OnLoadHierarchy>d__4.MoveNext () (at Assets/VRM/Runtime/IO/VRMImporterContext.cs:50)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UniGLTF.ImporterContext+<LoadAsync>d__32.MoveNext () (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:127)
Rethrow as AggregateException: One or more errors occurred.
Rethrow as AggregateException: One or more errors occurred.
UniGLTF.ImporterContextExtensions.Load (UniGLTF.ImporterContext self) (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContextExtensions.cs:22)
VRM.vrmAssetPostprocessor+<>c__DisplayClass2_0.<ImportVrmAndCreatePrefab>b__0 (System.Collections.Generic.IEnumerable`1[T] texturePaths) (at Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs:91)
UniGLTF.TextureExtractor+<>c__DisplayClass12_0.<ExtractTextures>b__0 () (at Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/TextureExtractor.cs:103)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at <a259d3c004024353a2c217da97495055>:0)

**Comment by ousttrue** [comment]
The latest version of UniVRM requires Unity2020.3 or higher.
