### ISSUE TITLE
internal modifier isn't valid?

### ISSUE THREAD

**Issue by toastywarmsweaters** [vrm-c/UniVRM#2024]
running on win 10, unity version 2019.4.31f1, newest vrc sdk imported alongside all other files needed for avatar

Assets\VRM10\Runtime\Components\Constraint\IVrm10Constraint.cs(7,23): error CS0106: The modifier 'internal' is not valid for this item 
this is the error i get. how do i fix it?

**Comment by ousttrue** [comment]
The latest version of UniVRM requires Unity2020.3 or higher.
