### ISSUE TITLE
URP（Unity Universal Render Pipeline）に関して

### ISSUE THREAD

**Issue by newdays-git** [vrm-c/UniVRM#2027]
いつもVRMライブラリ（UniVRM）を使わせていただいております。
質問なのですが、現在は、URP（Unity Universal Render Pipeline）へのサポートはされてますでしょうか？

ドキュメントを探してもそのような記載がないため、質問としてissueを上げさせていただきました。

対応済みであればどのバージョンからか教えていただけると幸いです。

**Comment by ousttrue** [comment]
URP の現状です。

URP 向けのロード時の Material 切り替え機能は実装されていますが、
肝心の URP 用 MToon の実装がまだ無い状態です。
そのため、URP ロードを試みると MToon が Unlit にフォールバックします。
ユーザーが独自に Shader を用意してカスタムロードする必要があります。

URP 向け MToon の作業は進んでいなかったのですが、
最近はアサインされて作業進行中です。
リリース次期に関してはまだ未定なので、確定したタイミングでリリースノート等でお知らせします。

**Comment by ousttrue** [comment]
https://github.com/vrm-c/UniVRM/pulls?q=label%3AURP

**Comment by ousttrue** [comment]
@creatornet 
`v0.111` でURP版 MToon の実装が入りそうです。

https://github.com/vrm-c/UniVRM/pulls?q=is%3Apr+label%3AURP+is%3Aclosed

**Comment by creatornet** [comment]
@ousttrue 
ちなみにこちらは、VRM 0.xとVRM1.0両方での対応という感じの認識で大丈夫でしょうか？

**Comment by ousttrue** [comment]
https://vrm-c.github.io/UniVRM/en/api/0_112_urp.html

に情報をまとめました。
VRM1.0 のみの対応となります(vrm-0.x を 1.0としてロードすることはできる)。
