### ISSUE TITLE
GLBロードにおいて、UniVRM 0.89 で正常に読み込めていたものが、UniVRM 0.109 ではエラーが出て読み込みに失敗する場合がある

### ISSUE THREAD

**Issue by fantom1x** [vrm-c/UniVRM#2028]
## 環境情報

 - UniVRM version: `0.109.0`
 - Unity version: `Unity-2020.3`
 - OS: `Windows 11`

## バグについて

* バグの内容

UniVRM 0.89 以降、1年半近くアップデートしてなかったので、どのバージョンからなのか調査はしてないのですが、最新版 UniVRM 0.109 や 0.105 あたりで試したところ、以前普通に読み込めていたものが、エラーが出て読み込めなくなる場合が多数あるようです。

おおよそ、エラーは２種類で、UniVRM 0.109 と 0.105 ではエラーが違うのですが、原因は同じような気がします。
エラーの内容は ConsoleLog の通りです（※サイズの値はモデルによって置き換えて下さい）。

* ConsoleLog

① InvalidOperationException 系
(UniVRM 0.109, 0.105 共に同じ)
InvalidOperationException: Types System.Byte (array length 177032) and UnityEngine.Color cannot be aliased due to size constraints. The size of the types and lengths involved must line up.
…(以下略)…

② ArgumentOutOfRangeException 系
(UniVRM 0.105 の場合)
ArgumentOutOfRangeException: sub array range 0-33635 is outside the range of the native array 0-16817
Parameter name: length
…(以下略)…

(UniVRM 0.109 の場合)
Exception: different length
UniGLTF.PrimitiveExtensions.GetColors (UniGLTF.glTFPrimitives primitives, UniGLTF.GltfData data, System.Int32 positionsLength) (at Assets/UniVRM/UniGLTF/Runtime/UniGLTF/IO/MeshIO/PrimitiveExtensions.cs:181)
…(以下略)…

* 再現方法
* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

例としては実際に販売されている .glb をロードするとエラーが出ます(UniVRM 0.89 のときは、どれも正常に読み込め、エラーは１つも出ませんでした）。

① InvalidOperationException 系のエラーが出るもの
- AraRoom.glb
https://tar.booth.pm/items/4297213
- CyberCity.glb
https://tar.booth.pm/items/4402718
- Factory.glb
https://tar.booth.pm/items/4153448
- 7God_BenzaiTen.glb
https://tar.booth.pm/items/4588248
- ShrineStage_02_Main.glb
https://tar.booth.pm/items/4560628
- Aquarium.glb
https://tar.booth.pm/items/3885337
- AstroRoom.glb
https://tar.booth.pm/items/3900794
- ChurchAgora_A_Main.glb
https://tar.booth.pm/items/4028466
- Doujou.glb
https://tar.booth.pm/items/4652542
- RyuguJou.glb
https://tar.booth.pm/items/4452232

② ArgumentOutOfRangeException 系のエラーが出るもの
- CyberStage_AB.glb
https://tar.booth.pm/items/3964661
- FantasyPub.glb
https://tar.booth.pm/items/3951840
- CrystalForest_02_Main.glb
https://tar.booth.pm/items/4063126
- 7God_DaikokuTen.glb
https://tar.booth.pm/items/4588248
- Ruins.glb
https://tar.booth.pm/items/4224945
- LibraryStage.glb
https://tar.booth.pm/items/4109859
- ChurchAgora_B_Add.glb
https://tar.booth.pm/items/4028466
- 01_StreamingRoom_Main.glb
- 02_StreamingRoom_Wall_Front.glb
https://tar.booth.pm/items/4500890
- Museum.glb
https://tar.booth.pm/items/4053128
- ArtRoom.glb
https://tar.booth.pm/items/4014937

このショップはとても人気があり、アプリでロードできないとなると多くの利用者をガッカリさせてしまいます。ぜひ以前と同様にロード可能となるようお願いします。m(_ _)m

**Comment by ousttrue** [comment]
報告ありがとうございます。
修正します。

**Comment by ousttrue** [comment]
現象を確認しました。
最近のバージョンで使用している Unity の NativeArray.GetSubArray で Alignment の制限にヒットしているかもしれないです。

#2018 が関連しているものもありそうで、これは実装しました。

**Comment by ousttrue** [comment]
https://github.com/Unity-Technologies/UnityCsReference/blob/2019.4/Runtime/Export/NativeArray/NativeArray.cs#L538

このエラーメッセージが出ている

**Comment by ousttrue** [comment]
カラーで UShort4 を Color(float4) として解釈することで 16 で割り切れないエラー。同じ問題

**Comment by ousttrue** [comment]
とりあえず `AraRoom.glb` は動くことを確認しました。
①, ② のメッセージがともに Float4 以外のVertexColor に起因するようなので、#2018 でなおっていそうです。
`v0.110` で様子見
