### ISSUE TITLE
これはバグですか？

### ISSUE THREAD

**Issue by sinkei0427** [vrm-c/UniVRM#2029]
## 環境情報

 - Unity version: `Unity-2019.4.31f1
 - OS: `Windows 10`

## バグについて

* バグの内容
*  Creator Companion経由でunityを開いた段階では何も異常はないのですがそこにVRM Converterを入れると以下のエラーログがずっとでます。理由が何なのかこれがバグなのかもわからない為こちらに投稿させていただきます。
*  Creator Companion,VRM Converterどちらとも4/2時点での最新版です。

* Logは以下の通りです

Library\PackageCache\jp.pokemori.univrm-extensions@7.3.0\SwayingObjects\VRMSpringBonesToVRCPhysBonesConverter.cs(207,51): error CS0029: Cannot implicitly convert type 'bool' to 'VRC.Dynamics.VRCPhysBoneBase.AdvancedBool'

Library\PackageCache\jp.pokemori.univrm-extensions@7.3.0\SwayingObjects\VRCPhysBonesToVRMSpringBonesConverter.cs(276,46): error CS0019: Operator '||' cannot be applied to operands of type 'VRCPhysBoneBase.AdvancedBool' and 'VRCPhysBoneBase.AdvancedBool'

**Comment by FujiSunflower** [comment]
VRM ConverterはUniVRM自体ではないので、VRM Converterの作者様に問い合わせするのが良いかなと思います。
