### ISSUE TITLE
MATERIALS_CONTAINS_NULL

### ISSUE THREAD

**Issue by gibbirg** [vrm-c/UniVRM#2033]
## Environments:

 - UniVRM version: `0.99.0`
 - Unity version: `Unity-2013.4.31f1`
 - OS: `Windows 10`

## Describe the bug

When i try to export my VRC avatar to the VRM file format i get this error and i cant find any way how to get around it

![Capture](https://user-images.githubusercontent.com/5681283/230616927-be0768f7-2a7e-47bd-b662-26fe553dcc3f.PNG)

**Comment by FujiSunflower** [comment]
I think you try to export FBX with ParticleSystem in Unity-2019.4.31f1.
It will be exported in the latest UniVRM
- Unity 2020.3 LTS or later
- UniVRM-0.110.0_3f7d.unitypackage

Unity 2019 LTS is no-update now already.
https://unity.com/releases/2019-lts

**Comment by ousttrue** [comment]
MATERIALS_CONTAINS_NULL means the renderer material contains "none".
This does not allow export.

![null_material](https://github.com/vrm-c/UniVRM/assets/68057/898cab60-63f4-4c8a-862a-02390dfb887e)

**Comment by ousttrue** [comment]
Modify to be able to export null material. #2313
