### ISSUE TITLE
Particle emiter dissapearing 

### ISSUE THREAD

**Issue by 1m1nk** [vrm-c/UniVRM#2034]
## Environments (please complete the following information):

 - UniVRM version: `0.66.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

![image_2023-04-08_211527427](https://user-images.githubusercontent.com/130247552/230738953-be9dda5a-0948-451a-834c-4864c2f7d3e5.png)
Hello
Using my basic knowledge of unity and relying on tutorials I was trying to add particles to one of my vrm models. Unfortunately every time I modified the particle emitter to my liking mainly following the tutorials and exported the model, the particles did not appear. I thought it was a problem with the application in question, but when I re-imported the exported model, I found that the particle emitter had completely disappeared! Well I didn't realize it right away because it kept appearing as such inside the prefab but when the inspector saw the component it was gone. I don't know if it's my problem because I'm using the same versions that the tutorials asked for and I was careful to apply the component after each modification.
Is it a bug or am I missing something?

**Comment by ousttrue** [comment]
Particle emiter is not supported by UniVRM.
Because glTF and VRM doesn't support particles.
