### ISSUE TITLE
MToon10において影色が乗算になっていない

### ISSUE THREAD

**Issue by okazu621** [vrm-c/UniVRM#2037]
## 環境情報

 - UniVRM version: `0.109.0`
 - Unity version: `Unity-2020.3.46f1`
 - OS: `Windows 11`

## バグについて

* バグの内容

MToon10において影色が乗算になっていないため、モデルを読み込んだときの見た目がvrm0.x用のUniVRMとvrm1.0用のUniVRMで大きく異る。

* スクリーンショット

<img width="545" alt="image" src="https://user-images.githubusercontent.com/46601797/230875445-b309aaad-7be2-427c-837f-9598ebaeea54.png">

* 再現方法

スクリーンショットはどちらにもLitColorに#0000FF、ShadeColorに#FF0000を設定しています。

**Comment by FujiSunflower** [comment]
# 環境
- Unity 2020 LTS
- UniVRM-0.110.0_3f7d
- VRM-0.110.0_3f7d

# 詳細
Mtoon (UniVRM-0.110.0_3f7d) とMtoon10 (VRM-0.110.0_3f7d) にテクスチャが無い状態でLitColorとShadeColorを設定することで再現しました。
![image](https://user-images.githubusercontent.com/20571538/233813102-5ab5af36-f875-4329-8f74-d9d1f308ded3.png)
![image](https://user-images.githubusercontent.com/20571538/233813107-d5e58942-0123-48f9-a4f5-aef3512355ca.png)

当初からUniVRMを使っている身からするとMToon10の状態が元々のMToonだった記憶があり、UniVRMの途中のバージョンからMToonCore.cgincの内部コードをコメントアウトすることで連携アプリ側で見た目を選択する箇所だったと思います。
![image](https://user-images.githubusercontent.com/20571538/233813250-6a41ef16-038f-4103-9859-0ded5da26c6f.png)

**Comment by Santarh** [comment]
報告ありがとうございます。
結論から言うとこれは仕様であり、修正しません。

VRM 1.0 の実装は VRM 1.0 の仕様に沿って行っているので、従来の VRM 0.x の実装とは細かに挙動が異なります。
この挙動はその仕様に沿って、意図して実装しています。

VRM 1.0 における MToon の仕様
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_materials_mtoon-1.0#lighting

---

追記として細かに仕様の経緯と意図を述べると以下です。

MToon 0.x においては「ユーザがどのような色を設定したとしても、計算式側でそれをカバーして、明暗を周りと合わせたそれっぽい見た目を担保する」を目標に計算式を組み立てていました。
したがって、例示のような「Lit 青・Shade赤」のような極端なユーザ設定の場合、それを無視してでも暗所は暗くしていました。

しかし MToon 1.0 では仕様のシンプルさ、可搬性をより重視した結果「ユーザが極端な色を設定した場合は、それを受け入れる」方向に舵が切られています。
言い換えれば、ある程度の外れ値は許容して、ユーザ側の表現自由度を上げることにしました。
したがって、例示の場合はそれをそのまま表示する状態になっています。

**Comment by StarMaster21** [comment]
I was told to use Mtoon10 for VRM 0 when Mtoon10 is only for VRM1

My model is VRM0 using Mtoon. Why did the Mtoon rim light broke with the new update? Unless it's the app creator fault for breaking mobile VRMPosting then oh okay. I see many others are getting this rim lighting problems on social media now. I witch to fumifumi app on ios without having this problem with Mtoon/VRM0 models.
