### ISSUE TITLE
Ability to freeze pose with GLTF export

### ISSUE THREAD

**Issue by anadin** [vrm-c/UniVRM#2041]
I am using UniVRM to export a runtime GLTF file but have not been able to export the character with its blend shapes frozen, All the blend shapes export fine but I'd really like to be able to freeze or at least set the values of the blend shapes when exporting.

**Comment by ousttrue** [comment]
`BoneNormalizer.Execute` is  the function you need.
Assets\UniGLTF\Runtime\MeshUtility\BoneNormalizer.cs
