### ISSUE TITLE
VRM 0系のファイルをVRM 1系で変換してインポートした際にVRM SpringBoneのCenterの設定が抜けてしまう

### ISSUE THREAD

**Issue by FujiSunflower** [vrm-c/UniVRM#2048]
## 環境情報

 - UniVRM version: `VRM-0.110.0_3f7d`
 - Unity version: `Unity-2020.3.43f1`
 - OS: `Windows 11`

### バグの内容
VRM 0系のファイルをVRM 1系で変換してインポートした際にVRM SpringBoneのCenterの設定が抜けてしまう。
### ConsoleLog
![image](https://user-images.githubusercontent.com/20571538/233363505-ec998c10-6ae2-4a60-8764-162ea5cddfe6.png)
### スクリーンショット
![image](https://user-images.githubusercontent.com/20571538/233363696-77fee6a4-5c1f-4cab-b7be-be2dacb52fc2.png)
![image](https://user-images.githubusercontent.com/20571538/233363796-5c698d66-2e56-4925-b569-3ad9a1013436.png)
### 再現方法
VRoid Studio 1.22.0のAvatarSample_BのVRM0系のファイルをVRM1系のプロジェクトで読み込む。

**Comment by ousttrue** [comment]
報告ありがとうございます。
修正します。
