### ISSUE TITLE
Metasequoiaを使用して作成したVRM 0系のファイルでFastSpringBoneを使用するとずれがある

### ISSUE THREAD

**Issue by FujiSunflower** [vrm-c/UniVRM#2049]
## 環境情報

 - UniVRM version: `UniVRM-0.110.0_3f7d`
 - Unity version: `Unity-2020.3.43f1`
 - OS: `Windows 11`

### バグの内容
Metasequoiaを使用して作成したVRM 0系のファイルでFastSpringBoneを使用するとずれがある。
なお、Blenderを使用して作成したVRM 0系・VRoid Studioを使用して作成したVRM 0系でも多少のずれがある。
### ConsoleLog
![image](https://user-images.githubusercontent.com/20571538/233620587-4a80885d-e579-46a2-aa8c-7060ae9d38ca.png)

### Metasequoiaの場合のスクリーンショット
![image](https://user-images.githubusercontent.com/20571538/233620645-4224ab58-ba06-40e0-b16c-a3868403fe97.png)
![image](https://user-images.githubusercontent.com/20571538/233620699-18be5ada-463d-4cdf-9692-d869526d5124.png)

### Blenderの場合のスクリーンショット
![image](https://user-images.githubusercontent.com/20571538/233621356-81a8ab58-e407-462e-9204-05ad0fd13592.png)
SpringBoneの半径が変わっている。
![image](https://user-images.githubusercontent.com/20571538/233621410-397e3fe6-b737-48a5-a82e-541b72ced82e.png)

### VRoid Stuidoの場合のスクリーンショット
![image](https://user-images.githubusercontent.com/20571538/233620989-0dd9eb56-70da-4d6e-8eba-97f1eca356d3.png)
ColliderGroupに対応する位置が若干ずれている、またSpringBoneの半径が変わっている。
![image](https://user-images.githubusercontent.com/20571538/233621201-7042c1cf-f0d6-4f4e-a28f-d249ae3c32c5.png)

### 再現方法
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using VRM;

public class TestFast : MonoBehaviour
{
    // Start is called before the first frame update
    async void Start()
    {
        Fast();
    }
    async void Fast()
    {
        await FastSpringBoneReplacer.ReplaceAsync(gameObject);
    }
    // Update is called once per frame
    void Update()
    {
        
    }
}

```
## 推測される不具合
- SpringBoneの半径の扱いが揃っていない。
- ColliderGroupに対応するボーンがTailなのかHeadなのかがずれている。
- ColliderGroupが複数のコライダーを用意出来ていない。

**Comment by FujiSunflower** [comment]
トップコメントのVRMからCenter設定を外すと、SpringBoneの位置は期待される位置になりました。
ColliderGroupに対応する位置のずれとSpringBoneの半径の違いはそのままのようです。
![image](https://user-images.githubusercontent.com/20571538/233624683-ec22928b-c1b9-41c9-9a68-9e72d12608f9.png)
![image](https://user-images.githubusercontent.com/20571538/233624539-e130f947-29a0-4675-ad38-34903acf4be6.png)
![image](https://user-images.githubusercontent.com/20571538/233625074-d69a18b4-dfe6-4274-b755-c75cded2218c.png)
![image](https://user-images.githubusercontent.com/20571538/233624944-b424cf9f-e996-4726-b54e-909533325eb8.png)

**Comment by FujiSunflower** [comment]
#2047 FastSpringBoneの位置の違いはFastSpringBoneでのCenterの仕様らしいと理解しました。

**Comment by ousttrue** [comment]
報告ありがとうございます。
調査します。
