### ISSUE TITLE
Model will not export

### ISSUE THREAD

**Issue by NyxNymphaea** [vrm-c/UniVRM#2051]
## Environments (please complete the following information):

 - UniVRM version: `0.99.1`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## Describe the bug
VRM was able to import using uniVRM. But when I try to export immediately after, it does not allow me to. The Export Option is greyed out. It says "The model needs to face the positive Z-axis"

I have confirmed that the upper leg bones are in the correct positions.

This happens every time I try to export the model. Even after going back into blender and applying all transforms and Exporting as a VRM again. I have not added or changed anything at this point. It was freshly imported. 

* A clear and concise description of what the bug is.
* ConsoleLog
* There is no Console update. Console remains clear
* ScreenShot
* 
![image](https://user-images.githubusercontent.com/131623831/233870092-8aeb1883-f765-477d-afe7-35051424f97a.png)

* Reproduction procedure
* 
* File that causes an error (those that can be pasted here)
*

**Comment by ousttrue** [comment]
Thank you for your report. 
This may be a problem that prefab coordinates cannot be obtained. 
Try putting it in the scene as a workaround and then exporting.

**Comment by Ry3yr** [comment]
This issue still persists.
The pmx model was imported via MMD4Mechanim.
It renders fine. But the export is greyed out ...
![Screenshot_2024-12-19-13-43-55](https://github.com/user-attachments/assets/b240d3f0-c4cc-431e-a7d6-833389c14f9d)
