### ISSUE TITLE
glTFMaterial is empty

### ISSUE THREAD

**Issue by vjixy** [vrm-c/UniVRM#2052]
## Environments (please complete the following information):

 - UniVRM version: `0.110.0`
 - Unity version: `Unity-2021.3`
 - OS: `Windows 10`

# Describe the bug
I generated a glb model from a python code it opens with colors using the 3d viewer of windows but in unity I can't import it I get:
glTFMaterial is empty
UnityEngine.Debug:LogWarning (object)
UniGLTF.MaterialImporter:CreateMaterial (int,UniGLTF.glTFMaterial) (at Assets/UniGLTF/Core/Scripts/IO/MaterialImporter.cs:84)
UniGLTF.ImporterContext/<LoadMaterials>d__35:MoveNext () (at Assets/UniGLTF/Core/Scripts/IO/ImporterContext.cs:574)
DepthFirstScheduler.CoroutineFunctor`1<DepthFirstScheduler.Unit>:Execute () (at Assets/UniGLTF/DepthFirstScheduler/Functor.cs:112)
DepthFirstScheduler.Schedulable`1<DepthFirstScheduler.Unit>:Execute () (at Assets/UniGLTF/DepthFirstScheduler/Schedulable.cs:102)
DepthFirstScheduler.Schedulable`1<DepthFirstScheduler.Unit>:ExecuteAll () (at Assets/UniGLTF/DepthFirstScheduler/Schedulable.cs:114)
UniGLTF.ImporterContext:Load () (at Assets/UniGLTF/Core/Scripts/IO/ImporterContext.cs:400)
UniGLTF.gltfAssetPostprocessor/<>c__DisplayClass2_0:<ImportDelayed>b__0 () (at Assets/UniGLTF/Core/Scripts/Editor/gltfAssetPostprocessor.cs:59)
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()
[model.zip](https://github.com/vrm-c/UniVRM/files/11312651/model.zip)

**Comment by ousttrue** [comment]
This error message is from the old `UniVRM`.
Try with the latest version of `UniVRM`.
