### ISSUE TITLE
VRM SpringBoneのCenterに指定出来るノード階層に制約が必要そう

### ISSUE THREAD

**Issue by FujiSunflower** [vrm-c/UniVRM#2053]
# 概要
特定の条件のアバターでVRM SpringBoneの挙動がアプリ毎に異なる現象が見つかりました。
原因はVRM SpringBoneのCenterに指定したノード階層によるもので、VRMの仕様に制約を追加する必要があると感じました。
- VRM SpringBoneのCenterに指定出来るノード階層に制約が必要そう
- ボーン階層にRootボーンが必須かどうかを決めた方が良さそう
# 検証
## 環境
- Unity 2020.3.43f1
-  UniVRM-0.110.0_3f7d.unitypackage 
- UniVRM_Samples-0.110.0_3f7d.unitypackage
## 詳細
Metasequoiaから出力したようなHipsボーンが直接Rootボーンとなっているアバターを使用します。
このアバターでHipsボーンと同じ階層のゲームオブジェクトをVRM SpringBoneのCenterに指定しました。
![image](https://user-images.githubusercontent.com/20571538/234188591-907fad54-bc05-4079-93f7-1a74b1948fee.png)

このアバターをSimpleViewerで読み込みます。
![image](https://user-images.githubusercontent.com/20571538/234190101-035bf466-a60f-4bb6-a449-00f59d8a47a7.png)

実験として、SimpleViewerのシーン上にあるVRMとVRMのHumanPoseTransferの元であるtmpをそれぞれ平行移動してみました。
- VRMを移動させた場合：スカートは激しい揺れが起こりませんでした。
- tmpを移動させた場合：スカートで激しい揺れが起こりました。
![image](https://user-images.githubusercontent.com/20571538/234190333-ca5179b5-5806-439d-bfff-e6cad277a44d.png)
# 考察
アバターの移動方法がUnity上で主に2種類あることが違いを生んだようです。
- VRMのプレハブ丸ごとを移動させる方法
- VRMをHips基準のアニメーションとして移動させる方法

ところで、Rootボーンの子階層にHipsボーンがありRootボーンと同じ階層のゲームオブジェクトをVRM SpringBoneのCenterに指定することが現在のところ可能です。この場合だと上記のどちらの方法でもスカートの激しい揺れが起こりません。Hipsボーンだけが移動するため、Rootボーンと同様にCenterのゲームオブジェクトが取り残されるからです。
> 追記：GenericアニメーションかHumanoidアニメーションか否かでも差が出そう。
![image](https://user-images.githubusercontent.com/20571538/234193248-3b346f0f-2a96-48f0-9efb-516f9bd01e65.png)

また、[VRoid Studio](https://vroid.com/studio)で作られたアバターにはRootボーンがありCenterとして指定されています。
この設定方法は[Unityのルートモーション](https://docs.unity3d.com/ja/2019.4/Manual/RootMotion.html)を想定したものと考えられ、上記２種の両方の移動方法を考慮していそうです。
![image](https://user-images.githubusercontent.com/20571538/234388399-0626f2fd-1976-49ab-b42e-dbfd61c1deca.png)

# 提案
検証したようなテクニカルな設定方法が出来るとアプリ毎の挙動の差を引き起こすためVRM SpringBoneのCenterに指定出来るノード階層をHipsボーン以下の階層とする制約が必要かなと感じます。
もしくは、テクニカルな設定方法を可能とする代わりにRootボーンの有無を決めてしまう必要があるかなと感じます。
厳密な制約条件としない場合でもドキュメントに記載が必要な内容ではあると感じます。

**Comment by ousttrue** [comment]
vrm-0.x の仕様は、修正しない方針です。

vrm-1.0 は center に関する記述があります。

> Centerノードは、そのSpringChainの0番目のJointもしくは、その祖先nodeである必要があります。 また、Centerノードには、他のSpringChainのJointノードおよびその子孫を指定することはできません。

https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_springBone-1.0/README.ja.md#center-space

vrm-1.0 のエクスポート時に
この制約外れることはお勧めでないという警告を出すことは可能です。

**Comment by FujiSunflower** [comment]
VRM 0系の仕様を修正しない代わりに、説明がVRMドキュメントあるのが落とし所ですかね。
> VRM 0系ではCenterに指定可能なノードに制約はありませんが、[VRM 1系ではCenterに指定可能なノードに制約が設けられました]( https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_springBone-1.0/README.ja.md#center-space)。

**Comment by ousttrue** [comment]
#2314
