### ISSUE TITLE
i have this error NotVrm0Exception: Exception of type 'VRM.NotVrm0Exception' was thrown. and I cant figure out how to fix it help

### ISSUE THREAD

**Issue by hehe-cheese** [vrm-c/UniVRM#2055]

**Comment by EmbershadeSC** [comment]
I've been having a similar issue so I'll elaborate on it. Whenever I attempt to use the VRM I made using UniVRM in VSeeFace, I get this error. I'm using 2021.3.5f1 and there's no Unity errors
![image](https://user-images.githubusercontent.com/48605020/235346742-5950fe84-f128-476a-86ac-7e936f077ddb.png)

**Comment by FujiSunflower** [comment]
It will happen on loading VRM1 in VRM 0 app. But VRM 1 app can load VRM 0.

**Comment by ousttrue** [comment]
This is from here.

https://github.com/vrm-c/UniVRM/blob/master/Assets/VRM/Runtime/IO/VRMData.cs#L16
