### ISSUE TITLE
Load GLTF file from Memory Stream or byte[]

### ISSUE THREAD

**Issue by cpetry** [vrm-c/UniVRM#2056]
Hello,

I have a *.gltf file completely in memory as a byte[].
How can I import this at runtime?
This here #1724 does not work as it expects *.glb content.

Notice: I can't directly load the *.gltf as a file as it is encrypted and needs to be decrypted first.

**Comment by cpetry** [comment]
Ah I guess I need a real existing file path.
`var data = new GltfFileWithResourceFilesParser(filePathWithExt, bytes).Parse();`

Otherwise I didn't find a solution.
Works for me though

**Comment by ousttrue** [comment]
GltfFileWithResourceFilesParser
is the target class.

https://github.com/vrm-c/UniVRM/blob/master/Assets/UniGLTF/Runtime/UniGLTF/IO/Parser/GltfFileWithResourceFilesParser.cs#L22

gltfFilePath is used to resolve relative paths for related resources such as textures.
