### ISSUE TITLE
glt import not detecting rig 

### ISSUE THREAD

**Issue by aj2620** [vrm-c/UniVRM#2059]
I tried importing gltf with uni gltf but it wont detect gltf model rig. im trying to import gltf model with avatar(rig) to add aniamtions. 

any workarounds or possible solutions for this or unity doesnt detect rig..?

thanks

**Comment by FujiSunflower** [comment]
I think this is useful.
HumanoidComponent https://vrm.dev/en/univrm/humanoid/meshutility_humanoid

**Comment by ousttrue** [comment]
gltf does not store a correspondence table between node and humanbone.
rig is lost when exporting to gltf. Only skinning is stored.
(VRM is a solution for storing humanbone mappings.)

It is possible to manually assign a human bone using the `HumanoidComponent`.
In Unity only fbx importer can generate human avatar.
Perhaps this avatar is guessed and not stored.
