### ISSUE TITLE
プロジェクトに URP Package を導入していないときに URP 版 MToon がエラーになる

### ISSUE THREAD

**Issue by Santarh** [vrm-c/UniVRM#2065]
master branch でおきる。
URP を選択しないユーザの環境でエラーが出る、またはビルドができなくなるのは好ましくない。

Unity 2021.3 では解決策がある。
UniVRM の最低サポートバージョンが 2021.3 になるのを待った方が楽。
https://docs.unity3d.com/Manual/SL-PackageRequirements.html

**Comment by ousttrue** [comment]
https://vrm.dev/univrm/error/could_not_include/

既知の無視できるエラー。
