### ISSUE TITLE
Unity crashes everytime I go to open up my blendshapes to change the values and get this error

### ISSUE THREAD

**Issue by BokeDazai** [vrm-c/UniVRM#2071]
Unity crashes everytime I go to open up my blendshapes to change the values and get this error:

GetManagerFromContext: pointer to object of manager 'RenderSettings' is NULL (table index 21) UnityEngine.GUIUtility:ProcessEvent (int,intptr)

I attached the console log and error message. This is kinda weird since I didn't have this issue until recently as I had no problem creating and editing blendshapes before but now it crashes everytime I click on a blendshape in Unity. Anyone have any idea how to fix this?
![Error Message Unity (05 25 2023)](https://github.com/vrm-c/UniVRM/assets/92343446/c32cc6a1-260e-4a80-aac4-c5a333ad791c)
![Error Log (05 25 2023)](https://github.com/vrm-c/UniVRM/assets/92343446/490d4080-eaaa-405b-a8af-7fec1a36da18)

**Comment by ousttrue** [comment]
Thank you for your report.
It's crashing at the C level and I'm not sure.

You can stop PreviewFaceRenderer.Render with

`Assets\VRM\Editor\BlendShape\PreviewFaceRenderer.cs`

```cs
        public Texture Render(Rect r, GUIStyle background, PreviewSceneManager scene,
        float yaw, float pitch, Vector3 position)
        {
            //if (scene == null) return null;
            return null;
        }
```
