### ISSUE TITLE
UniVRMが不正なVRMを出力出来るべきではない

### ISSUE THREAD

**Issue by Narazaka** [vrm-c/UniVRM#2072]
## 環境情報

 - UniVRM version: `0.110.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 10`

## バグについて

* バグの内容

UniVRMでエクスポートしたVRMがclusterやVRoid Hubでは受け入れられるが、VirtualCastやVRMLiveViewer等で不正なデータとして拒否されてしまいます。

エラーも要領を得ず何を直したら良いかが分からないものです。

不正なVRMがUniVRMで出力出来るというのはユーザーにとって最も不親切な挙動で、少なくとも事前にエラーにするべきだと思います。

* ConsoleLog
* スクリーンショット

![image](https://github.com/vrm-c/UniVRM/assets/1712548/2df4364a-2e84-4234-8725-8b129f5237fc)

* 再現方法

* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

**Comment by Narazaka** [comment]
![image](https://github.com/vrm-c/UniVRM/assets/1712548/923f681e-74a4-4001-950a-660134d87a9e)
出力時の警告としては上記のようなものがでていました。
これが原因で不正なデータになるならばエラーにするべきであると思います。

**Comment by Narazaka** [comment]
逆にアプリケーション・サービス側の問題であるという話であればVRMの大本感のあるバーチャルキャストは対応していて欲しいという気持ちがあります……（気持ちです

**Comment by ousttrue** [comment]
普通の状態のモデルではあまり発生しないと思われますが、
Unity 上で何らかの組み換えをすることで起こりそうな気がします。
ただ、推理した原因と問題の因果関係があるかどうかは何とも言えません。
よくわからないので、関係ありそうなところを勘でふさぎました。

**Comment by FujiSunflower** [comment]
詳しい情報ソースを用意できなかったのですが、UnityのBoneWeight.boneIndex0からBoneWeight.boneIndex3まではボーンの影響数によらず設定される数値なのでBoneWeight.boneIndex1以降を-1と設定することでボーンの影響数を指定するような扱いだった気がします。そのため-1は不正値というよりは予約済みの値かなと思います。
ちなみにボーンの影響数は少ないほど綺麗な変形になるという基本知識があるため、VRMが必ず4ボーン変形であるというのは仕様にはしづらいです。
https://docs.unity3d.com/ja/2021.2/ScriptReference/BoneWeight.html
