### ISSUE TITLE
The inspector for BlendShapeClip and BlendShapeAvatar doesn't work properly

### ISSUE THREAD

**Issue by FrostyShadow** [vrm-c/UniVRM#2084]
## Environments (please complete the following information):

 - UniVRM version: `UniVRM-0.111.0_b413`
 - Unity version: `Unity-2019.4.31f1`
 - OS: `Windows 11`

## Describe the bug

When I open BlendShapeAvatar and select any of the blendshapes it doesn't give me the option to modify or preview the blendshape.
![image](https://github.com/vrm-c/UniVRM/assets/24304185/5ceb86c1-7989-42a3-bcc2-5e8f2c05398d)

Opening the BlendShapeClip shows an empty inspector window.
![image](https://github.com/vrm-c/UniVRM/assets/24304185/7431fe1c-dbc0-4a28-a236-8b50051e3435)
And this message shows up in the console.
![image](https://github.com/vrm-c/UniVRM/assets/24304185/92d10777-cd33-43e4-af74-9cc9d0d146f5)

And after exporting the vrm none of the blendshapes work. The blendshapes on the model itself work fine in Unity it's just the UniVRM that has issues for some reason.

**Comment by Huynhmaianh2001** [comment]
have you found a way to solve this? i ran into the same issues but still haven’t known what to do
