### ISSUE TITLE
x.extensions.KHR_materials_unlit != null always true

### ISSUE THREAD

**Issue by JalalJaberi** [vrm-c/UniVRM#209]
In UniGLTF\Scripts\IO\MaterialImporter, `x.extensions.KHR_materials_unlit != null` is always true event when there is no `KHR_materials_unlit` key presented in gltf material json data.

**Comment by JalalJaberi** [comment]
It seems affected by Unity JSONUtility that initialize non-presented variables (in deserializing) with default values. Cause problematic results.

**Comment by yutopp** [comment]
Hi. Thank you for your reporting. I'll investigate the probrem.

**Comment by yutopp** [comment]
It will be safe when `extensions` is `null` on native Windows environments, but it may causes unexpected behaviour when running on `UWP` environments or `extensions` is `{}`.

It seems time has come to replace the JSON deserializer from `JSONUtility` (But it's a heavy task...).

**Comment by PoChang007** [comment]
Sorry for the late reply. This issue has been fixed. Please try again with the latest version. Thanks!
