### ISSUE TITLE
Unable to import VRM 1.0 model exported with Vertex Painted meshes

### ISSUE THREAD

**Issue by jeebsnifty** [vrm-c/UniVRM#2105]
- UniVRM version: `[v0.111.0](https://github.com/vrm-c/UniVRM/releases/tag/v0.111.0)`
 - Unity version: `Unity-2021.1`
 - OS: `Windows 11`

* ConsoleLog
* InvalidOperationException: Types System.Byte (array length 72744) and UnityEngine.Color cannot be aliased due to size constraints. The size of the types and lengths involved must line up.
Unity.Collections.NativeArray`1[T].CheckReinterpretSize[U] (System.Int64 tSize, System.Int64 uSize, System.Int32 expectedTypeSize, System.Int64 byteLen, System.Int64 uLen) (at <fd88a7f744c8413fa794c8fc6e0439f6>:0)
Unity.Collections.NativeArray`1[T].Reinterpret[U] (System.Int32 expectedTypeSize) (at <fd88a7f744c8413fa794c8fc6e0439f6>:0)
UniVRM10.MeshImporterShared.LoadSharedMesh (VrmLib.Mesh src, VrmLib.Skin skin) (at Assets/VRM10/Runtime/IO/Model/MeshImporterShared.cs:29)
UniVRM10.Vrm10Importer+<LoadGeometryAsync>d__11.MoveNext () (at Assets/VRM10/Runtime/IO/Vrm10Importer.cs:176)

[DigiVillan (1).zip](https://github.com/vrm-c/UniVRM/files/11971248/DigiVillan.1.zip)

**Comment by ousttrue** [comment]
Thank you for your report.
I will investigate the issue.
