### ISSUE TITLE
VRM1: VRMが無回転でない状態でシーンに配置されたとき、LookAtの挙動がおかしい

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/UniVRM#2106]
## 環境情報

 - UniVRM version: `0.112.0`
 - Unity version: `Unity-2021.3.27`
 - OS: `Windows 11`

## バグについて

VRM1を利用時、VRMが無回転でない状態でシーンに配置し、Look At Targetに任意のGameObjectを設定し、プレイを行うと、VRMモデルが明後日の方向を向いてしまいます。

### 再現手順

- UniVRMプロジェクト内で空のシーンを作成
- VRM1ファイルをドラッグアンドドロップで読み込む
- VRMをY軸周りに180度回転させ、Main Cameraの方向を向ける
- VRMInstanceのLook At TargetにMain Cameraを設定
- プレイを行う

https://github.com/vrm-c/UniVRM/assets/7824814/e6dd8355-e9ef-48a3-8707-fe1cffe14671

### Workaround

また、このとき、VRMを無回転でプレイし、あとからVRMをY軸周りに180度回転した場合、本事象は発生しません。

### 考えられる原因

LookAtの該当箇所のロジックはControlRigに依存しています。
ControlRigの初期化に問題がありますでしょうか……？

https://github.com/vrm-c/UniVRM/blob/v0.112.0/Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeLookAt.cs#L36-L39

**Comment by ousttrue** [comment]
ControlRig の初期化は、`そのときにモデルが T-Pose になっている` というのに依存しています。

**Comment by ousttrue** [comment]
ControlRig の初期化フローを確認しました。

- Vrm10Runtime の初期化時に生成される
- Vrm10RuntimeControlRig が初期化時にヒエラルキーが T-Pose であると見なして、各ボーンの localRotation, rotation を収集する

というロジックになっています。
現状、仕様ということになります。

**Comment by ousttrue** [comment]
#2427
