### ISSUE TITLE
The root transform should have default translation, rotation and scale.

### ISSUE THREAD

**Issue by Marinaecc** [vrm-c/UniVRM#2108]
## Environments (please complete the following information):

 - UniVRM version: `0.59.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 11`

## Describe the bug

* A clear and concise description of what the bug is.
![16896538505653017427611314620512](https://github.com/vrm-c/UniVRM/assets/139837561/088a4227-c76e-4c1b-8993-634c4d05a3b4)

![16896538067496078960750891765331](https://github.com/vrm-c/UniVRM/assets/139837561/90073611-2357-48af-851c-88fd1d8021)
my procedure:
1. Import my vrn model as always
2. Export humanoid
3. try to export it as a new vrm
4. The error

**Comment by Marinaecc** [comment]
I re

**Comment by ousttrue** [comment]
Thank you for your report.
Well I do not know.

**Comment by ElizabethMcFife** [comment]
I solved this by resetting the transform properties back to default

![image](https://github.com/user-attachments/assets/7fc9b936-0380-4773-81fe-35cedcb9e822)
