### ISSUE TITLE
ボーン変形を持たないSkinnedMeshRendererをVRM1.0でエクスポートするとローカル座標が反映されない

### ISSUE THREAD

**Issue by tsgcpp** [vrm-c/UniVRM#2119]
## 環境情報

 - UniVRM version: `v0.113.0`
 - Unity version: `Unity-2021.3.27f1`
 - OS: `Windows 10`

## バグについて

* バグの内容
  * ボーン変形を持たないSkinnedMeshRendererをVRM1.0でエクスポートするとローカル座標(厳密には配置した親オブジェクトからのオフセット)が反映されない
* ConsoleLog
  * 特になし
* スクリーンショット
  * 以下のように `head 1` 以下にボーン変形なしの`BlendShapedOnlyQuad`とボーン変形ありのオブジェクト`ArmatureQuad`を入れてVRM1.0にエクスポートして、`VRM10Viewer`で読み込むとボーン変形なしのオブジェクトはローカル座標(オフセット)が反映されず、頭から離れた床の位置に表示されます。ボーン変形ありの方はローカル座標が保持されています。
  * ![image](https://github.com/tsgcpp/UniVRM/assets/19503967/bb49f390-3bb8-404a-92a1-2770e0c21132)
  * ![image](https://github.com/tsgcpp/UniVRM/assets/19503967/95e7c8c2-d3f0-46ea-9709-039ed979d5df)
* 再現方法
  * Forkしたリポジトリのブランチ `report_SkinnedMeshRenderer_export` に再現用のシーンを用意しました。
    * https://github.com/tsgcpp/UniVRM/tree/report_SkinnedMeshRenderer_export
  * `Assets/Report/Report.unity` を開いて、配置された`ReportModel`をMenuItemの `Export VRM-1.0`からエクスポート
  * `VRM10Viewer`でエクスポートしたVRMを読み込むと、ボーン変形を持たないSkinnedMeshRendererの位置が頭から離れていることが確認できるかと思います。
* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)
  * 特になし

**Comment by ousttrue** [comment]
v0.116 で MeshUtility(Mesh統合ダイアログ)に機能を実装し、
v0.117 以降でエクスポーターに、bake/統合/分割 機能を合体する予定です作業しています。

#2169
