### ISSUE TITLE
VRM1.0において、光源から受ける影響を旧Shader(VRM/MToon)と同程度にしてほしい

### ISSUE THREAD

**Issue by ForJobOk** [vrm-c/UniVRM#2147]
## 環境情報

 - UniVRM version: `0.114.0`
 - Unity version: `Unity-2021.3.10f1`
 - OS: `Windows 11`
 - レンダーパイプライン：ビルトイン

## 提案内容
VRM1.0において利用されるVRM10/MToon10について、光源から受ける影響を旧Shader(VRM/MToon)と同程度とすることをご検討いただきたいです。

VRM10/MToon10はライトの影響を強く受けすぎているように感じます。
VRM/MToonはライトの影響をさほど受けなかった印象です。

既存のVRプラットフォームにおいては、この違いにより光源の再設定が必要となり、VRM1.0利用の大きなハードルとなってしまうのではないかと懸念しています。

以下はそれぞれ比較したものです。
右側のVRM/MToonを適用したモデルはライトの影響をほとんど受けないのに対し、左側のVRM10/MToon10はライトの影響を強く受けていることがわかります。
![mtoon10sample](https://github.com/vrm-c/UniVRM/assets/41860455/e5c40ba6-cc96-42fe-bbc3-314def014890)

---

### 再現方法
以下サンプルのVRM10ViewerというシーンにてVRMをインポートして検証しました。
https://github.com/vrm-c/UniVRM/releases/tag/v0.114.0

利用したモデルは以下です。
https://github.com/vrm-c/UniVRM/blob/master/Tests/Models/Alicia_vrm-0.51/AliciaSolid_vrm-0.51.vrm

**Comment by Santarh** [comment]
懸念は理解しますが、大きなハードルだとは思いません。
VRM 1.0 の実装においては PBR により親和性の高い実装を行います。

また光源に比例して明るくなった方が、よりリッチな背景および総合的な絵作りができるメリットが大きいと判断します。
たとえばトーンマッピングや自動露光によって明暗が制御されることを期待します。

**Comment by ousttrue** [comment]
仕様でした。
