### ISSUE TITLE
Issue with Unity 2019.4.31f1 and Unity 2020.3.1f1

### ISSUE THREAD

**Issue by julianpoelmann** [vrm-c/UniVRM#2149]
UniVRM version: 0.114.0
Unity version: Unity 2019.4.31f1 (Used by vrchat and ive used this before)
OS: Windows 11 Pro For Workstations N

## Describe the bug

After adding the packages it keeps giving me 8 console errors. removing the packages and adding to the upm manifest gives the same errors. this also happens with a 2020 version of unity but not with the 2022.1.0a13 version (however i need 2019 due to vsf compatibilty)

The console: 

Library\PackageCache\com.vrmc.vrmshaders@d90b26b987\GLTF\IO\Runtime\Texture\Importer\TextureFactory.cs(48,36): error CS1061: 'KeyValuePair<SubAssetKey, Texture>' does not contain a definition for 'Deconstruct' and no accessible extension method 'Deconstruct' accepting a first argument of type 'KeyValuePair<SubAssetKey, Texture>' could be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.vrmc.vrmshaders@d90b26b987\GLTF\IO\Runtime\Texture\Importer\TextureFactory.cs(48,36): error CS8129: No suitable Deconstruct instance or extension method was found for type 'KeyValuePair<SubAssetKey, Texture>', with 2 out parameters and a void return type.

Library\PackageCache\com.vrmc.vrmshaders@d90b26b987\GLTF\IO\Runtime\Texture\Importer\TextureFactory.cs(48,27): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'k'.

Library\PackageCache\com.vrmc.vrmshaders@d90b26b987\GLTF\IO\Runtime\Texture\Importer\TextureFactory.cs(48,30): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'v'.

Library\PackageCache\com.vrmc.vrmshaders@d90b26b987\GLTF\IO\Runtime\Animation\Importer\AnimationClipFactory.cs(47,38): error CS1061: 'KeyValuePair<SubAssetKey, AnimationClip>' does not contain a definition for 'Deconstruct' and no accessible extension method 'Deconstruct' accepting a first argument of type 'KeyValuePair<SubAssetKey, AnimationClip>' could be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.vrmc.vrmshaders@d90b26b987\GLTF\IO\Runtime\Animation\Importer\AnimationClipFactory.cs(47,38): error CS8129: No suitable Deconstruct instance or extension method was found for type 'KeyValuePair<SubAssetKey, AnimationClip>', with 2 out parameters and a void return type.

Library\PackageCache\com.vrmc.vrmshaders@d90b26b987\GLTF\IO\Runtime\Animation\Importer\AnimationClipFactory.cs(47,27): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'key'.

Library\PackageCache\com.vrmc.vrmshaders@d90b26b987\GLTF\IO\Runtime\Animation\Importer\AnimationClipFactory.cs(47,32): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'o'.

![afbeelding](https://github.com/vrm-c/UniVRM/assets/28513665/b4e92fed-16fb-4462-8a2c-e68a4d6ef3ca)

To reproduce: import the 4 packages using the unitypackage or upm on version 2019.4.31f1

idk what im doing wrong, i just hope there is a solution. it all comes from the TextureFamily.cs and AnimationClipFactory.cs from the VRM Shaders package

**Comment by AraHaan** [comment]
I have the same problem when I need to allow converting of vrchat avis to vrm and sadly must wait until they release a build of the vrcsdk that upgrades unity.

**Comment by nicoqwertyu** [comment]
I am having the same problem. Can provide any logs needed.

**Comment by yahagi-day** [comment]
The latest version of UniVRM currently supports Unity 2021.3 and later. If you are using Unity 2020.3, please use v0.111.0, and if you are using Unity 2019.4, please use v0.99.4.

**Comment by nicoqwertyu** [comment]
> The latest version of UniVRM currently supports Unity 2021.3 and later. If you are using Unity 2020.3, please use v0.111.0, and if you are using Unity 2019.4, please use v0.99.4.

Thank you for the info. In my case, the issue I was having was for exporting a VRChat avatar to VRM format. The combination I was able to get working this morning was UniVRM 0.113.0 and VRChat Avatar SDK 3.2.3.

**Comment by ousttrue** [comment]
Unity version of UniVRM Supported is here.

https://vrm-c.github.io/UniVRM/en/release/index.html

**Comment by AraHaan** [comment]
I found an even better option: if you still have the *.blend file to your VRChat avatar you can use a VRM export plugin in blender to export as a VRM file. You will need to know which shape keys are supported on it however.
