### ISSUE TITLE
After using the “FastSpringBoneReplacer.ReplaceAsync” interface, scaling the VRM model results in incorrect behavior. 

### ISSUE THREAD

**Issue by pxh1991** [vrm-c/UniVRM#2158]
## Environments (please complete the following information):

 - UniVRM version: `0.113.0`
 - Unity version: `Unity-2021.3.26f1`
 - OS: `Windows 10`

## Describe the bug

After using the FastSpringBoneReplacer.ReplaceAsync interface, scaling the VRM model results in incorrect behavior. For example, components such as hair and skirt, which have spring bones configured, are being stretched or displaced in an unintended manner.

Like Below:
![image](https://github.com/vrm-c/UniVRM/assets/8117346/436e73e0-2ac3-43b0-be01-21a2792d3f7d)

* A clear and concise description of what the bug is.
* ConsoleLog
* ScreenShot
* Reproduction procedure
* File that causes an error (those that can be pasted here)

**Comment by ousttrue** [comment]
We do not recommend using SpringBone and scaling together.

**Comment by ousttrue** [comment]
#2403

**Comment by ousttrue** [comment]
Please try `v0.127.1` or later.
Fastspringbone's reconstruct functionality has been improved.

**Comment by shinyflvre** [comment]
The issue still persists in VRM1 and VRM0
