### ISSUE TITLE
Option to use animator and non-legacy animation clips in importer

### ISSUE THREAD

**Issue by congxinUSC** [vrm-c/UniVRM#2176]
While trying to import a gltf model with animations, erverything looks fine in the preview. However when I tried to replace the animation component generated by default with an animator and creates the corresponding animator controller, things get wrong.
Basically when I try to create states with the imported animation clips, eigher as subasset or as extracted external asset I get the warnning:
> The legacy Animation Clip **<clip name>** cannot be used in the State **<state name>**. Legacy AnimationClips are not allowed in Animator Controllers.
What makes things even worse is that toggling the "isLegacy" property of the animation clip is very untrivial. You have to set the inspector window into Debug mode and uncheck isLegacy. As far as I know the imported animation clip data is compatible with both cases and it's just a legacy flag blocking me from placing the animation into animator controller. That might be wrong but anyways I hope there could be some options in the animation import tab to choose which format of animation controlling and the cooresponding animation clip flag about legacy to be used as a quality of life improvement comparing to the current state where legacy mode is hard coded.
I would like to provide some template code as a PR later to demonstrate the idea if the request makes sense but without enough understanding of the current code base it might look like a bunch of trash code so please ignore it's details and don't expect the PR to be actually merge-ready.

**Comment by FujiSunflower** [comment]
Ah, it is like very Unity problem.
You were said already "You have to set the inspector window into Debug mode and uncheck isLegacy".
https://docs.unity3d.com/ja/2018.4/Manual/InspectorOptions.html

**Comment by congxinUSC** [comment]
I think you might need a better translation tool... I't pretty hard to conclude this a "unity probelm" from the description above.

**Comment by ousttrue** [comment]
Unity's animation conversion feature is an option for the fbx importer.
Since the specification is not public, UniVRM cannot implement compatible conversions on its own.
