### ISSUE TITLE
Still wont work for me

### ISSUE THREAD

**Issue by Enikimm** [vrm-c/UniVRM#2182]
## Environments (please complete the following information):

 - UniVRM version: `0.99.0`
 - Unity version: `Unity-2019.4`
 - OS: `Windows 11`

## Describe the bug
Facial blendshape still don't work despite me being on the correct version of UniVRM

![image](https://github.com/vrm-c/UniVRM/assets/75760726/e6a1d294-119f-4037-8b0d-9d97e5461f18)
![image](https://github.com/vrm-c/UniVRM/assets/75760726/64c928a2-ee13-42f3-a5b3-abe4309b84b4)

**Comment by ousttrue** [comment]
UniVRM error messages do not seem to be included...
