### ISSUE TITLE
Shader error when installing uniVRM

### ISSUE THREAD

**Issue by iillya** [vrm-c/UniVRM#2204]
## Environments (please complete the following information):

 - UniVRM version: `0.116.0`
 - Unity version: `Unity-2022.3.6f1`
 - OS: `Windows 11`

## Describe the bug
I creat a new project in unity 2022.3.6f1 and install uniVRM 0.116.0.Then it's throwing some error after installing the package.
<img width="1249" alt="Snipaste_2023-12-17_15-23-36" src="https://github.com/vrm-c/UniVRM/assets/112866800/d24834d5-e00f-4990-8bbb-259eeed128ed">

**Comment by djtigon** [comment]
also getting the same

**Comment by ousttrue** [comment]
Thank you for the report.
You can safely ignore this error. I wrote an explanation.

https://vrm.dev/en/univrm/error/could_not_include/
