### ISSUE TITLE
VRM10ObjectFirstPersonにより生成された一人称用Meshが破棄されずメモリーリークしている

### ISSUE THREAD

**Issue by tsgcpp** [vrm-c/UniVRM#2209]
## 環境情報

 - UniVRM version: `v0.116.0`
 - Unity version: `Unity-2021.3.27f1`
 - OS: `Windows 10`

## バグについて

* バグの内容
  * VRM10ObjectFirstPersonにより生成された一人称用Meshが破棄されずメモリーリークしている
  * [BoneMeshEraser.CreateErasedMeshAsync](https://github.com/vrm-c/UniVRM/blob/e3d4ea53e8002a60b8f13b607f21ba8359e61da2/Assets/UniGLTF/Runtime/MeshUtility/BoneMeshEraser.cs#L142) で生成された一人称用の`Mesh`インスタンス (_headless_のprefixがあるもの) が破棄されていないと思われます
* ConsoleLog
  * 特になし
* スクリーンショット
  * ![スクリーンショット 2024-01-06 003806](https://github.com/vrm-c/UniVRM/assets/19503967/6c74fa2f-11c1-48cd-87b3-755fa343c6a7)
  * Memory Profilerで 100回 VRMを`instance.Vrm.FirstPerson.SetupAsync`有りでロード → 破棄を繰り返した後のスナップショットのスクリーンショットになります
* 再現方法
  * https://github.com/tsgcpp/UniVRM/releases/tag/report_20240106 をcheckout
  * `Assets/Report/Scenes/Report_MemoryLeak_VRM10ObjectFirstPerson.unity` を開いてPlayモードに移行
  * アバターが複数回ロードと破棄されるまで待機 (100回ロード後に`Vrm10LoadMemoryLeakCheck.LoadLoopAsync finished`とコンソールに出すようにしています)
  * その後Memory Profilerを確認すると一人称用のMesh群が破棄されていないことを確認できます
* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)
  * 特になし

**Comment by ousttrue** [comment]
TODO: RuntimeGltfInstance の管理リストに追加する

**Comment by ousttrue** [comment]
vrm-0.x の方は、
VRM.VRMFirstPerson.OnDestroy で素直に Destroy していた。

**Comment by ousttrue** [comment]
`v0.120` で修正されます。
