### ISSUE TITLE
[Question] Compatibility with Unity Assetbundle Workflow

### ISSUE THREAD

**Issue by BunyaPineTree** [vrm-c/UniVRM#2226]
## Environments (please complete the following information):

 - UniVRM version: `0.117.0`
 - Unity version: `2022.3.9f1`
 - OS: `Windows 10`

## Context for my bug/issue/question

I am a modder trying to create a simple workflow to port VRM models into Lethal Company.

My method involves importing a .vrm file into the unity editor, migrating it to vrm 1 if necessary, performing some work on the prefab with no modification of the VRM scripts, packaging it into an assetbundle, and loading it in game via that assetbundle. 

I have taken the scripts from the [v0.117.0 VRM1 Unitypackage](https://github.com/vrm-c/UniVRM/releases/tag/v0.117.0) and compiled them into a single .dll (With the exception of Test and Editor scripts, which I left out), and I have modified the assembly definitions in the unitypackage to reference that .dll. As of this moment I can confirm that the game can access those scripts, and that all of the scripts are present in game on my prefab.

## The bug/issue/question

While I can confirm that the `VRM10Instance`, `VRM10SpringBoneJoint`, `VRM10SpringBoneCollider`, etc... are all serializing correctly, `Vrm10InstanceSpringBone` does not serialize at all. Both `Vrm10InstanceSpringBone.ColliderGroups` and `Vrm10InstanceSpringBone.Springs` are empty lists, despite this VRM having populated lists in Unity, and the `VRM10SpringBoneColliderGroup`s existing in the scene on the prefab.

Is this an issue regarding assetbundles in general, and if so is there any solution to the problem?

**Comment by ousttrue** [comment]
Since it is a normal class, it seems possible to serialize it. I don't know why.
