### ISSUE TITLE
VRMShader\GLTF errors on empty/blank/new unity 2019.4.31f1 project

### ISSUE THREAD

**Issue by BanyosShep** [vrm-c/UniVRM#2228]
![VRM errors](https://github.com/vrm-c/UniVRM/assets/157431952/09000d45-6d8c-4532-85c5-e673eac2112e)
## Environments (please complete the following information):

 - UniVRM version: today install: 1/22/2024 1849est
 - Unity version: `Unity-2019.4.31f1
 - OS: `Windows 10`

## Describe the bug

literally a blank/new/empty project file, just trying to install VRM to start a VRM export project and immediately recieve the errors listed in the screen shot. im not well versed in Unity, but per any tutorial ive seen, this just aint working. ive tried using base Unity AND Creator Companion with exact same results
![VRM errors](https://github.com/vrm-c/UniVRM/assets/157431952/7d22cfe3-fdae-40ae-9ba9-58ef1ba80380)

**Comment by BanyosShep** [comment]
![VRM errors Unity 2022](https://github.com/vrm-c/UniVRM/assets/157431952/c4511340-f54e-4a78-b023-d776b977a53d)

these are the errors received in Unity 2022.3.6f1

**Comment by MoldOnPepperoni** [comment]
Try old ver. https://github.com/vrm-c/UniVRM/releases/tag/v0.99.0
Pay attention to your Unity version. Versions older than 0.99 require the new one, while older ones support 2019.4
