### ISSUE TITLE
UniVRMの正規化処理の際に表情の正規化がされていない

### ISSUE THREAD

**Issue by FujiSunflower** [vrm-c/UniVRM#2234]
## 環境情報

 - UniVRM version: `0.118.0`
 - Unity version: `Unity-2021.3.27f1`
 - OS: `Windows 11`

## バグについて
* UniVRMの正規化処理の際に表情の正規化がされていない
* スクリーンショット
![スクリーンショット 2024-01-28 050748](https://github.com/vrm-c/UniVRM/assets/20571538/1cde5899-89fb-4e5c-9d9b-b6411c7b5e6a)
* 再現方法
UniVRM 0.116以降でTポーズにした後、正規化処理を行う（VRM0メニューのVRM 0 .x Freeze T-Pose）
UniVRM 0.115では問題が無さそうであった

**Comment by ousttrue** [comment]
Duplicate of #2236
こちらの方が先着ですが、英語の人にも見えるように #2236 に作業を書きます 🙏

**Comment by ousttrue** [comment]
#2240 で修正しました。`v0.119.0`
