### ISSUE TITLE
Exporting in newer versions of UniVRM cause issues with blendshapes and scaling

### ISSUE THREAD

**Issue by Harrison-B** [vrm-c/UniVRM#2236]
## Environments (please complete the following information):

 - UniVRM version: `0.118.0`
 - Unity version: `Unity-2022.3.6`
 - OS: `Windows 10`

## Describe the bug

Exporting the avatar with a newer version of UniVRM causes the Mesh Bounds to increase in size and the blendshapes to be out of whack. I suspect this is due to the scaling on the avatar being weird. 

For some reason on older versions of UniVRM it exports just fine. Version 0.107 exports correctly. Not sure exactly which version causes the issue though. 

Adjusting the blendshapes after exporting then re-importing the VRM:
![image](https://github.com/vrm-c/UniVRM/assets/20074924/ecbca0b0-8681-4d7b-8d5c-e3adc4514917)

Scaling and bounds pre-export
![image](https://github.com/vrm-c/UniVRM/assets/20074924/27456036-c8ed-4679-b631-4d0a883e0319)

Scaling and bounds after export and re-import with UniVRM 0.118
![image](https://github.com/vrm-c/UniVRM/assets/20074924/9c7c4449-0823-452f-abc5-5bfc48e3b6e0)

**Comment by ousttrue** [comment]
I confirmed the reproduction.
A SkinedMesh without bone weights might be the condition to reproduce this.

**Comment by ousttrue** [comment]
- root (scaling 100)
  - hips
     -  spine
        -  head(SkinnedMesh without bone weight but with blendshape)

**Comment by ousttrue** [comment]
👆 Latent bug

I reconfirmed it.

👇 new bug

- root (scaling 100)
  - mesh(SkinnedMesh with bone weight and blendshape)

**Comment by ousttrue** [comment]
It seems to be a regression bug caused by the processing order during normalization from `v0.116`.
