### ISSUE TITLE
[MeshUtility] GUIで統合対象のメッシュを変更できない

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#2248]
## 環境情報

 - UniVRM version: `0.119.0`
 - Unity version: `Unity-2023.2.10f1`
 - OS: `Windows 10`

## バグについて

* バグの内容
    * Unityエディタ上のGUIの、glTF MeshUtility、VRM 0.x MeshUtilityで、対象のメッシュを変更できません。
* ConsoleLog
   > \- clicked : 11.
   > UnityEngine.Debug:Log (object)
   > UniGLTF.MeshUtility.MeshIntegrationTab/<>c:<.ctor>b__9_6 (UnityEditorInternal.ReorderableList) (at ./Library/PackageCache/com.vrmc.gltf@0.119.0/Editor/MeshUtility/MeshIntegrationTab.cs:81)
   > UnityEditorInternal.ReorderableList/Defaults:DrawFooter (UnityEngine.Rect,UnityEditorInternal.ReorderableList)
   > UnityEditorInternal.ReorderableList:DoListFooter (UnityEngine.Rect)
   > UnityEditorInternal.ReorderableList:DoList (UnityEngine.Rect,UnityEngine.Rect)
   > UnityEditorInternal.ReorderableList:DoList (UnityEngine.Rect)
   > UniGLTF.MeshUtility.MeshIntegrationTab:ShowSelected (UnityEngine.Rect) (at ./Library/PackageCache/com.vrmc.gltf@0.119.0/Editor/MeshUtility/MeshIntegrationTab.cs:98)
   > UniGLTF.MeshUtility.Splitter:OnGUI (UnityEngine.Rect,System.Action\`1<UnityEngine.Rect>,System.Action`1<UnityEngine.Rect>) (at ./Library/PackageCache/com.vrmc.gltf@0.119.0/Editor/MeshUtility/Splitter.cs:54)
   > UniGLTF.MeshUtility.MeshIntegrationTab:OnGui (UnityEngine.Rect) (at ./Library/PackageCache/com.vrmc.gltf@0.119.0/Editor/MeshUtility/MeshIntegrationTab.cs:104)
   > UniGLTF.MeshUtility.MeshUtilityDialog:MeshIntegrateGui () (at ./Library/PackageCache/com.vrmc.gltf@0.119.0/Editor/MeshUtility/MeshUtilityDialog.cs:321)
   > VRM.VrmMeshIntegratorWizard:MeshIntegrateGui () (at ./Library/PackageCache/com.vrmc.univrm@0.119.0/Editor/SkinnedMeshUtility/VrmMeshIntegratorWizard.cs:48)
   > UniGLTF.MeshUtility.MeshUtilityDialog:OnGUI () (at ./Library/PackageCache/com.vrmc.gltf@0.119.0/Editor/MeshUtility/MeshUtilityDialog.cs:138)
   > UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
* スクリーンショット
* 再現方法
    1. 「AliciaSolid_vrm-0.51.vrm」をAssetsへインポート
    2. 「AliciaSolid_vrm-0.51.prefab」をシーンへインスタンス化
    3. 「glTF MeshUtility」または「VRM 0.x MeshUtility」を開く
    4. 「ターゲットオブジェクト」でインスタンス化した「AliciaSolid_vrm-0.51」を選択
    5. 「IntegrateSplit」タブを開く
    6. Render一覧で、
        - どれかを選択した状態で「−」を押す
        - 「+」を押す
        - どれかをNoneへ変更しようとする
    7. コンソールにボタンが押された旨のログが出力されるだけで、何も起こらない
* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)
    + https://github.com/vrm-c/UniVRM/blob/v0.119.0/Tests/Models/Alicia_vrm-0.51/AliciaSolid_vrm-0.51.vrm

**Comment by ousttrue** [comment]
実装するのを忘れていました。
`v0.121` で修正予定です。
