### ISSUE TITLE
Exporting Issue

### ISSUE THREAD

**Issue by tea0mouse** [vrm-c/UniVRM#2275]
## 環境情報

 - UniVRM version: `0.109.0`
 - Unity version: `Unity-2019.4.31f1`
 - OS: `Windows 10`

## バグについて

* バグの内容
- I get an error when I try to extract the avatars that combine the head and body of both avatars as vrm. Only showing the texture folder and will not import anything else

* ConsoleLog
* スクリーンショット
* 再現方法
* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

![1111](https://github.com/vrm-c/UniVRM/assets/165929025/1337c304-8b48-44b1-b621-73aebfe5be05)
![2222](https://github.com/vrm-c/UniVRM/assets/165929025/ee10bfd7-c99c-4107-8b2a-79504ebde2e9)
![3333](https://github.com/vrm-c/UniVRM/assets/165929025/71df19e1-012b-408e-b7c3-cc7a1b3462cf)

**Comment by ousttrue** [comment]
It seems that the name of the GameObject that becomes the humanoid bone is duplicated.
Please rename appropriately.

UnityEngine.Avatar creation limitation.
https://docs.unity3d.com/ja/2021.3/ScriptReference/HumanBone.html

**Comment by ousttrue** [comment]
This issue is expected to be exportable in `v0.124.1`.

**Comment by ousttrue** [comment]
#2326
