### ISSUE TITLE
UniVRM request to not reset in-project shaders

### ISSUE THREAD

**Issue by illumkiwi** [vrm-c/UniVRM#2276]
Sometimes there's an issue with the project prompting me to reinstall UniVRM and External Receiver Pack to proceed.
However, I'm working in HDRP and whenever UniVRM is reinstalled, all VRM materials located in project are automatically converted to toon.
![image](https://github.com/vrm-c/UniVRM/assets/116492325/7beced57-aed0-4916-9418-dcd7d3fba2b3)
![image](https://github.com/vrm-c/UniVRM/assets/116492325/37493579-3d19-41c8-8103-f514c6c793b9)

**Comment by ousttrue** [comment]
vrm outputs material to a fixed file path, so
Is it possible to move material to another folder?
