### ISSUE TITLE
The newer UniVRMS

### ISSUE THREAD

**Issue by Enikimm** [vrm-c/UniVRM#2279]
## Environments (please complete the following information):

 - UniVRM version: `0.99.1 and newer`
 - Unity version: `Unity-2019.4 and newer`
 - OS: `Windows 10 or newer`

SO I reverted to windows 10 and also used Pop OS at one point. And guess what I found.
On Pop OS. the 2019.4 version of unity VRM worked perfectly fine with my models.
On windows 10. I found that 2019.4 version of Uni Vrm works perfectly fine with the newer version of unity. 
No blend shape problem. 
But when I use the newer Uni Vrm. It can't read my blend shapes.
This is literally not the first time I brought this up and I feel as thought I've been getting ignored.
additionally. Uni Vrms do not work for me on windows 11. They have missing blend shapes. And the ones from Uni Vrm 2019.4 is no longer working for me some reason. 

Why is it. That. the newer Vrms can't read my blend shapes but the older ones can. 
Also to add on to this. Some of the other newer ones I tried also fucked up the blend shapes even if they could read them.
It was like working with a broken mess. 
I watched as I tried to set the Ah blend shape as my entire mouth up to my lower eye lids deformed. I never had that issue with 2019.4

**Comment by Enikimm** [comment]
I did later reinstall windows 10 due to other issues.

**Comment by ousttrue** [comment]
I need simple reproducible data
