### ISSUE TITLE
Is 0.121 really the latest version?

### ISSUE THREAD

**Issue by cpetry** [vrm-c/UniVRM#2282]
## Environments (please complete the following information):

 - UniVRM version: `0.121.0`
 - Unity version: `Unity-2022.1`
 - OS: `Windows 10`

## Describe the bug

* In this repository there is the version 0.121 marked as latest. This was in march 2021.
Is this really the latest 'stable'/'production' version?
Should I just use the latest development version or will there be a newer release?

**Comment by TigerHix** [comment]
Mar 21 is March 21 2024, not March 2021.

**Comment by cpetry** [comment]
Oh alright, It seems I missed that.
Sorry for the misunderstanding!
