### ISSUE TITLE
The model needs to face the positive Z-Axis

### ISSUE THREAD

**Issue by Sec-Ana** [vrm-c/UniVRM#2283]
## Environments (please complete the following information):

 - UniVRM version: `0.107.0`
 - Unity version: `Unity-2019.4.31f1`
 - OS: `Windows 11`

## Describe the bug

* A clear and concise description of what the bug is: For some reason, even though the model is facing the Z-Axis, the VRM Export function says that it isn't. I've already read the advice in #1507 and #2151 
* No console log.
* ScreenShot:
![image](https://github.com/vrm-c/UniVRM/assets/88745608/43f684bc-0f86-4c16-b1a9-95c0020834ea)

**Comment by Sec-Ana** [comment]
Update: I even tried to modify all the Z-Position of the bones to 0 in the avatar, but it still shows me the same error, I'm not even sure what might be happening. 

It needs to be a positive number (Not zero) for it to work? Doesn't make sense to me, but I might try that as well

**Comment by ousttrue** [comment]
vrm-0.x prints -z forward(invert z). vrm-1.0 outputs +z forward(invert x).
This is determined by the specification.

glb depends on the InvertAxis setting as it is in the scene.

**Comment by Sec-Ana** [comment]
Do you want me to try something? Being honest I don't know what to do in order to help, I'm pretty new to Unity stuff. xD

Thanks for your time btw! <3
