### ISSUE TITLE
VRM10 Spring Bone Collider の Capsule の当たり判定が表示されている範囲よりも長くなっている

### ISSUE THREAD

**Issue by LanternaBlender** [vrm-c/UniVRM#2291]
## 環境情報

 - UniVRM version: `0.122.0`
 - Unity version: `Unity-2022.3.8f1`
 - OS: `Windows 11`

## バグについて

* バグの内容
Capsuleの当たり判定が、シーン上に表示されている赤い２つの球とそれらを結ぶ直線間よりも広い範囲に渡って発生しているようです。

* スクリーンショット
【実行前：Capsuleが真ん中の3つのSpringsに触れ、両端の2つには触れないように配置】
![実行前](https://github.com/vrm-c/UniVRM/assets/159165605/93fc232e-6524-48a8-922a-d82a5689fbc6)
【実行後：Capsuleの当たり判定が両端の2つにまで影響している】
![実行後](https://github.com/vrm-c/UniVRM/assets/159165605/aeb1d666-58ec-43be-b930-4173171001bb)
【期待値：Capsuleの当たり判定が真ん中の3つにだけ影響する】
![修正後](https://github.com/vrm-c/UniVRM/assets/159165605/4a1f8943-0bbc-437a-93d3-682ee38e7f01)

* 再現方法
CapsuleのHeadまたはTailが向く方向の、Capsuleの範囲外にSpringsを配置する。

**Comment by ousttrue** [comment]
This will be fixed in `v0.123`
