### ISSUE TITLE
spring bone is not working correctly.

### ISSUE THREAD

**Issue by chensinit** [vrm-c/UniVRM#2293]
## Environments (please complete the following information):

 - UniVRM version: `0.122.0` vrm1.0
 - Unity version: `Unity-2022.3.20f1`
 - OS: `Windows 11`

## Describe the bug

* When i move character, Hair and skirt are shook. It is not natural.

![Untitled mp4_20240517_103538 538](https://github.com/vrm-c/UniVRM/assets/28124957/4e102ab4-e50e-4d11-a33e-87797109cfef)
![Untitled mp4_20240517_103541 530](https://github.com/vrm-c/UniVRM/assets/28124957/7095f049-4c6a-4416-bee4-f5f056afba25)

https://github.com/vrm-c/UniVRM/assets/28124957/63aba9ce-78a5-4b4e-bca3-b29e4a7a9093

**Comment by ousttrue** [comment]
Even if you show me just a screenshot, I can't investigate without the model and settings.

**Comment by chensinit** [comment]
I remember that I set SpringBoneUpdateType to fixedupdate and it is working good.
But there is no option for vrm1.0

I try to attached model.
[normal_girl.zip](https://github.com/user-attachments/files/16102849/normal_girl.zip)
