### ISSUE TITLE
常にエラー

### ISSUE THREAD

**Issue by darkyvr** [vrm-c/UniVRM#2294]
空のプロジェクトから開始した場合でも、univrm は常にエラーで開始されます。私が添付した画像をご覧ください。
![always error](https://github.com/vrm-c/UniVRM/assets/115593820/8ca8c5e6-a8ae-4499-9924-04830671af86)

**Comment by ousttrue** [comment]
Please ignore this error

https://vrm.dev/en/univrm/error/could_not_include/
