### ISSUE TITLE
system.collections.generic.list'1[System.ValueTuple'2[unityengine.renderer,unityengine.transform[]]]: MATERIAL_CONTAINS_NULL

### ISSUE THREAD

**Issue by MonkeAk** [vrm-c/UniVRM#2295]
how would i go about fixing this error?
![Screenshot 2024-05-18 173953](https://github.com/vrm-c/UniVRM/assets/114530852/c548560f-c217-45a1-9cd4-bef796fc062f)

**Comment by ousttrue** [comment]
Please paste the text of the error message, not the image.

Maybe renderer materials has null.
![materials_null](https://github.com/vrm-c/UniVRM/assets/68057/a3b1b3a7-3e03-4be6-928b-bef1d0b1acc8)

**Comment by ousttrue** [comment]
Modify to be able to export null material. #2313

**Comment by ousttrue** [comment]
This will be fixed in `v0.123`
