### ISSUE TITLE
Cant get my avatar to export

### ISSUE THREAD

**Issue by RozzieTheJester** [vrm-c/UniVRM#2299]
## Environments (please complete the following information):

 - UniVRM version: `0.122.0_326b`
 - Unity version: `Unity-2022.3.6f1`
 - OS: `Windows 11`

## Describe the bug

![Screenshot 2024-05-22 231050](https://github.com/vrm-c/UniVRM/assets/157340673/58e87ee7-2e53-4d34-a648-b416651e0f91)

This is what i got in my logs and i cant make sense of it

**Comment by ousttrue** [comment]
Modify to be able to export null material. #2313

**Comment by ousttrue** [comment]
This will be fixed in `v0.123`
