### ISSUE TITLE
Two problems of springbone

### ISSUE THREAD

**Issue by Graval504** [vrm-c/UniVRM#2331]
I want to mimic dynamicbone's movement with springbone,
but I have two problems with it, so I want some functions to solve this problem.

1. well-used parameter of dynamic bone is three(damping, elasticity, stiffness) but well-used parameter of spring bone is only two(stiffness, dragforce). So mimicking dynamicbone with these two parameter is quite awkward.
To solve this problem, I use gravity to mimic dynmaicbone's stiffness(work differently with springbone's stiffness).
When using gravity direction with unit vector of bone's direction, it works quite similar with dynamicbone's stiffness.
But many of the bones are not straight. Many of hair, cloth, etc's bones turns direction on their child bones.
I tried setting spring bone on child bones but not working.(depending on parent's bone's springbone's movement)
So I want,
being able to separate springbone of child bone and parent bone,
or making priority of child bones'spring bone higher than parent's bone,
or being able to set several gravity direction on each bones in one spring bone component(parent bone)

2.  There is springbone capsule collider on VRM1.0, but isn't on VRM0.x.
but many programs don't support VRM1.0, only support VRM0.x, so I can't use VRM1.0.
There is only sphere collider on VRM0.x, so I had to set several sphere colliders to mimic capsule collider.
So what I want to know is, do you have any plans to implement capsule collider on VRM0.x in the future.

**Comment by ousttrue** [comment]
1. Pure Hooke's law is not used to constrain the mass point. Therefore, the parameters may not be compatible.
2. Our policy is not to backport capsules to 0.0 because we want to popularize 1.0. 🙏
