### ISSUE TITLE
VrmShaders を UniGLTF に合流する

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/UniVRM#2337]
メンテナンス

#1341
#2156

**Comment by Santarh** [comment]
目的
- 今後のユーザ導入体験の向上
  - 名称からよく分からないパッケージの導入をせずに済む
  - よく分からない名称の asmdef に依存せずに済む
  - よく分からない名称の名前空間を using せずに済む
- VRM 1.0 だけを導入する際に MToon 0.X が勝手に導入されてビルドに含まれてしまう問題への対処
- すべての関連シェーダが Resources に含まれているが、Resources は現在の Unity では非推奨であるためこれに対処する
- MToon0.X を UniVRM の都合で機能改善しやすくする

**Comment by ousttrue** [comment]
#2365
#2366
#2367 
#2370
#2372
#2373
#2377
