### ISSUE TITLE
Freeze T-pozeすると手首のメッシュが壊れてしまいます

### ISSUE THREAD

**Issue by KUROI-NYAN** [vrm-c/UniVRM#234]
**バグについて**

Export Humanoid、もしくはFreeze T-pozeすると手首のメッシュが壊れてしまいます。
画像をご覧ください。

**再現方法**

現在問題が置きているモデルでしか確認できません。

![D2U5hPZUgAAeHDJ](https://user-images.githubusercontent.com/42903566/54863213-6e6ce780-4d89-11e9-9345-a06d49b199fb.jpg)

**環境情報**

 - OS: [e.g. `Windows 10`]
 - UniVRM version: [e.g. `0.52.0`]

**Comment by hiroj** [comment]
返答遅くなってしまい、申し訳ありません。
ご報告ありがとうございます、調査致します。

**Comment by hiroj** [comment]
状況を再現出来ないため推測になってしまいますが、手首のメッシュかGameObjectにマイナススケールがかかっていると壊れてしまうケースがあるかもしれません。
その他に以下の項目を確認していただけると助かります。
・見えなくなった手首のSkinnedMeshRendererは正しい位置にあるかどうか
・SkinnedMeshRendererのMesh項目にメッシュが設定されているかどうか

**Comment by KUROI-NYAN** [comment]
お返事が遅くなり申し訳ありません。
問題が解決しないので、色々試していたところ、
ボーンをシンメトライズし直してFBXを書き出し、
上書きでなく新規に設定したところ手首が壊れる現象は起きなくなりました。
調査ありがとうございました。
