### ISSUE TITLE
正規化されたVRMモデルにてNormalマップが動作しない

### ISSUE THREAD

**Issue by kan-pc** [vrm-c/UniVRM#235]
正規化した状態のモデルにNormalマップを設定したマテリアルを設定した際、Normalマップが設定されていないような状態で表示されます。

実際にはマテリアルにNormalマップは設定されており、マテリアルのプレビューでは、きちんとNormalマップが設定された状態でレンダリングされています。

発生例①
1. fbxモデルをシーンに配置
2. fbxにマテリアルを適用
3. モデルの正規化
4. 正規化したモデルをシーンに配置すると、Normalマップが動作していない
(正規化された際に新たに生成されたマテリアルにNormalマップは設定されており、マテリアルのプレビューではNormalマップは動作している。

発生例②
1. fbxモデルをシーンに配置
2. モデルの正規化
3. 正規化されたモデルにマテリアルを適用
4. Normalマップが動作していない

発生した環境 
・Unity 2017.4.15g1
・最新版Unity

発生したバージョン
・新しめのバージョンを3,4つほど試しましたが、すべてのバージョンで同じ不具合が発生しています。

**Comment by hiroj** [comment]
返答遅くなってしまい申し訳ありません、ご報告ありがとうございます。
調査のためお手数ですがマテリアルが使用しているシェーダを教えていただけると助かります。

**Comment by hiroj** [comment]
UnityとUniVRMのバージョンが何度も更新されたため、最新のバージョンでも同じ問題が起きるか確認して頂けると助かります。問題が起きる場合はこのisseuを再オープンしてください。
