### ISSUE TITLE
BlendShape を持たないメッシュのみで構成されたモデルを VRM にするとメッシュが見えなくなる

### ISSUE THREAD

**Issue by ani-kun** [vrm-c/UniVRM#2353]
## 環境情報

- UniVRM version: `0.124.0`
- Unity version: `Unity-2022.3.22f1`
- OS: `Windows 11`

## バグについて

- バグの内容
BlendShape を持たないメッシュのみで構成された fbx モデルを VRM にするとメッシュが見えなくなる (メッシュ自体は存在しているのでスキン情報が壊れている？)
- ConsoleLog
なし
- スクリーンショット
なし
- 再現方法
Blender で BlendShape を持たないメッシュのみでモデルを作成 (ウェイトは設定) して fbx として出力し、freeze ありで VRM に変換
- エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)
なし

**Comment by ousttrue** [comment]
#2339 かもしれないので `v0.124.1` でお試しください。

**Comment by ani-kun** [comment]
`0.124.1` で問題ないことが確認できましたので close します
