### ISSUE TITLE
[MeshAttachInfo.cs:23] Unable to Export to VRM 0 / VRM 1

### ISSUE THREAD

**Issue by mikavalencia** [vrm-c/UniVRM#2361]
## Environments (please complete the following information):

- UniVRM version: `0.121.0`
- Unity version: `Unity-2022.3.22f1`
- OS: `Windows 11`

## Describe the bug

- When attempting to export I receive the following errors but cannot figure out what the issue is : 
![image](https://github.com/user-attachments/assets/9601d1aa-f0d5-404a-9bac-28d67cebc961)

**Comment by ousttrue** [comment]
Seems to be the same issue as #2336 

https://vrm.dev/en/univrm/error/0_124_1_NullReferenceExceptionMeshAttachInfo/

Please try `v0.124.1`.

**Comment by mikavalencia** [comment]
I need to export to VRM 0.0 and v0.124.1 only allows export to VRM 1.0.

**Comment by ousttrue** [comment]
I think it will work.
Please try it with the latest version
