### ISSUE TITLE
Collider get inverted and rotated by 90 degrees when export

### ISSUE THREAD

**Issue by cranverry** [vrm-c/UniVRM#2368]
## 環境情報

- UniVRM version: `0.124.1`
- Unity version: `Unity-2022.3.22f1`
- OS: `Windows 11`

## バグについて

![image](https://github.com/user-attachments/assets/45e53556-5111-4d73-b939-13d7dff1c03f)
![image](https://github.com/user-attachments/assets/2056903b-4838-4414-8c7a-472cb353cdf0)

look at the collider on the leg side, it is created by reversing the position of the joint.

- バグの内容
- ConsoleLog
- スクリーンショット
- 再現方法
- エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

**Comment by t-shindo** [comment]
What are the steps? I can't fix it.

**Comment by ousttrue** [comment]
What are the steps? I can't fix it.

**Comment by ousttrue** [comment]
#2426
