### ISSUE TITLE
VrmAnimationのロードをexe上で行うとエラーになる

### ISSUE THREAD

**Issue by TwilightWings** [vrm-c/UniVRM#2384]
はじめまして。syと言います。

VrmAnimationのロードはEditor上ではうまくいきますが、exeにするとエラーになります。
ちょっと原因がわからなくて悩んでいます。

## 環境情報

- UniVRM version: `0.114.0`
- Unity version: `2021.3.10f1`
- OS: `Windows 10`

## バグについて

- バグの内容

VrmAnimationのロードはEditor上ではうまくいきますが、exeにするとエラーになります。

- ConsoleLog
Value cannot be null.
Parameter name: Shader

- スクリーンショット
- 再現方法

string path ="VRMAのパス"
using GltfData data = new AutoGltfFileParser(path).Parse();
using var loader = new VrmAnimationImporter(data);
return await loader.LoadAsync(new ImmediateCaller()); // ここでエラー「Value cannot be null. Parameter name: Shader」が出る

エディター上では問題なし。UniVRMはv0.114.0
読み込んだVRMAniationは公式Boothで無料配布されている「VRMA_MotionPack」のもの。

インポートしたパッケージ
https://github.com/vrm-c/UniVRM.git?path=/Assets/VRMShaders#v0.114.0
https://github.com/vrm-c/UniVRM.git?path=/Assets/UniGLTF#v0.114.0
https://github.com/vrm-c/UniVRM.git?path=/Assets/VRM10#v0.114.0
Unity公式Universal RP

- エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)
VRMA_MotionPack
https://booth.pm/ja/items/5512385

**Comment by TwilightWings** [comment]
エラーをはいている箇所は恐らくVRMShader内のMaterialFactory、
「public async Task<Material> LoadAsync(MaterialDescriptor matDesc, GetTextureAsyncFunc getTexture, IAwaitCaller awaitCaller)」関数内の下記。

ここで引っかかるとしたらなぜエディタではロード完了できるのだろう…。

```
if (matDesc.Shader == null)
{
     throw new ArgumentNullException(nameof(matDesc.Shader));
}
```

**Comment by TwilightWings** [comment]
MaterialDescriptorGenerator.GetGltfDefault()　がエディタとexeで動きが違うのかもしれない。

**Comment by TwilightWings** [comment]
exeにするとUnityの「Standard」Shaderが取れないのが原因。。なのですが、どうしてこうなった。。

**Comment by TwilightWings** [comment]
これかもしれない・・・。
https://qiita.com/shirai/items/3d2e3ff9e0d9a55a2e23

**Comment by TwilightWings** [comment]
ランタイム時にStandardシェーダーが入っていないだけでした。
深夜に作業すると脳ミソが使えてないのが分かります🙄

**Comment by Santarh** [comment]
最新バージョン向けではありますが、こちらのドキュメントをご参照ください。

https://vrm.dev/api/build/

**Comment by Santarh** [comment]
URP を利用しているときにも Standard シェーダに依存してしまっているのはバグなので、
近いうちのバージョンで修正予定です。

https://github.com/vrm-c/UniVRM/issues/2399
