### ISSUE TITLE
Spring Bones when Avatar is on a moving platform

### ISSUE THREAD

**Issue by shogoki-vnz** [vrm-c/UniVRM#240]
Hi. Is there a way to prevent the spring bones from triggering when the Avatar is on a moving platform? 

I'm using FinalK, and already applying the VRIKPlatform script that update the Avatar position to the moving platform, but I can't find a way to prevent the spring bones from triggering without having to turn then off completely.

You can see an example of what I'm talking here: https://clips.twitch.tv/BlitheKawaiiShrewSeemsGood notice once the stage start, the spring bones goes to overdrive even when the Avatar remains fixed on the platform.

**Comment by hiroj** [comment]
![image](https://user-images.githubusercontent.com/39366194/57283327-df721f80-70e9-11e9-8e86-e8445134b15f.png)
Setting moving platform transform to "Center" prevents SpringBone by moving the center transform.
If "center" is set, it works by the difference with "center".

**Comment by shogoki-vnz** [comment]
やた！完璧だ。ありがとございます
