### ISSUE TITLE
スケールを大きくすると、SpringBoneの動きがおかしくなる。

### ISSUE THREAD

**Issue by emptybraces** [vrm-c/UniVRM#2403]
## 環境情報

- UniVRM version: `0.124.1`
- Unity version: `Unity-2023.2`
- OS: `Windows 11`

## バグについて

- バグの内容
キャラのスケールが１なら問題ないが、スケールを大きくすると（例えば１０とか）、SpringBoneの動きがかなりスローになりその場で動かなくなる。大きいキャラを表示させたいのですが、SpringBoneが使えず困っています。

## 実装

- [x] vrm-0 `v0.126.0`
- [x] vrm-0fastspringbone
- [x] vrm-1fastspringbone

**Comment by ousttrue** [comment]
```cs
            // verlet積分で次の位置を計算
            var nextTail = currentTail
                           + (currentTail - prevTail) * (1.0f - dragForce) // 前フレームの移動を継続する(減衰もあるよ)
                           + ParentRotation * LocalRotation * m_boneAxis * stiffnessForce * m_transform.UniformedLossyScale() // 親の回転による子ボーンの移動目標
                           + external * m_transform.UniformedLossyScale(); // 外力による移動量
```

**Comment by ousttrue** [comment]
`v0.126.0` vrm-0springbone に入ります。
vrm-0fastspringbone と vrm-1fastspringbone は順次作業予定です。

**Comment by ousttrue** [comment]
`v0.127.0` 実装

https://vrm.dev/api/springbone/vrm0/runtime/

`SupportsScalingAtRuntime`
