### ISSUE TITLE
UniVRM_Samples-0.125.0での出力エラー

### ISSUE THREAD

**Issue by kuni-0930** [vrm-c/UniVRM#2404]
## 環境情報

- UniVRM version: `0.125.0`
- Unity version: `Unity-2021.3.29f1`
- OS: `Windows 11`

## バグについて

- バグの内容
UniVRM_Samples-0.125.0_f812のサンプルシーンで入出力テストをしてみるとエラーが発生します。

アバターLoad時(Warning)：VrmUtility.LoadAsync: awaitCaller argument is null. ImmediateCaller is used as the default fallback. When playing, we recommend RuntimeOnlyAwaitCaller.

アバターExport時(Normalize On)：NullReferenceException: Object reference not set to an instance of an object

アバターExport時(Normalize Off)：ArgumentException: no animator nor humanoid

また、スタンドアロンアプリでVRM_Samples/RuntimeExporterSample/VRMRuntimeExporterのExportSimpleで出力したところ、出力は成功したのですが出力したアバターをUnityで確認するとオブジェクトからSkinnedMeshRendererコンポーネントが消えている状態でした。
ご確認をよろしくお願い致します。

- ConsoleLog
[Editor.log](https://github.com/user-attachments/files/16568294/Editor.log)

- スクリーンショット
- 
- 再現方法
UniVRM_Samples-0.125.0_f812でVRoidStudio_v1.29.1のアバターを入出力してみる

- エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)

**Comment by ousttrue** [comment]
再現確認しました。
修正します。
