### ISSUE TITLE
VRM1.0でエディターの再生中にSpringBobeの調整ができない

### ISSUE THREAD

**Issue by c-colloid** [vrm-c/UniVRM#2410]
## 環境情報

- UniVRM version: `0.125.0`
- Unity version: `Unity-2022.3`
- OS: `Windows 11`

## バグについて

- バグの内容
SpringBoneの設定まで済んだアバターをUnityエディター上に用意して、再生モードでSpringBoneの動作を確認していました

SpringBoneの動作自体は問題なく確認できたのですが、その挙動を調整しようとパラメーターを動かしても全く挙動に変化がありませんでした

再生モードを抜けて調整した後再度再生モードに入れば挙動は変化していたので、再生モード中のみの問題だと思われます

また、同バージョンのVRM0.xを導入したプロジェクトでは再生中でも挙動の変化が見られたのでVRM1.0特有の問題かと思われます

**Comment by ousttrue** [comment]
joint と collider の変更時に Reconstruct を呼び出すようにしました。
`v0.126.0` に入ります。
