### ISSUE TITLE
Unity Save Crash After "Freeze T-Pose"

### ISSUE THREAD

**Issue by Iplay4u** [vrm-c/UniVRM#2412]
## Environments (please complete the following information):

- UniVRM version: `0.123.0_f812`
- Unity version: `Unity-2022.3.22f1`
- OS: `Windows 11`

## Describe the bug

I am using an avatar that is 146k Polygons, 1x Skinned Mesh Renderer, 15 materials and 165 bones
When I use the "Freeze T-Pose" feature, it does what it should normally but when I save the scene, it crashes Unity every time. It is saved before the "Freeze T-Pose" but doesn't save afterwards since it crashes.

While freezing: (took 07:15 to execute the code)
![HF4 0319 23hr 24 08 24](https://github.com/user-attachments/assets/579d9fdc-f35a-445b-afb3-c92398a7f515)

Nothing in the console before saving:
![EJK 0320 23hr 24 08 24](https://github.com/user-attachments/assets/59f01f61-ca98-477f-be33-8ec076a9e6ad)

Seconds before the crash: (took 05:45 to execute the code)
![ZxE 0321 23hr 24 08 24](https://github.com/user-attachments/assets/b9d1668f-dc02-4c50-93e0-4054a6d68c4e)

If anyone wants to reproduce the issue and are having problems doing it, it may be the avatar thats the issue. DM me on Discord and ask for it and I will provide: phederal_phoenix

**Comment by Iplay4u** [comment]
Edited cause what I thought fixes it indeed doesn't fix it

**Comment by Anna-Spanner** [comment]
Hi, I haven't gotten round to checking it again yet (I am Iplay4u on an alt account)
