### ISSUE TITLE
マテリアル設定でRendering TypeをTransparent、Cull ModeをOffにすると奥側の面の色が透けてしまう

### ISSUE THREAD

**Issue by eishin178** [vrm-c/UniVRM#2439]
## 環境情報

- UniVRM version: `0.126.0`
- Unity version: `Unity-2022.3.7f1`
- OS: `Windows 11`

## バグについて

マテリアル設定でRendering TypeをTransparent、Cull ModeをOffにすると奥側の面の色が透けてしまいます。
仕様でしょうか。
できれば修正をお願いします。

![CullBack](https://github.com/user-attachments/assets/71530816-958b-42f9-9403-5bff1b206967)
![CullOff](https://github.com/user-attachments/assets/227c826c-2cf9-4c4b-aae2-5ac1bf92fe9c)
スクショは全面色違いの立方体です。

**Comment by ousttrue** [comment]
裏面の描画を防止するには、backface culling もしくは depth test のいずれかが必要です。
Transparent にすると depth test が無効になります。
GPU 一般の仕様となります。

**Comment by eishin178** [comment]
やはり仕様なんですね。
回答ありがとうございます。

**Comment by ousttrue** [comment]
`depth test が無効` が不正確でした。
`depth write` (zwrite) が無効になります。
transparent の場合に zwrite を無効にするのが一般的です。
MToon は transparent で zwrite する仕様があるようです。
zwrite の有無は各 Material の仕様となっています。
