### ISSUE TITLE
Many errors after importing in brand new project

### ISSUE THREAD

**Issue by MochyPei** [vrm-c/UniVRM#2441]
## Environments (please complete the following information):

- UniVRM version: `0.124.2`\Latest (on day of writing this)
- Unity version: `Unity-2019.4.31f1` \ `Unity-2022.3.22f1`
- OS: `Windows 10`

## Describe the bug

- A clear and concise description of what the bug is.
After importing UniVRM in brand new project, and doing nothing i got +290 errors like (expected ';', ')', '}', '=', etc)
- ConsoleLog
[Editor.log](https://github.com/user-attachments/files/17102438/Editor.log)
- ScreenShot
![image](https://github.com/user-attachments/assets/3a81e368-8e68-4dc0-96e0-d36da38f8c8b)
- Reproduction procedure
1. Import unityasset of UniVRM (or VRM)
2. To get it again, delete all files and folders of UniVRM, VRM (etc imported by unityasset)
3. Import again
- File that causes an error (those that can be pasted here)
unityassets? (from releases)

(UPD)
Tested in newer unity, errors changed but still can do nothing, it's still don't work...
Errors like "(are you missing a using directive or an assembly reference?)" and "is not an attribute class"
Here's log from 2022 ver
[Editor2022.log](https://github.com/user-attachments/files/17102666/Editor2022.log)

**Comment by ousttrue** [comment]
v0.124 support Unity-2021.3 or later.
I don't know about  `Editor2022.log`. Is this a Unity error?
