### ISSUE TITLE
Can't attach Meta to model

### ISSUE THREAD

**Issue by 99-Abigail-10** [vrm-c/UniVRM#2442]
- UniVRM version: 0.89.0
- Unity version: 2019.4.31f1
- OS: Windows 10

I'm having trouble attaching the Meta to my model, I've added the VRM Meta script, but it won't select my Meta file.
![image_2024-09-23_205344321](https://github.com/user-attachments/assets/7b7b2443-a385-45a9-a42b-cd1c9922a7e0)

**Comment by ousttrue** [comment]
I tried it and it worked without any problems.
Please tell me the steps in more detail.
