### ISSUE TITLE
Support exporting texture as jpg

### ISSUE THREAD

**Issue by il-m-yamagishi** [vrm-c/UniVRM#245]
https://github.com/vrm-c/UniVRM/blob/39f29c28d93fd5f59fa73375173c08961d8eb8e5/Assets/VRM/UniGLTF/Scripts/IO/TextureIO.cs#L136

現在の UniGLTF 実装では、全てのテクスチャを `png` として出力していますが、アルファチャンネルを利用していないテクスチャを `jpg` として出力することで、 VRM ファイルの容量を削減出来るのではないでしょうか。

例えば [ニコニ立体ちゃん (VRM)](https://3d.nicovideo.jp/works/td32797) は 10,462 KB のうち 5,038 KB と約半分がテクスチャです。

テクスチャ出力の際、全てのピクセルでアルファチャンネルを利用していないか確認するか、 NormalMap や Emission など、アルファチャンネルが利用されないことが判明しているテクスチャを自動的に判別し出力時に変換することで、 VRM ファイルサイズを小さく抑えることが出来るのではないでしょうか。

例に挙げたニコニ立体ちゃんを純粋に全て jpg 85% に変換した所、合計 916 KB と約 18% まで削減することが可能でした(サムネイル用画像が 1.5 MB もあるのが問題な気がしますが)。

実際はアルファチャンネルのあるテクスチャが多いためここまでの削減率にはならないと思いますが、ご検討いただければと思います。

- ref. https://docs.unity3d.com/ja/2017.4/ScriptReference/ImageConversion.EncodeToJPG.html

**Comment by saturday06** [comment]
非可逆圧縮を使うなら、最近glTFに入ったWebPテクスチャの拡張に乗っかるのもアリだと思います。
https://github.com/KhronosGroup/glTF/blob/05e819829fb9aae5a2f614daa37cb7c01ba32718/extensions/2.0/Vendor/EXT_texture_webp/README.md 。

また、NormalMapなどのRGB三原色では無い値を格納しているテクスチャに対して `jpg` など画像用の非可逆圧縮をしてしまうと、テクスチャーの表示が歪む事象が発生するので、それらの圧縮は可逆圧縮を使うような工夫が必要になると思いました。

**Comment by hiroj** [comment]
WebPはアルファ付きで圧縮率も良さそうなので検討してみます

**Comment by esperecyan** [comment]
PNGのエクスポートについてですが、テクスチャの設定でAlpha SourceがNoneになっている場合は、アルファチャンネルを含めずに24bitでエクスポートできないでしょうか。できれば元のPNGファイルのbit数に応じて、エクスポート時のPNGのbit数が変わればと思います。

**Comment by esperecyan** [comment]
UniVRM-0.55.0現在、サムネイルがPNGの場合、サムネイルファイルがそのままエクスポートされます。

- ファイル容量の肥大化
- エクスポートに時間がかかる

再圧縮による上記の問題を回避するため、同じようにすべてのテクスチャで再圧縮しないようScripting Define Symbolsなどで切り替えられるようにすることはできないでしょうか。

**Comment by hiroj** [comment]
EditorExport時にAssets以下にjpgが存在していた場合はそれを書き込むように変更しました。
