### ISSUE TITLE
iOS実機でランタイムにVRMをLoadするとたまにエラーが起きてアプリが落ちる

### ISSUE THREAD

**Issue by umiyuki** [vrm-c/UniVRM#246]
**バグについて**

iOSのVRMアプリの開発を行っていますが、iOS実機でランタイムにStreamingAssetsに置いておいたVRMファイルをロードするとたまにエラーが起きてアプリが落ちてしまいます。
xCodeではエラー「ETC_BAD_ACEESS」と表示されます。
どなたか回避する方法をご教授頂ければ幸いです。

**再現方法**

サンプルのVRMRuntimeLoaderSample、VRMRuntimeLoaderSample.Net4のシーンでも発生する事を確認しています。（ただしランタイムで読み込むために読み込むファイルのパスだけStreamingAssetsに変更しています）
VRMファイルもいくつか試していますが同じ状況です。

**環境情報**

 - OS: iOS12
 - UniVRM version: 0.51.0（0.44などのバージョンでも同様でした）
 - Unityエディタ: 2018.3.9
 - Scripting Runtime Version: 4.x
 - 端末: iPhoneX、iPhone6S

**追加の状況・背景**

読み込みにLoadAsync、LoadAsyncTask、Load（同期）それぞれ試してみましたが同様でした。

**Comment by hiroj** [comment]
ETC_BAD_ACEESS（EXC_BAD_ACCESSが正しい？）はおそらくメモリアクセス違反が起きていると思われますが、iOSの検証環境が無いためどなたか調べていただけると助かります。

**Comment by hiroj** [comment]
バージョンが何度か更新されたので、もしよろしければ最新バージョンで再度ご確認頂けると助かります。もしまだエラーが出るようでしたら再Openして頂けると助かります。
