### ISSUE TITLE
UV sometimes flips when a same accessor is referred by multiple meshes

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/UniVRM#2474]
Original discussion: https://github.com/vrm-c/UniVRM/pull/2464#issuecomment-2434290706

## 環境情報

- UniVRM version: `master` @ 675bb7b
- Unity version: `Unity-2021.3`
- OS: `Windows 11`

## バグについて

同じaccessorが複数のメッシュで偶数回用いられている場合、UVのY-flipがうまく動作しないことがあります。
これは、同じaccessorに対してY-flipのY-flipを行っていることによって発生しているものと思います。

また、UVのY-flipの他にも、近い箇所で `ReverseAxisAndFlipTriangle` が呼ばれており、こちらも偶数回処理していることの影響を受けていると推察します。

### 考えられる修正手順

以下のようなコードで、ユニークなaccessorのバッファを取り出して（ `g`, `m`, `uv` ではユニーク判別できませんでした）処理することにより一応対処できました。
該当箇所: https://github.com/ousttrue/UniVRM/blob/333ae766d0dbc0a1b56b1f735ff10f57af9c49d8/Assets/VRM10/vrmlib/Runtime/Model.cs#L402

![image](https://github.com/user-attachments/assets/2659d4e4-2957-4e6d-9898-8c34ed3a118c)

### 再現するファイル

[isbinary-overrides.zip](https://github.com/user-attachments/files/17501346/isbinary-overrides.zip)

#2464 で対応されている、表情のisBinaryとoverrideの相互作用のチェック用モデルです。
4つのmeshesから1つの同じaccessorが参照されています。

![image](https://github.com/user-attachments/assets/2d06b9d5-2be2-4837-9adf-c5154fad9059)

現状のUniVRMでの挙動: チェックボックスや文字が上下反転しています。

![image](https://github.com/user-attachments/assets/0d01833a-a2f9-494e-9a90-416388ca263e)

**Comment by ousttrue** [comment]
確認しました。
uv 反転等を buffer に対して inplace  でやっているのがよろしくないようです。
歴史的事情で vrm-1.0 だけ違うロジックで import しているので、
glb など他の mesh import と処理を統合して対処する予定です。

https://github.com/vrm-c/UniVRM/milestone/95

でやります。
