### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by DRIVER1ksa** [vrm-c/UniVRM#2479]
- UniVRM version: `0.127.2`
- Unity version: `Unity 6`
- OS: `Windows 11`

## Describe the bug

NullReferenceException: Object reference not set to an instance of an object
VRM.VrmGeometryBackup..ctor (UnityEngine.GameObject root) (at Assets/VRM/Runtime/IO/VrmGeometryBackup.cs:76)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings, UniGLTF.IMaterialExporter materialExporter, System.Collections.Generic.List`1[T] destroy) (at Assets/VRM/Editor/Format/VRMEditorExporter.cs:211)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings, UniGLTF.IMaterialExporter materialExporter) (at Assets/VRM/Editor/Format/VRMEditorExporter.cs:29)
VRM.VRMExporterWizard.ExportPath (System.String path) (at Assets/VRM/Editor/Format/VRMExporterWizard.cs:261)
UniGLTF.ExportDialogBase.EndGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:162)
UniGLTF.ExportDialogBase.OnGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:82)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) (at <9e3a60dbcacc4e77a9c6e1c14064183a>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect dockAreaRect) (at <9e3a60dbcacc4e77a9c6e1c14064183a>:0)
UnityEditor.DockArea.OldOnGUI () (at <9e3a60dbcacc4e77a9c6e1c14064183a>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEventBubbleUp (UnityEngine.UIElements.EventBase evt) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.EventDispatchUtilities.HandleEventAcrossPropagationPathWithCompatibilityEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.EventBase compatibilityEvt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement target, System.Boolean isCapturingTarget) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.EventDispatchUtilities.DispatchToCapturingElementOrElementUnderPointer (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, System.Int32 pointerId, UnityEngine.Vector2 position) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.PointerEventBase`1[T].Dispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <24e165613ea9441aa6d9c8989219aecd>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <9ac54da9a3624080ae596e505f7da9ed>:0)

**Comment by ReefSnax** [comment]
@DRIVER1ksa I encountered this issue as well.

`Unity 2021.3.18f1`
`UniVRM v0.127.2 [Latest](https://github.com/vrm-c/UniVRM/releases/latest)

I had the same error when trying to export any VRM. Using the [previous version](https://github.com/vrm-c/UniVRM/releases/tag/v0.127.1) by importing into my current project solved the issue, so it definitely seems like a bug with one of the files since edited during the recent update.
