### ISSUE TITLE
Can add support for gltf  export?  

### ISSUE THREAD

**Issue by longde123** [vrm-c/UniVRM#248]
json format    gltf  file  ?

**Comment by walf443** [comment]
https://vrm.dev/en/vrm_about/

> Available to handle the humanoid character (3D model data) without limiting to a specific platform.
VRM is based on the 3D standard format glTF2.0, which is the format added with constraints and extensions for handling the humanoid model. Ease of implementation as it is based on this standard format.

VRM file is actually just .glb file. So you can convert it with glb to json converter, I think.

**Comment by FMS-Cat** [comment]
No there are no support for separated gltf export, I think it sounds good though.

**Comment by FMS-Cat** [comment]
In anyway there are no way to import/export a vrm file as a separated gltf file so far, at least on the open source universe

**Comment by walf443** [comment]
I mean. UniVRM does not need support exporting gltf json format, I think.

gltf json format support for vrm specification may be good for mobile environment.

**Comment by longde123** [comment]
user need  support exporting gltf json format, I think.

**Comment by PoChang007** [comment]
Currently we don't plan to add support for gltf export. Sorry about that. 
For gltf export, you may try this one https://github.com/najadojo/gltf-import-export
