### ISSUE TITLE
Incorrect matcap behaviour when only `matcapFactor` is set

### ISSUE THREAD

**Issue by mrxz** [vrm-c/UniVRM#2505]
## Environments (please complete the following information):

- UniVRM version: `0.127.2`
- Unity version: `Unity-2023.2.20f1`
- OS: `Linux`

## Describe the bug
In case `matcapFactor` is defined, but no `matcapTexture` is set, there should effectively be no matcap applied. However, in UniVRM it seems that the `matcapFactor` is applied to the entire mesh.

![image](https://github.com/user-attachments/assets/02e0e135-6575-4f58-8ae3-1a47fa2c0d81)
The avatar on the left uses _no_ `matcapFactor` and no `matcapTexture`. The avatar on the right has `matcapFactor` set to `[1, 1, 1]` and no `matcapTexture`. There are no errors or warnings logged.

A quick look at the shaders, seem to suggest the bug is on the following line:
https://github.com/vrm-c/UniVRM/blob/264a6bcf7897082ad381a1bccffb31c25f10cab2/Assets/VRM10/MToon10/Shaders/vrmc_materials_mtoon_lighting_mtoon.hlsl#L146
The [VRM spec](https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_materials_mtoon-1.0#implementation-2) uses the following pseudo-code:
```
rim = matcapFactor * texture( matcapTexture, matcapUv ).rgb
```
Where a missing `matcapTexture` should be treated as returning `0.0` for all RGB channels.

Here's a file reproducing the issue (zipped as otherwise GitHub would not allow me to upload it): [matcapFactor.zip](https://github.com/user-attachments/files/17722554/matcapFactor.zip)

**Comment by Santarh** [comment]
Thank you for your report.

According to the spec, when `matcapTexture` doesn't exist it should be black.
I'll work on a fix.

> When the texture is not defined, it must be sampled as having 0.0 in RGB components.
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_materials_mtoon-1.0#matcaptexture
