### ISSUE TITLE
WebGLでVRMをランタイムロードすることができない。

### ISSUE THREAD

**Issue by yahagi-day** [vrm-c/UniVRM#251]
**バグについて**

WebGLで下記のコードをGameObjectにアタッチしてビルドしてもモデルが表示されない。(EditorとかWinビルドでは動く)
また、DevToolのConsoleにそれらしきエラーは出ていない。
**再現方法**
```
using UnityEngine;
using UnityEngine.Networking;
using VRM;
using UniRx.Async;

public class LoadVRM : MonoBehaviour
{
    private async UniTask Start()
    {
        var path = Application.streamingAssetsPath + "/model.vrm";
        byte[] data;

        using (UnityWebRequest uwr = UnityWebRequest.Get(path))
        {
            await uwr.SendWebRequest();
            data = uwr.downloadHandler.data;
        }

        var context = new VRMImporterContext();
        context.ParseGlb(data);
        await context.LoadAsyncTask();

        context.ShowMeshes();
    }
}

```

**期待する動作**

StreamingAssetsからモデルを取得して画面にVRMモデルを表示する。
**スクリーンショット**

ある場合は、問題の説明に役立つスクリーンショットを追加してください。

**環境情報**

 - OS: [`Windows 10`]
- Unity: [`2019.1.4f1`]
 - UniVRM version: [`0.510_1b36`] 
Mtoonのみ[v2.0](https://github.com/Santarh/MToon/releases/tag/v2.0)に差し替え
- Browser: [`Chrome`]

**Comment by hiroj** [comment]
https://docs.unity3d.com/ScriptReference/Application-streamingAssetsPath.html
> It is not possible to access the StreamingAssets folder on WebGL and Android platforms.
↑のリファレンスに書いてある通り、WebGLビルドした場合は StreamingAssets にアクセス出来ないため、pathはURLで指定する必要があります、Cドライブ等から始まるpathではアクセス出来ません
そのため uwr.downloadHandler.data の時点でnullになっていると思われます。

**Comment by yahagi-day** [comment]
These platforms return a URL. Use the UnityWebRequest class to access the Assets.
とあるのでWebGLでApplication.streamingAssetsPathをするとStreamingAssetsのURLが返ってきます。
これでUnityWebRequestしてるのでvrm自体は読み込めていました。

WebGLはマルチスレッドが使えないので、
VRM.VRMImporterContext.LoadAsyncTask
を使うことができないようでした。
非同期を使わずにVRMImporterContext.Load
を使ったところ、読み込むことができました。
お手数おかけしました。

**Comment by hiroj** [comment]
調査して頂きありがとうございました。
紛らわしいためWebGL環境ではVRM.VRMImporterContext.LoadAsyncTaskを使用出来ないように修正致します。
