### ISSUE TITLE
URP exporter not implemented for VRM0

### ISSUE THREAD

**Issue by oh-nyoo** [vrm-c/UniVRM#2516]
## Environments (please complete the following information):

- UniVRM version: `0.128.0`
- Unity version: `Unity 6 (6000.0.29f1)`
- OS: `Linux bazzite 6.11.9-303.bazzite.fc41.x86_64`

## Describe the bug

Error trying to export using `VRM0` > `Export VRM 0.x...`

```
NotImplementedException: URP exporter not implemented
VRM.VrmMaterialExporterUtility.GetValidVrmMaterialExporter () (at Assets/VRM/Runtime/IO/MaterialIO/VrmMaterialExporterUtility.cs:13)
VRM.VRMExporter..ctor (UniGLTF.ExportingGltfData data, UniGLTF.GltfExportSettings exportSettings, UniGLTF.IAnimationExporter animationExporter, UniGLTF.IMaterialExporter materialExporter, UniGLTF.ITextureSerializer textureSerializer) (at Assets/VRM/Runtime/IO/VRMExporter.cs:33)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings, UniGLTF.IMaterialExporter materialExporter, System.Collections.Generic.List`1[T] destroy) (at Assets/VRM/Editor/Format/VRMEditorExporter.cs:239)
VRM.VRMEditorExporter.Export (UnityEngine.GameObject exportRoot, VRM.VRMMetaObject meta, VRM.VRMExportSettings settings, UniGLTF.IMaterialExporter materialExporter) (at Assets/VRM/Editor/Format/VRMEditorExporter.cs:29)
VRM.VRMExporterWizard.ExportPath (System.String path) (at Assets/VRM/Editor/Format/VRMExporterWizard.cs:261)
```

The VRM1 export from VRM-0.128.0_264a seems to work but I wish to use VRM0.

Possibly related to https://github.com/vrm-c/UniVRM/issues/2480 where a Mtoon export of urp has been implemented in this pull request https://github.com/vrm-c/UniVRM/pull/2484

**Comment by ousttrue** [comment]
vrm-0.x does not support URP.
(There is no urp version of mtoon-0.x shader)

Please use builtin-RP for vrm-0.x.
If you want to use vrm-0.x in URP,

You can convert vrm-0.x to vrm-1.0 during runtime import in your application.
