### ISSUE TITLE
Meshes with quads not exported correctly

### ISSUE THREAD

**Issue by cpetry** [vrm-c/UniVRM#2525]
## Environments (please complete the following information):

- UniVRM version: `0.128.0`
- Unity version: `Unity-2022.1.24`
- OS: `Windows 11`

## Describe the bug

- Meshes (and submeshes) with quads are not exported correctly.
Fails because triangles are assumed but indices of quads coming in

**Comment by cpetry** [comment]
#2526

**Comment by ousttrue** [comment]
https://github.com/vrm-c/UniVRM/milestone/96
