### ISSUE TITLE
uniVRM0.52上でMToonのマテリアルを変更し、VRM出力しても反映されない

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#258]
**バグについて**
VRMをインポートし、そのマテリアルを編集し(ex:RimColorテクスチャ、AutoAnimationのマスクテクスチャを設定する等)、VRMを出力しても、json上にそれらのパラメータが現れない

![SS](https://user-images.githubusercontent.com/3232308/58879661-194a3c00-8711-11e9-9d53-6adf2b922359.jpg)

**環境情報**

 - OS: [`Windows 10`]
 - unity.2018.3.7f1 
 - uniVRM0.52

**Comment by hiroj** [comment]
ご報告ありがとうございました、以下のバージョンで修正が入りました
https://github.com/vrm-c/UniVRM/releases/tag/v0.53.0

**Comment by iCyP** [comment]
修正確認いたしました。ありがとうございます。
