### ISSUE TITLE
[エディタ拡張] VRM正規化時のデフォルト出力先フォルダ

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#282]
VRM正規化を行う際にデフォルトで選択されている出力先フォルダについて、正規化前のモデルのプレハブが存在するフォルダと同じフォルダをあらかじめ選択できないでしょうか。

https://github.com/vrm-c/UniVRM/blob/ec644b635ac0bcc3d586d012bc41a206b8cfd799/Assets/VRM/UniVRM/Editor/Format/VRMExporterMenu.cs#L30-L35

**Comment by ousttrue** [comment]
同じフォルダに出力するとすぐにImporterが動作し上書きされてしまいます。
この動作を望まない人もいるので、同じフォルダをデフォルトにするのを避けています。

**Comment by esperecyan** [comment]
元がprefabの場合は、デフォルトのファイル名が重複しないようにするなどで対処できないでしょうか。

**Comment by ousttrue** [comment]
検討した結果、
https://docs.unity3d.com/ScriptReference/EditorUtility.SaveFilePanel.html
の第２引数がnullなのはよろしくないとなりました。
初回に UnityProjectの root (Assetsの一個上)、２回目から前回エクスポートした場所を指定するように変更する予定です。
