### ISSUE TITLE
UniVRM v0.52でスキーマが黙って非互換変更された

### ISSUE THREAD

**Issue by vyv03354** [vrm-c/UniVRM#284]
#129 で変更は慎重に行うとおっしゃっていたにもかかわらず、#257 で突然スキーマに[非互換変更が加えられ](https://github.com/vrm-c/UniVRM/commit/5c5a966f1815f355ec094f27a19954216d92418d)、しかも`specVersion`も更新されず、おまけにReleaseNoteに言及すらありません。非互換変更を加えてもバージョンが変わらないのではバージョンをつけている意味がありません。

せめて[v0.52のReleaseNote](https://github.com/vrm-c/UniVRM/wiki/ReleaseNote-v0.52.0(ja))に追記していただけないでしょうか。

**Comment by vyv03354** [comment]
cc @yutopp @saturday06 @hiroj

**Comment by hiroj** [comment]
申し訳ありません、こちらの確認漏れでSchemaに更新が入ってしまいました。
#129 の通り、minimum=0をSchemaに含めるかどうかは十分検討された結果ではないため、v0.46時点で出力された状態にSchemaを戻す対応を行います。
Schemaに対する仕様変更は1.0まではやらない方針ですが、今後変更が入る場合はspecVersionを上げ、0.0とは別の場所に出力＆配置するように致します。

**Comment by vyv03354** [comment]
v0.53で解決したようなので閉じます。
