### ISSUE TITLE
[提案] 仕様と実装のリポジトリの分離

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#288]
リポジトリを仕様策定用のvrm-c/VRM_specification かなにか適切な名称と、実装のvrm-c/uniVRMに分けられないでしょうか？
私はそれにより仕様の議論と、実装の議論、実装に使うスキーマの分離が図れると考えます。

**Comment by hiroj** [comment]
ご提案ありがとうございます、おっしゃる通り仕様と実装を分離したほうが議論もし易いと思いますので、仕様策定のspecificationを別リポジトリに分離することに致します。

**Comment by hiroj** [comment]
https://github.com/vrm-c/vrm-specification
仕様策定用のリポジトリを作成しました、仕様についての議論はこちらで行っていただけると助かります。
