### ISSUE TITLE
【リクエスト】BlendShape等をコピーしたい、FBXを差し替えたい

### ISSUE THREAD

**Issue by KUROI-NYAN** [vrm-c/UniVRM#289]
モデルにウェイトミス等が有った場合等に、
unityで使用するデータなら、FBXを上書きするだけで修正できますが、
現状VRMは作り直しになります。

クライアントさんとのやり取りなどで
VRMの制作し直しが頻繁にあるので、
BlandShapeやSpringボーン等のコピーや
FBXの差し替えを簡単に行えるようにしていただきたいです。
切実です、ご一考下さい。

**Comment by hiroj** [comment]
![image](https://user-images.githubusercontent.com/39366194/61373409-b8e41800-a8d4-11e9-9598-100ebe8994d8.png)
SpringBoneに関しては、ヒエラルキーの構成が変わっていなければ↑を使用して復旧出来る可能性があります

**Comment by hiroj** [comment]
![image](https://user-images.githubusercontent.com/39366194/61374070-63a90600-a8d6-11e9-82a8-b29165d64beb.png)
![image](https://user-images.githubusercontent.com/39366194/61374287-f77ad200-a8d6-11e9-8f0d-4ecaa60fb5d1.png)

BlendShapeに関しては、ブレンドシェイプの構成が変わっていなければ変更前のBlendShapesアセットをとっておき、VRMBlendShapeProxyにセットすれば復旧可能です、VRMが出力しているBlendShapeアセットにはブレンドシェイプの組み合わせが記録されているだけなので再利用出来ます。
記録されている情報はMeshのindexと、そのMeshのBlendShapeのindexなので、順番が変わっていないことが条件です。

**Comment by hiroj** [comment]
ただ差し替えが面倒なのは把握していますので、何か対策を考えたいと思います。

**Comment by esperecyan** [comment]
拙作の CopyVRMSettings.cs を利用すると、ボーン構造やシェイプキーの順番に変更があった場合でも、VRMBlendShapeやVRMSpringBoneの移行が可能です。UniVRM側で対策が行われるまでのワークアラウンドとしてこちらに追記しておきます。
https://twitter.com/esperecyan/status/1139083740246708225
