### ISSUE TITLE
BlendShapeProxyの各BlendShapeClipの値について

### ISSUE THREAD

**Issue by yohawing** [vrm-c/UniVRM#29]
現状EditorGUIによって、各BlendShapeClipの値をいじれるようになっていますが、
Playモードのみ編集なのには何か理由がありますでしょうか？

可能であれば、
・Editモードでの編集と表情への反映
・AnimationClipで編集できるようにプロパティ化

などできるようになりますと、生のBlendShapeの値をいじる必要がなくなり幅が広まると思います。
ご検討のほどよろしくお願いします。

**Comment by ousttrue** [comment]
Playモードのみ編集可能なのは、編集対象がPlayモードにしか存在しないからです。
VRMBlendShapeProxy.Startで、内部的にBlendShapeMergerを初期化していてその値を操作しています。Editor時はこれが無いので操作できません。

AnimationClipで編集できるようにプロパティ化は、
操作対象がDictionary<string, float>になるので直接は難しいです。
事前定義されている、
A, I, U, E, O, Blink, Fun, Angry, Sorrow, Joy
等ならば可能なので検討します。

**Comment by yohawing** [comment]
自分でいじってみた範囲では、SlderGUIの編集不可のFlagを外して、
BlendShapeProxyにExecuteInEditMode属性を付与することで、
簡易的ではありますが、Editモード時にBlendShapeProxy経由でBlendShapeを変更することは確認できました。

Dictionaryをやめて、KeyValueペアのSerializableなクラスを作ると良さそうな気がしますが、いかがでしょうか？

**Comment by ousttrue** [comment]
BlendShapeProxyはシーンを終了したら元に戻る変更しかしないことをわかりやすくするために
エディタで動かないようにしています。

しかし、エディタで表情を設定して操作したいという需要があるとわかりました。
BlendShapeProxy操作用のTimelineのアセット的なものがよいかと思いました。

**Comment by hiroj** [comment]
0.xでは対応しない方針になります、お手数ですがPlayModeでの確認をお願いします。

**Comment by kwea123** [comment]
[こちらの記事](https://qiita.com/yuto_onizakura/items/24875ec861aa9298006f)を参考にして、別のスクリプトでpropertyを設定し、blendshapeの値と連動させれば、Timeline上でAnimationをコントロールすることができました。
だたし、Preview modeでは動かず、play modeでしか結果を確認できません。
