### ISSUE TITLE
[エディタ拡張] インポート時の Texture の Max Size

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#291]
TextureのMax Sizeが常に2048になっていますが、PNGのサイズに応じて自動的に設定できないでしょうか。

**再現方法**

1. 一辺が2048pxを超えるTextureを含むモデルを、Max Sizeを4098に設定した上でVRMエクスポート
1. エクスポートしたVRMファイルを、Unityエディタ上でインポート
2. ◯◯◯.Texturesフォルダ内のPNGファイルを確認すると、ファイル自体の一辺のサイズは2048pxを超えているが、Max Sizeは2048になっている

**期待する動作**

VRMファイルに含まれるPNGの一辺が4098pxを超えていればMax Sizeを8192に、2048pxを超えていれば4098にしてほしい。

**環境情報**

 - OS: `Windows 10`
 - UniVRM version: `0.53.0`
 - Unity version: `2017.4.28f1` `2019.1.10f1`

**Comment by hiroj** [comment]
なるほど、次のバージョンで変更を入れたいと思います

**Comment by hiroj** [comment]
https://github.com/vrm-c/UniVRM/releases/tag/v0.54.0
v0.54に修正が入りました
