### ISSUE TITLE
When I imported the vrm file, the Unity crashed.

### ISSUE THREAD

**Issue by gkegkn** [vrm-c/UniVRM#292]
When I imported the vrm file, the unity crashed.

1. Imported "UniVRM-0.53.0_6b07.unitypackage"
2. Imported my VRM file
3. See error 
![1](https://user-images.githubusercontent.com/41095198/61545913-a0265e80-aa9c-11e9-8f1d-b1a842cdc5e8.png)

4. Unity crashed
![2](https://user-images.githubusercontent.com/41095198/61545923-a4eb1280-aa9c-11e9-89f7-ad68e40cb02f.png)

 - OS: Windows 10`64
 - UniVRM version: 0.53.0
 - Unity version: 2019.3.0a3 Alpha

**Comment by hiroj** [comment]
Unity 2019.3からnew asset pipelineがデフォルトで有効になる予定があるみたいです。
new asset pipelineはまだ試験段階のようでまったく情報が無いため、asset pipeline v1に切り替えて使用してみてください。

https://forum.unity.com/threads/asset-pipeline-version-2.679366/

**Comment by hiroj** [comment]
New asset pipeline seems to be enabled by default from Unity 2019.3.
Since the new asset pipeline is still in the testing stage and there is no information at all, please switch to asset pipeline v1 and try using it.

https://forum.unity.com/threads/asset-pipeline-version-2.679366/

**Comment by hiroj** [comment]
Fixed in v0.54 because there was an error in SubAssets of AssetPiplineV2.
