### ISSUE TITLE
There is no Avatar in the Animator

### ISSUE THREAD

**Issue by gkegkn** [vrm-c/UniVRM#294]
There is no Avatar in the Animator when I Imported my VRM file.
![vrmerror](https://user-images.githubusercontent.com/41095198/61882238-2c78cb80-af4c-11e9-856f-6ca7d4fc055a.png)

OS: Windows 10`64
UniVRM version: 0.53.0
Unity version: 2019.3.0a8 Alpha
Already switched to asset pipeline v1

**Comment by hiroj** [comment]
Not yet compatible with the new asset system of 2019.3.0 Alpha.
please switch to asset pipeline v1 and try using it.
https://forum.unity.com/threads/asset-pipeline-version-2.679366/

**Comment by hiroj** [comment]
I will check it

**Comment by hiroj** [comment]
https://github.com/vrm-c/UniVRM/releases/tag/v0.54.0
fixed version released.
If there is a problem, please report again with an issue.
