### ISSUE TITLE
BlendShapeの数が多いとファイルサイズが肥大化しがちである

### ISSUE THREAD

**Issue by skishida** [vrm-c/UniVRM#295]
BlendShapeがたくさんある(かつ頂点数がそこそこある)モデルの最終的なファイルサイズのほとんどをBlendShapeが占めてしまい，ファイルサイズ制限が厳しい外部サービスにVRMモデルを登録する手間が増えてしまいます．

実際に手持ちのモデルをエクスポートし，ファイルサイズの専有割合を比べてみたところ，最終サイズ約47MBに対してBlendShapeが約35MBを占めていました．
なぜこの値になるかというと，次の計算式になります．

`18179 (モデルの頂点数) * 2 (usePosition, useNormal) * 84 (BlendShape数) * 12 (float[3]のbyte数) ≒ 35MB`

gLTFフォーマットの規定までは追いかけられていませんが，VRMの特性上必ずしも出力されたモデルにFBX等に含まれていたBlendShapeすべてを含める必要はないのかなと思います．
VRMとしてはBlendShapeProxy経由で操作されることが期待されていて，サービス利用側としてもそれ以外のBlendShapeに対応することはオプションであるという認識でいます．

**Comment by esperecyan** [comment]
Unity 2018.3 は、FBXのBlendShapeにおける法線・接線データに対応しました。

Unityエディタ上の話ですが、これに伴い、同バージョン以降を利用してGLB/VRM/VCI化を行うと、メッシュアセットのファイルサイズが大きくなるとともに、頻繁に読み込みで止まるようになりました。
https://twitter.com/esperecyan/status/1135511660293107718

Unity 2018.2以前でFBXからエクスポートした場合と同様に、既定でBlendShapeの法線・接線データを無視するようにし、オプションでこれらのデータを利用できるようにしても良いのではないかと思います。

**Comment by hiroj** [comment]
BlendShapeの法線・接線データのExportはオプションにするのは良いと思います。Unity 2018.3以降で問題が出ているとのことなので、出来れば次バージョンで対処したいところではあります。

**Comment by hiroj** [comment]
UniVRM v0.53以下のバージョンでは、法線の無いブレンドシェイプを読み込むとエラーになる箇所があったため、v0.54ではいったんこのエラー修正を入れ、Export時に法線を取り除くオプションは次回以降のバージョンで再度検討致します。

**Comment by esperecyan** [comment]
別案ですが、出力時などにブレンドシェイプを含むメッシュと含まないメッシュに分離する機能を実装できないでしょうか。

**Comment by hiroj** [comment]
![image](https://user-images.githubusercontent.com/39366194/73646263-6a556a00-46bc-11ea-9e8e-5d5fbfea783c.png)
出力時では無いですが、MeshIntegratorを使うとBlendShapeを使用していないメッシュを統合し、SubMesh(GltfのPrimitive)に変換する機能があります。（VRM/UniVRM/Editor/SkinnedMeshUtility/MeshIntegrator）

**Comment by esperecyan** [comment]
はい、メッシュの統合ではなく分離で、Cats Blender Plugin の Separate by shapes のように、ポリゴン単位で分離したいという意図でした。
https://github.com/michaeldegroot/cats-blender-plugin#model-options

#### 変換前
- アバター
	+ スキンドメッシュ
		* サブメッシュ🟠【ブレンドシェイプあり】
		* サブメッシュ🟢

#### 変換後
- アバター
	+ スキンドメッシュ
		* サブメッシュ🟠-1【ブレンドシェイプあり】
	+ スキンドメッシュ_noshapes
		* サブメッシュ🟠-2
		* サブメッシュ🟢

**Comment by hiroj** [comment]
なるほど、分離するUlitityの追加を検討してみます。

**Comment by ousttrue** [comment]
0.56の作業予定

## FBX等に含まれていたBlendShapeすべてを含める必要はない

* BlendShapeClip から参照されていない BlendShape をスキップする
* Preset が Unknown のものも対象から外す

のオプションを追加して BlendShape の数を減らせるようにします

**安全なオプション**

## sparse

GLTF仕様のsparseアクセッサーの有効化

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#sparse-accessors

メッシュの分割方法によりますが容量削減の効果があります。
これも、受け入れ側のアプリケーションのローダーが対応している必要がありますが、
UniVRMはだいぶ前のバージョンからロードできます(2018の夏実装)。 

**UniVRMと別の実装ではロードできない場合があります**

## UniVRM v0.53以下のバージョンでは、法線の無いブレンドシェイプを読み込むとエラーになる箇所があった

* BlendShapeの法線・接線データを削除するチェックボックスを追加します。ただし、受け入れ側のアプリケーションがUniVRM v0.53以下はエラーでロードに失敗します。利用先の、UniVRMのバージョンに注意してください

**UniVRM v0.53以下はロードできない**

## メッシュ分割
Unityシーンの構成変更のUtilityとして存在した方がよさそうです。
VRM作らないけど、ツールだけ使うという便利さがあります。

**Comment by hiroj** [comment]
ブレンドシェイプを削るオプションを追加しました、v0.56のバージョンから使用出来る予定です。
メッシュ分割に関しては別のissueを立てます。
