### ISSUE TITLE
Error in VRMExport after IL2CPP build

### ISSUE THREAD

**Issue by hiroj** [vrm-c/UniVRM#297]
* Add AOTCall
* Manually call the part where generics were used in the inner class
* UniJSON.JsonObjectValidator.GenericValidator.ObjectValidator._CreateFieldValidator
* UniJSON.JsonObjectValidator.GenericValidator.Serializer._CreateFieldValidator
* UniJSON.FormatterExtensionsSerializer.SerializeArray

**Comment by saturday06** [comment]
細かいですが
```
UniJSON.JsonObjectValidator.GenericValidator.ObjectValidator._CreateFieldValidator
```
は
```
UniJSON.JsonObjectValidator.GenericValidator.Serializer._CreateFieldSerializer
```
が正しそうです。

**Comment by saturday06** [comment]
IL2CPPでの動作対応は、私もこちらのコミットでも確認しています。https://github.com/saturday06/UniVRM/pull/1/commits/0bb8aefd7a9bd20d0801f56b65727276de682d31

ちょっとソースコードのより良い組み方が思いつかないまま放置していてしまいプルリクエストを躊躇していたのですが、iOSとAndroidでの動作確認はしていますのでこちらも参考にしていただければ幸いです。

**Comment by hiroj** [comment]
ありがとうございます、参考にさせていただきます。
JsonObjectValidator辺りはジェネリクスがネストしていて読み辛いため何とかしたいところではあります・・・。

**Comment by saturday06** [comment]
ちょっと自信はないのですが、自分が取り組んだときは下記のようなことを考えていました。。。

- _CreateFieldValidator と _CreateFieldSerializer はprivateメソッドなので、これをinternalにするなどすればAOTCall.g.csに含められるかも？
- UniJSONはどこまでUnityのオブジェクトのシリアライズに対応するべきなのかを考える必要があるかも？今回は関係無さそうなRectとかQuaternionも対応すべき・・・？
- ジェネリックスの組み合わせが肥大化してコンパイル後のバイナリサイズが肥大化するかもしれない？

しかし、私としても、もしかしたらもっと読みやすくできるしれない・・・？とか妄想だけはしていました・・・（手は動かなかった・・・）

あと、書き忘れていたのですが、上記のコミットは第2回VRM勉強会でnontan-rhさんにより紹介されていたコミットになります。

**Comment by hiroj** [comment]
* Genericsを使用しないシリアライザコードを事前生成する手法を検討中です。
* 出力されるシリアライザは愚直なコードになってしまいますが、Genericsを使った場合にランタイムでT型が展開されいないことが発覚してエラーになるよりも、ビルド時に無いことが分かるほうが堅牢ではないかと思いました。
* Genericsを使用する場合でも、T型を空呼びするAOTCallを事前生成する必要があるため、生成コストは変わりません。
* 既存のシリアライザを置き換えるのではなく、追加で選択できるようにします。

#298

**Comment by saturday06** [comment]
解説ありがとうございます。一点だけ懸念点がありまして、

> 既存のシリアライザを置き換えるのではなく、追加で選択できるようにします。

既にシリアライザは通常版とExperimental版の2種類あり、それが3種類になるのは厳しいと思っています。できればIL2CPP版で統一、厳しいようなら古い2つに `@Obsolete` をつけていただきたいです。

**Comment by hiroj** [comment]
シリアライザが乱立するのは確かに良くないため、最終的に統一させる予定です。
v0.54ではいったん古いものをObsoleteにし、問題なさそうであればv0.55で完全に置き換えることにします。

**Comment by hiroj** [comment]
#341 v0.54では以下のようにしました
* 通常版 はObsolete.
* ExperimentalだったUniJson(Refrection serializer ) をデフォルトに変更
* Experimentalを指定するとGenerated serializer を使用する
