### ISSUE TITLE
GLTFランタイムロードにおいて、RenderingModeのFadeが効かなくなった？

### ISSUE THREAD

**Issue by fantom1x** [vrm-c/UniVRM#299]
**バグについて**

SSIA
以前のバージョン（UniVRM0.49）では普通に Fadeモードが機能していたのに対し、現バージョン（UniVRM0.53）ではFadeモードを使っているマテリアルは透過しなくなってます。
ちなみにエディタ上では普通に透過してます。ランタイム時だけみたいですね。

**再現方法**

何でも良いので、Fadeモードを使っている素材をランタイムでロードする。

**期待する動作**

UniVRM0.49のスクリーンショットのように透過できる（この素材はPlaneオブジェクトでFadeモード[StandardShader]が使われてました）。

**スクリーンショット**

●UniVRM0.49 でロードした場合
![RenderMode_Fade_UniVRM0 49](https://user-images.githubusercontent.com/8603961/62645741-c8142e00-b987-11e9-9404-2e0da772ff46.jpg)

●UniVRM0.53でロードした場合
![RenderMode_Fade_UniVRM0 53](https://user-images.githubusercontent.com/8603961/62645776-df531b80-b987-11e9-9739-71ba4d058378.jpg)

**環境情報**

 - OS: Windows 10
 - UniVRM 0.53

**Comment by hiroj** [comment]
確認致します。

**Comment by hiroj** [comment]
StanderdマテリアルでFadeを使用したglbを作成し、RuntimeLoadしてみましたが同じ現象を再現出来ませんでした。よろしければ該当の現象が出るモデルファイルを頂けると助かります。

**Comment by fantom1x** [comment]
あ、そう言えば GLTF と書き忘れてました。:bow:
使ったモデルは以下のモデルです。
https://sketchfab.com/3d-models/vr-alien-forest-with-download-a82890cdeb9f4032aba416547711a3d2

以前は普通に表示されたんですけどね…。

**Comment by hiroj** [comment]
![image](https://user-images.githubusercontent.com/39366194/70693583-130ccc00-1d01-11ea-863e-3e1b59c05e91.png)
Edit > ProjectSettings > GraphicsのAlways Included shadersにStanderdを指定してビルドすると治る可能性があります。
ビルド後のStanderdシェーダは、最適化のためにシーン内で使用しているStanderdシェーダのパラメータの組み合わせ以外は削られるようになっていて、それ以外は正常に動作しない可能性があります。
Always Included shadersにStanderdを指定すると全ての組み合わせをビルドしますが、ビルド時間がかなり長くなってしまうことに注意してください。

**Comment by hiroj** [comment]
#244 
同じようなissueがありましたので参考になれば

**Comment by fantom1x** [comment]
なるほどです。最適化の問題でしたか…。
WebGLやAssetBundleでも似たような問題にぶつかったことありますが、
http://fantom1x.blog130.fc2.com/blog-entry-237.html#assetbundle_dummy
なんらかダミーを仕込んでおく方法でも対処できるかもですね。
Always Included shadersにStanderdを入れるのはビルド時間が超絶に伸びるのと、ファイルサイズが巨大になった経験があるので、スマホには向いてないかもですね…。
まぁ、以前はなぜかできていたので、また色々試して研究してみます(笑)。

**Comment by fantom1x** [comment]
ちょっと試しに↑の方法でやってみましたが、解決しました。

具体的なやり方は、
・Create＞Material で新規作成したマテリアルを Standard シェーダの Fade モードにしておく
・ダミーのシーンを作る（File＞New Scene）
・ダミーのスクリプトを作り、インスペクタで Material を設定できるようにし、ヒエラルキーに配置する
・先ほど作った Fade モードのマテリアルをインスペクタでアタッチする
・Build Settings... でダミーのシーンを追加しておく

これでOKです。
内容的には以下の記事と同じですね。
http://fantom1x.blog130.fc2.com/blog-entry-237.html#assetbundle_dummy
（※記事は WebGL や AssetBundle を対象にしているが、最適化という問題では同じ）

ダサイ方法ですが、言うなれば「最適化されて困るなら、無理やり参照して最適化させない作戦」ですね(笑)。同じように「Transparent」や「Cutout」なども作っておけば、最適化で削られることはないでしょう（ちなにみスクリプトから必要なコンポーネントを参照しておく方法はテラシュールブログでも紹介されてます）。

あと、この方法を使えば、ビルド時間もファイルサイズもほぼ変わらないというのも利点です（せいぜい増えても1MBくらいなので、誤差の範囲ですね）。何かの記事で見たことありますが、ビルトインシェーダを Graphic setting 等に追加して、ビルドが長くなり、ファイルサイズが増えるのは、「別物」として複製物が作られてしまっている可能性が高いので、あまり良くはないかもですね（確かに解決はするかもだが、内部的には同じ素材が２重に含まれてしまう？）。

まぁ、以前は私のプロジェクトか、もしくはMToonなど、何らかが Fade を参照していたのかも知れません（特に意識はしてなかったが使えた）。

とにかく解決できたので、ありがとうございました。もっとスマートな方法もあるかも知れませんが、とりあえず利用できれば良いので、方法を共有しておきます。
