### ISSUE TITLE
GLTF Import Error:System.ArgumentException: Offset and length were out of bounds for the array...

### ISSUE THREAD

**Issue by Stephengower** [vrm-c/UniVRM#300]
**Describe the bug**

When I import the attached MedievalFantasyBook GLTF, I'm seeing the following error:
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.

This GLTF comes from Sketchfab (Creative Commons, author is 
Pixel), and the Sketchfab Unity plugin can open this without this error.  Can you please take a look? thanks.

[MedievalFantasyBook.zip](https://github.com/vrm-c/UniVRM/files/3517584/MedievalFantasyBook.zip)

**Comment by hiroj** [comment]
Thanks for the report, I will fix it in the next version.
