### ISSUE TITLE
VRMを出力する際の色情報について

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#301]
**バグについて**
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughnessbasecolorfactor
gltfマテリアルの仕様では色情報について、リニアであるとされています。
しかし、VRMに出力されている色情報は、gltf、VRM拡張共にカラーピッカーそのままの値、つまりsRGB空間で保存されています。

**再現方法**
MToonの色設定を(0.5,1,1,1)でVRMを出力します。
VRM出力時に期待される色情報はおおむね（0.21586,1,1,1）になりますが、gltf、VRM拡張共のjsonには（0.5,1,1,1）で記録されています。

**環境情報**

 - OS: [`Windows 10`]
 - UniVRM version: [`0.53.0`]

**Comment by FMS-Cat** [comment]
インポート側もリニアとして入力する必要がありそうですね。

**Comment by hiroj** [comment]
ご報告ありがとうございます、詳しく確認したところ以下のような状態になっていました。

### 通常の Color Property の RGB Channel
* UnityのMaterial に記録されている値はsRGBなので、 sRGB2Linear で変換して書き込む必要がある
* MToon該当: Lit Color, Shade Color, Outline Color

### HDR Attribute 付き Color Property の RGB Channel
* このAttribute が付いている場合はUnityのMaterial に記録されている値がLinearになっているため、変換せずに書き込む
  * Material に記録されている値 0.5 (Linear)
  * Inspector 上のプレビュー 0.73 (sRGB) 
  * Shader に渡される値 0.5 (Linear)　（無変換）
* MToon該当: Emission Color, Rim Color

### 普通/HDR の Alpha Channel
* どちらの場合もLinearであったため変換なしで書き込む

この件の対応として、gltfの領域に書き込まれているColor 値に関しては次のUniVRMバージョンで修正し、VRM(MToon)の領域に関しては specification=0.0 では今の状態を仕様とし、Material拡張対応(#175)と合わせて1.0で修正するissueを切ります。

**Comment by hiroj** [comment]
#339
MainColorをExportする時にLinearに変換するように修正しました

**Comment by hiroj** [comment]
その他のlinear変換対応はv1.0で予定しています
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_materials_mtoon-1.0_draft/MToon_comparision.md
