### ISSUE TITLE
Loading uses too much memory

### ISSUE THREAD

**Issue by tiboretk** [vrm-c/UniVRM#303]
**Describe the bug**

Loading several glft models that reference same Albedo, NormalMap and SpecularMap load each texture separately for each model so multiple instances of same textures end up in memory.
The textures on a disk use around 300-400kB while in memory each of them uses 32MB leading to a several GB of memory usage for dozen of models.

**To Reproduce**

Load several different models that reference same textures. Textures are not reused yet they get loaded each time on different model load.

**Expected behavior**

If different gltf models reference same texture they should reuse it and optimally load only one shared texture among them.

**Screenshots**

![image](https://user-images.githubusercontent.com/54531333/63680287-973f5000-c7f3-11e9-8819-ae534b641ce8.png)

**Environments (please complete the following information):**

 - OS: [e.g. `Windows 10`]
 - UniVRM version: [e.g. `0.52.0`]

**Comment by tiboretk** [comment]
Solved! 解決済み:)
I solved the issue by updating ProcessOnMainThread() to store texture references.

**Comment by tiboretk** [comment]
Solved! 解決済み:)
I solved the issue by updating ProcessOnMainThread() to store texture references.

**Comment by hiroj** [comment]
If you want to share resources, try extending ITextureLoader.
