### ISSUE TITLE
8 critical errors in UniVRM-0.53.0_6b07 on package import

### ISSUE THREAD

**Issue by Loupyboy** [vrm-c/UniVRM#307]
**Describe the bug**

Error type 1/2 (CS0433):

`Assets\VRM\DepthFirstScheduler\Schedulable.cs(227,23): error CS0433: The type 'Task<TResult>' exists in both 'System.Threading, Version=1.0.2856.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

`Assets\VRM\DepthFirstScheduler\Schedulable.cs(232,23): error CS0433: The type 'Task<TResult>' exists in both 'System.Threading, Version=1.0.2856.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

`Assets\VRM\UniVRM\Scripts\Format\VRMImporter.cs(88,23): error CS0433: The type 'Task<TResult>' exists in both 'System.Threading, Version=1.0.2856.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

`Assets\VRM\UniVRM\Scripts\Format\VRMImporter.cs(96,23): error CS0433: The type 'Task<TResult>' exists in both 'System.Threading, Version=1.0.2856.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

`Assets\VRM\UniVRM\Scripts\Format\VRMImporter.cs(104,29): error CS0433: The type 'Task<TResult>' exists in both 'System.Threading, Version=1.0.2856.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

`Assets\VRM\UniGLTF\Scripts\IO\ImporterContext.cs(484,22): error CS0433: The type 'Task<TResult>' exists in both 'System.Threading, Version=1.0.2856.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

Error type 2/2 (CS1983):

`Assets\VRM\UniVRM\Scripts\Format\VRMImporter.cs(104,46): error CS1983: The return type of an async method must be void, Task or Task<T>`

`Assets\VRM\UniGLTF\Scripts\IO\ImporterContext.cs(484,39): error CS1983: The return type of an async method must be void, Task or Task<T>`

**To Reproduce**

1. Load Unity 2018.4.0f1 Personal
2. Import unrelated asset packages (Bolt and Dialogue System)
3. Import UniVRM (versions 51, 52 or 53)
4. Errors everywhere

**Screenshots**

![image](https://user-images.githubusercontent.com/54676216/63950755-e0560500-ca7c-11e9-8e74-332786248be6.png)

**Environments:**

 - OS: Windows 10 x64
 - Unity Version: 2018.4.0f Personal
 - UniVRM version: UniVRM-0.53.0_6b07

**Additional context**

Assets loaded: Bolt, Dialogue System, 3D models.

**Comment by hiroj** [comment]
It seems that "Task" and "System.Threading.Task" that other libraries have are in conflict.
If you are not using a package that contains ADF (Assembly Definition File), you may be able to solve it by using it.
https://github.com/vrm-c/UniVRM/releases/tag/v0.53.0
packageName: UniVRM.asmdef-0.53.0_6b07.unitypackage

**Comment by Loupyboy** [comment]
> 
> 
> It seems that "Task" and "System.Threading.Task" that other libraries have are in conflict.
> If you are not using a package that contains ADF (Assembly Definition File), you may be able to solve it by using it.
> https://github.com/vrm-c/UniVRM/releases/tag/v0.53.0
> packageName: UniVRM.asmdef-0.53.0_6b07.unitypackage

I've tried importing both the standard package and the ASMDEF package (as the ASMDEF alone isn't working, I guess it's more of an addon to the base package, right?). Anyway, the errors have been reduced to only two CS0433: 

> The type 'Task<TResult>' exists in both 'System.Threading, Version=1.0.2856.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

Errors are said to be located on
`public static Task<T> ToTask<T>(this Schedulable<T> schedulable)`
and
`public static Task<T> ToTask<T>(this Schedulable<T> schedulable, IScheduler scheduler)`

As the plugin is already using System.Threading.Tasks, is there a way to solve this? Do you think it's a bug on my end or is it related to the asset itself? I'll try to install it on a blank project.

**Comment by Loupyboy** [comment]
Issue documented and fixed by the Bolt team. Closing the issue as it's not an UniVRM-related issue.
