### ISSUE TITLE
textureのmap類のカラースペースについて

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#309]
**バグについて**
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughnessmetallicroughnesstexture
上記のようにgltfのmap系テクスチャはテクスチャの値はリニアとして扱いますが、MToonのmap系テクスチャ（ex: outlinewidth_texture.shadinggrade_texture）はsRGB->リニア変換された値がシェーダに渡されているように見えます。
これは仕様でしょうか。
<img width="963" alt="無題" src="https://user-images.githubusercontent.com/3232308/64033693-fc929880-cb87-11e9-9597-6cbe4a64e6ae.png">

**再現方法**
[bake_linear.zip](https://github.com/vrm-c/UniVRM/files/3560544/bake_linear.zip)
MToonのshaderのoutlinewidth、widthscale_maxdistanceの上限、値をかなり大きくするようにすると分かりやすくなります。
例: 動作の再現させる手順:
![Untitled](https://user-images.githubusercontent.com/3232308/64032961-775ab400-cb86-11e9-9a38-45b246a74372.png)
上記は左から右へリニアに0-1のグラデーションを記録したテクスチャです。
これをoutlinewidth_textureに割り当てた上記zipのvrmを読み込ませると、アウトラインが上から下に曲線になります。

**期待する動作**
期待するアウトラインは上から下に直線に斜めになることです。これは、テクスチャ設定のsRGB(Color texture)のチェックを外すことにより達成されます。

**環境情報**

 - OS: [ `Windows 10`]
 - UniVRM version: [`0.53.0`]

**Comment by FMS-Cat** [comment]
自分の見解は、ノーマルマップなどと同等に、リニアのテクスチャとして読み込まれるべきだと思います。

**Comment by hiroj** [comment]
同じくリニアテクスチャとして読み込まれるべきだと思うので修正致します

**Comment by iCyP** [comment]
破壊的変更になると思いますが、v0.54対応で良いのですか？　@Santarh

**Comment by Santarh** [comment]
破壊的変更が許されるのであれば、その対応でも良いと思います。

色空間の話はややこしいので整理のためにまず前提を言います。
まず、シェーダの実装は sRGB や Linear といった特定の色空間を要求しません。
特定の色空間を要求するのは、画像ファイルを解釈してシェーダに渡すシステム側です。

その上で本来であれば、テクスチャの設定で `sRGB` フラグを外せばシステムの解釈を変更して
リニアテクスチャを渡すことが現状でもできます。（ @iCyP さんの言う通りです）
ただもちろんこの場合、sRGB2Linear 変換で暗部の値の精度を失うことにはなります。

ここで確認したところ、UniVRM の現在の実装は MToon に割り当てられているテクスチャの
`sRGB` フラグを無視して出力しているバグがあるようです。つまり、テクスチャ製作時に
色空間の変換を考えて制作しなければならないということです。これはたしかに不健全なので
テクスチャの `sRGB` フラグを加味した出力をするべきだと思います。

ただもちろん前述したように、この手法は値の精度を失ってしまうので、MToon のパラメタ
テクスチャは Linear を要求する、としてしまったほうが良いかもしれません。破壊的変更が
許されるのであれば、ですが。

**Comment by FMS-Cat** [comment]
glTFの仕様では、色に相当するテクスチャについてはsRGBで予めエンコードされているもの、その他のmetallicRoughnessやnormalMapなどのテクスチャについてはlinearとして収録するよう定義されています。
MToonについても、各テクスチャごとにどちらで収録すべきかを仕様として明示すると良いと思います。

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughnessbasecolortexture
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughnessmetallicroughnesstexture

**Comment by hiroj** [comment]
改めて調査したところ、EditorでExportした場合に限りUnityEditor.AssetDatabaseを使って直接pngファイルを入手してバイト列を書き込むようになっていたため、sRGBフラグによってUnityがテクスチャに変換をかけていた場合でも無視されるようになっていました。

https://github.com/vrm-c/UniVRM/blob/b8273cb430fef7b20de6a330cb75cb22e2e9b19c/Assets/VRM/UniGLTF/Scripts/IO/TextureIO.cs#L122

pngを直接入手して書き込む挙動を止めて、Runtimeと同じくTextureからコピーするようにすることで表示は直線になり正しくなりました。

![image](https://user-images.githubusercontent.com/39366194/64110044-fe44a200-cdbb-11e9-8436-797071f41a86.png)
上記は該当箇所を修正後、テクスチャ設定をsRGB = falseにした状態でExportしたものを再度Importしたもの。

もちろん各テクスチャごとにsRGB or Linearを仕様で明示して処理するのがベストですが、破壊的な変更になってしまうため、対処案としましては v0.54 では Texture からコピーして Texture Asset の sRGB フラグを考慮して出力する対応をします。
そして今後、 MaterialExtensionの導入時にmap系テクスチャがLinearであることを定義する形にしたいと思うのですがいかがでしょうか。

**Comment by iCyP** [comment]
それはリニアの画像をsRGBで解釈したときにでリニア0-1になるように画像変換しているもので、記録されている画像はリニアでなくimport時にsRGB->リニア変換をかけた状態がリニアになっている物であるので、gltfが持っているmapとしては正しくない修正ではないでしょうか？
言い換えると、uniVRM上でのみ正しくなり、他のプラットフォームでは逆にuniVRM0.54以降のVRMのmapﾃｸｽﾁｬに対してsRGB->Linearを掛けないといけなくなるのではないかということです。

**Comment by FMS-Cat** [comment]
本件、UVスクロールを制御するMaskテクスチャでも確認しました。
画素値としてリニアなテクスチャを入力しましたが、アニメーション速度の変化がリニアでないよう見えます。

![image](https://user-images.githubusercontent.com/7824814/64148583-9abf8080-ce5e-11e9-84e5-122721f98e78.png)

**Comment by hiroj** [comment]
すみません説明不足でした、この修正案はRuntiemExportとEditorExportの挙動を合わせるためのものであり、gltfが持っているmapとしては正しくなっていなっておらずsRGBで書き込まれているのはその通りです。（UniVRMを使用してRuntimeExportしたモデルはすでにTextureからsRGBでコピー＆書き込みする処理を通っており、差を無くす意図の修正でした）
1.0までは破壊的変更は避けたいため、この問題は 1.0 で修正を行う方針にします。

**Comment by hiroj** [comment]
もう少し調べたところ、TexturePropaty名が _MetallicGlossMap, _BumpMap, _OcclusionMap, 以外のテクスチャは全てsRGBとしてエクスポート＆インポートされていました、つまり現状MToonが扱っているmap系テクスチャは_BumpMap以外はsRGBのテクスチャとして扱われているようです。

**Comment by iCyP** [comment]
ランタイムエクスポートは(ユーザーがVRMファイルをローカルに置けるアプリでは)VRoid studioとセシル変身アプリがおそらく使っていると思います。これらは私の知る限りVRMインポートを現時点で持たないはずなのでテクスチャ変換を介することは現仕様でも問題ないと考えます。
　EditerエクスポートはユーザーがVRMのモデル改変のため繰り返し行う可能性があるので、そのたびテクスチャを変換するとそのたびmapの中階調が明るくなり続けてテクスチャが破綻します。
　従って、現時点で仕様を揃える修正は逆に悪影響となると考えますので、1.0での修正をお願いします。

**Comment by hiroj** [comment]
確かに出し入れを繰り返すと変換がかかるため良くないですね。では現状の挙動はそのままにして 1.0 にて修正を行うことに致します。

**Comment by hiroj** [comment]
spec v1.0および、v1.0draft実装にてこれらの問題に対処しました。問題が再度発見された場合は各リポジトリのissueに報告をしていただけると助かります。
https://github.com/vrm-c/vrm-specification
https://github.com/vrm-c/UniVRM_1_0
