### ISSUE TITLE
vertex NORMAL attribute is not Normalized

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#313]
**バグについて**
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes
には
NORMAL | "VEC3" | 5126 (FLOAT) | Normalized XYZ vertex normals
頂点法線は正規化、つまり長さが１になるよう正規化されていると記載されているが
https://hub.vroid.com/characters/4899514063994461875/models/4334462906997839645
上記モデル（Vroid studio 0.73で出力したモデルをuniVRM0.53でin-outしたもの）の法線属性を下記コード
```python
            for n in pymesh.NORMAL: #pymeshはバイナリを単純に数値に変換して属性名で格納したもの
                l = Vector(n).length
                if l > 1.1 or l < 0.9:
                    print(l,n)
```
[NORMAL_DUMP.txt](https://github.com/vrm-c/UniVRM/files/3569622/NORMAL_DUMP.txt)
eg:
```
長さ：法線値(gltf:x,y,z)
1.1597291179396134 [0.3686876595020294, 1.0093015432357788, 0.4362927973270416]
1.1182365527247409 [-0.3020893633365631, 0.7804145812988281, -0.741719663143158]
1.1639392230663237 [0.6574106812477112, 0.941243588924408, 0.19137980043888092]
...
0.0 [0.0, 0.0, -0.0]
0.0 [0.0, 0.0, -0.0]
...
```
で出力すると、添付ファイルのとおり、長さが1.1以上か0.9未満に限定しても大量に出現しています。

**期待する動作**

長さ１に正規化された法線属性の出力

**環境情報**

 - OS: [ `Windows 10`]
 - UniVRM version: [`0.53.0`]

**Comment by iCyP** [comment]
[normal_2_2_2_from_uniVRM053.zip](https://github.com/vrm-c/UniVRM/files/3569740/normal_2_2_2_from_uniVRM053.zip)
法線属性をすべて[-2,2,2]で埋めた平面だけのVRMファイルを用意しました。
これをimportしてVRM出力されたときに期待される法線属性はすべて[-0.3333..., 0.3333..., 0.3333...]
となっていることです

**Comment by hiroj** [comment]
ありがとうございます、こちらも確認しましたところほとんど正規化されていなかったため修正を入れます

**Comment by hiroj** [comment]
#314の修正後に頂いたモデルをexportしたところNormalizedされた値になっていました、ご確認頂けると助かります。（[-2,2,2]だと[-0.5773503, 0.5773503, 0.5773503]ですよね・・・？）

**Comment by iCyP** [comment]
例値について、その通りです。間違っていました。申し訳ありません。

**Comment by iCyP** [comment]
https://github.com/hiroj/UniVRM/tree/fix_meshNormalExport
https://github.com/Santarh/MToon/tree/master
にて出力値が0.9999999701976772 [-0.5773502588272095, 0.5773502588272095, 0.5773502588272095]
であることを確認できました。

が、[0,0,0]の場合、[0,0,0]のまま出力されてしまうようです。（このようなモデルが存在することが問題ではあるのですが…。
[normal_0_fromUni190904.zip](https://github.com/vrm-c/UniVRM/files/3570286/normal_0_fromUni190904.zip)
検証用モデルを添付します。
法線[0,0,0]を含むモデルの法線正規化については(どこを向いているか分らないので)、1.0での仕様定義、変更としたほうが良いと思います。方策としては、面法線からの計算か、固定値のどちらかになると思います。

**Comment by hiroj** [comment]
法線[0,0,0]の件了解いたしました。
ひとまず今回のNormalizedの処理を次のバージョンに入れ、[0,0,0]の場合にどのように扱うかは仕様を決めて1.0で対応する内容のissueを別に作ることに致します。
