### ISSUE TITLE
AliciaSolid_vrm-0.40 validation fails

### ISSUE THREAD

**Issue by vpenades** [vrm-c/UniVRM#315]
**Describe the bug**

AliciaSolid_vrm-0.40.vrm is set as the default example of vrm, but when I check it with [Khronos GLTF Validator](http://github.khronos.org/glTF-Validator/) it gives some errors related to morph targets.

**To Reproduce**

1. Open [Khronos GLTF Validator](http://github.khronos.org/glTF-Validator/) 
2. Drag AliciaSolid_vrm-0.40.vrm into it.

**Expected behavior**

VRM files should be valid glTF files, so the number of morph targets and morph weights on each mesh must always be the same.

**Environments (please complete the following information):**

 - OS: `Windows 10`
 - UniVRM version: `0.40`

**Additional context**

I only checked the file AliciaSolid_vrm-0.40.vrm , which I assume has been created with UniVRM 0.40, so I don't know if this has been fixed in newer versions, if that's the case, it would be nice if AliciaSolid_vrm-0.40.vrm is replaced with a newer version with morph targets fixed.

**Comment by hiroj** [comment]
https://github.com/vrm-c/UniVRM/commit/b989972883d3f638ff112449eccfd90f55638843
We have updated the model, please try again.
If you have a problem, please open a new issue.
