### ISSUE TITLE
StackOverFlowException with deep nested JSON in VRM

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#318]
**バグについて**
深くネストされたJSONを含むVRMをUnity Editorにインポートすると、StackOverFlowException
が発生する。またはUnityEditorがクラッシュする。Runtime importするアプリケーションもクラッシュする。（一部確認済）
**再現方法**
深くネストされたJSONを含むVRM（下記）をUnity Editorにインポートする。以上。
[deep_nest.zip](https://github.com/vrm-c/UniVRM/files/3595735/deep_nest.zip)

普通にJSONをパースしても大概は失敗すると思うので、Stringで出力するか、直接
バイナリを読むのが良いと思いますが、中身は通常のVRMのJSONの後ろに{"a":{"a":{"a":{"a":{"a":{"a":{"a":{"a":{"a":{"a":{"a":{"a":{"a":1}}}}}}}}}}のような（上記の中身はもっとネストが深い）ゴミがくっ付いているだけです。
**期待する動作**
　uniVRMにおけるStackOverFlowExeptionのハンドリング、かつ仕様に必要ない程の深いネスト構造に対する対応。（読まない、例外送出など
　また、VRM処理系の実装上における注意点として挙げられると尚よいと考えます。仕様としてJSONの深さを決めるのは入力に対する弱点となるので、実装者に対する留意事項となるべきと考えます。

**環境情報**
 - OS: [e.g. `Windows 10`]
 - UniVRM version:  `0.53.0`]

**追加の状況・背景**
VRM-Cのメールアドレスにこの問題について確認したところ、リポジトリのissueでどうぞという事でしたので、それに従いこのissue建てました。

　webで普通にユーザ環境で上記VRMに含まれているJSONをそのままJson.Parseするとパースに失敗してアップロードできないので、変に最適化していないサービスには致命的ではない。
　逆に最適化している某サイトでは、アップロードできて、かつuniVRMを使っているだろう所でアプリケーションがクラッシュしたり、サーバサイド処理しているらしき某サイトでは、サーバサイド辺りでエラーを起こしているのかアップロード通知がこないことがあった（アップロードできていなかった）。

**Comment by hiroj** [comment]
返答遅れてしまい申し訳ありませんでした、何処でエラーが出ているか調査致します。

**Comment by hiroj** [comment]
JSONパース時にStackOverFlowExeptionをハンドリングし、パースに失敗したことをExceptionでthrowするようにしました。

**Comment by iCyP** [comment]
ご対応ありがとうございます。
