### ISSUE TITLE
Exporting primitives with different colors exports with only one color

### ISSUE THREAD

**Issue by tiboretk** [vrm-c/UniVRM#322]
**Describe the bug**

Exporting Unity Primitives with different colors exports them with same color.

**To Reproduce**

Create two primitives cube1 and cube 2 and attach them to a common parent testParent.
Click Play and export the parent by clicking UniGLTF-1.27->Export.
Stop Play and import the exported model.
Both cubes are green.

```
            GameObject testParent = new GameObject("test");

            GameObject cube1 = GameObject.CreatePrimitive(PrimitiveType.Cube);
            cube1.transform.SetParent(testParent.transform);
            cube1.transform.position = Vector3.one;
            MeshRenderer cubeRenderer = cube1.GetComponent<MeshRenderer>();
            cubeRenderer.material.color = Color.green;

            GameObject cube2 = GameObject.CreatePrimitive(PrimitiveType.Cube);
            cube2.transform.SetParent(testParent.transform);
            cube2.transform.position = Vector3.one + Vector3.one;
            MeshRenderer cubeRenderer1 = cube2.GetComponent<MeshRenderer>();
            cubeRenderer1.material.color = Color.blue;
```

**Expected behavior**

cube1 should be green while cube2 should be blue.

**Screenshots**

![image](https://user-images.githubusercontent.com/54531333/66756615-b3c64300-ee9a-11e9-8f01-cc3c9790f45b.png)

![image](https://user-images.githubusercontent.com/54531333/66756495-719d0180-ee9a-11e9-917d-7b67dbf70932.png)

**Environments (please complete the following information):**

 - OS: Windows 10, Unity 3D 2018.4.9f1
 - UniGLTF version: 1.27

**Comment by hiroj** [comment]
In the current version, SharedMaterial is exported, and InstanceMaterial export is not supported. Try creating individual materials in advance and changing the value of SharedMaterial.

**Comment by tiboretk** [comment]
I created new Materials and assigned different names and colors but result is same.
Before export one cube has material blue1 while other green1. After export both have green1 with same instance -553608.

```
            GameObject testParent = new GameObject("test");


            Material material1 = new Material(Shader.Find("Standard"));
            material1.name = "green1";

            material1.color = Color.green;

            GameObject cube1 = GameObject.CreatePrimitive(PrimitiveType.Cube);
            cube1.transform.SetParent(testParent.transform);
            cube1.transform.position = Vector3.one;
            MeshRenderer cubeRenderer1 = cube1.GetComponent<MeshRenderer>();
            cubeRenderer1.material = material1;
            cubeRenderer1.sharedMaterial = material1;


            Material material2 = new Material(Shader.Find("Standard"));
            material2.name = "blue1";

            material2.color = Color.blue;

            GameObject cube2 = GameObject.CreatePrimitive(PrimitiveType.Cube);
            cube2.transform.SetParent(testParent.transform);
            cube2.transform.position = Vector3.one + Vector3.one;
            MeshRenderer cubeRenderer2 = cube2.GetComponent<MeshRenderer>();
            cubeRenderer2.material = material2;
            cubeRenderer2.sharedMaterial = material2;
```

![image](https://user-images.githubusercontent.com/54531333/66816503-74e7ca00-ef3a-11e9-8d6d-26d3d7c1e500.png)

**Comment by hiroj** [comment]
The one exported by UniGLTFv1.27 had a bug when both nodes had the same MeshIndex number and multiple renderers were using the same MeshInstanceID.
UniGLTF used in this repository seems to have fixed the problem, so try changing the package.

**Comment by tiboretk** [comment]
Thanks for the reply. I changed to latest version of UniVRM and export works. I even didn't had to create new materials and set them to sharedMaterial, I just updated current material color.
