### ISSUE TITLE
法線の転写情報がMtoonで反映されない

### ISSUE THREAD

**Issue by Sugi-Chanchan** [vrm-c/UniVRM#327]
**バグについて**

Mtoonの仕様が新しくなってからRendering Mode:Opaqueで法線を転写した3Dモデルをレンダリングすると影の付き方がおかしくなります.
**再現方法**

1. 法線を転写させた3Dモデルをunityに取り込む
2. マテリアルを作成, シェーダーをMtoonにする
3. Shade Colorを変えて陰影をつけると, rendering modeがOpaqueとCutoutのときには法線の転写情報が反映されていないことが確認できます.
transparentとtransparentWithZwriteでは法線の転写情報が反映されています

**期待する動作**
MtoonのRerendering Mode: OpaqueとCutoutでの影の付き方がversion0.51以前に戻ること

**スクリーンショット**

ある場合は、問題の説明に役立つスクリーンショットを追加してください。

Rendering Mode : Opaque
![スクリーンショット (4)](https://user-images.githubusercontent.com/38928279/67763564-567de480-fa8b-11e9-8805-84a68970520f.png)

Rendering Mode : TransparentWithZwrite
![スクリーンショット (5)](https://user-images.githubusercontent.com/38928279/67763592-6b5a7800-fa8b-11e9-8802-a9841fdf5933.png)

**環境情報**

 - OS: [e.g. `Windows 10`]
 - UniVRM version: [e.g. `0.53.0`]
-Unity version:[e.g. `2019.2.10f1`] ([e.g. `2018.4.11f1`]でも同様のことが起きることを確認)

**Comment by iCyP** [comment]
[seta_sibu_normal.zip](https://github.com/vrm-c/UniVRM/files/3906988/seta_sibu_normal.zip)
上記ファイルでも起こるか試してみてください。球法線をVroidの顔とスザンヌに転写し、MToon_opacue設定したものをVRMとしてblenderから出力したものです。

OS: [e.g. Windows 10]
UniVRM version: [e.g. 0.53.0]
unity[2018.3.8f1]
の環境では上記ファイルがopacueでもカスタム法線が反映されています
![コメント 2019-11-30 190318](https://user-images.githubusercontent.com/3232308/69899064-94c93500-13a4-11ea-9bf8-0221d6ece65e.png)

[suzannu.zip](https://github.com/vrm-c/UniVRM/files/3907011/suzannu.zip)
逆に、issueと同様と思われるfbxを作成しインポートしたところ、問題は再現しましたが、Mtoonを設定せずとも、standard shaderでも同じことが起こっており、fbx のIO系からくる問題ではないかと私は思います。

**Comment by hiroj** [comment]
standard shaderでも起きている問題であることから、おそらくUnityのFBXImporterの互換問題かである可能性があります。（他のFBXビューアでsuzannuを見ても法線がおかしい）
UniVRMでは対処出来ないためCloseします。
