### ISSUE TITLE
［要望］初期登録したブレンドシェイプが壊れる

### ISSUE THREAD

**Issue by suyasuyasuya** [vrm-c/UniVRM#329]
fbxのブレンドシェイプを変更したままVRM変換するとそれが初期状態になるので、カスタムモデル製作に重宝しているのですが、表情操作時に他のブレンドシェイプが壊れてしまいます。
VRM変換前はブレンドシェイプの合成ができるので、その状態を初期状態としてVRMに変換し、その後も表情をスムーズに動かせるようにしていただきたいです。

ブレンドシェイプ変更前後のVRMを１つずつ添付したので、検証して頂ければ幸いです。

**環境情報**

 - OS:Windows 10
 - UniVRM version: 0.53.0

**追加の状況・背景**

![vrm_issue2](https://user-images.githubusercontent.com/58087670/69453997-87121f00-0da8-11ea-8731-1c7fe3b3b1e9.PNG)
![_2019_11_23_04_10_07](https://user-images.githubusercontent.com/58087670/69454008-9002f080-0da8-11ea-89cc-777336b9b853.png)
[LILY_test_defolt.zip](https://github.com/vrm-c/UniVRM/files/3881077/LILY_test_defolt.zip)

**Comment by hiroj** [comment]
ご報告ありがとうございます、こちらでも検証を行ってみます。

**Comment by Kohei-Yanagida** [comment]
BlendShapeを変更し、Pose Freeze オプションにチェックを入れた状態でVRMを出力した際に、一部BlendShapeの値がおかしくなっていることをこちらでも確認しました。

修正後は変換前後でBlendShapeを組み合わせた際同じ表情になるようになります。

添付していただいたモデルを例にしますと、
`POCHI_face = 100` に変更した状態でVRM出力した場合、

 変換前のモデルで
`POCHI_face=100` , `ANEMONE_face=100` にした表情と

変換後のモデルで
`ANEMONE_face=100` にした表情とが同じ表情になります。

**Comment by suyasuyasuya** [comment]
ご対応頂き誠にありがとうございます！
修正をお待ちしております。

**Comment by hiroj** [comment]
https://github.com/vrm-c/UniVRM/releases/tag/v0.54.0
v0.54.0に対応が入りました

**Comment by suyasuyasuya** [comment]
無事動作確認ができました！
ご対応ありがとうございました。
