### ISSUE TITLE
v0.41以降でインポートしたモデルをFBX Exporterで変換できない

### ISSUE THREAD

**Issue by vyv03354** [vrm-c/UniVRM#33]
再現手順:
1. Unityをインストール(確認したバージョン: 2018.2.6f1)
2. [FBX Exporter](https://assetstore.unity.com/packages/essentials/fbx-exporter-101408)をインストール(確認したバージョン: 1.3.0f1)
3. UniVRMのv0.41以降をインストール
4. [VRoid](https://vroid.pixiv.net/)で適当にモデルを作成してエクスポート
5. エクスポートしたモデルをUnityにインポート。「NormalMap setings」のダイアログでは「Fix now」を選択
6. インポートで作成されたprefabを適当にシーンに配置
7. Hierarchyタブのツリーでモデルを右クリックし、「Export to FBX...」でエクスポート

エラーメッセージ:
```
ArgumentNullException: Argument cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[UnityEngine.Transform,UnityEngine.Matrix4x4].TryGetValue (UnityEngine.Transform key, UnityEngine.Matrix4x4& value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:588)
FbxExporters.Editor.ModelExporter.ExportBoneTransform (Unity.FbxSdk.FbxNode fbxNode, Unity.FbxSdk.FbxScene fbxScene, UnityEngine.Transform unityBone, FbxExporters.Editor.SkinnedMeshBoneInfo boneInfo)
FbxExporters.Editor.ModelExporter.ExportSkeleton (UnityEngine.SkinnedMeshRenderer skinnedMesh, Unity.FbxSdk.FbxScene fbxScene, System.Collections.Generic.Dictionary`2& skinnedMeshToBonesMap)
FbxExporters.Editor.ModelExporter.ExportSkinnedMesh (UnityEngine.GameObject unityGo, Unity.FbxSdk.FbxScene fbxScene, Unity.FbxSdk.FbxNode fbxNode)
FbxExporters.Editor.ModelExporter.ExportMesh (UnityEngine.GameObject gameObject, Unity.FbxSdk.FbxNode fbxNode)
FbxExporters.Editor.ModelExporter.ExportInstance (UnityEngine.GameObject unityGo, Unity.FbxSdk.FbxNode fbxNode, Unity.FbxSdk.FbxScene fbxScene)
FbxExporters.Editor.ModelExporter.ExportComponents (Unity.FbxSdk.FbxScene fbxScene, Boolean exportAnim)
FbxExporters.Editor.ModelExporter.ExportAll (IEnumerable`1 unityExportSet, System.Collections.Generic.Dictionary`2 animationExportData)
FbxExporters.Editor.ModelExporter.ExportObjects (System.String filePath, UnityEngine.Object[] objects, IExportOptions exportOptions)
FbxExporters.Editor.ExportModelEditorWindow.Export ()
FbxExporters.Editor.ExportOptionsEditorWindow.OnGUI ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:255)
```

上記の手順ではVRoidで出力したモデルを使いましたが、必ずしもVRoidで出力したモデルでなくても発生するようです(とりあえず[青いユニティちゃんCRS](https://3d.nicovideo.jp/works/td41262)で発生確認)。

v0.40では発生しないことから回避策として「UniVRM v0.40を使う」が知られているので、UniVRMのバージョンアップの妨げになっています。

**Comment by m-sigepon** [comment]
v0.4.3でSkinnedMeshRendererからルートボーンが抜けている問題が継続しています。
こちらの問題は、UniVRMでエクスポート時の時点で情報が抜けてしまっているのが問題なのでしょうか？
だとするとその上で、インポート時点で復元する処理をUniVRMで行ってほしいです。
https://twitter.com/m_sigepon/status/1041279411838832641

**Comment by ousttrue** [comment]
UnityのSkinnedMeshRenderer.rootBoneは、

* メッシュのバウンディングボックスを決める基準になっていて`SkinnedMeshRenderer.updateWhenOffscreen=false`のときに描画するか否かを決める基準になります。人間が見た目で判断しないと適切なボーンがわからないときがあります。

* おそらくWeightの無い頂点の親の乗るボーンになります(スキニング無しでBlendShapeのみがあるメッシュで顕著)。これで、顔だけ変なところに行くという現象が起こり得ます(過去のバージョンであった)。

という事情で、nullでもプログラムで勝手にrootBoneをセットするのを避けています。
もうひとつ、

* 過去のバージョンでは、バグで間違えてモデルのルートをrootBoneにセットしていた。nodeのインデックス指定がデフォルト値の0になり、0はルートボーンになるため

でした。

とりあえず、エクスポート前に呼び出し側で

エクスポート時にSkinnedMeshRenderer.rootBoneがnullならば、
SkinnedMeshRenderer.rootBoneに対して
SkinnedMeshRenderer.bonesから一番根元のボーンを選んでセットするか、
SkinnedMeshRenderer.bonesが空の場合はSkinnedMeshRenderer.transformを設定

していただければと思います。

次のバージョンで、
追加の引数や、明示的な関数呼び出しで上記のrootBone割り当てをする機能を検討します。

**Comment by ousttrue** [comment]
元々セットしてあるrootBoneが落ちている可能性もあるので確認します

**Comment by m-sigepon** [comment]
https://twitter.com/m_sigepon/status/1043158540670492672
VRoidStudio v0.2.11をリリースいたしましたが。Skinned Mesh Rendererが割り当てられいるメッシュの名前を変更したところ、ルートボーンが設定されるようになりました。
名前に起因する問題なのかもしれません。

**Comment by hiroj** [comment]
UniVRMではrootBoneのImportExportは問題無かったため、FBX Exporterで出力する場合は手動でrootBoneを設定していただくようお願いいたします。
