### ISSUE TITLE
Export時にメタ情報を設定する

### ISSUE THREAD

**Issue by gatosyocora** [vrm-c/UniVRM#333]
現状ExportHumanoidからExport時にTitleおよびAuthorの入力は可能です。
しかし、その他の項目についてはVRMファイルをインポートしてから記入する必要があります。
一部のサービスにおいては項目が抜けているとエラーとして処理されてしまいます。
例）THE SEED ONLINE : Version, ContactInformation, Reference

VRMMetaコンポーネントに入力が必要な現方式ではこれらのメタ情報が欠落したまま利用されるケースが予想されます。

* TitleやAuthorのようにVersionなども入力可能にする
* 初期値として何かしらが入力されている（または自動入力される）
のようにするほうがいいかと思います。

**Comment by hiroj** [comment]
#338 でExportUIの設定項目にVersion, ContactInformation, Referenceを追加しました
またVersionが空だった場合は "0.0"を入れるようにしました。
この変更はExporterの実装であり、VRM-v0.xの仕様を変更して特定の項目をRequiredにするわけではないため注意してください。（すでに項目が抜けているVRMが出回ってしまっているため）

VRM-v1.0の仕様ではどの項目がRequiredなのかをSchemaに明記するように致します。

**Comment by esperecyan** [comment]
VRMの他の設定についても、正規化前に設定できないでしょうか。FBX等をプレハブ化したものにそのまま各コンポーネントを設定し、正規化と同時にエクスポートできれば、モデルに細かな修正をする場合の手間が大幅に削減できるかと思います。

#### 現在のVRMファイル修正手順
1. FBXなどを上書き
2. VRMとしてエクスポート
3. 古いモデルと別名で 2 をインポート
4. 古いモデルから設定を移行
5. VRMとしてエクスポート

#### 正規化とVRM化を同時に行う場合
1. FBXなどを上書き
2. VRMとしてエクスポート

**Comment by esperecyan** [comment]
↑を実現するエディタ拡張を作りました
https://twitter.com/esperecyan/status/1336109743341928448
