### ISSUE TITLE
Unity Asset Store への登録

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#334]
UniVRM を Unity Asset Store で公開することで、以下のような使い勝手の向上などが期待できます。

- 導入が容易になる
- アップデートの通知が行われる
- UniVRMを依存関係に定義できるようになる

**Comment by hiroj** [comment]
v1.0でAsset Store登録＆PackageManager導入を検討しています。

**Comment by shiena** [comment]
Unity2020.1a21とUnity2019.3.4f1からupmのgit urlにサブフォルダを指定できるようになりました。
https://forum.unity.com/threads/some-feedback-on-package-manager-git-support.743345/#post-5425311

**Comment by shiena** [comment]
#393 でpackage.jsonがマージされたのでUnity2019.3のPackage Managerで以下のgit URLを指定すると取り込むことができました。

```
https://github.com/vrm-c/UniVRM.git?path=/Assets/VRM
```

ですがMToonのLICENSEとREADME.mdにmetaファイルがないのでビルドの度にコンソールにエラーが出ます。エラーが出る事以外は問題ありませんがVRMとMToonのどちらの問題でもないので悩ましいです。
![image](https://user-images.githubusercontent.com/1295639/82137775-ffd4ce00-9855-11ea-9dec-10b996bc3224.png)

**Comment by hiroj** [comment]
なるほど、こちらも何か対処法が無いか探してみます

**Comment by hiroj** [comment]
v0.56バージョンからUMP対応になります。
