### ISSUE TITLE
Experimental Exportをしたときに、nodes配下のchildrenが空配列になる

### ISSUE THREAD

**Issue by Haresaku** [vrm-c/UniVRM#350]
**バグについて**
UniVRM 0.54にて `Export humanoid` を実行した時、`Use Experimental Export` にチェックを入れた状態でExportを行なった場合、
nodes配下にchildrenが空配列で出力されるノードが出る

**再現方法**
1. メニュー VRM > Export humanoidからVRM Exporterを開く
2. Use Experimental Exporterにチェックを入れてExport

使ったVRMファイル: https://drive.google.com/file/d/1UoQUO4EZX-L2T947-8RVDwaWpq9TVzC8/view?usp=sharing

**スクリーンショット**
![スクリーンショット 2019-12-24 15 55 00](https://user-images.githubusercontent.com/41988080/71399346-a4b3fc00-2666-11ea-9e0f-adc169303621.png)

**期待する動作**
Exportされたnodesのchildrenには空配列が存在しない。空の場合はchildrenのキーがそもそも存在しないのが正しそう.
gltfのspecificationはそのように定義されてます

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/node.schema.json

**環境情報**

 - OS: macOS Mojave 10.14.6
 - UniVRM version: 0.54.0

**追加の状況・背景**

**Comment by hiroj** [comment]
ご報告ありがとうございます、childrenを確認して空の場合は書き込まない処理を追加します。

**Comment by hiroj** [comment]
https://github.com/vrm-c/UniVRM/releases/tag/v0.55.0
修正が入りました
