### ISSUE TITLE
Experimental Exportをしたときに、マテリアルのシェーダーが unlit から Standard に変わる

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#351]
**バグについて**

UniVRM-0.54.0において、エディタ拡張でVRMをエクスポートする際、シェーダーが unlit の場合、Standard シェーダーとしてエクスポートされます。

**再現方法**

1. Unity 2019.2.17f1 で UniVRM-0.54.0 をインポート
1. [AliciaSolid_vrm-0.51-unlit.zip](https://github.com/vrm-c/UniVRM/files/4001053/AliciaSolid_vrm-0.51-unlit.zip) をインポート
1. マテリアルのシェーダーが UniGLTF/UniUnlit であることを確認
1. Export humanoid でエクスポート
1. エクスポートしたVRMファイルをインポート
1. マテリアルのシェーダーが Standard であることを確認

**期待する動作**

マテリアルのシェーダーが UniGLTF/UniUnlit であること

**環境情報**

- OS: `Windows 10`
- UniVRM version: `0.54.0`
- Unity version: `2019.2.17f1`

**追加の状況・背景**

エクスポートする際、「Use Experimental Export」のチェックを外すと、問題を回避できました。

**Comment by hiroj** [comment]
ご報告ありがとうございます、Experimental Exportのシリアライズ時にKHR_materials_unlit拡張が出力されていないことが原因でした。
問題を修正し、Experimental Exportはデフォルトfalseにする変更を加えます。

**Comment by hiroj** [comment]
https://github.com/vrm-c/UniVRM/releases/tag/v0.55.0
Experimental Export修正致しました。
