### ISSUE TITLE
0.54.0のExperimental Exportのデフォルトをfalseにしたものをいったん年内リリースお願いしたいです

### ISSUE THREAD

**Issue by saturday06** [vrm-c/UniVRM#355]
こちらのissue https://github.com/vrm-c/UniVRM/issues/351#issuecomment-568967535 で言及されている、Experimental Exportのデフォルトをfalseにしたものをいったん年内にリリースお願いしたいです。

今回のExperimental Exporter機能はかなり大規模な変更で、既に発生している不具合 https://github.com/vrm-c/UniVRM/issues/350 https://github.com/vrm-c/UniVRM/issues/351 の以外にも何かが出てくる可能性があります。しかし、そろそろ世間は冬休みになり、それを利用してVRMモデルを作る方が増えると思いますが、反対にUniVRMの開発陣はお休みになると思います。そのため、ひとまずデフォルトfalseにしておくことで、ユーザーへの影響がかなり防げると思います。

また、Experimental Exporterの主な更新点はIL2CPP対応だと思うので、ひとまずEditor上でのデフォルトを外しても悪影響は軽微だと考えます。IL2CPP対応自体は、多方面に恩恵のある大変ありがたい機能だと思っています。

何卒ご検討のほどよろしくお願い致します 🙇

**Comment by hiroj** [comment]
Experimental Exportのデフォルトfalse対応と、#351 #350 #349 #348 の修正を入れて v0.55をリリースします。

**Comment by saturday06** [comment]
すごい、ありがとうございます！とても助かります 🙇

**Comment by saturday06** [comment]
こちら確認しました。迅速な対応ありがとうございます！
