### ISSUE TITLE
Unlitシェーダーについて提案

### ISSUE THREAD

**Issue by KatanoShingo** [vrm-c/UniVRM#364]
# 問題
- VRMの一つのアバターでどこへでも行き来できる思想からは、Unlitシェーダーはアプリケーションの世界からはずれてしまうと考えています。  
例：真っ暗な暗いシーンに置いて、アバターが暗くならない  
- Unlitシェーダーによってアプリケーションとの交わりが少なくなってしまっている。  
 # 提案  
- Unlitシェーダーの削除  
- または、Unlitシェーダー選択への非推奨

**Comment by iCyP** [comment]
仕様については https://github.com/vrm-c/vrm-specification でのissueが適切かと思います。

**Comment by KatanoShingo** [comment]
ありがとうございます。そちらにissue出しました。  
https://github.com/vrm-c/vrm-specification/issues/104
