### ISSUE TITLE
uniGLTF1.28 export when the model contain animator, it can't work

### ISSUE THREAD

**Issue by 643364103** [vrm-c/UniVRM#365]
**Describe the bug**

uniGLTF1.28 export when the model contain animator, it can't work
---------------------------------------------------------------------------------
NullReferenceException
UniGLTF.AnimationExporter.Export (UnityEngine.AnimationClip clip, UnityEngine.Transform root, System.Collections.Generic.List`1 nodes) (at Assets/VRM/UniGLTF/Scripts/IO/AnimationExporter.cs:128)
UniGLTF.gltfExporter.FromGameObject (UniGLTF.glTF gltf, UnityEngine.GameObject go, Boolean useSparseAccessorForMorphTarget) (at Assets/VRM/UniGLTF/Scripts/IO/gltfExporter.cs:311)
UniGLTF.gltfExporter.Export () (at Assets/VRM/UniGLTF/Scripts/IO/gltfExporter.cs:144)
UniGLTF.gltfExporter.ExportFromMenu () (at Assets/VRM/UniGLTF/Scripts/IO/gltfExporter.cs:42)
----------------------------------------------------------------------------------------------------

**Comment by hiroj** [comment]
Can you tell me the steps to create an error condition?
I imported the following model, set up Animator and tested it, but I could not find any errors.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan

**Comment by 643364103** [comment]
@hiroj   
CesiumMan is use animations. 
[test.zip](https://github.com/vrm-c/UniVRM/files/4045001/test.zip)
This model is download from unity assets store.
When exporting glb, there will be many warnings and no errors. But this glb can not be loaded.

**Comment by PoChang007** [comment]
Any chance of trying later versions like unity 2018, 2019? Not sure it will work though

**Comment by akehir** [comment]
I had the same issue. Deleting the Animator fixed it for me.

Settings of reproduction with CesiumMan. Unity 2013.3.12f1.

![image](https://user-images.githubusercontent.com/1078202/80869025-421ade80-8c9e-11ea-98d3-960647452104.png)

![image](https://user-images.githubusercontent.com/1078202/80869051-6d053280-8c9e-11ea-8aae-a7bd981219df.png)

**Comment by PoChang007** [comment]
Nice! This interface looks like you were using Unity 2019?
@643364103  Please try akehir's method with the latest Unity version and see if it works for you.
Thanks,

**Comment by PoChang007** [comment]
This issue will be closed. Feel free to reopen it if errors still occur.
Thanks,
