### ISSUE TITLE
Export時にエラーが発生する

### ISSUE THREAD

**Issue by Yukoneko-User** [vrm-c/UniVRM#366]
**バグについて**

そもそもExport出来ない状態に陥ることと、Exportしてもテクスチャのデータだけを残して他が消えてしまう現象

**再現方法**

Incident 1:
マテリアルをMToonに変更済みのモデルを用意する。(アクセサリーで複数のMeshあり)
通常のExport手順を行う
エラーが発生し「"モデルの名称"(normalized)」と名付けられたものがHierarchyに出来る。
※この際、Export先に指定したファイルの中身は存在しない
Incident 2:
原因がExo_Spine(Mesh)ということがわかり、非表示にする
通常のExport手順を行う
出力されたVRMファイルをUnityにinportする
エラーが発生しテクスチャが入ったファイルとVRMファイルのみがファイルの中に存在する。

**スクリーンショット**

Incident 1: ![Error_1](https://user-images.githubusercontent.com/59576516/71967679-fd7abb80-3246-11ea-8996-8d49ded99d9b.png)
Incident 2: ![Error_2](https://user-images.githubusercontent.com/59576516/71967697-08355080-3247-11ea-9955-3ceed0a0e20e.png)

**環境情報**

 - OS: [Windows 10 64bit]
 - UniVRM version: [UniVRM-0.55.0_ce1c]
 - Unity version:[Unity 2017.4.28f1]

**Comment by hiroj** [comment]
ご報告ありがとうございます
下記のissueと同じ現象の可能性があるため、UnityEditorのツールバーにある Edit >Preferences… > General から 「Compress Assets on Import」にチェックを入れた状態で再度Importを試していただけますでしょうか。
https://github.com/vrm-c/UniVRM/issues/336
![image](https://user-images.githubusercontent.com/39366194/71969296-b7732700-3249-11ea-92c2-0d6c201f25b2.png)

**Comment by Yukoneko-User** [comment]
チェックが入っている状態で試しましたが、変わらずエラーが発生しています

**Comment by hiroj** [comment]
Incident 1の２つめのエラーからの推測になってしまいますが、Mesh(SkinnedMeshRenderer)がスキニングのために参照していたボーンが無くなっていて出力時に失敗している可能性があります。
Unityに読み込んだ元の状態からボーンの編集が行われたかどうか確認出来ますか？

**Comment by Yukoneko-User** [comment]
Incident 1はExo_Spineの本来のRootBoneをモデルに追加することで解決出来ました、ですが2については相変わらず"MissingReferenceException: The object of type 'Material' has been destroyed but you are still trying to access it."というエラーが出ております。MeshのRootBoneを変更するのはこのエラーの原因となりますか？

**Comment by hiroj** [comment]
MeshのRootBone変更はエラーに影響はないと思われます。
`MissingReferenceException: The object of type 'Material' has been destroyed but you are still trying to access it.`
 同じ内容のエラーが出ている #336 ではUnity2018.4でImportすると正常にImport出来る場合があったため、お手数かけて申し訳ないのですがUnity2018.4または2019系でImportを試していただけるでしょうか。

**Comment by Yukoneko-User** [comment]
2018.4.14f1でUniVRMのImport及びモデルのExportを行いました。特に問題なくPrefabが生成されましたが、`Assertion failed on expression: 's_AssetProgressBar.dialog'`というエラーが発生しました。これは何か影響を及ぼしますか？
補足:Compress Assets on Importにチェックを入れた状態でUniVRMのImportを行いました

**Comment by hiroj** [comment]
`Assertion failed on expression: 's_AssetProgressBar.dialog'`
恐らくですが変換中に出ているプログレスバーでエラーで何等かのAssertionが失敗しているだけのようなので、入出力のファイルやプレハブには影響は無いと思います。こちらでもエラーが確認できた場合は追って調査致します。
また、Unity 2017.4.28f1で'MissingReferenceException'を回避する方法が見つかり次第修正を入れます。

**Comment by hiroj** [comment]
Unity 2017.4の公式サポートが切れたため、このissueはクローズします。
