### ISSUE TITLE
could you add  KHR_Texture_transform extension?

### ISSUE THREAD

**Issue by hswangrui** [vrm-c/UniVRM#367]
could you add   KHR_Texture_transform extension ? Thx!

**Comment by esperecyan** [comment]
This is duplicated of https://github.com/vrm-c/UniVRM/issues/216

**Comment by hiroj** [comment]
Will be supported in the next version

**Comment by hiroj** [comment]
#229
The changes will be merged and will be available in v0.56. The only parameters supported are offset and scale, not rotation.
