### ISSUE TITLE
LWRP / URP support

### ISSUE THREAD

**Issue by dblatner** [vrm-c/UniVRM#368]
I'm wondering how the UniGLTF package can be adapted to use Unity's LWRP or URP materials/shaders instead of the standard shaders.

Especially for mobile platforms or Oculus Quest I would expect a great performance boost when switching to LWRP/URP.

**Comment by hiroj** [comment]
I want to support it in the future, but I want to know what to do to make the shaders provided by UniVRM work universally with user-defined RendererPipline.

**Comment by dblatner** [comment]
When using LWRP / URP you basically only have to change the shaders/materials to a compatible LWRP/URP shader instead of the standard shader. (there's a default standard LWRP / URP shader, too)

As far as I understand the LWRP / URP sets up a setting referencing a "render pipeline" asset. If it's null or empty the Unity standard shaders are used, but if set to another pipeline, then those shaders are used like the ones of the LWRP/URP.

I had a look into the MaterialImporter classes of the UniGLTF package. I think support could be easily added by adding the LWRP / URP shader names to the MaterialImporter types and check whether Legacy Render Pipeline is used or LWRP/URP -> choose appropriate standard shader

**Comment by shogoki-vnz** [comment]
+1 to the URP support, I'm porting my project to URP and the performance boost is tremendous but sadly I can't use VRM anymore

**Comment by ming436534** [comment]
I just found a kind developer who developed a shader graph version of MToon shader, you can just replace the current shader with that, here is the link: https://github.com/simplestargame/ShaderGraphsMToonForURPVR

**Comment by dblatner** [comment]
> I just found a kind developer who developed a shader graph version of MToon shader, you can just replace the current shader with that, here is the link: https://github.com/simplestargame/ShaderGraphsMToonForURPVR

Very good! In the referenced repository the author also mentions what needs to be changed to switch to a URP shader instead of the standard shader -> update VRMMaterialImporter to just reference the URP shader by name, that simple :)

**Comment by hiroj** [comment]
Thank you for providing information. I actually run it to see if there are any problems.

**Comment by bregassa** [comment]
> 
> 
> > I just found a kind developer who developed a shader graph version of MToon shader, you can just replace the current shader with that, here is the link: https://github.com/simplestargame/ShaderGraphsMToonForURPVR
> 
> Very good! In the referenced repository the author also mentions what needs to be changed to switch to a URP shader instead of the standard shader -> update VRMMaterialImporter to just reference the URP shader by name, that simple :)

Did you find another solution? I'm using that shader on latest unity 2019 LTS, but the shader seems to be a bit broken, here's my ss : https://imgur.com/a/DElbCIx , anybody have a fix for this issue?

**Comment by bregassa** [comment]
> 
> 
> > > I just found a kind developer who developed a shader graph version of MToon shader, you can just replace the current shader with that, here is the link: https://github.com/simplestargame/ShaderGraphsMToonForURPVR
> > 
> > 
> > Very good! In the referenced repository the author also mentions what needs to be changed to switch to a URP shader instead of the standard shader -> update VRMMaterialImporter to just reference the URP shader by name, that simple :)
> 
> Did you find another solution? I'm using that shader on latest unity 2019 LTS, but the shader seems to be a bit broken, here's my ss : https://imgur.com/a/DElbCIx , anybody have a fix for this issue?

Weird problem.. I just found that the broken shader will exist when I try to play the game and the broken shader shape is following my scene window view.. so when my scene view looking at the sky or nothing.. the glitch will disappear

**Comment by caxapexac** [comment]
Can you explain please how to use https://github.com/simplestargame/ShaderGraphsMToonForURPVR
It says
" Find VRMMaterialImporter if you use UniVRM package
Edit lines as follows. "
But there is not such file as VRMMaterialImporter in 0.80.0

This is almost 2 years of lack of urp support but still no builtin solution

**Comment by rendi88** [comment]
yeah it happen in me too and its intermittent
it seems the reflection but just the outline
https://ibb.co/cvmR8DR

**Comment by breadnone** [comment]
> 
> 
> I just found a kind developer who developed a shader graph version of MToon shader, you can just replace the current shader with that, here is the link: https://github.com/simplestargame/ShaderGraphsMToonForURPVR

This is okay but not quite. It doesn't have custom lighting or anything to handle lights automatically in URP environment, it will generate wrong colors unless you map each and every one of them.

Tho adding another layer of filter for light fixes it, but still, its more of a workaround

**Comment by ousttrue** [comment]
see #1214
