### ISSUE TITLE
Unity 2019.3 へのプロジェクトアップグレード時にVRMが再インポートされる

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#373]
**バグについて**

Unity 2019.2 で作成したプロジェクトを、Unity 2019.3 で開くと、アップグレード時にVRMが再インポートされ、プレハブに加えた変更が破棄されます。

**再現方法**

1. Unity 2019.2.19f1 で新規3Dプロジェクトを作成する
1. UniVRM-0.55.0 をインポートする
1. 任意のVRMファイルをインポートする
1. 生成されたプレハブになんらかの変更を加える
1. プロジェクトを Unity 2019.3.0f6 で開く
1. VRMのインポート処理が走り、プレハブが上書きされ、手順4で変更したデータが消える

**期待する動作**

プロジェクトのアップグレード時は、VRMファイルのインポートを行わない

**環境情報**

 - OS: `Windows 10`
 - UniVRM version: `0.55.0`

**Comment by hiroj** [comment]
現状、EditorImport は AssetPostprocessor によってImport処理をキックしており、UnityがReimport or Reimport Allを実行すると再読み込みが行われます。
`VRM_STOP_ASSETPOSTPROCESSOR`の DefineSymbolを設定してAssetPostprocessor を無効化した
状態でプロジェクトのアップグレードすると、Reimport All時の再読み込みをを防ぐことが出来るのでお試しいただけますか？

**Comment by esperecyan** [comment]
ありがとうございます。
`VRM_STOP_ASSETPOSTPROCESSOR` を設定すると、Reimportされることなくアップグレードできました。

**Comment by hiroj** [comment]
Unityのバージョン更新時は全てのアセットがReimportされてしまうため、AssetPostprocessor の発動を止める場合はVRM_STOP_ASSETPOSTPROCESSORを設定していただくようお願いいたします。
