### ISSUE TITLE
Unity2017.4.28f1でExport時に応答なしになる。

### ISSUE THREAD

**Issue by Ekuri0204** [vrm-c/UniVRM#374]
**バグについて**
boothにて購入したアバターをインポートし、シェーダーをVRM Mtoonに全て設定した後
Export HumanoidにてExportするとUnityが動作停止して10分以上放置していてもExportされない。
応答なし状態の時、エラーログもでないので何が原因なのかわからない。

**再現方法**
1.FBXをhumanoidに設定する
2.各メッシュのShaderをMtoonに切り替える
3.VRMタブからExporthumanoidを選択する
4.Force T Pose,PoseFreezeにチェックを入れてUse Experimental Exportにチェックを入れる（入れない場合も同じ）
5.Unity自体が応答なしになり強制終了しか受け付けなくなる。

**期待する動作**

販売モデルをVRMとして出力したい。

**環境情報**

 - OS: [Windows 10]
 - UniVRM version: [v0.55.0]

**追加の状況・背景**

boothにて販売されている下記モデルなのですが、Unityでのみ改変しているのでboneの名前が重複したりしている部分があるのでそういった原因があるのかもしれません。
モデル本体【https://armadillon.booth.pm/items/1484117】
衣装モデル【https://booth.pm/ja/items/1810602】

**Comment by hiroj** [comment]
原因がImportかExportかを切り分けるために、ＶＲＭの出力場所をUnityのAssetsフォルダ以外を指定して試していただけますでしょうか。
この状態でUnityが応答なしになる場合は、おそらくBlendShapeなどのExport処理が重い部分で停止している可能性があるため調査致します。

**Comment by Ekuri0204** [comment]
回答ありがとうございます。
desktop上に出力先を設定してみましたが全く同じ挙動をして応答なしになります。
ご検討よろしくお願いいたします。

**Comment by sh-akira** [comment]
着せ替えモデルをVRM出力する際に固まったりUnityごと落ちる場合、
おっしゃる通り、殆ど着せ替えや後付けアクセサリーが、体のHumanoidのボーンと同じ名称のボーンを持っている場合です。
例えば体にHipsがあり、服にもHipsがあるとき、服側をHips2等に名前変更してからなら出力可能かと思います。
ChestやSpine等すべてのボーンで同様です。
(ところで再現方法に改変が入っていませんが、改変無しだとエラーにならないと思います)

上記はTwitterやユーザーからの報告で対処方法を見つけ出したもので私は多数の質問を受けていますが、私自身は再現手順を持ち合わせていないためissueにしていませんでした。
よろしくお願いします。

**Comment by Ekuri0204** [comment]
確認いたしました。
おっしゃる通りboneの名前が重複しているとエクスポートできませんでした。
boneの名前を変更しましたら無事エクスポートできるようになりました。
問題解決に助力いただきありがとうございました。

**Comment by hiroj** [comment]
ご報告ありがとうございます、同名ボーンに関してはVRM出力前に検知して警告を出すなどの対処を検討致します。
