### ISSUE TITLE
UniVRM0.54以降で BaseColorFactor の Linear 変換が入ったので、過去にエクスポートしたモデルが 白っぽくなったり、黒っぽくなったり、見た目が以前と異なってしまうものがある

### ISSUE THREAD

**Issue by fantom1x** [vrm-c/UniVRM#375]
**バグについて**

たぶん以下のIssueの関連の気がしますが（同じならまとめちゃって下さい）
https://github.com/vrm-c/UniVRM/issues/369
「Standard Shader」でも白っぽくなり(輝度が異様に高くなる？)、以前と見た目がかなり変わってしまうものがあるので、レポートとして挙げておきます。

**再現方法**

例えば、以下URLの素材をロードする（エディタでも可）。

**期待する動作**

UniVRM0.53のスクリーンショットのように白っぽく（黒っぽく）ならない。

**スクリーンショット**

お花見セット (GLB ※拡張子を.glbに変えて下さい)
https://hub.vroid.com/characters/637505527785006989/models/1628906739367953109

(UniVRM0.53)
![hanami_0_53](https://user-images.githubusercontent.com/8603961/73910941-0e752600-48f4-11ea-8569-5f29e644152b.jpg)

(UniVRM0.55)
![hanami_0_55](https://user-images.githubusercontent.com/8603961/73910953-15039d80-48f4-11ea-8eb4-e1b653f0087e.jpg)

sea of star (GLTF)
https://sketchfab.com/3d-models/sea-of-star-71c898a3e6ca4bbab6e2ae6b47c97798

(UniVRM0.53)
![sea_of_star_0_53](https://user-images.githubusercontent.com/8603961/73911034-51cf9480-48f4-11ea-9114-41a728e9e3d2.jpg)

(UniVRM0.55)
![sea_of_star_0_55](https://user-images.githubusercontent.com/8603961/73911045-572cdf00-48f4-11ea-994c-1e459c62ec40.jpg)

Hampton Lake Dam (GLTF)
https://sketchfab.com/3d-models/hampton-lake-dam-post-hurricane-irma-a28144252dc74062a40672b5de3b7120

(UniVRM0.53)
![dam_0_53](https://user-images.githubusercontent.com/8603961/73911092-70ce2680-48f4-11ea-9849-9d4dc8c02c78.jpg)

(UniVRM0.55)
![dam_0_55](https://user-images.githubusercontent.com/8603961/73911099-7592da80-48f4-11ea-932c-323ce98050e8.jpg)

**環境情報**

 - OS: Windows 10 (x64)
 - UniVRM version: 0.53-0.55
 - Unity 2019.2.18f1-2.20f1

**Comment by hiroj** [comment]
https://github.com/vrm-c/UniVRM/issues/301
https://github.com/vrm-c/UniVRM/pull/339
上記の修正によってUniVRM0.55から Gltf の BaseColor にGamma変換が入るようになりました。
UniVRM0.53以前では、UnityのColor値(sRGB)をそのまま出力していましたが、GltfではColor値はLinearで出力する仕様であることが判明したためバグとして修正が入っています。
Import : GltfLinear -> UnitysRGB
Export : UnitysRGB -> GltfLinear
この修正の影響として、StanderdとUnlitを使用してかつ Color が(1, 1, 1 ,1)or(0, 0, 0, 0)以外を設定したUniVRM0.53以前のモデルの色がご報告して頂いた通り変わります。
MToonの Color は Gltf の BaseColor を参照していないため影響はありません。
対策としてUniVRM0.53以前で出力されたモデルはsRGB変換を行わない等の対策を検討します。（ただちゃんとsRGB変換している他のライブラリで読み込んだ場合はやはり色が変わっているはずなので、UniVRM限定の局所的対応にはなってしまいます）

**Comment by fantom1x** [comment]
なるほど、仕様的な問題なのですね。詳しい情報を有難うございます。

確かに、キャラクターモデルで影響受けてるのはあまり見かけませんね（MToonを使っているものが多いが、たまにStandard/Unlitを使っているものもある）。「Color が(1, 1, 1)or(0, 0, 0)以外」という条件もあるからでしょうか。そうなると少なくもなるか…。🤔 

まぁ、背景モデルに関しては、かなり作者の制作環境(ツール等)に依存するので、ある程度は諦めるしかないかもですね。「sRGB変換を行わない」実装を待つことにします（ランタイム時にロードオプションみたいにできれば汎用的に使えそうですが）。

＊ ＊ ＊ ＊ ＊ ＊ ＊ ＊ ＊ ＊

キャラとは言い難いですが、以下のようなモデルは影響受けてますね…。ご参考までに(笑)。
Dragon
https://hub.vroid.com/characters/8819627042892951588/models/6009718067118488885

(UniVRM 0.53)
![dragon_0_53](https://user-images.githubusercontent.com/8603961/73930062-48a4ee80-4919-11ea-9e74-9a38fea1c543.jpg)
(UniVRM 0.55)
![dragon_0_55](https://user-images.githubusercontent.com/8603961/73930072-4c387580-4919-11ea-8488-95da2d88e8a1.jpg)

Cerberus
https://hub.vroid.com/characters/256837281355081925/models/6703438975281016999

(UniVRM 0.53)
![cerberus_0_53](https://user-images.githubusercontent.com/8603961/73929993-2612d580-4919-11ea-8026-d263a473a191.jpg)

(UniVRM 0.55)
![cerberus_0_55](https://user-images.githubusercontent.com/8603961/73930003-2c08b680-4919-11ea-8f18-062ca1a2d253.jpg)

**Comment by hiroj** [comment]
UniVRM0.54以降であれば、エクスポート時にLinear変換されたColorが出力されるため、これをUnityにインポートするとsRGBに再変換されて値が元に戻り、エクスポートした時と同じ色になります。
* Unity上のBaseColor: (0.5, 0.5, 0.5, 0.5)
↓Linear変換する
* Gltfに書き込まれるBaseColor: (0.217637, 0.217637, 0.217637, 0.5)
↓sRGB変換する
* Unityに読み込まれた後のBaseColor: (0.5, 0.5, 0.5, 0.5)

WebGLについてはそこまで詳しくないのですが、VRoidHub上の色がUniVRM 0.53で出力したモデルと同じになっているということは、VRoidHubも同じ問題を抱えている可能性がありますね・・・（BaseColorFactorをsRGBとして扱っているかもしれない）
