### ISSUE TITLE
Single Pass Instanced for XR Plugin System(Oculus) not supported.

### ISSUE THREAD

**Issue by torano111** [vrm-c/UniVRM#377]
**Describe the bug**

Current VRM Models are not rendered correctly with Single Pass Instanced and XR Plugin System. You can see VRM isn't rendered for the left eye at all if Single Pass Instanced is used.

Because XR Plugin System(Oculus Desktop) has only "Multi Pass" and "Single Pass Instanced" option and Unity recommends to use the new XR system instead of legacy VR, I think Single Pass Instanced should be supported.

VRM with Legacy VR and Single Pass Instanced doesn't work either, so I guess VRM materials don't support Single Pass Instanced.

**To Reproduce**

1. Enable XR Plugin Management and setup it for Oculus Desktop
2. put a VRM prefab(used Alicia Solid from https://3d.nicovideo.jp/works/td14712) to a scene
3. play

**Expected behavior**

The right eye camera renders VRM models as well as the left eye camera.

**Environments**

 - OS: Windows
 - UniVRM version: 0.55
 - Oculus(Desktop)
 - Unity 2019.3.0f6
 - XR Management 3.0.6
 - Oculus XR Plugin 1.1.5

**Comment by hiroj** [comment]
Thanks for the report.
We will consider the response.

**Comment by PoChang007** [comment]
Hi,

VRM materials now support Single Pass Instanced (UniVRM `0.71.0`~).

Thanks,
