### ISSUE TITLE
When unity URP  will be supported?

### ISSUE THREAD

**Issue by fenglindubu** [vrm-c/UniVRM#387]
When unity URP  will be supported?

**Comment by DavidAntliff** [comment]
FWIW, you can convert to Unity Universal Render Pipeline (URP) by selecting the materials for the imported prefab and choosing "Edit > Render Pipeline > Universal Render Pipeline > Update Selected Materials to UniversalRP Materials".

**Comment by fenglindubu** [comment]
Toon Shader Can't Convent

**Comment by hiroj** [comment]
We are investigating how the functions and definitions used in older style shaders have changed in URP.
If anyone knows about it, you can help by making a pull request.
The date when it can be used is undecided.

**Comment by hiroj** [comment]
Ref: #368

**Comment by Santarh** [comment]
duplicate issue #368
