### ISSUE TITLE
Imports with UniGLTF 1.28 look less like Blender equivalent than 1.27

### ISSUE THREAD

**Issue by DavidAntliff** [vrm-c/UniVRM#388]
This isn't a bug, it's a question about UniGLTF.

I used UniGLTF 1.27 and UniFLTF 1.28 (part of UniVRM-0.55.0) to import the KhronosGroup [FlightHelmet](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/FlightHelmet) model into Unity 2019.3. I also used "Edit > Render Pipeline > Universal Render Pipeline > Update Selected Materials to UniversalRP Materials" to update the imported materials to work with the Universal Render Pipeline.

I notice that I get visibly different results:

![image](https://user-images.githubusercontent.com/11261038/79059790-402eb280-7cd2-11ea-9c58-0410b15ee819.png)

The front instance (on the left) is from 1.27, the rear instance (on the right) is from 1.28. I notice that the 1.28 version is a lot less reflective than 1.27. I thought that this might be expected due to the changelog notes for 1.28, and the FAQ, but when I compare with the .gltf imported into Blender, I see that it more closely matches version 1.27:

![image](https://user-images.githubusercontent.com/11261038/79059919-bda6f280-7cd3-11ea-8d3c-aec69781c029.png)

Note the specularity of the leather helmet and the nose and mouthpiece - the Blender image looks more like the front/left 1.27 image than the newer 1.28 image. The specular highlights on the hose in v1.27 are also closer to the Blender image.

I realise this is a fairly subjective opinon, so I'm looking for the technically correct answer. Is 1.27 more correct? Or is v1.28 more correct?

**Comment by hiroj** [comment]
Thank you for the report.
I could see the difference in the reflection.
I will investigate.

**Comment by ousttrue** [comment]
`v0.69.0`
