### ISSUE TITLE
asmdef を本体の unitypackage へ同梱

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#391]
UniVRM に依存する asmdef 対応のエディタ拡張を、UniVRMが使われている既存のUnityプロジェクトへ、ユーザーが導入しやすくするために、UniVRM本体とasmdefを単一のunitypackageで提供してもらえないでしょうか。

**Comment by hiroj** [comment]
次のバージョン(v0.56)から同梱するようにします

**Comment by hiroj** [comment]
package生成コードを変更してadfが同梱するようにしました。
