### ISSUE TITLE
Not being able to export due to a specific reason. 

### ISSUE THREAD

**Issue by Lyeco** [vrm-c/UniVRM#394]
One of my models wouldn't export due to an error. 
![Screenshot_128](https://user-images.githubusercontent.com/15318314/81399761-2e6bee00-915e-11ea-9428-fadb31d9d3fa.png)
I don't know how it fails by having a な shape key or having the blendshape frame being greater than the frame height. 

I couldn't get to edit the shape keys either as my model comes from a prefab.

**Comment by hiroj** [comment]
Thank you for reporting.
Could you tell me which version of Unity and UniVRM you are using, how to reproduce it, etc.

**Comment by PoChang007** [comment]
We just released v56.2. If it still doesn't work, we are wondering if it is possible to share your model with us?

We will look into this problem.

**Comment by hiroj** [comment]
Try with the latest version.
If you still have problems, please re-open.
