### ISSUE TITLE
Blend shape normals broken after export/import via VRM format

### ISSUE THREAD

**Issue by hakanai** [vrm-c/UniVRM#415]
**Describe the bug**

Exporting to a VRM file and then re-importing, normals break when applying blend shapes to the imported model when they were fine before importing.

**To Reproduce**

1. Import an FBX file with stored blend shape normals
2. Select the model and **ensure that "Blend Shape Normals" is set to "Import"**
3. Hit Apply
4. Proceed with rest of humanoid setup as per normal
5. Select a mesh with blend shapes, e.g. the face, and apply a blend shape, e.g. ああ
6. **Observe:** Take note of how the blend shapes look. They should look fine. In the case of models which have stored blend shape normals, the normals being broken should be very obvious. Screenshot below.
7. VRM > UniVRM > Export humanoid
8. Fill in Author, otherwise leave settings at default (Force T Pose checked, Pose Freeze checked)
9. Hit Export
10. Drop that VRM file back into the project and wait
11. Drop the created .prefab file into a scene
12. Test the blend shape again
13. **Observe:** The normals around where the blend shape is applied are now broken.

**Expected behavior**

The imported blend shape normals should have been present in the export so that they could be imported again, so the result of applying the blend shape after importing the VRM file should be the same as what I got before I exported to VRM.

Suspicion is that either the blend shape normals are not exported along with the mesh, or they are not being imported when the mesh is imported.

**Screenshots**

Normals before export:

<img width="411" alt="normals-before" src="https://user-images.githubusercontent.com/43236/83214675-1d802c80-a1a0-11ea-9be7-6b64fcaddffc.png">

Normals after re-import:

<img width="416" alt="normals-after" src="https://user-images.githubusercontent.com/43236/83214684-24a73a80-a1a0-11ea-8897-c5115e642b2a.png">

**Environments (please complete the following information):**

- OS: macOS 10.15.5
- Unity version: 2018.4.20f1
- UniVRM version: 0.55.0

**Additional context**

The reason my Unity version is old is because I also develop content for VRChat and that's what I happened to have on the computer already. If a newer version works better I am willing to try any recommendations at this point.

Workarounds tried so far:

* Tried "Use Experimental Export", appears to make no difference.

**Comment by trejkaz** [comment]
I have since reproduced this issue on another publicly available model as well, so as far as I know all models are affected and I have no idea how nobody has noticed this before.

**Comment by comdost** [comment]
Yeah same, it's been a headache. Only solution that worked somewhat is using an old version of univrm

**Comment by comdost** [comment]
Oh it's UniVRM-0.53.0_6b07, I can still export without the normals bug with this one

**Comment by trejkaz** [comment]
Legacy blend shape normals seems to be a workaround as well. I was trying to avoid using it, but the reasons to use it keep stacking up, so I guess at some point I'll probably cave and just live with it.

**Comment by ousttrue** [comment]
https://vrm.dev/en/docs/univrm/blendshape/check_blendshape_normal/
