### ISSUE TITLE
VRMファイルをテキストエディタで開くと文字化けする?

### ISSUE THREAD

**Issue by taichi-suzuki-pckg** [vrm-c/UniVRM#418]
![vrm](https://user-images.githubusercontent.com/62616423/83318751-9c459a00-a272-11ea-92bf-810e703460f9.JPG)

VRM初心者ですみません。
VRMファイルをテキストエディタで開いてみると、JSON～～と書かれた部分以外は文字化けしていて読めないのですが、これは正常な状態でしょうか？

正常な状態だとしたら、ここから文字化け部分を排除してプログラミングでJSONの値を取得するにはどうしたら良いですか？

VRM内に埋め込まれた骨情報やBlendShape情報へのデータアクセスの仕方が分からないので教えてください。

**Comment by PoChang007** [comment]
こんにちは！
テキストエディタでバイナリーデータは化けしちゃうので、バイナリーエディタで文字コードをutf8にすれば、文字化け部分を見れます。

よろしければ、以下にリンクを参考してください：
https://vrm.dev/dev/univrm-0.xx/gltf/gltf_about/#glb%E5%BD%A2%E5%BC%8F
https://vrm.dev/dev/univrm-0.xx/programming/univrm_import_runtime/
https://github.com/vrm-c/UniVRM/blob/master/Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs#L277
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#glb-file-format-specification

**Comment by taichi-suzuki-pckg** [comment]
ありがとうございます。JSONの値を取得することが出来ました！
