### ISSUE TITLE
VROID Model Face Clipping when Camera too close, when animator attached

### ISSUE THREAD

**Issue by ArEnSc** [vrm-c/UniVRM#422]
**Describe the bug**

Adding Animator to the Vroid model results in a clipping issue.

**To Reproduce**
create an animator and add it to the VROID Avatar
Zoom the camera in and when you do this happens

**Expected behavior**
The animator shouldn't clip the face of the VROID Avatar
**Screenshots**

<img width="583" alt="Screen Shot 2020-06-02 at 10 59 49 PM" src="https://user-images.githubusercontent.com/6252325/83602243-2b3b0680-a540-11ea-8c29-ab61b33a9cd1.png">
<img width="205" alt="Exepcted" src="https://user-images.githubusercontent.com/6252325/83602249-2d04ca00-a540-11ea-83e4-ad435ae384b1.png">

 - OS: OSX
 - UniVRM version: 0.52.0

**Comment by ArEnSc** [comment]
Its likely that the Avatar definition is incorrect, when I remove the avatar and have an animation controller it seems to show the face. When I have the vrm avatar it doesn't lol

**Comment by ArEnSc** [comment]
Also you cannot configure the VROID avatar?

**Comment by PoChang007** [comment]
Thanks for your report. If you enable `UpdateWhenOffScreen`  in face's `SkinnedMeshRenderer`, this issue probably can be resolved. This method also applies to other SkinnedMeshRenderers whose RootBones are not set up properly. See similar discussion in #324. 
![UpdateWhenOffscreen](https://user-images.githubusercontent.com/17579532/84017038-18e62000-a9b9-11ea-829b-6a5c69356d09.jpg)

**Comment by ArEnSc** [comment]
@PoChang007 Thank you so much!
