### ISSUE TITLE
Fatal error concerning memory when exporting model

### ISSUE THREAD

**Issue by DarksabreGaming** [vrm-c/UniVRM#438]
Hello, I was hoping someone could help me on an issue I've run into when using this. I'm running Unity 2018.4.20f1 and have exported two FBX models to VRM using this addon successfully before. However I am trying to do a third in the exact same way and keep receiving this fatal error, out of memory. My PC is pretty beast so I suspect it has something to do with the model itself? Is there a limit to the number of polys or materials it can have? I believe it has about 50,000 polys and the FBX file for the model itself is only 3.4 MB. I've seen a lot of post point to the GI Cache but deleting that has not changed anything. I'm just not sure where else to even look now.

![Screenshot_781](https://user-images.githubusercontent.com/67114125/85042806-a3691500-b159-11ea-9c26-b50200bea6dd.png)

**Comment by PoChang007** [comment]
Related to UniVRM. Moved to UniVRM repo.

**Comment by PoChang007** [comment]
Hi,
We are wondering if it is possible to share your model with us? We will try to find out where the problem is.

**Comment by vovan-ivanoff** [comment]
I have the same issue while reimporting vrm model. Exactly with same numbers as in screenshot in topic. here is my vrm file and fbx model which i am converting https://drive.google.com/file/d/1LjfzFpDK9_VwupdoSmeaLaJJ4JCGT5sF/view?usp=sharing (vrm is to big(about 100 MB) to github so i uploaded ZIP it to google drive)

**Comment by vovan-ivanoff** [comment]
> I have the same issue while reimporting vrm model. Exactly with same numbers as in screenshot in topic. here is my vrm file and fbx model which i am converting https://drive.google.com/file/d/1LjfzFpDK9_VwupdoSmeaLaJJ4JCGT5sF/view?usp=sharing (vrm is to big(about 100 MB) to github so i uploaded ZIP it to google drive)

**Comment by hiroj** [comment]
#479
