### ISSUE TITLE
エクスポート時、ルートに回転・スケールがある場合にメッセージを出す

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/UniVRM#444]
GLTF に変換するときに、root(unity) を scene(gltf) にその子をroot(gltf)にしている。
scene(gltf) には TRS が無いのでうまくいかない。

rootに回転・スケールがある場合、
rootの親を追加するか、回転スケール用のノードを中間に挿入する必要がある。

**Comment by PoChang007** [comment]
VRMとGLBエクスポートする時にrootのTransform値がディフォルトじゃない場合はエラーメッセージ出すことになりました。
