### ISSUE TITLE
[v0.56.0] VRMSpringBone の Collider Groups がインポートされない

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#460]
**バグについて**

VRMファイルのインポート時、VRM Spring BoneコンポーネントのCollider Groupsプロパティーで、2つ目以降が「なし」になります。

**再現方法**

1. Unity Hubで新規3Dプロジェクトを作成する
2. [UniVRM-0.56.0_41b3.unitypackage](https://github.com/vrm-c/UniVRM/releases/download/v0.56.0/UniVRM-0.56.0_41b3.unitypackage) をインポートする
3. [AliciaSolid_vrm-0.51.vrm](https://github.com/vrm-c/UniVRM/blob/v0.56.1/Tests/Models/Alicia_vrm-0.51/AliciaSolid_vrm-0.51.vrm) をダウンロードして、インポートする

**期待する動作**

VRMファイルのインポート時、VRM Spring BoneコンポーネントのCollider Groupsがセットされる

**スクリーンショット**

![](https://user-images.githubusercontent.com/3625160/86504515-3bbaf700-bdf4-11ea-83f6-b23b65168490.png)

**環境情報**

 - OS: `Windows 10`
 - Unity version: `Unity-2018.4.20f1` `Unity-2019.4.2f1`
 - UniVRM version: `0.56.0`

**追加の状況・背景**

UniVRM-0.55.0で試したところ問題は発生しませんでした。

**Comment by ousttrue** [comment]
再現確認しました。
`v0.56.2` で修正するべく調査します。

**Comment by esperecyan** [comment]
v0.56.2で正常にインポートされることを確認いたしました。
早急にご対応いただきありがとうございます。
