### ISSUE TITLE
ColorSpace Linear を奨める

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/UniVRM#466]
ダイアログに表示するなど

**Comment by FMS-Cat** [comment]
Linearワークフローを推奨とし、何らかの形でユーザに提示するのは良いアイデアだと思います。

ただ、現状では多くのユーザおよびアプリケーションはGammaワークフローを想定してモデルを制作しており、これまでのモデルについては、この変更によって見た目が変わってしまうことが多いと想定されます。
