### ISSUE TITLE
UniGLTF runtime export not compatible with IL2CPP AOT compilation for iOS and Android

### ISSUE THREAD

**Issue by dblatner** [vrm-c/UniVRM#471]
Hey all!

when using the runtime export with `ToGlbBytes()` method for IL2CPP builds, the application crashes or reports a `NullReferenceException` and a `ExecutionEngineException: Attempting to call method 'System.Linq.Expressions.Interpreter.LightLambda::MakeRun0<System.Int32>' for which no ahead of time (AOT) code was generated.`.

![UniGLTF-bug](https://user-images.githubusercontent.com/3613737/86827122-e69c1100-c091-11ea-8109-8898d70d7e63.png)

I found the problem in the method
``` csharp
public static void KeyValue<T>(this IFormatter f, Expression<Func<T>> expression)
        {
            var func = expression.Compile();
            var value = func();
            if (value != null)
            {
                var body = expression.Body as MemberExpression;
                if (body == null)
                {
                    body = ((UnaryExpression)expression.Body).Operand as MemberExpression;
                }
                try
                {
                    f.Key(body.Member.Name);
                    f.Serialize(expression.Compile()());
                }
                catch
                {
                    
                }
                //var method = GetMethod(expression);
                //method.Invoke(this, new object[] { value });
            }
        }
```

IL2CPP ahead-of-time (AOT) compilation is not compatible with Expression Trees expression.Compile() method that uses JIT compilation of the expression.

More information can be found here:
- https://forum.unity.com/threads/are-c-expression-trees-or-ilgenerator-allowed-on-ios.489498/

Either the UniGLTF plugin must avoid having Int32 as parameters or return values and only use "string" or it should avoid using Expression Tree lambda functions.

How can the runtime export be changed to not use the Expression Tree??

**Comment by hiroj** [comment]
https://github.com/vrm-c/UniVRM/blob/8876a2c48ade775c310b34b8497c71c2bca210df/Assets/VRM/UniGLTF/Scripts/Format/glTF.cs#L471
ToGlbBytes can change Serializer Types.
Try a serializer other than UniJson.
