### ISSUE TITLE
unitypackageにフォルダが含まれていない

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#472]
**バグについて**

unitypackageにフォルダが含まれていないため、インポートするたびにフォルダのGUIDが変わってしまいます。

これは意図した動作でしょうか。

**再現方法**

1. Unity 2019.4.3f1 で新規プロジェクトAを作成
1. プロジェクトAへ [UniVRM-0.56.3_3b68.unitypackage](https://github.com/vrm-c/UniVRM/releases/download/v0.56.3/UniVRM-0.56.3_3b68.unitypackage) をインポート
1. プロジェクトAから Assets/VRM、Assets/VRMShaders をエクスポート
1. Unity 2019.4.3f1 で新規プロジェクトBを作成
1. プロジェクトBへ UniVRM-0.56.3_3b68.unitypackage をインポート
1. プロジェクトBから Assets/VRM/README.url (UniVRMに含まれる任意のファイル) を削除
1. プロジェクトBへ、エクスポートした unitypackage をインポート
1. GUIDが異なるという警告を確認できる

**期待する動作**

フォルダのGUIDが変わらない。

**スクリーンショット**

![](https://user-images.githubusercontent.com/3625160/87214156-382fee80-c365-11ea-8a8a-49be46f38c1c.png)

**環境情報**

 - OS: `Windows 10`
 - Unity version: `Unity-2019.4.3f1`
 - UniVRM version: `0.56.3`

**Comment by hiroj** [comment]
unitypackage作成時にフォルダのパス指定が無いからかもしれないです。確認してみます。

**Comment by esperecyan** [comment]
UniVRM-0.57.0_52e7.unitypackage で警告が出なくなったのを確認しました。
修正ありがとうございます。
