### ISSUE TITLE
Neutralをbakeするオプション

### ISSUE THREAD

**Issue by Rikurus** [vrm-c/UniVRM#485]
**バグについて**
VRMにエクスポートを行った際、
ブレンドシェイプのNEUTRALにアバターの体系（胸）を変更するブレンドシェイプの設定を行ったにも関わらず
実際にエクスポートしたもので確認すると標準では体系が変わっていない（ブレンドシェイプで変更される前の体系になる）

**再現方法**

拾い部屋　様作
【PC/Quest対応】VR用3dモデル「2A-7-4 / VRCXset　シヴィー/ヨツル/フォーシー/クールク」
https://booth.pm/ja/items/2019040

本アバターのシヴィーにて

1. 一旦モデルをエクスポートしてVRMモデルの出力準備を整える
2. シーン内に出現したモデルに対してブレンドシェイプにてBreast_Materialの設定を変更する
※NEUTRALにてBreast_Materialを100に設定
3. VRMへエクスポートし、VRMモデルに対応しているソフトで確認する
※確認したのはVDRAW、3tene

**期待する動作**

デフォルト表情ではブレンドシェイプのNEUTRALに設定されている状態で動作して欲しい
※或いは、UnityからVRMにエクスポートする際にブレンドシェイプの値をデフォルトで記憶して欲しい

**環境情報**

 - OS: [Windows 10]
 - Unity version: [Unity-2019.2.8f1]
 - UniVRM version: [0.56]

**追加の状況・背景**

なんとなくですが、VRMモデルを読み込んでいるアプリ側で
標準の表情として「NEUTRAL」を再生していないのではないか、ということも予想しています。
※標準の表情の場合はVRMモデルの初期値（全てのブレンドシェイプが0）として指定されているような

**Comment by Rikurus** [comment]
＞UnityからVRMにエクスポートする際にブレンドシェイプの値を記憶して欲しい
この件については一応、VRMエクスポート時に Pose Freeze にチェックを付けることで対応できました。
ただ、依然として「NEUTRAL」について使用されていないのようですのでそこは調査をお願いしたくございます。

**Comment by hiroj** [comment]
Export時にNEUTRALをベイク出来るように変更します。

**Comment by sh-akira** [comment]
(一応念のため)
拙作バーチャルモーションキャプチャーは正しくNEUTRALを標準の表情として使用するように(意図的に)処理を追加して対応してあります。
VRM対応アプリ作った際何もしないと全てのBlendShapeが0が初期になっているので、どちらかというとVRMBlendShapeProxyがデフォルトでNeutral適用したほうが良いような気もしますが、
既存のNEUTRALに対応してないアプリに影響与えないようにするには確かにベイク出来るほうが良いのかもしれません。
しかしベイクしてしまうと、そのNEUTRAL表情に別の表情が混ざったりしないか気になります。

**Comment by ousttrue** [comment]
次のような内容を予定しています。

* Exportのダイアログに Neutral を bake するチェックボックスを追加(デフォルト off。ユーザーが意図的にonにする必要あり)
* [チェックボックスがonのとき] 正規化する前に SkennedMeshRendererのBlendShape を neutral 状態にして bake する
* [チェックボックスがonのとき] blendShapePreset.Neutral はエクスポート対象から除外する

何か、お気づきの点があれば指摘していただれば。

**Comment by ousttrue** [comment]
![scene](https://user-images.githubusercontent.com/68057/99239541-8aff4280-283e-11eb-8f75-71801652d289.jpg)

`Pose-Freeze` でシーンの状態がベイクされる(T-Pose と BlendShape)という概念になります。
