### ISSUE TITLE
MatcapテクスチャがMipmap関連の何かでリムがジャギってしまう問題

### ISSUE THREAD

**Issue by m-sigepon** [vrm-c/UniVRM#49]
UniVRM v0.44のエディターインポートで読み込んだVRMをシーンに読み込むとMatCapテクスチャがMipmap関連の何かが原因でジャギってしまう問題が起きているようです。
ランタイムロードでは起きてないようです。
状態は、UniVRM v0.44でVRMファイルをインポートして新規シーンに配置しただけです。
この問題は、UniVRM v0.43でエディタ、ランタイムともの読み込みで起きていてv0.44テストバージョンで試したときは両者ともで解決していました。
MatCapテクスチャのGenerate Mip Mapをオフにすると綺麗になりますが、v0.44テストバージョンではオフにせずにキレイな状態になりました。
![default](https://user-images.githubusercontent.com/26161297/46822024-42563f00-cdc5-11e8-8229-500f8b603024.jpg)

こちらが、UniVRM v0.43とv0.44テストバージョンでエディターインポート、ランタイムロードで比較した画像です。
両者とも、MatCapテクスチャのGenerate Mip Mapはオンの状態でAniso Levelも1の状態です。
![univrm55](https://user-images.githubusercontent.com/26161297/46822133-9a8d4100-cdc5-11e8-8591-0d1eea5b6b3c.jpg)
![vrm22](https://user-images.githubusercontent.com/26161297/46822138-9eb95e80-cdc5-11e8-82fe-52b98591dd79.jpg)

**Comment by ousttrue** [comment]
![filtermode](https://user-images.githubusercontent.com/68057/46851957-3fdefe00-ce34-11e8-888d-e26d112573e3.png)
このあたり関係ないでしょうか。

GLTFでは、MipMap項目は無かったと思います。

**Comment by m-sigepon** [comment]
確認してみましたが、そちらの設定は関係無いようです。

**Comment by ousttrue** [comment]
#947 と同じ問題
