### ISSUE TITLE
Assets/VRM/DepthFirstScheduler/Functor.cs(80,55): error CS1525: Unexpected symbol `;', expecting `('

### ISSUE THREAD

**Issue by BunnySushibun** [vrm-c/UniVRM#498]
![image](https://user-images.githubusercontent.com/69126880/89134897-de02f300-d4f6-11ea-93cc-b35e0089e07c.png)

I just Installed the package, please help :(

**Comment by hiroj** [comment]
Please use the 2018.4 version of Unity and set the C# setting in PlayerSettings to ".net4.x".
