### ISSUE TITLE
コンストレイントをサポートしてほしい

### ISSUE THREAD

**Issue by m-sigepon** [vrm-c/UniVRM#50]
現在、VRMではSpringBoneによる揺れ物をサポートしていますが
それと同じように、拡張情報としてVRMでコンストレイントをサポートしてほしいです。
すでに、頭部などでLookAtとして特定の部位に対して実装されていると思います。
これを、セカンダリのように任意のジョイントに設定できる機能が欲しいです。
例えば、使いたい場所として体の、肘ボーンや膝ボーンやねじれ防止のツイストボーンをコンストレイントで追従させるというような箇所です。
それ以外にも、衣装の一部を連動させて動かしたいなどにもコンストレイントが可能になるとウェイトのみで処理しないといけない部分の問題が解決します。

サポートしてほしいコンストレイントとしては、Unity標準でサポートされているような以下のコンストレイントになります。
https://docs.unity3d.com/Manual/Constraints.html
・方向コンストレイント（Aim Constraints）
・位置コンストレイント（Position Constraints）
・回転コンストレイント（Rotation Constraints）
・スケールコンストレイント（Scale Constraints）

**Comment by ousttrue** [comment]
将来的には入れたいと思います。
今のところUniVRMはサポートをUnity-5.6からとしているので、`Constraint` のような新しいUnityにしかないコンポーネントを前提とする機能はつらいところもあります。
