### ISSUE TITLE
Output the texture size at the time of export in the size set in Texture Importer Settings

### ISSUE THREAD

**Issue by hiroj** [vrm-c/UniVRM#502]
* 現状はテクスチャAssetsにあるテクスチャをそのまま書き込んでいるが、これをTexture Importer Settingsで指定したサイズで書き込むように変更する。

**Comment by Santarh** [comment]
MToon の Shade Texture などに設定されたテクスチャが、適切なサイズで出力されない場合がある。
たとえば Texture Importer を MaxSize = 1024 にした 4K テクスチャを VRM 出力するとファイルには 4K が含まれてしまう。
