### ISSUE TITLE
Error when importing VRM to Version 2018.4.26f1

### ISSUE THREAD

**Issue by Seratonin** [vrm-c/UniVRM#518]
**Describe the bug**

The bug is when I simply import via the VRM menu and then click import. I select the .vrm files and it spits out the following errors.

Steps to reproduce the behavior: I imported two different VRM files with the same results.

create prefab: unity://Assets/AliciaSolid.prefab
UnityEngine.Debug:LogFormat(String, Object[])
UniGLTF.ImporterContext:SaveAsAsset(UnityPath) (at Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs:947)
VRM.<>c__DisplayClass0_0:<ImportMenu>b__0() (at Assets/VRM/UniVRM/Editor/Format/VRMImporterMenu.cs:61)
UnityEditor.EditorApplication:Internal_CallDelayFunctions() (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:209)

create prefab: unity://Assets/AliciaSolid_vrm-0.51.prefab
UnityEngine.Debug:LogFormat(String, Object[])
UniGLTF.ImporterContext:SaveAsAsset(UnityPath) (at Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs:947)
VRM.<>c__DisplayClass1_0:<ImportVrm>b__0() (at Assets/VRM/UniVRM/Editor/Format/vrmAssetPostprocessor.cs:52)
UnityEditor.EditorApplication:Internal_CallDelayFunctions() (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:209)

https://i.imgur.com/U3EuC7h.png

 - OS: [e.g. `Windows 10`]
 - Unity version: [e.g. `2018.4.26f1`]
 - UniVRM version: [`0.58.1_029d`]

Also while I am here quick question, does this package work with the latest version of Unity? Thanks.

**Comment by PoChang007** [comment]
Hi,

I think those are Debug messages. No worry about it. Your VRM should be fine. Have you tried importing your VRM at runtime yet?

Just tried the latest version in Unity Hub (Unity 2020.1.2f1) with UniVRM0.58.1_029d.  No problem on import/export
