### ISSUE TITLE
VRM exporting blank mesh

### ISSUE THREAD

**Issue by Eloritia** [vrm-c/UniVRM#519]
I'm trying to export and import the vrm to set up the bones and everything for VUP. The export seemingly goes fine from fbx, but when I try to import the vrm back into unity there is simply no mesh. The armature is still there, but the mesh is just gone. This is for 2020 Unity. 

In 2018 it just crashes when trying to import mesh.

 - OS:Windows 10
 - Unity version: Unity 2020 AND 2018.4.26f1
 - UniVRM version: 0.57.1_60a9

**Comment by hiroj** [comment]
If you encounter an error, please let us know the details. I will investigate.
If you can get the problematic VRM model, you can investigate further.

**Comment by hiroj** [comment]
If you have any problems with the new version, please reopen.
