### ISSUE TITLE
Spring Bones Not Working Well With Colliders

### ISSUE THREAD

**Issue by VRArt1** [vrm-c/UniVRM#52]
I've noticed that spring bones work pretty badly with colliders. As it currently stands I've only been able to get actual collision from then when moving VERY slowly. Which proves to be a challenge when you want to move around more quickly or even just want to do a basic dance. As you can see from the gyazos below the colliders just phase right through. In the third one it shows how slow I need to go in order to get the colliders to do anything.

https://gyazo.com/c4ac90812e892cab6fdc21e93684210e
https://gyazo.com/5ab063c099eb6411845dcf789787157c
https://gyazo.com/e34279502bb771b56005fb9cc45bdf92

**Comment by PoChang007** [comment]
Thanks for your feedbacks. We think that these problems cannot be prevented by spring bones. We are considering adopting cross simulation method in v1.0.

**Comment by VRArt1** [comment]
I don't use vrm much more myself now-a-days but I look forward to the updates since some of my clients do.
