### ISSUE TITLE
KeyNotFoundException

### ISSUE THREAD

**Issue by Ginyoru** [vrm-c/UniVRM#551]
been getting this error for the paste couple hours and tried pretty much everything to fix it without succes

https://pastebin.com/mMZNGxZb

**Comment by asuina** [comment]
I'm having the same issue, is there a solution?

**Comment by ousttrue** [comment]
BlendShapeClip reference to mesh may be corrupted.
`reference to mesh` is below.

<img width=500 src=https://user-images.githubusercontent.com/68057/93069935-36faa500-f6b9-11ea-9c45-87763cf85d1d.jpg>

Please fix this, before export.

I will show this issue in the GUI in the next version. I think it helps users fix the problem.

**Comment by Ginyoru** [comment]
![image](https://user-images.githubusercontent.com/25467422/93160048-88b52680-f6dd-11ea-8b39-27dc3e557322.png)
everything is perfectly fine on every blendshape

**Comment by ousttrue** [comment]
In v0.60.0, the export dialog now detects this issue. Please try it.

**Comment by ousttrue** [comment]
If 0.60.0 doesn't fix the problem, please reopen
