### ISSUE TITLE
Cannot export FBX to VRM

### ISSUE THREAD

**Issue by Yoposoc** [vrm-c/UniVRM#552]
**Describe the bug**

I cannot export a FBX into A VRM using the VRM Exporter. Under the "Exporter Version", there is nothing listed.
![image](https://user-images.githubusercontent.com/2718371/93054200-db2f0e00-f61d-11ea-95f5-98d32833627e.png)

**To Reproduce**

e.g. Steps to reproduce the behavior:

1. Have a FBX model
2. Click VRM -> UniVRM -> Export humanoid
3. See error

**Expected behavior**

I should be able to export.

**Screenshots**

There is one console output:
![image](https://user-images.githubusercontent.com/2718371/93054347-0ade1600-f61e-11ea-9520-37db4192c8cf.png)

**Environments (please complete the following information):**

 - OS: [Win 10
 - Unity version: Unity 2020.1.5f1 Personal
 - UniVRM version: 0.59.0_873a

**Comment by ousttrue** [comment]
Renderer may have null material.

<img width=500 src=https://user-images.githubusercontent.com/68057/93171551-471b8e80-f764-11ea-952a-a123f5a9e2f9.jpg>

I fix it so that the exception does not occur.

**Comment by ousttrue** [comment]
In v0.60.0, the export dialog now detects this issue. Please try it.

**Comment by ousttrue** [comment]
If 0.60.0 doesn't fix the problem, please reopen
