### ISSUE TITLE
Unlit/TextureをVRMに変換するとUniGLTF/UniUnlitのVertex Color Blend ModeがMultiplyになってしまう

### ISSUE THREAD

**Issue by masa-ibara** [vrm-c/UniVRM#565]
**バグについて**
Unlit/TextureをVRMに変換するとUniGLTF/UniUnlitのVertex Color Blend ModeがMultiplyになってしまう
Unlit/TextureはVertex Colorが反映されないため、UniGLTF/UniUnlitのVertex Color Blend ModeがNoneでないと見た目に差異が出る

**再現方法**
Vertex Colorに暗色系の色を入れ、UniVRM＞Export humanoidでVRM化

**期待する動作**
変換後のVRMを読み込んだ際にUniGLTF/UniUnlitのVertex Color Blend ModeがNoneになる

**環境情報**

 - OS: Windows 10
 - Unity version: Unity-2019.2.21f1
 - UniVRM version: 0.60.0

**Comment by ousttrue** [comment]
現状、`VColorを保持するが使わない` という選択ができません。

> Unlit を記録するときに、`GLTFのUnlit` として記録していて、 GLTF のマテリアルは、Vertex Color Blend Mode がありません。
そのため、 Import するときに Mesh が VertexColor を保持するか否かで Vertex Color Blend Mode を決めています。

対策としては、

![remove_vcolor](https://user-images.githubusercontent.com/68057/94226693-2bb63d80-ff33-11ea-85be-6c50a219ad6e.jpg)

を使ってください。

わかりにくいので、`Vertex Color Blend Mode == MultiPlay` の時以外は 自動で `Remove Vertex Color` を発動させることに変えることを検討します。
