### ISSUE TITLE
No Animator In ExportRoot

### ISSUE THREAD

**Issue by DemonRem** [vrm-c/UniVRM#566]
**Describe the bug**

No Animator in ExportRoot

**To Reproduce**

[girl.zip](https://github.com/vrm-c/UniVRM/files/5289670/girl.zip)

Model Attached

**Expected behavior**

once i import the model i try to export it by going to tab called VRM > UniVRM 0.58.0
after using the 60 version and its didn't work i try that version but  i get the same error

**Screenshots**

screenshot added
![1](https://user-images.githubusercontent.com/29927382/94385076-d8b7d280-014c-11eb-8fec-4939f19ffa76.png)

**Environments (please complete the following information):**

 - OS: Windows 10 64x
 - Unity version: Unity 2019.4.0f1 (64-bit)
 - UniVRM version: 0.58.0

**Comment by PoChang007** [comment]
Set animation type to `humanoid`. This error message should be gone.

**Comment by PoChang007** [comment]
closed. feel free to reopen this issue if the bug still persists.

thanks,
