### ISSUE TITLE
エクスポート時Title, Author, Versionをそれぞれ空欄にすると誤って「必須項目」と表示される

### ISSUE THREAD

**Issue by saturday06** [vrm-c/UniVRM#575]
**バグについて**

VRMエクスポート時にTitle, Author, Versionをそれぞれ空欄にすると「必須項目」と表示されますが、それは誤りです。

VRMの仕様は下記のようになっていて、[json schemaにおけるrequiredの指定](https://json-schema.org/understanding-json-schema/reference/object.html#required-properties)は無いです。そのため、それぞれの項目は「必須項目」ではありません。

https://github.com/vrm-c/vrm-specification/blob/8b34abe6fb6775e0d5d8740a227995cc2be311c6/specification/0.0/schema/vrm.meta.schema.json#L5-L16
```json
 "title": { 
     "description": "Title of VRM model", 
     "type": "string" 
 }, 
 "version": { 
     "description": "Version of VRM model", 
     "type": "string" 
 }, 
 "author": { 
     "description": "Author of VRM model", 
     "type": "string" 
 }, 
```

**再現方法**

VRMをエクスポートする際、Title, Version, Authorのそれぞれの入力欄を空欄にします。

**期待する動作**

- Title, Author, Versoinそれぞれが無くてもエクスポートできるようにする。
- これを必須にする場合は、互換性が無くなるためVRMのバージョンを0.1などに更新する。

**スクリーンショット**

![キャプチャ](https://user-images.githubusercontent.com/532872/95678322-e10d1480-0c06-11eb-9985-5dfbb83612cd.PNG)

**環境情報**

 - OS: Windows 10
 - Unity version: Unity-2018.4.27f1
 - UniVRM version: 0.61.0

**追加の状況・背景**

VRM 1.0のほうも必須になってないようにみえます。
https://github.com/vrm-c/vrm-specification/blob/7f9ae0baf8f1fdc6c3e0850338324dc699eaa3cf/specification/VRMC_vrm-1.0_draft/schema/VRMC_vrm.meta.schema.json#L6-L20

**Comment by ousttrue** [comment]
これは  `JsonSchema` の方の記述漏れです。
JsonSchema の方を修正します。

**Comment by ousttrue** [comment]
https://github.com/vrm-c/vrm-specification/issues/178

**Comment by saturday06** [comment]
いや、さすがに記述漏れの誤りにしても互換性の無い仕様の変更なので、仕様のバージョンを上げる必要があると思います。このような互換性の無い仕様変更が許されるならこれよりも先に `ussage` などのtypoや、軸の混乱などを直してほしいです。

**Comment by saturday06** [comment]
ん、でも非互換の変更を0.x系で行うのは今までの方針に反する気がしますね。typoなどの修正を行っていないのはそのためだったと思います。

@ousttrue  この件って、非互換の変更を行うに足る重大な問題なのでしょうか？

**Comment by saturday06** [comment]
後方互換性を保つため、 https://github.com/vrm-c/vrm-specification/issues/178 で0.x系で空欄の場合はデフォルト値を設定する提案をしました。

**Comment by ousttrue** [comment]
> @ousttrue この件って、非互換の変更を行うに足る重大な問題なのでしょうか？

重大じゃないので、やめることになりました。

一方で、Title, Author, Version は引き続き UniVRM の実装では必須を維持します。
これらの項目の有無に関してエラー処理をしていないコードがありえます(必須に見える状態だった)し、アプリやライブラリで追加の必須項目があることは重大な問題とならないと思われます。

**Comment by saturday06** [comment]
承知しました。UniVRM 0.xとVRM 0.0の組み合わせは実験的な意味合いもあると思っているのでこの対応でも良いのかなと思います。VRM 1.0を処理するUniVRM 1.xで同様の事象が発生した場合はちょっと困ると思うので、そういうことが無いことを祈ります。
