### ISSUE TITLE
Spring Bone Collider dosen't work correctly in 0.61.0

### ISSUE THREAD

**Issue by Yan-K** [vrm-c/UniVRM#576]
**Describe the bug**

Spring Bone Collider dosen't work correctly in 0.61.0

**To Reproduce**

Any VRM file contain Spring Bone and Spring Bone Collider.

**Screenshots**

![Collider1](https://user-images.githubusercontent.com/44521090/95704427-60402e00-0c83-11eb-88e1-6316aea5e6c4.png)
![Collider2](https://user-images.githubusercontent.com/44521090/95704452-75b55800-0c83-11eb-8730-0e5866ce9be2.png)
![ColliderAnime](https://user-images.githubusercontent.com/44521090/95704386-38e96100-0c83-11eb-87c8-ed54ff968b96.gif)

**Environments (please complete the following information):**

 - OS: Windows 10
 - Unity version: Unity 2019.3.14f1
 - UniVRM version: 0.61.0

**Additional context**

Full bug video, Collider in 0.60.0 compare to 0.61.0:
https://youtu.be/LQussyX6YDQ

**Comment by ousttrue** [comment]
We have released v0.61.1 which fixes the bug.

https://github.com/vrm-c/UniVRM/releases/tag/v0.61.1

Please try.

**Comment by Yan-K** [comment]
Yes, 0.61.1 fixed my problem, thanks a lot for the hard work!
