### ISSUE TITLE
テクスチャに基づいたヒューマノイドエラーをエクスポート

### ISSUE THREAD

**Issue by ZexMaxwell001** [vrm-c/UniVRM#585]
DeepL機械化翻訳 と 同業者同士で翻訳:

Humanoid のエクスポートは行いません。テクスチャに関連するもの 
エラーメッセージが曖昧すぎて、ユーザーが解読することができません。
VRMファイルが作成されていません。
エラー: https://pastebin.com/LWNfZEfm

**再現するには**

PSO2からNinja ripperでリッピングしたモデル。
テクスチャは.DDSを使用。
.FBX 3DS Maxで作成。
FBXファイル: https://drive.google.com/file/d/1VFqWvLpJzKLleRHt71_VK1T6A0A0qeQN/view?usp=sharing

**想定される動作**

作成される.VRM。
または
わかりやすいエラーメッセージで問題を修正します。

**環境：＊＊。

OS: `Windows 10
Unity version: Unity-2019.4
UniVRM version: 61.1

English:

Does not export Humanoid. something related to a texture. Error message is too ambiguous for user to decipher 
No VRM file created.
Error: https://pastebin.com/LWNfZEfm

**To Reproduce**

Model ripped from PSO2 with Ninja ripper.
Textures are made from .DDS
.FBX Made in 3DS Max.
FBX file: https://drive.google.com/file/d/1VFqWvLpJzKLleRHt71_VK1T6A0A0qeQN/view?usp=sharing

**Expected behavior**

An .VRM to be created.
or
understandable error message to correct the issue.

**Environments (please complete the following information):**

 - OS: `Windows 10
 - Unity version: Unity-2019.4
 - UniVRM version: 61.1

**Comment by PoChang007** [comment]
Hi,

This problem should have been solved in the latest UniVRM version. Try `0.74.0`.

#831 #829

Thanks,
