### ISSUE TITLE
拡張子 glTF のファイルを UnityEditor で読み込むときに MetallicRoughness マップを PNG で保存する

### ISSUE THREAD

**Issue by Santarh** [vrm-c/UniVRM#587]
Unity Editor で Import した glTF ファイルが参照する PBR の Metallic-Roughness 情報は
Unity の Standard Shader の入力に合わせてチャンネルを再解釈し `asset` ファイルとして Project に保存される。

しかしサイズ変更といった最適化や、内容の編集において `asset` ファイルは取り回しが悪く
`png` ファイルになっていたほうが望ましい。

**Comment by ousttrue** [comment]
Linear

**Comment by Santarh** [comment]
Import した Metallic-Roughness マップは内部値が Linear になっていると思われるため、そのときは Unity の EditorTexturrImporter の sRGB フラグをオフにしなければならない。

**Comment by ousttrue** [comment]
glb は ScriptedImporter化しました。
extract 時に、

TextureImporterの設定

* MetallicRoughness, Occlusion => sRGB = false
* NormalMap => isNormalMap = true

となるようになりました。
