### ISSUE TITLE
BlinkerでInter Valなどの変数がPrivateになっている

### ISSUE THREAD

**Issue by yahagi-day** [vrm-c/UniVRM#589]
現在Blinkerの変数(m_interValなど)はSerializeFieldになっておりUnityEditorからは変更可能ですがScriptから編集できず、動的に生成されたモデルにAttachした場合にまばたきの間隔などが変更できません。
特別な理由がなければpublic変数にして欲しいです。

**Comment by ousttrue** [comment]
なんで `m_interVal` なんだろう・・・。
public にしました。
