### ISSUE TITLE
VRMExportエラー

### ISSUE THREAD

**Issue by mikonaka** [vrm-c/UniVRM#593]
**バグについて**

手順通りVRMExportすると、エラーが出ます。vrmファイルは作成されますが、開いても何も表示されません。

**再現方法**

マニュアルどおりに進めて最初の正規化（Export）した時。
画像のようなエラーが出ます。
![002](https://user-images.githubusercontent.com/73706773/97720380-9139b300-1b0b-11eb-943e-2db429176e45.jpg)
![003](https://user-images.githubusercontent.com/73706773/97720382-926ae000-1b0b-11eb-87cf-2e8f16b458be.jpg)
![004](https://user-images.githubusercontent.com/73706773/97720383-93037680-1b0b-11eb-874d-3e4a33881317.jpg)
![005](https://user-images.githubusercontent.com/73706773/97720385-93037680-1b0b-11eb-8843-693f3e633146.jpg)
![006](https://user-images.githubusercontent.com/73706773/97720387-939c0d00-1b0b-11eb-9b24-7f99e0eff015.jpg)
![001](https://user-images.githubusercontent.com/73706773/97720389-939c0d00-1b0b-11eb-9f72-d9d8aed4c8ae.jpg)

**環境情報**

 - OS: Windows 10
 - Unity version: Unity-2019.4.13f1
 - UniVRM version: 0.61.1

**追加の状況・背景**
Mayaで作成した自作の3Dモデルです。

**Comment by yahagi-day** [comment]
エラーでは無くただのLog出力なので正常にExportされているように見えます。

可能であるなら出力したVRMファイルを共有して頂くと何か分かるかもしれません。

**Comment by mikonaka** [comment]
ありがとうございます。解決いたしました。
エラーではないということ教えていただいたので、助かりました。
FBXの時点で、Rootボーンをメッシュの子にしていたのが原因だったようです。
