### ISSUE TITLE
"Force T Pose" option is too easy to overlook

### ISSUE THREAD

**Issue by emilianavt** [vrm-c/UniVRM#595]
**Describe the bug**

Recently, I had a number of people who reported issues with strange arm and finger bending while hand tracking. The cause was often that a model was exported in A pose, not T pose. Fixing it takes some time, because it needs to be explained to the user that the model needs to be reexported from FBX not VRM and that the "Force T Pose" option on the "Export Settings" tab needs to be enabled.

**To Reproduce**

Not applicable.

**Expected behavior**

I would like to suggest implementing one of the following to improve ease of use:
- If the avatar being exported is not already VRM, default to enabling the "Force T Pose" option instead of having it disabled by default.
- Somehow detect if the avatar is not in T pose and show a warning, telling the user to enable the option or enabling it by default. This could perhaps be done by comparing Y coordinates of hand and shoulder bones.
- Showing the option directly on the export tab instead of "Export Settings" would make it easier to discover for new users.

**Screenshots**

Not applicable.

**Environments (please complete the following information):**

Not applicable.

**Additional context**

Not applicable.

**Comment by ousttrue** [comment]
#559 implement T-Pose validation

**Comment by emilianavt** [comment]
Thank you! That's perfect!

**Comment by marcusx2** [comment]
@ousttrue @emilianavt Can I call the Force T-Pose at runtime?
