### ISSUE TITLE
[How To]Any way to Export VRM on Runtime?

### ISSUE THREAD

**Issue by Yukakiri0213** [vrm-c/UniVRM#602]
Is there any way to export VRM on Runtime?(and can be used by build binary?)

if There is, how to do that?

**Comment by yahagi-day** [comment]
UniVRM-samples-0.XX.X_XXXX.unitypackage should contain a sample run-time export.

https://vrm.dev/docs/univrm/install/univrm_install_samples/

**Comment by ousttrue** [comment]
`Assets/VRM.Samples/Scenes/VRMRuntimeExporterSample.unity`

**Comment by Yukakiri0213** [comment]
I didn't notice that VRM.Sample have runtime export functions. thank you very much!!
