### ISSUE TITLE
VRMLookAtHead and VRMLookAtBoneApplyer should prioritize over animator

### ISSUE THREAD

**Issue by TigerHix** [vrm-c/UniVRM#612]
**Describe the bug**

When an animator is added to the VRM GameObject to play an idle animation, VRMLookAtHead and VRMLookAtBoneApplyer no longer take control of the eye bones.

I tried adding an avatar mask to the animation like this:

![image](https://user-images.githubusercontent.com/3406505/99178791-c5ed6300-26e4-11eb-9489-76e15657ae4e.png)

But it doesn't work. :(

Is there a workaround or I am understanding something incorrectly?

Thanks!

**Environments (please complete the following information):**

 - OS: Windows 10
 - Unity version: Unity 2019.4.13f1
 - UniVRM version: 0.61.1

**Comment by yahagi-day** [comment]
Is your Avater mapping set up correctly?
You can check this by opening the fbx inspector you imported and clicking on the configure in the rig tab.
![image](https://user-images.githubusercontent.com/32870950/99205899-40110b00-27fd-11eb-97f2-807b571a8e0d.png)

Also, you probably won't be able to use AvaterMask in VRM. because it won't output the Animation Controller set in the Animator.

**Comment by TigerHix** [comment]
@yahagi-day This actually reminds me something that I forgot to mention. The VRM avatar does not show anything in the inspector.

![image](https://user-images.githubusercontent.com/3406505/99215994-8ab16980-27a2-11eb-9bc0-d8fb6e2836f4.png)

As for the FBX you mentioned - I imported a VRM file directly, so there is no FBX anywhere :/ There are some .mesh generated in the `[Name].Meshes` folder, but I don't think UniVRM has unpacked a FBX. Thanks for helping though!

**Comment by ousttrue** [comment]
![try_lateupdate](https://user-images.githubusercontent.com/68057/99220750-93498480-2822-11eb-8b0b-46762c9d12e6.jpg)

Animator overwrite all Transform between update and lateUpdate.
Please try use lateUpdate.

**Comment by yahagi-day** [comment]
My reply was off the mark.
And with Late Update, it did indeed work.

**Comment by TigerHix** [comment]
@ousttrue @yahagi-day Thank you both! Yes, this workaround indeed worked. Closing this ticket.

I am also assuming this would mean avatar masks would not work on VRM, correct?

**Comment by yahagi-day** [comment]
avatermask disables the animation in the specified area, but this is a script operation and cannot be disabled.
