### ISSUE TITLE
materials not created

### ISSUE THREAD

**Issue by DemonRem** [vrm-c/UniVRM#624]
**Describe the bug**

i using the latest version of univrm with unity version 2018.4.29f1
and its give me an error once generated fbx
![1](https://user-images.githubusercontent.com/29927382/100016412-0c784700-2de2-11eb-9866-778b734cc782.png)

**Environments (please complete the following information):**

 - OS: Windows 10
 - Unity version: 2018.4.29f1
 - UniVRM version: v0.62.0

**Comment by yahagi-day** [comment]
mmd4mecanim is an external plugin and has nothing to do with UniVRM.
It's wrong to ask questions here.
