### ISSUE TITLE
Custom Blendshapes Disappear In Blendshape Animation Driver After Unity Reset

### ISSUE THREAD

**Issue by CadetDelValle** [vrm-c/UniVRM#628]
**Describe the bug**

-When adding custom blendshapes to a VRM and then leave Unity, you go back to the blendshape animation driver and the custom blendshapes are no longer registered.

**To Reproduce**

1. Import VRM model without custom blendshapes (Exported from FBX)
2. Add a custom Blendshape
3. Save Project
4. Exit Unity
5. Go back to the project before and look at the Blendshape animation driver (The custom blendshapes will no longer be there but in the assets panel)

If there are some minimal examples(e.g. model files) to reproduce the behavior, please attach them to this issue.

-N/A

-Upon Unity reset, custom blendshapes would stay in the Blendshape animation driver in case for future editing of the VRM file.

BEFORE: Added a custom blendshape before Unity reset.
![image](https://user-images.githubusercontent.com/75085867/100373281-896d1180-2fd8-11eb-8817-5fda11f60811.png)

AFTER: Resets Unity and checks the Blendshape animation driver.
![image](https://user-images.githubusercontent.com/75085867/100373441-c802cc00-2fd8-11eb-80f0-5f0e6e71aa88.png)

**Environments (please complete the following information):**

 - OS: Windows 10
 - Unity version: Unity-2019.1.6f1
 - UniVRM version: 0.62.0

**Additional context**

-Unsure if this is a bug regarding UniVRM or Unity itself but this happens with older versions of UniVRM like 0.58.

**Comment by ousttrue** [comment]
SetDirty cause write assets modification.

```c#
                    m_avatar.Clips.Add(clip);

                    // save clips
                    EditorUtility.SetDirty(m_avatar);
```

**Comment by ousttrue** [comment]
`v0.65.0`
