### ISSUE TITLE
VRMFirstPerson.Setup() の他人用バージョンを追加する

### ISSUE THREAD

**Issue by TORISOUP** [vrm-c/UniVRM#633]
**バグについて**

[VRMFirstPerson](https://vrm.dev/docs/univrm/firstperson/univrm_firstperson/) がセットアップ対象が「自分自身のアバター」であるか「他人のアバター」であるかを考慮できていない。

そのためネットワーク同期するVRシステムなどを構築していた場合、「`FirstPersonOnly`」「`ThirdPersonOnly`」を設定しているメッシュは「全員の目から見えなくなる」か「全員の目に映るか」という挙動になってしまう。

「自分のアバターのみ`VRMFirstPerson.Setup()`を実行する」「他人のアバターは何もしない」という使い方をすれば回避できなくもないが、この場合は`FirstPersonOnly`が使えなくなってしまう（FirstPersonOnlyなのに他人に見えてしまう）

**再現方法**

例: 動作の再現させる手順:

1. VRMFirstPersonで可視設定をを設定する
2. VRSNSようなシステムを構築する
3. 読み込んだすべてのVRMに対して`VRMFirstPerson.Setup()`を実行する

**期待する動作**

`VRMFirstPerson.Setup(bool: isMine)` のように、「他人のアバターであるかどうか」のフラグを渡すなどしたい。

**環境情報**

 - OS: Windows 10
 - Unity version: 2020.1
 - UniVRM version: v0.62.0

**Comment by ousttrue** [comment]
`VRMFirstPerson.SetupForOther` を追加する感じにしようと思います。

* FirstPersonOnly => 表示されないようにする
* ThirdPersonOnly => そのまま表示する
* Auto => ThirdPersonOnly と同じ？

関数名は、 `HideFirstPersonOnly` でいいかもしれない。

**Comment by ousttrue** [comment]
既存

```cs
                    case FirstPersonFlag.FirstPersonOnly:
                        x.Renderer.gameObject.layer = FIRSTPERSON_ONLY_LAYER;
                        break;

                    case FirstPersonFlag.ThirdPersonOnly:
                        x.Renderer.gameObject.layer = THIRDPERSON_ONLY_LAYER;
                        break;

                    case FirstPersonFlag.Both:
                        //x.Renderer.gameObject.layer = 0;
                        break;
```

自VRM VRMFirstPerson.Setup

| 設定            | layer                       |
|-----------------|-----------------------------|
| FirstPersonOnly | FIRSTPERSON_ONLY_LAYER      |
| ThirdPersonOnly | THIRDPERSON_ONLY_LAYER      |
| Both            | 何もしない                      |
| Auto            | BothとFirstPersonOnlyに分割する |


自分以外のVRM

| 設定            | layer                       |
|-----------------|-----------------------------|
| FirstPersonOnly | 消えるべき                      |
| ThirdPersonOnly | 何もしない                      |
| Both            | 何もしない                      |
| Auto            | BothとFirstPersonOnlyに分割する |

こう？

**Comment by Santarh** [comment]
合ってそう。
以下は設定とカメラの種類の組み合わせのうち、それが描画されるべきかされないべきかを表した表

-- | HMD から見た自分のアバター | その他から見た自分のアバター | HMD から見た他人のアバター | その他から見た他人のアバター
--- | --- | --- | --- | --- 
FirstPersonOnly | v | - | - | - 
ThirdPersonOnly | - | v | v | v 
Both | v | v | v | v
