### ISSUE TITLE
FreezT-Poseによって膝の向きが変更されてしまう問題

### ISSUE THREAD

**Issue by pixiv-sigepon** [vrm-c/UniVRM#634]
**バグについて**

FreezT-Poseを実行すると、UniHumanoidのResoucesに入っているT-Pose.poseというScriptableObjectに保存されているMuscle値を参照してTポーズ化を行うようですがこれにより膝の向きがおかしくなってしまいます。
これによって、FinalIKのVRIKなど膝の向きによって足の曲がる方向が決まるアセットで問題が起きています。
ニコニ立体ちゃんでは、足が蟹股になります。

**再現方法**
こちらで、配布してるニコニ立体ちゃんにFreezT-Poseを実行する
FinalIKのFullBodyBipedIKを適用すると膝の向きが確認できるので、膝の向きが外側を向くことを確認できます。
https://3d.nicovideo.jp/works/td14712

**期待する動作**
FreezT-Poseを実行前は、膝の向きが正面を向いた状態でありFreezT-Poseを実行してもそれを維持してほしい。
それにより、VRIKでしゃがんだ際に足がクロスしたり蟹股になる問題が解決します。

**スクリーンショット**

ニコニ立体ちゃんは、足が完全に正面を向いておりX軸（横からみてくの字になるように）値が入ってるだけのためサンプルとして適切と思い選定しました。
画像は、Humanoidの設定画面です。
![image](https://user-images.githubusercontent.com/57120933/101145364-07768b80-365d-11eb-8cc1-0cceea612988.png)
![image](https://user-images.githubusercontent.com/57120933/101145453-25dc8700-365d-11eb-8ae7-499611dc1685.png)
Leg_Rには一切回転値は入っていない
![image](https://user-images.githubusercontent.com/57120933/101146058-e8c4c480-365d-11eb-8eb9-278e4ab04f58.png)
Knee_LのX軸にのみ値が入っている
![image](https://user-images.githubusercontent.com/57120933/101145891-b87d2600-365d-11eb-8d10-36827fce9d02.png)

ニコニ立体ちゃんを、元の状態でFullBodyBipedIKを適用して膝の向きを確認した状態（ワールドに対して正面を向いている）
![image](https://user-images.githubusercontent.com/57120933/101144273-6804c900-365b-11eb-8a52-666ae3d4e293.png)
![image](https://user-images.githubusercontent.com/57120933/101144312-7357f480-365b-11eb-9c35-ab4b94fbc5d0.png)
VRIKを適用してHead Targetに適当なゲームオブジェクトを割り当てしゃがませた状態（足がキレイに正面を向いて曲がっている）
![image](https://user-images.githubusercontent.com/57120933/101144482-bc0fad80-365b-11eb-94b1-9380390e49f3.png)
![image](https://user-images.githubusercontent.com/57120933/101144498-c29e2500-365b-11eb-8042-f769deca3fbc.png)

ニコニ立体ちゃんに、FreezT-Poseを実行してFullBodyBipedIKを適用して確認した状態（膝が外側を向いている）
![image](https://user-images.githubusercontent.com/57120933/101144880-54a62d80-365c-11eb-9c81-30ec74ba7fb3.png)
FreezT-Poseを実行してしゃがませた状態（FreezT-Pose実行前は綺麗に正面を向いてしゃがめていたのが蟹股になってしまっている）
![image](https://user-images.githubusercontent.com/57120933/101145097-a5b62180-365c-11eb-9c5d-27788945f0f8.png)

VRMとしてエクスポート後も同様の状態になり、同様の問題が起きます。
![image](https://user-images.githubusercontent.com/57120933/101147793-2b879c00-3660-11eb-92c4-8e23ed936361.png)
![image](https://user-images.githubusercontent.com/57120933/101147855-3fcb9900-3660-11eb-89ce-b811a7c4bf35.png)

VRoidモデルのケース
FreezT-Pose前は、FullBodyBipedIKを当てて確認すると膝が適切に正面を向いています。
![image](https://user-images.githubusercontent.com/57120933/101146508-6b4d8400-365e-11eb-9d75-bc77588ccddd.png)
VRIKを適用しても、膝が正面を向いてしゃがむことできます。
![image](https://user-images.githubusercontent.com/57120933/101146814-d0a17500-365e-11eb-8636-250047722700.png)
FreezT-Poseを実行して、FullBodyBipedIKを適用して確認すると膝の向きが内側を向いてしまっている
![image](https://user-images.githubusercontent.com/57120933/101146935-034b6d80-365f-11eb-99b7-aa4a15f2a291.png)
VRIKを適用して、しゃがませるとFreezT-Poseによって膝の向きがおかしくなった方向に足がクロスしてしまう
![image](https://user-images.githubusercontent.com/57120933/101147031-2d049480-365f-11eb-87d6-9f1945c37d1e.png)

VRMとしてエクスポート後も同様の状態になり、同様の問題が起きます。
![image](https://user-images.githubusercontent.com/57120933/101147444-b9af5280-365f-11eb-9d08-a5357ac069dd.png)
![image](https://user-images.githubusercontent.com/57120933/101147564-e5323d00-365f-11eb-9f92-3334dde9153b.png)

手元で独自に、足の状態を維持して腕のみにTポーズ処理を行った状態
FullBodyBipedIKを適用して確認して、膝の向きが正面を向いてるのを確認できます。
![image](https://user-images.githubusercontent.com/57120933/101147973-6f7aa100-3660-11eb-8deb-112e42423192.png)
VRIKを適用して、頭の位置を下げても足がちゃんとTポーズ状態で正面を向いてる方向に曲がります。
![image](https://user-images.githubusercontent.com/57120933/101148209-b7012d00-3660-11eb-9294-c11f4a21117a.png)
![image](https://user-images.githubusercontent.com/57120933/101148239-bc5e7780-3660-11eb-8ac6-8b1fb0cde704.png)

VRMとしてエクスポート後でも、元状態の膝の方向がちゃんと維持されています。
![image](https://user-images.githubusercontent.com/57120933/101148647-3abb1980-3661-11eb-8765-233e96f3e93d.png)
![image](https://user-images.githubusercontent.com/57120933/101148803-6ccc7b80-3661-11eb-862d-181bd82881bc.png)
![image](https://user-images.githubusercontent.com/57120933/101148827-71912f80-3661-11eb-831a-e5869544ccac.png)

T-Pose.poseは、UniHumanoidのHumanPoseTransferのPose to HumanPoseClipで作成されているデータのようなので上記の独自に作成したポーズをT-Pose.poseとして置き換えることでVRoid Studioから出力されるデータでこのクロスする問題はおそらく解決できると思います。
ただし、UniVRMでユーザーが再度FreezT-Poseを実行すると現状UniVRMに同梱されるT-Pose.poseによって膝の向きがおかしくなってしまいます。
この問題は、UniVRMに同梱されているデフォルトのT-Pose.poseは何かのモデルから作成したTポーズデータであるが、そのモデル固有のMuscle値のデータであるため別のモデルに適用するとモデルにより差異があるために膝の向きなどに問題が起きてるのではと思います。
その為、FreezT-Poseを実行して膝の向きがおかしくならない根本対処を行っていただきたいです。
ちなみに、UnityのForceT-PoseはUnityのTポーズ基準内であれば下半身のポーズは維持する処理のようです。
検証したところ、Humanoidが許容する一定の状態を超えると足にもTポーズ処理が入りますが足の自動Tポーズ化はかなり怪しいようです。
その為、足は元の状態を維持するというような処理が望ましいのではないかと思いました。

**環境情報**

 - OS: [e.g. `Windows 10`]
 - Unity version: [e.g. `Unity-2019.4.12f1`]
 - UniVRM version: [e.g. `0.62.0`]

**追加の状況・背景**

この問題に関するその他の状況・背景など記載したい場合にここに記載してください。

**Comment by ousttrue** [comment]
version 0.62 はこうなってます。
`T-Pose` にするボタンでシーン上のモデルに同じ処理を適用できますが、これは `義務ではない` です。
シーン上で T-Pose にするのがめんどくさい方のために一応残してありますが、もう必要無いかと思います。

![dialog62](https://user-images.githubusercontent.com/68057/101155376-5ecf2880-366a-11eb-851f-92e5e7aa46f7.jpg)

`FreezT-Pose` はたぶん `Force T Pose` の間違いであろうということで、

https://vrm.dev/docs/univrm/export/univrm_export/#force-t-pose

の説明ごらんください。

義務ではないことが分かりづらいかもしれないので、
`Force T Pose` はチェックボックスは、ボタンになりました。

**Comment by pixiv-sigepon** [comment]
Freeze T-PoseはUniVRMのメニュー上で表記されております。
![image](https://user-images.githubusercontent.com/57120933/101156959-bc647480-366c-11eb-9cf1-f7776cf26540.png)

また、義務ではないとのことですがTポーズではないモデルに対してモーションを流し込む上でTポーズ化は必要です。
その為、T-Poseにする機能で起きている問題ですので改善頂きたいです。

**Comment by pixiv-sigepon** [comment]
すみません、誤ってクローズしてしまいましたので戻しました。

**Comment by ousttrue** [comment]
ええと、お読みいただけたでしょうか。これ。
> エクスポート前に強制的にT-Poseにします。 手動でだいたいT-Poseに出来た場合は、チェックしなくても問題ありません。

手の角度が 大きく水平からずれているときはエクスポートできないようにエラーチェックしていますが、それ以外はユーザーに任せております。

**Comment by pixiv-sigepon** [comment]
はい、ドキュメントの方は読みました。
その上で、T-Pose化機能を利用する場合は膝の向きがおかしくなってしまうのでその改善をお願いしたいという要望です。
![image](https://user-images.githubusercontent.com/57120933/101163808-85e02700-3677-11eb-89b3-51f2f6253b1e.png)

例えば、コンストレイント機能が今後実装されますがコンストレイント機能を使うか使わないかはユーザー次第だと思いますが、コンストレイント機能に問題があったら改善する必要があるというのと同じかと思います。

**Comment by ousttrue** [comment]
#868
