### ISSUE TITLE
Face Materials are Transparent

### ISSUE THREAD

**Issue by DemonRem** [vrm-c/UniVRM#638]
If there are some minimal examples(e.g. model files) to reproduce the behavior, please attach them to this issue.

Model Uploaded 

The Model Materials are totally transparent i choose in the materials section material style to be VRM > Cartoon

ScreenShot Uploaded

**Environments (please complete the following information):**

 - OS: Windows 10 64x
 - Unity version: Unity-2018.4.29f1
 - UniVRM version: v0.62.0

**Additional context**

i try the model under vmagicmirror and its work just fine but other software like "VUP , 3tene, Facerig" meet the same error

[Hatsune(normalized).zip](https://github.com/vrm-c/UniVRM/files/5683263/Hatsune.normalized.zip)
![bug](https://user-images.githubusercontent.com/29927382/101987111-cd2f6e80-3c9a-11eb-8c53-da86d17f2fb5.png)

**Comment by PoChang007** [comment]
I think `face` material doesn't need to be set as transparent. Also try setting up `Render Queue` for transparent materials.

**Comment by PoChang007** [comment]
closed. feel free to reopen this issue if the problem still persists.

thanks,
