### ISSUE TITLE
スクリーンショット作成ボタンで作成される画像が中身はJPEGなのにMIMEがimage/pngになっている

### ISSUE THREAD

**Issue by superswanman** [vrm-c/UniVRM#639]
VRMMetaObjectEditor.cs の TakeScreenShot() 内において EncodeToJPG したデータを拡張子 png で保存していることが原因と思われます。

**Comment by ousttrue** [comment]
修正

**Comment by superswanman** [comment]
@ousttrue 
対応ありがとうございます。
確認したところ、ここで渡された拡張子をJoinした結果、"png,jpg"という拡張子で保存されてしまっているようです
https://github.com/vrm-c/UniVRM/blob/bfde101c869c18ca0a9ab884126cd756a8fdfe5a/Assets/VRM/Editor/Meta/VRMMetaObjectEditor.cs#L295

**Comment by ousttrue** [comment]
<img width=400 src=https://user-images.githubusercontent.com/68057/103743512-a23cfe00-503f-11eb-94a6-c7da4e56d276.jpg>

うーん 🤔 。よし、 `jpg` やめます。

**Comment by ousttrue** [comment]
PNGを作るように修正
