### ISSUE TITLE
blendshapeGroupのマテリアルバインドについて

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#64]
https://github.com/dwango/UniVRM/blob/master/specification/0.0/schema/vrm.blendshape.materialbind.schema.json
名前でバインドターゲットを決めるようですが、マテリアルの名前が同じものがある場合の挙動はどうなっていますでしょうか。
material.nameはユニークでなくてよいので、マテリアル名の重複はあり得ると思うのですが。（というより、Vroid0.3.0のサンプルモデルのjsonは２つのマテリアル名が重複している
参考： https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materialname

**Comment by ousttrue** [comment]
フィードバックありがとうございます。

作成した当初はランタイムエクスポートは考慮されていませんでした。
また、アセットとしてファイルを作るので同じ名前は困るので
Importerで強制リネームをかけていました。

https://github.com/ousttrue/UniGLTF/blob/master/Core/Scripts/IO/ImporterContext.cs#L673-L682

なので、後で格納されている方が違う名前になる挙動になると思います。

使っているところこのあたり
https://github.com/dwango/UniVRM/blob/master/Scripts/BlendShape/MaterialValueBindingMerger.cs

GLTF的には名前はあってもなくてもいいような扱いなのですが、
VRMでは破綻してしまうので仕様として名前がユニークであることを追加しようと思います。

エクスポーターでマテリアル名の重複をエラーにすることを検討します。

**Comment by FMS-Cat** [comment]
本件、マテリアルのインデックスではなく、マテリアル名での指定となっているのには理由がありますでしょうか？
`extensions.VRM.materialProperties` では `materials` のインデックスを用いて参照しているため、こちらの方針に統一するのが分かりやすいと思いました。

**Comment by ousttrue** [comment]
無いです

**Comment by hiroj** [comment]
spec v1.0ではmaterialIndex参照に変更されます。
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#materialvaluebind
