### ISSUE TITLE
VRMエクスポート時、メッシュに対する重複したjointを除去

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#643]
### 問題 Is your feature request related to a problem? Please describe.

SkinnedMeshRendererのボーンの参照が重複していると、以下のような不正なVRMが出力されます。
https://cdn.discordapp.com/attachments/511077066628661271/795472624934846474/AliciaSolid_vrm-0.51-invalid.vrm

このVRMファイルを[VRoid Hub](https://hub.vroid.com/)へアップロードしようとすると、以下のエラーが表示されます。
> バリデーションに失敗しました: VRMファイルの検証に失敗しました。
> [{"error":"invalid_vrm","errors":["The property '#/skins/0/joints' contained duplicated array values in schema skin.schema.json : [36, 37, 103, 38, 104, 39, 105, 40, 106, 41, 107, 58, 50, 54, 46, 42, 108, 112, 120, 116, 124, 59, 51, 55, 47, 43, 109, 113, 121, 117, 125, 60, 52, 56, 48, 44, 110, 114, 122, 118, 126, 61, 53, 57, 49, 45, 111, 115, 123, 119, 127, 62, 63, 64, 129, 128, 33, 34, 35, 2, 8, 3, 36, 129, 128, 33, 34, 35, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12, 7, 2, 33, 8, 3, 27, 29, 13, 15, 31, 17, 19, 23, 21, 25, 34, 28, 30, 14, 16, 32, 18, 20, 24, 22, 26, 35, 36, 129, 128, 2, 33, 8, 3, 27, 29, 13, 15, 31, 17, 19, 23, 21, 25, 28, 30, 14, 16, 32, 18, 20, 24, 22, 26, 2, 33, 27, 29, 13, 15, 31, 17, 19, 23, 21, 25, 28, 30, 14, 16, 32, 18, 20, 24, 22, 26, 2, 27, 29, 13, 15, 31, 17, 19, 23, 21, 25, 28, 30, 14, 16, 32, 18, 20, 24, 22, 26, 64, 87, 65, 66, 68, 67, 91, 90, 100, 62, 63, 64, 96, 85, 87, 89, 102, 65, 66, 68, 67, 97, 69, 91, 86, 88, 90, 98, 70, 99, 100, 64, 96, 85, 87, 89, 101, 102, 65, 66, 68, 67, 92, 69, 77, 91, 86, 88, 90, 93, 70, 78, 94, 71, 79, 100, 95, 72, 80, 73, 81, 74, 82, 75, 83, 76, 84, 63, 64, 65, 68, 67, 97, 98, 99, 100, 62, 36, 64, 96, 85, 87, 65, 66, 68, 67, 91, 86, 88, 90, 100, 64, 65, 66, 68, 67, 91]","The property '#/skins/1/joints' contained duplicated array values in schema skin.schema.json : [36, 37, 103, 38, 104, 39, 105, 40, 106, 41, 107, 58, 50, 54, 46, 42, 108, 112, 120, 116, 124, 59, 51, 55, 47, 43, 109, 113, 121, 117, 125, 60, 52, 56, 48, 44, 110, 114, 122, 118, 126, 61, 53, 57, 49, 45, 111, 115, 123, 119, 127, 62, 63, 64, 129, 128, 33, 34, 35, 2, 8, 3, 36, 129, 128, 33, 34, 35, 2, 8, 3, 9, 4, 10, 5, 11, 6, 12, 7, 2, 33, 8, 3, 27, 29, 13, 15, 31, 17, 19, 23, 21, 25, 34, 28, 30, 14, 16, 32, 18, 20, 24, 22, 26, 35, 36, 129, 128, 2, 33, 8, 3, 27, 29, 13, 15, 31, 17, 19, 23, 21, 25, 28, 30, 14, 16, 32, 18, 20, 24, 22, 26, 2, 33, 27, 29, 13, 15, 31, 17, 19, 23, 21, 25, 28, 30, 14, 16, 32, 18, 20, 24, 22, 26, 2, 27, 29, 13, 15, 31, 17, 19, 23, 21, 25, 28, 30, 14, 16, 32, 18, 20, 24, 22, 26, 64, 87, 65, 66, 68, 67, 91, 90, 100, 62, 63, 64, 96, 85, 87, 89, 102, 65, 66, 68, 67, 97, 69, 91, 86, 88, 90, 98, 70, 99, 100, 64, 96, 85, 87, 89, 101, 102, 65, 66, 68, 67, 92, 69, 77, 91, 86, 88, 90, 93, 70, 78, 94, 71, 79, 100, 95, 72, 80, 73, 81, 74, 82, 75, 83, 76, 84, 63, 64, 65, 68, 67, 97, 98, 99, 100, 62, 36, 64, 96, 85, 87, 65, 66, 68, 67, 91, 86, 88, 90, 100, 64, 65, 66, 68, 67, 91]"]}]

以下は、同じ状態になっているVRMファイルを添付してVRoid Hubへ問い合わせた返答の抜粋です。

> 頂いたデータをUniVRM 0.62.0でインポートしたところ、単一のSkinnedMeshRendererに同一のボーンが重複登録されている箇所がありました。例えば"vrm-mesh"というGameObjectのSkinnedMeshRenderer.bonesには、"Chest"などのボーンが複数個登録されています。 その状態でUniVRMでVRMエクスポートをした場合、下記のVRMの仕様に違反するデータが出力されてしまいます。
> https://github.com/KhronosGroup/glTF/blob/fa4e11c77c906362f8ac3a22506c4d07f27fcb20/specification/2.0/schema/skin.schema.json#L23
> (glTF 2.0の仕様ですが、VRMはglTF 2.0の仕様にも準拠する必要があります)

### 追加する機能 Describe the solution you'd like
GLB/VRMエクスポート時に、このような状態になっているSkinnedMeshRendererを正規化し、正常なVRMが出力されるようにできないでしょうか。

### 記録内容の変更の有無 Requirement to update gltf
なし

**Comment by ousttrue** [comment]
以下のステップが必用

* SkinnedMeshRenderer.bones をから重複を除去する
* Mesh.boneWeights の joint の index ずれを解決する
* Mesh.bindposes を SkinnedMeshRenderer.bones と同じ順番・長さにする
