### ISSUE TITLE
colliderGroupのoffset座標のz軸のシリアライズについて

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#65]
OpenGL系でなくunity系の座標のままシリアライズされているように思うのですが、いかがでしょうか。
https://3d.nicovideo.jp/works/td44058 をuni0.45で出力しなおしたものを拙作(https://github.com/iCyP/VRM_IMPORTER)で インポートし、そのままエクスポートするとｺﾗｲﾀﾞｰのZ軸が逆になってしまいます。ｺﾗｲﾀﾞｰの座標変換のみz軸を*-1して出力するとDLしたVRMと同じｺﾗｲﾀﾞｰの位置に戻ります。ご確認お願い致します。

**Comment by ousttrue** [comment]
確かに。
ちょっと、対応を考えます。
ひとまず、左手系のまま出てしまっているところをJsonSchema等に明示します。

**Comment by iCyP** [comment]
won't fixなのか、spec x.x で修正予定なのかの段取りが付くのであれば、予告していただけると助かります。

**Comment by hiroj** [comment]
こちらのパラメータは spec v1.0 でOpenGL系に統一されます。
特別指定が無い場合は座標系は右手系になります。
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft
