### ISSUE TITLE
Unity非再生中にScene画面のモデルにVRMBlendShapeClipを適用できるようにしてほしい

### ISSUE THREAD

**Issue by kuni-0930** [vrm-c/UniVRM#658]
SkinnedMeshRenderer.SetBlendShapeWeightのような再生中でなくてもweightを反映できるようにして欲しいです。
proxy.AccumulateValue()→proxy.Apply()は停止中ではScene画面のモデルに適用できないようなので要望を出しました。
また、反映したものをクリアするメソッドも欲しいです。

**Comment by ousttrue** [comment]
何故、proxy が play 中に動かないかというと

* AwakeやStartで初期化する変数を中で持っているので、Play中でないと変数を変更できない。Play中でないときに動かそうとすると、状態管理が難しいトリッキーな実装が必要になる。
* Play中でないときに変更する => Editor で Asset を変更するという意味合いが強いです
  * BlendShapeClip のマテリアル変更が含まれているものを適用して元に戻さないと、対象の Material が変わったままになってしまう
  * シーンにダーティフラグ(Ctrl-Sすると保存される状態)がついてしまう

などです。
故意に動かないようになっています。

https://vrm.dev/docs/univrm/blendshape/univrm_bake_blendshape/
で代用できるか検討してみてください。

Editor 時に Scene に適用したい用途は何しょうか？

**Comment by kuni-0930** [comment]
情報ありがとうございます。
諸々の理由で(動かさない)ようにしている件、理解できました。
BlendShape単体であればBlendShapeBindの情報でSkinnedMeshRendererにセットすることは可能だと思っていましたが、マテリアルを戻すのが大変なのですね。

用途としてはUnityを再生していない時にフェイスモーションキャプチャでVRMBlendShapeClipを動かすことが出来れば、モーションキャプチャの動き具合を見ながらリアルタイムにVRMBlendShapeClipの調整が出来ると考えたからです。

明確な回答が得られたのでcloseさせて頂きます。
ありがとうございました。

**Comment by ousttrue** [comment]
逆に Play中に VRMBlendShapeClip を変更して反映できるとよいかもしれないですね。
そうすれば、Play中に変更して反映できる機能を作れるので。
現状、初期化が複雑で後から変わった Clip 値を反映できなかったような気がします。
参考になりました。

**Comment by ousttrue** [comment]
#666
