### ISSUE TITLE
Inconsistent `VRMSpringBoneColliderGroup` scaling behaviour

### ISSUE THREAD

**Issue by emilianavt** [vrm-c/UniVRM#673]
**Describe the bug**

The behaviour of the `VRMSpringBoneColliderGroup` does not seem to be consistent when first created in a game object with a scale not equal to 1, 1, 1. In the editor it scales along with object after setting it, even if this would lead to an inconsistent result (e.g. a collider in a 1, 1, 1 sphere with a radius of 0.5 shown to cover exact sphere). When exporting a scaled object with a collider on it, the radius of the collider seems to be divided by some component of the scale, even though it still shows the original value.

**To Reproduce**

1. Take a basic VRoid VRM model
2. Add a sphere to the Root bone
3. Set the sphere's scale to 0.5, 0.5, 0.5
4. Add a `VRMSpringBoneColliderGroup`
5. Set the radius of the collider to 0.5
6. Note that the purple sphere of the collider matches the sphere
    1. Optional:
    2. Use the scale tool to scale the sphere to 1, 1, 1
    3. Note that the collider gizmo still matches the sphere, while the collider radius is still 0.5
    4. Press Ctrl+Z to reset the scale to 0.5, 0.5, 0.5
7. Export using UniVRM 0.63.2
8. Import the file
9. The sphere on the imported VRM has a scale of 1, 1, 1 and looks the same size as the 0.5, 0.5, 0.5 sphere, as expected
10. The collider has a radius of 0.5, as expected
11. The collider gizmo shows it to be twice as big as the visible sphere mesh, so the collider is actually as big as an unscaled 1 1, 1 sphere and collision tests confirm this

**Expected behavior**

The collider radius gives an absolute scale in world coordinates and is not influenced by the scaling of the object.

**Screenshots**

Original collider:
![ColliderBeforeExport](https://user-images.githubusercontent.com/38952746/104530013-5542c400-560b-11eb-97a0-272c2e404f8c.png)

Settings and gizmo after export:
![ColliderAfterExport](https://user-images.githubusercontent.com/38952746/104530017-57a51e00-560b-11eb-97c3-9a370bd82d11.png)

Comparison of both:
![ColliderAfterExportBoth](https://user-images.githubusercontent.com/38952746/104530020-596ee180-560b-11eb-9517-b381f4083f5a.png)

Comparison of both in play mode:
![ColliderAfterExportPlayback](https://user-images.githubusercontent.com/38952746/104530099-86bb8f80-560b-11eb-8cf4-e30e9dad4876.png)

The sphere arcs on both models have spring bones set to collide with the collider.

**Environments (please complete the following information):**

 - OS: Windows 8.1
 - Unity version: Unity 2019.4.16f1
 - UniVRM version: 0.63.2

**Comment by ousttrue** [comment]
The current SpringBone are implemented so that all nodes can be exported in a normalized state.
It makes it easier to implement the exporter.
Please export (normalize) before setting the spring, then set the spring and export again.

In the future, we plan to fix it so that it works without normalization.

**Comment by emilianavt** [comment]
For now, could a warning be added when exporting spring bone colliders without normalized nodes? I encountered this while investigating a report somebody made to me about colliders not working correctly.

**Comment by ousttrue** [comment]
Implemented support for SpringBone collider scaling during normalization.
Please try the next version `v0.66.0`.

**Comment by emilianavt** [comment]
Thank you, the collider is now exported the way it is shown!
