### ISSUE TITLE
UniVRM0.64 で GLTF のアニメーションが動くものと動かないものがある

### ISSUE THREAD

**Issue by fantom1x** [vrm-c/UniVRM#678]
**バグについて**

https://github.com/vrm-c/UniVRM/issues/657
の修正で一部の GLTF のアニメーションが動くようになりましたが、なぜか動かないものが多数存在します（UniVRM0.62 では全て動きます）。

エディターでも見てみましたが、エラー等は出てないようです。

ちなみに、GLB や VRM に付いているアニメーションは正常に動いてます。

**再現方法**

とりあえず、UnVRM0.64 付属の SimpleViewer で読み込めば、動くものと動かないものがあるのがわかります。
以下にいくつかの例を挙げておきます（zip のままロードでも可）。

(UniVRM0.64 でも動くもの)
https://sketchfab.com/3d-models/endless-floor-vr-a543fe201f4c458ba16b81f1c5cf2055
https://sketchfab.com/3d-models/looping-snow-2-939d059c7a43424f93c3e8e44e1d5489
https://sketchfab.com/3d-models/tropical-island-f91862f8c38b481aa19edccac851eefb
https://sketchfab.com/3d-models/ancient-temple-185d333942a84565b11087f92a336a79

(UniVRM0.64 では動かないもの)
https://sketchfab.com/3d-models/extra-destination-034ce3253d424ca5b4f431063c40351d
https://sketchfab.com/3d-models/pflow-practice-music-spread-4877a06236ae4b76baa48b2735bbdaad
https://sketchfab.com/3d-models/shadow-dance-16c43f2db9ee414388df62292aa52730
https://sketchfab.com/3d-models/henry-stickmin-e85d8a103eab4ef1bae1a52d9b6878fb
https://sketchfab.com/3d-models/bullet-physics-animation-9-reconstruction-ed7088cb742a43e18aeb73dac4508c75
https://sketchfab.com/3d-models/cat-practice-ancient-space-guy-6dc665f607374fc89385668e2ccc4a5d
https://sketchfab.com/3d-models/spartan-armour-mkv-halo-reach-57070b2fd9ff472c8988e76d8c5cbe66
(※動かないものの方が多い)

※UniVRM0.62 では全て動きます。

**期待する動作**

UniVRM0.62 以前と同様に動く

**スクリーンショット**

(UniVRM0.62 での動作)

https://user-images.githubusercontent.com/8603961/104813070-1e0e2600-584a-11eb-9957-56c4f728bd4b.mp4

(UniVRM0.64 での動作)

https://user-images.githubusercontent.com/8603961/104813082-29615180-584a-11eb-8c24-1c227370aec1.mp4

**環境情報**

 - OS: Windows 10 x64
 - Unity version: Unity-2019.4
 - UniVRM version: 0.64

**追加の状況・背景**

ここでは UniVRM0.62 の SImpleViewer にも zip のロード(switch文)を追加してテストしてます。

**Comment by ousttrue** [comment]
![missing](https://user-images.githubusercontent.com/68057/105661780-9d1df100-5f11-11eb-94cb-eb72b9c9913f.jpg)

調査中・・・

**Comment by ousttrue** [comment]
GLTFの無名ノードに適当な名前を付ける対策

**Comment by fantom1x** [comment]
なるほど、名無しのノードがある/なしで動かなかったり、動いてたりしていたんですね…。
UniVRM0.66 で動作確認できました。
いつも対応ありがとうございます。
