### ISSUE TITLE
Rendere is null - after removing a mesh from an imported vrm

### ISSUE THREAD

**Issue by ilker-aktuna** [vrm-c/UniVRM#680]
I am editing a vrm file on Unity. I removed a mesh and added another one.
Now when I want to export it back to vrm, I get an error [VRMFirstPerson] CharName Renderers(9).Renderer is null. It won't let me export. 
how can we remove the renderer totally ? (from UI) 
I don't want that mesh anymore , so no renderer is required.
But the VRM exporter gives such error.

steps to reproduce:
1. import a vrm.
2. delete a mesh object from hierarchy
3. optionally add a new mesh
4. try to export vrm

- OS: Windows 10
 - Unity version: Unity-2019.4.18f1
 - UniVRM version: 0.64.0_920c

**Comment by FMS-Cat** [comment]
@ilker-aktuna Check your `VRM First Person` on the root level of your model, you might be specifying the missing mesh from the array `Renderer` !
We should make the error message more specific though.

**Comment by ilker-aktuna** [comment]
thanks. I don't know how but now the error has disappeared and the VRM is exported.
so I am not able to check...
but if it happens again, you suggest to check on the root of the model  , VRM First Person component.
which parameter to check ?

**Comment by ousttrue** [comment]
`VRM First Person` can not detect hierarchy modification at real time.

Click the ⚙️  button in the upper right corner of the `VRMFirstPerson` Pop-up menu,
![manual reset](https://user-images.githubusercontent.com/68057/105665619-c8590e00-5f1a-11eb-9e01-c34e1a795c70.jpg)
`reset` can Find all `renderer` in the VRM hierarchy and set `Auto`.

**Comment by ilker-aktuna** [comment]
thanks. I will try this next time I got this error.

**Comment by ousttrue** [comment]
![reset_renderer_btn](https://user-images.githubusercontent.com/68057/105804652-aecfc900-5fe3-11eb-8327-d2dfa08f064f.jpg)
Added `reset` button on export dialog 😃

**Comment by ousttrue** [comment]
`v0.65.0`
