### ISSUE TITLE
Using UniVRM with Universal Render Pipeline

### ISSUE THREAD

**Issue by ilker-aktuna** [vrm-c/UniVRM#683]
I am trying to import a VRM to a Universal Render Pipeline project.
UNIVRM package is added as usual.
When I add my VRM file to assets it just doesn't get the textures. The mesh is all pink like there's no textures added to it.

To reproduce:
1. add UniVRM package to a new Universal Render Pipeline project.
2. import a vrm asset

OS: Windows 10
Unity version: Unity-2019.4.18f1
UniVRM version: 0.64.0_920c

**Comment by Junioreddn** [comment]
how I can solve this, I have the same problem

**Comment by Santarh** [comment]
duplicate issue #368
