### ISSUE TITLE
error CS0103: The name 'MToon' does not exist in the current context

### ISSUE THREAD

**Issue by Bloaky** [vrm-c/UniVRM#684]
**Describe the bug**

When trying to import UNI-vrm into fresh project, getting multiple errors to do with "Mtoon".

**To Reproduce**

Drag into project folder.

If there are some minimal examples(e.g. model files) to reproduce the behavior, please attach them to this issue.

**Expected behavior**

**Screenshots**

![unityerrorvrm](https://user-images.githubusercontent.com/77817701/105435803-fb8c6a80-5c98-11eb-8abd-10a7c6b07ec2.png)

**Environments (please complete the following information):**

 - OS: `Windows 10`
 - Unity version:  `Unity-2018.4`
 - UniVRM version: `0.64.0`

**Additional context**

plz help

**Comment by ousttrue** [comment]
You may have created a `git clone` .
In that case, you need `git submodule update --init` .

**Comment by PoChang007** [comment]
The submodule (MToon) needs to be updated if you cloned/download the repo.
Import UniVRM package into a Unity project should not have this problem.

https://vrm.dev/en/docs/univrm/install/univrm_install/

**Comment by PoChang007** [comment]
This issue will be closed. Feel free to re-open it if you still get stuck on UniVRM import.

Thanks,
