### ISSUE TITLE
Unity 2020.2.2f1 でプレハブからVRM出力できない

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#688]
**バグについて**

Assets上のプレハブを選択して「Export UniVRM-0.64.0」を押すと、以下のエラーが表示され、Exportボタンが押せない

> Z+ 向きにしてください

**再現方法**

1. Unity 2020.2.2f1 で新規3Dプロジェクトを作成する
2. UPMで以下のURLを追加
    - https://github.com/vrm-c/UniVRM.git?path=/Assets/VRMShaders#v0.64.0
    - https://github.com/vrm-c/UniVRM.git?path=/Assets/UniGLTF#v0.64.0
    - https://github.com/vrm-c/UniVRM.git?path=/Assets/VRM#v0.64.0
3. [AliciaSolid_vrm-0.51.vrm](https://github.com/vrm-c/UniVRM/blob/v0.64.0/Tests/Models/Alicia_vrm-0.51/AliciaSolid_vrm-0.51.vrm)をダウンロードして、インポートする
4. Assets上の `AliciaSolid_vrm-0.51.prefab` を選択した状態で、「VRM0」→「Export UniVRM-0.64.0」を選択

**期待する動作**

プレハブから直接VRMをエクスポートできる

**スクリーンショット**

![](https://user-images.githubusercontent.com/3625160/105621613-cfb1e600-5e4c-11eb-930a-6a2677dcfbd9.png)

**環境情報**

 - OS: `Windows 10`
 - Unity version: `Unity-2020.2.2f1`
 - UniVRM version: `0.64.0`

**追加の状況・背景**

ヒエラルキー上のプレハブインスタンスは、Unity 2020.2.2f1でもエクスポートできます。

**Comment by ousttrue** [comment]
Unityの挙動が変わったようです。

`OpenPrefab` して、Hierarchy の方を選択した場合はエクスポートできました。
スクリプトから `OpenPrefab` する必要ができたのかもしれない。
スクリプトから `OpenPrefab` できるのか。

**Comment by ousttrue** [comment]
https://forum.unity.com/threads/open-prefab-scene-view-via-script.667165/

**Comment by ousttrue** [comment]
`v0.69.0`
