### ISSUE TITLE
materialPropatiesでシリアライズされるパラメータについて

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#69]
VRMシリアライザをblenderアドオンとして作る際、unityEditor上に出てこない内部のパラメータまで定義しないと表示が正しくない（透過されない等）がありました。

VRMﾌｫｰﾏｯﾄとして持つべきはマテリアルの本質的な部分のみで、そこからのマテリアル初期化はuniVRM側で処理するべきと思います。　そうでなければ、uniVRM以外からのVRM出力は難しいですし、出来たとしてもunity内部向けのパラメータの更新の追随を要求されるのはプラットフォーム非依存とは言えないと思います。

**Comment by ousttrue** [comment]
MToonで固有のMaterial拡張を作るなど検討

**Comment by hiroj** [comment]
spec v1.0ではmaterial拡張にパラメータが書き込まれるようになります。
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_materials_mtoon-1.0_draft/MToon_comparision.md
