### ISSUE TITLE
vrm import export caused model file validation fail at Vroid Hub

### ISSUE THREAD

**Issue by ilker-aktuna** [vrm-c/UniVRM#694]
I had to make a change on one of my models which was exported using UniVRM
So I imported it to a new project , made the change and exported again.
Actually I slightly modified the pose of the model for a perfect T-pose.
But the new exported model is not accepted by Vroid Hub.
I get the error:

```
Validation failed: model file validation failed.
[{"error":"invalid_vrm","errors":["The property '#/blendShapeMaster/blendShapeGroups/2/presetName' value \"ı\" did not match one of the following values: unknown, neutral, a, i, u, e, o, blink, joy, angry, sorrow, fun, lookup, lookdown, lookleft, lookright, blink_l, blink_r in schema vrm.blendshape.group.schema.json : \"ı\""]}]
```

I did not change anything other than the pose of the model.
"ı" is a character used in my locale for lower "I"  where in English locale lower "I" is "i"
so is this something I can fix ?

I need to change other settings on my model before publishing. So I did not try importing and exporting the model using English locale.

**Comment by ousttrue** [comment]
This issue can occur with ToLower in the Turkish locale

**Comment by ousttrue** [comment]
`v0.65.1`
