### ISSUE TITLE
standardシェーダーの取り扱いについて

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#70]
https://github.com/dwango/UniVRM/wiki/ReleaseNote-v0.44(ja)#vrm-unlit%E3%81%A8standard%E3%83%9E%E3%83%86%E3%83%AA%E3%82%A2%E3%83%AB%E3%81%AB%E9%96%A2%E3%81%97%E3%81%A6%E3%81%AFvrm%E9%83%A8%E3%81%AB%E9%87%8D%E8%A4%87%E3%81%97%E3%81%9F%E6%83%85%E5%A0%B1%E3%82%92%E4%BF%9D%E5%AD%98%E3%81%97%E3%81%AA%E3%81%84%E4%BB%95%E6%A7%98%E5%A4%89%E6%9B%B4
　にて、standardシェーダーはgltfで記述可能なため、省略する旨記載されています。しかし、unity2018.2 のstrandard shaderではsecondary map やheight mapの項目があるのですが、gltfのmaterialのみではそれらの情報が失われます。

**Comment by ousttrue** [comment]
> GLTFで記述可能

というのが筆が滑ったかもしれません。
マイルドな文言を心がけようと思います。

**Comment by PoChang007** [comment]
返事大変遅くなって、すみません。gltf側からUnity Standardをサポートしてますのパラメータを足しました
