### ISSUE TITLE
MeshUtility Validation.cs のコンパイルエラー

### ISSUE THREAD

**Issue by seibe** [vrm-c/UniVRM#701]
**バグについて**

非エディタ環境 (UNITY_EDITOR定義がない状況)で、コンパイルエラーになる

**再現方法**

1. UniVRM を含むプロジェクトをビルドする
2. 次のエラーが表示され、ビルドに失敗する  
`Library\PackageCache\com.vrmc.unigltf@cfec160f4a\MeshUtility\Runtime\Validation.cs(53,13): error CS0103: The name 'Extended' does not exist in the current context`

**期待する動作**

コンパイルエラーは発生せず、ビルドに成功する

**環境情報**

 - OS: Windows 10
 - Unity version: Unity-2019.4.18f1
 - UniVRM version: 0.65.1

**追加の状況・背景**

この問題を修正する PR #702 を提出しました

**Comment by ousttrue** [comment]
`v0.65.2`
