### ISSUE TITLE
Oculus環境においてSingle Pass Instancedだと右目にだけVRMShaderがレンダリングされない

### ISSUE THREAD

**Issue by yahagi-day** [vrm-c/UniVRM#729]
**バグについて**

UniVRMと[Oculus Integration](https://assetstore.unity.com/packages/tools/integration/oculus-integration-82022?locale=ja-JP)を使用したVR開発環境下において、Oculusの「Stereo Rendering Mode」を「Single Pass Instanced」に設定した場合VRMShaderが使われているオブジェクトが右目にだけ描画されなくなる。

[Stereo Rendering Mode](https://developer.oculus.com/documentation/unity/unity-single-pass/?locale=ja_JP)について

**再現方法**

1. 空のプロジェクトを作成し、UniVRMと[Oculus Integration](https://assetstore.unity.com/packages/tools/integration/oculus-integration-82022?locale=ja-JP)をImportします
2. SceneにAssets/Oculus/VR/Prefabs/OVRCameraRigを配置します。
3. SceneにVRMShaderをセットアップしたモデル(アリシア・ソリッドなど)を配置します。
4. Edit/Project Settings... を開き、XR Plug-in Management/Oculusを開きます。
5. Stereo Rendering ModeをMulti PassからSingle Pass Instancedに変更します。
6. OculusデバイスをPCに接続しEditor上でPlayします。

**期待する動作**

Single Pass InstancedでもVRMShaderでセットアップされたモデルが正しく描画される

**スクリーンショット**

![image](https://user-images.githubusercontent.com/32870950/107024973-1825b800-67ec-11eb-9648-7458fe7f0418.png)
左目にはCameraでキャプチャした映像のRenderTextureでQuadに貼り付けた鏡（Unlit/Texture)とアリシア・ソリッドが見えているが、右目には鏡しか描画されていない。

![image](https://user-images.githubusercontent.com/32870950/107025052-34c1f000-67ec-11eb-8dba-07016b10d3b2.png)
Multi Passでは両目に正しく描画されている。

**環境情報**

- OS:Windows10
- Unity version: 2019.4.18f1
- UniVRM version: 0.65.2
- Oculus Integration 23.1.0

**Comment by ousttrue** [comment]
`v0.70.0`
