### ISSUE TITLE
glb import fails with "Bone index is not within the number of bones"

### ISSUE THREAD

**Issue by infosia** [vrm-c/UniVRM#741]
**Describe the bug**

glb import fails with "Bone index is not within the number of bones".

**To Reproduce**

1. Download glTF model file -> [xbot.glb](https://github.com/infosia/themachinery-issues/blob/master/0012/xbot.glb)
2. Check downloaded glTF file is valid (e.g. Open it in Windows 3D Viewer)
2. Launch Unity, select `UniGLTF` -> `Import (gltf,glb)` from menu
2. Choose `xbot.glb`.
3. Import fails with following error

```
Bone index is not within the number of bones.
UnityEditor.AssetDatabase:CreateAsset(Object, String)
UniGLTF.UnityPath:CreateAsset(Object) (at Assets/UniGLTF/Runtime/UniGLTF/IO/UnityPath.cs:404)
UniGLTF.ImporterContext:SaveAsAsset(UnityPath) (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs:977)
UniGLTF.<>c__DisplayClass2_0:<ImportDelayed>b__0() (at Assets/UniGLTF/Editor/UniGLTF/gltfAssetPostprocessor.cs:66)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()
```

**Expected behavior**

Import does not fail and show a figure like below

![Capture](https://user-images.githubusercontent.com/1661068/107718956-68d07000-6d1a-11eb-9c1c-54d0d1d43599.PNG)

**Screenshots**

Actual (In Unity Editor preview):

![Capture2](https://user-images.githubusercontent.com/1661068/107719035-9d442c00-6d1a-11eb-941f-a58e3e9ecf7b.PNG)

**Environments (please complete the following information):**

 - OS: Windows 10
 - Unity version: Unity 2019.4.10f1
 - UniVRM version: UniVRM-0.66.0_39d5

**Comment by ousttrue** [comment]
TODO:

fix
`var joints0 = ctx.GLTF.GetArrayFromAccessor<UShort4>(prim.attributes.JOINTS_0); // uint4`

**Comment by ousttrue** [comment]
`v0.68.0`
