### ISSUE TITLE
Imported glb model faces wrong direction

### ISSUE THREAD

**Issue by infosia** [vrm-c/UniVRM#742]
**Describe the bug**

Imported glb model faces wrong direction.

**To Reproduce**

1. Download glTF model file -> [CesiumMan.glb](https://github.com/infosia/themachinery-issues/blob/master/0006/CesiumMan.glb)
2. Check downloaded glTF file is valid (e.g. Open it in Windows 3D Viewer)
2. Launch Unity, select `UniGLTF` -> `Import (gltf,glb)` from menu
2. Choose `CesiumMan.glb`.
3. Imported glb model faces wrong direction. Front and back faces are reversed

![Capture](https://user-images.githubusercontent.com/1661068/107719619-01b3bb00-6d1c-11eb-9b5a-f2eeaa39072b.PNG)

**Expected behavior**

Imported model faces front direction

![Capture2](https://user-images.githubusercontent.com/1661068/107719820-6ec75080-6d1c-11eb-822f-b3910deaf21d.PNG)

**Environments (please complete the following information):**

 - OS: Windows 10
 - Unity version: Unity 2019.4.10f1
 - UniVRM version: UniVRM-0.66.0_39d5

**Comment by FMS-Cat** [comment]
I believe it's working as intended? Note that z axis in Unity is opposite from glTF's one.
Is this a regression?

**Comment by infosia** [comment]
Seems like it's not a regression (Tested old UniGLTF and it did the same) I would expect that asset importer is taking care of final coordinate accordingly based on asset's coordinate system 🤔 For instance [UnityGLTF](https://github.com/KhronosGroup/UnityGLTF) does the coordinate fix accordingly (and fixes the face direction), I believe Unity's fbx importer does that too...I would expect that's what importers would do :hushed:

**Comment by ousttrue** [comment]
とりあえず右手系(GLTF)・左手系(Unity)の変換をするために (x, y, -z) という変換をしています。
今から変えると、過去のデータが突然反対向きになるので混乱しそうです。
とりあえず import/export の関数に x反転か、z反転かを明示する引数を追加するところまでが限界。

**Comment by infosia** [comment]
VRM 1.0 で https://github.com/vrm-c/vrm-specification/issues/205 が対応されれば glTF も自然と正面を向きそうな気がしますしインポータの挙動の変更もメジャーバージョンアップのタイミングがいいかもしれませんね。

**Comment by ousttrue** [comment]
importer / exporter が座標変換オプションを持って、ユーザーが用途に応じて選択できるようにします。
デフォルトは vrm0 の仕様に合わせて z-reverse 、これを UniVRM の実装仕様とします。

|  | runtime import | asset import | runtime export |editor export|
|:--|:--|:--|:--|:--|
|glb| #747 選択できるようにする(defaultはz-reverse)| #733 で選択できるようにする(defaultはz-reverse)| #747 選択できるようにする(defaultはz-reverse)| #746 dialogを新設し選択できるようにする(defaultはz-reverse)|
|vrm0|z-reverse が仕様|z-reverse が仕様|z-reverse が仕様|
|vrm1 https://github.com/vrm-c/vrm-specification/issues/205 |x-reverse が仕様|x-reverse が仕様|x-reverse が仕様|

**Comment by TokageItLab** [comment]
[#223](https://github.com/vrm-c/vrm-specification/issues/223) でも書きましたが恐らく KhronosGroup/UnityGLTF の X-Flip が正規の実装であり vrm0 仕様の Z-Flip は間違っています...。厳密には UniGLTF の Z-Flip 後の 180 度回転が内部的に適用できていなかったのが問題（例として blender だと回転後にトランスフォームを適用していない状態を変換の最終形としてしまったような状態）です。

**Comment by infosia** [comment]
glTF のドキュメントには `The front of a glTF asset faces +Z` と記載されています [Coordinate System and Units](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#coordinate-system-and-units)。 なので glTF で +Z を向いている方がアセットの正面であり、インポータの挙動としては UnityGLTF のように Unity でも正面を向くように変換するのが期待されると思います。

**Comment by ousttrue** [comment]
#755, #888 で実装
