### ISSUE TITLE
UPM の Scoped Registry 対応

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#743]
バージョンアップなどを行いやすいように、UPMのScoped Registryに対応できないでしょうか。
https://docs.unity3d.com/ja/current/Manual/upm-scoped.html

**Comment by ousttrue** [comment]
今のところ、自前でサーバーを立てる予定はありません。
特定のサーバーにオフィシャルとして登録するのも現状そぐわない感じです。
