### ISSUE TITLE
Shape keys broken after exporting fbx to vrm

### ISSUE THREAD

**Issue by lordtitankronos** [vrm-c/UniVRM#751]
Model was exported from blender 2.90 to fbx file. After importing fbx to Unity and exporting with UniVRM (tested with versions 0.53.0, 0.59.0, 0.66.0), some of the shape keys became broken. 

Example1 original shape key: 
![image](https://user-images.githubusercontent.com/19216104/108345519-545c0e00-7219-11eb-8560-9a1efc5b2ebb.png)

Example 1 after exporting with UniVRM: 
![image](https://user-images.githubusercontent.com/19216104/108346081-f7148c80-7219-11eb-8a09-edc3d668b428.png)

Example 2 original shape key:
![image](https://user-images.githubusercontent.com/19216104/108346420-507cbb80-721a-11eb-80b6-e648e6024328.png)

Example 2 after exporting with UniVRM: 
![image](https://user-images.githubusercontent.com/19216104/108346487-638f8b80-721a-11eb-8e60-df433c9a42ec.png)

**Comment by ousttrue** [comment]
It is difficult to guess and fix the problem with just the screenshots.
