### ISSUE TITLE
Saving SpringBone to JSON does not work in 0.66

### ISSUE THREAD

**Issue by shantih19** [vrm-c/UniVRM#753]
Saving SpringBones to JSON produces no result. No error/warning, no files are created.

**To Reproduce**

1. Select Avatar in Hierarchy
2. Open VRM0 dropdown
3. Select SaveSpringBonetoJSON
4. Select folder to save to, no folder seems to work
5. Nothing happens

**Expected behavior**

On previous versions, a VRMSpring.JSON file was created.

**Environments:**

 - OS: Windows 10 64bit
 - Unity version: Tested in both 2018.4.20f1 and 2019.4.9f1
 - UniVRM version: 0.66

**Comment by ousttrue** [comment]
`v0.68.0`
