### ISSUE TITLE
ユニティのアニメーションを再生時に肩が下がります。

### ISSUE THREAD

**Issue by jtrpc** [vrm-c/UniVRM#779]
VRoidキャラクターモデル（基本キャラクターモデルもどれでも）を抽出します。
ユニティにインポートします。
mixamoに公開されたアニメーションやその他の一般的なキャラクタアニメーションを適用してみます。
再生時、相対的に肩の位置が下に降りていきます。
最初から肩の位置を上げる補正をしてくださることができませんか？

**Comment by jtrpc** [comment]
他の場所で生成された文字のモデルは、カスタムオーダーメイドモデルは、コイカツモデリングなどから抽出した文字モデルは肩の位置が正常に再生されます。有毒VRoidでunivrmに変換抽出モデリングだけアニメーションを再生するときに肩がすごく下がって見えます。非常に障害のあるキャラクターモデルのように見えます。

**Comment by ousttrue** [comment]
I can't say anything because it's not specific about which Unity method to use to apply the animation.
