### ISSUE TITLE
"An item with the same key has already been added. Key: Shader_NoneNormal.png.001"  

### ISSUE THREAD

**Issue by Roseweave** [vrm-c/UniVRM#782]
**Describe the bug**

Whenever I try to import VRMs made in Blender, this error occurs. 

**To Reproduce**

Import a model(at least my model) made in blender. 

If there are some minimal examples(e.g. model files) to reproduce the behavior, please attach them to this issue.

**Expected behavior**

The model to import 

**Environments (please complete the following information):**

Windows 10, 
Unity 2019.4.22f1 
UniVRM-0.67.1

**Comment by jtrpc** [comment]
ArgumentException: An item with the same key has already been added. Key: Shader_NoneNormal
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UniGLTF.TextureFactory.TryGetExternal (UniGLTF.GetTextureParam param, System.Boolean used, UnityEngine.Texture2D& external) (at Assets/UniGLTF/Runtime/UniGLTF/IO/TextureLoader/TextureFactory.cs:62)
UniGLTF.TextureFactory+<GetTextureAsync>d__14.MoveNext () (at Assets/UniGLTF/Runtime/UniGLTF/IO/TextureLoader/TextureFactory.cs:157)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
VRM.MToonMaterialItem+<CreateAsync>d__1.MoveNext () (at Assets/VRM/Runtime/IO/VRMMaterialImporter.cs:76)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UniGLTF.MaterialFactory+<LoadMaterialsAsync>d__18.MoveNext () (at Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialLoader/MaterialFactory.cs:157)
--- End of stack trace from previous location where exception was thrown ---
UniGLTF.ImporterContextExtensions.Load (UniGLTF.ImporterContext self) (at Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContextExtensions.cs:23)
VRM.vrmAssetPostprocessor+<>c__DisplayClass1_0.<ImportVrm>b__0 (System.Collections.Generic.IEnumerable`1[T] texturePaths) (at Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs:55)
UniGLTF.TextureExtractor+<>c__DisplayClass15_0.<ExtractTextures>b__0 () (at Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/TextureExtractor.cs:179)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)


I come out the same way.

**Comment by ousttrue** [comment]
#786 may have resolved the problem.
Please try `v0.68.1`.

**Comment by ousttrue** [comment]
Please try v0.68.2.

**Comment by PoChang007** [comment]
If the problem still exists, feel free to reopen this issue.

Thanks,
