### ISSUE TITLE
Unity 2020.3.0f1でglbのインスペクターが表示されない

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/UniVRM#783]
**バグについて**

プロジェクトウィンドウでglbファイルを選択しても、インスペクターに何も表示されず、エラーが発生する。

**再現方法**

1. Unity 2020.3.0f1 で新規3Dプロジェクトを作成する
2. 以下のUPMに従いUniVRM-0.68.0を導入  
    https://github.com/vrm-c/UniVRM/releases/tag/v0.68.0
3. [DamagedHelmet.glb](https://github.com/KhronosGroup/glTF-Sample-Models/blob/0bc2ad7535aba4e16fb1afba1f85fd827bbbea6d/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb)をダウンロードして、プロジェクトウィンドウへドラッグ&ドロップ
4. プロジェクトウィンドウのDamagedHelmetを選択
5. インスペクターウィンドウに何も表示されず、以下のエラーが繰り返し発生する
    > NullReferenceException: Object reference not set to an instance of an object
6. プロジェクトウィンドウの選択を解除すると、以下のエラーが発生する
    > GlbScriptedImporterEditorGUI.OnEnable must call base.OnEnable to avoid unexpected behaviour.

**期待する動作**

インスペクターウィンドウに、https://vrm.dev/docs/univrm/gltf/glb_import/ と同様のGUIが表示される。

**スクリーンショット**

![](https://user-images.githubusercontent.com/3625160/111020121-ddc0c380-8406-11eb-8bc0-3e57fe939ba5.png)

**環境情報**

 - OS: `Windows 10`
 - Unity version: `Unity-2020.3.0f1`
 - UniVRM version: `0.68.0`

**追加の状況・背景**

発生する3つのエラー

> NullReferenceException: Object reference not set to an instance of an object
UnityEditor.AssetImporters.AssetImporterEditor.DrawImporterSelectionPopup () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.AssetImporters.AssetImporterEditor.OnHeaderControlsGUI () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.Editor.DrawHeaderGUI (UnityEditor.Editor editor, System.String header, System.Single leftMargin) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.Editor.DrawHeaderGUI (UnityEditor.Editor editor, System.String header) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.Editor.OnHeaderGUI () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.Editor.DrawHeader () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.UIElements.EditorElement.DrawEditorLargeHeader (UnityEditor.Editor[] editors, System.Boolean& wasVisible) (at <1d96ce257f0e45ff836d157d33fd933d>:0)
UnityEditor.UIElements.EditorElement.DrawEditorHeader (UnityEditor.Editor[] editors, UnityEngine.Object target, System.Boolean& wasVisible) (at <1d96ce257f0e45ff836d157d33fd933d>:0)
UnityEditor.UIElements.EditorElement.HeaderOnGUI () (at <1d96ce257f0e45ff836d157d33fd933d>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

> NullReferenceException: Object reference not set to an instance of an object
UnityEditor.AssetImporters.AssetImporterEditor.DrawImporterSelectionPopup () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.AssetImporters.AssetImporterEditor.OnHeaderControlsGUI () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.Editor.DrawHeaderGUI (UnityEditor.Editor editor, System.String header, System.Single leftMargin) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.Editor.DrawHeaderGUI (UnityEditor.Editor editor, System.String header) (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.Editor.OnHeaderGUI () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.Editor.DrawHeader () (at <50f55621a2ca4f31a35283e2979a8bf5>:0)
UnityEditor.UIElements.EditorElement.DrawEditorLargeHeader (UnityEditor.Editor[] editors, System.Boolean& wasVisible) (at <1d96ce257f0e45ff836d157d33fd933d>:0)
UnityEditor.UIElements.EditorElement.DrawEditorHeader (UnityEditor.Editor[] editors, UnityEngine.Object target, System.Boolean& wasVisible) (at <1d96ce257f0e45ff836d157d33fd933d>:0)
UnityEditor.UIElements.EditorElement.HeaderOnGUI () (at <1d96ce257f0e45ff836d157d33fd933d>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.UIElements.IMGUIContainer.DoIMGUIRepaint () (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.UIElements.UIR.RenderChainCommand.ExecuteNonDrawMesh (UnityEngine.UIElements.UIR.DrawParams drawParams, System.Single pixelsPerPoint, System.Exception& immediateException) (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
Rethrow as ImmediateModeException
UnityEngine.UIElements.UIR.RenderChain.Render () (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.UIElements.UIRRepaintUpdater.Update () (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase phase) (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.UIElements.Panel.UpdateForRepaint () (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.UIElements.Panel.Repaint (UnityEngine.Event e) (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <1cdf5c2cc10149169242b9590b7ebb6b>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <c44e24cb7b9d4e5096e65a3281e887f5>:0)

> GlbScriptedImporterEditorGUI.OnEnable must call base.OnEnable to avoid unexpected behaviour.
UnityEditor.AssetImporters.AssetImporterEditor:OnDisable ()

**Comment by ousttrue** [comment]
2020 LTS になったので #688 と一緒に対応します。

**Comment by ousttrue** [comment]
https://docs.unity3d.com/ScriptReference/AssetImporters.AssetImporterEditor.html

`base.OnEnable` の呼び出しが必要になったぽい。

**Comment by ousttrue** [comment]
`v0.69.0`
