### ISSUE TITLE
NotImplementedException error

### ISSUE THREAD

**Issue by KingWolfInk** [vrm-c/UniVRM#785]
**Describe the bug**

Cannot import the VRM prefab to set up the blendshapes because it gives me this error, and I cannot figure out why;
NotImplementedException: The method or operation is not implemented.
UniGLTF.UnityPath.GetAssetFolder (System.String suffix) (at Assets/UniGLTF/Runtime/UniGLTF/IO/UnityPath.cs:181)
VRM.VRMEditorImporterContext.ConvertAndExtractImages (UniGLTF.UnityPath assetPath, System.Action`1[T] onTextureReloaded) (at Assets/VRM/Editor/Format/VRMEditorImporterContext.cs:154)
VRM.VRMImporterMenu.ImportMenu () (at Assets/VRM/Editor/Format/VRMImporterMenu.cs:77)

**To Reproduce**
I don't think this will really be any good without the specific files I'm using, which I don't know if I can attach.

**Expected behavior**

Import the VRM prefab

**Screenshots**

https://gyazo.com/9a8e923f1733fbb35effd2626f07ddba
https://gyazo.com/661d270077fff4f0581050220ff52776

**Environments (please complete the following information):**

 - OS: Windows 10
 - Unity version: Unity 2019.4.16f1
 - UniVRM version: v0.68.0

**Additional context**

I don't know if I can add the files I'm using, it's a VRChat avatar that I'm converting to VRM. I've done this before with no issues but this time it just won't work.

**Comment by ousttrue** [comment]
This issue occurs when the vrm and the path where the asset is created are different.
For example
From `C: / some.vrm`` C: / Projects / Assets / some.prefab`
Occurs in the `VRM0 / import` menu.

Workaround
DnD` * .vrm` in the folder inside the asset.

**Comment by VensyMeow** [comment]
What does "DnD" mean?

I was experiencing the same issue as OP, and when I attempt to add the *.vrm into the Asset folder, it simply gives me an error stating 

![image](https://user-images.githubusercontent.com/80720002/111221134-53f43000-8597-11eb-93cf-b4b715d80941.png)

It does not generate all the folders it would normally create, only the textures folder and doesn't create a prefab. If I then try to import the *.vrm from inside the Assets folder I get this error

![image](https://user-images.githubusercontent.com/80720002/111221228-71c19500-8597-11eb-87e2-626e8d350b67.png)

**Comment by ousttrue** [comment]
`DnD` is `drag and drop`.

`An item with the same key has already been added` may fixed #786 .

Please try `v0.68.1`.

**Comment by ousttrue** [comment]
Please try `v0.68.2`.

**Comment by KingWolfInk** [comment]
Using v0.68.2 but it still does the same thing

**Comment by ousttrue** [comment]
fix `v0.69.0`.

`v0.68.2` Workaround
Drag and drop * .vrm to unity `Assets`

**Comment by x3256** [comment]
I was getting the same error, fixed it by creating another folder inside the **asset** folder and import the model there.

**Comment by flarn2006** [comment]
Why is this issue closed? Just because there's a workaround doesn't mean the problem is solved; IMO the issue should remain open until either 1) importing directly into Assets works with no errors, or 2) the error message is made more user-friendly, so people don't need to search in closed issues to figure out what to do.

**Comment by ControlCoreAngel** [comment]
Confirming issue is still occurring. Above workaround works, but still not a fix.
