### ISSUE TITLE
DisposeOnGameObjectDestroyed() を呼び出すと、VRMBlendShapeProxy による値の変更ができない

### ISSUE THREAD

**Issue by kechako** [vrm-c/UniVRM#794]
**バグについて**

`VRMImporterContext` を使用して VRM ファイルをロードした際に、`VRMImporterContext.DisposeOnGameObjectDestroyed()` を呼び出すと、`BlendShapeAvatar.Clips` の全ての要素が削除され、`VRMBlendShapeProxy` による値の変更ができなくなります。

**再現方法**

```csharp
var parser = new GltfParser();
parser.ParsePath(file);

using (var context = new VRMImporterContext(parser))
{
    await context.LoadAsync();

    context.EnableUpdateWhenOffscreen();
    context.ShowMeshes();

    var proxy = context.Root.GetComponent<VRMBlendShapeProxy>();

    Debug.LogFormat("Clips: {0}", proxy.BlendShapeAvatar.Clips.Count);
    // => Clips: 19

    context.DisposeOnGameObjectDestroyed();

    Debug.LogFormat("Clips: {0}", proxy.BlendShapeAvatar.Clips.Count);
    // => Clips: 0

    return context.Root;
}
```

あくまでワークアラウンドとしてですが、`DisposeOnGameObjectDestroyed()` を呼び出す前に、`VRMImporterContext.BlendShapeAvatar` プロパティをダミーのオブジェクトで差し替えると、回避できます。

**期待する動作**

`BlendShapeAvatar.Clips` の要素が削除されない。

**スクリーンショット**

Unity 上で実行中、Inspector に BlendShape の全てのパラメーターが表示されません。

<img width="300" alt="unity-inspector" src="https://user-images.githubusercontent.com/1865660/111311415-8f7b2100-86a1-11eb-9580-eb74c1b717da.png">

**環境情報**

 - OS: `macOS BigSur 11.2.2`
 - Unity version: `Unity-2019.4.16f1`
 - UniVRM version: `0.68.1`

**追加の状況・背景**

特に無し

**Comment by ousttrue** [comment]
`v0.68.2` で修正しました。

**Comment by kechako** [comment]
`v0.68.2` にて確認致しました。
対応ありがとうございます 👍

**Comment by ousttrue** [comment]
👍
