### ISSUE TITLE
UniVRM import Error

### ISSUE THREAD

**Issue by nwnisworking** [vrm-c/UniVRM#808]
**Describe the bug**

The import for UniVRM is not working and it displays an error message on GLTF

**To Reproduce**

e.g. Steps to reproduce the behavior:

1. Go to 'VRM0'
2. Click on 'Import'
3. Choose any vrm file to import 
4. Error + Warning message shows

If there are some minimal examples(e.g. model files) to reproduce the behavior, please attach them to this issue.

**Expected behavior**

3D model is suppose to appear after importing.

**Screenshots**

![image](https://user-images.githubusercontent.com/66354122/111920293-1cbadd00-8ac9-11eb-88db-08957a3c406b.png)

**Environments (please complete the following information):**

 - OS: Windows 10
 - Unity version: Unity-2019.4
 - UniVRM version: v0.68.2

**Comment by ousttrue** [comment]
This is the same issue as #785

fix v0.69.0.

v0.68.2 Workaround
Drag and drop * .vrm to unity Assets
