### ISSUE TITLE
GLTF

### ISSUE THREAD

**Issue by critchupitty** [vrm-c/UniVRM#820]
Hi, 
I am seeing these errors when I select UniGLTF > Generate Deserializer or Generate Serializer. I am not even clear on the function but I believe it should extract the sub-asset (meshes) from my GLB asset after import. 

DirectoryNotFoundException: Could not find a part of the path "F:\GLTFtest\fullVRM\Assets\UniGLTF\UniGLTF\Scripts\IO\GltfDeserializer.g.cs".
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
System.IO.File.Open (System.String path, System.IO.FileMode mode) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UniGLTF.DeserializerGenerator.GenerateSerializer () (at Assets/UniGLTF/Editor/UniGLTF/Serialization/DeserializerGenerator.cs:48)

**Comment by PoChangSu** [comment]
This issue has been transferred to UniVRM repo.

**Comment by ousttrue** [comment]
`Generate Deserializer` or `Generate Serializer` require gltf JsonSchema.

![submodule](https://user-images.githubusercontent.com/68057/113388292-ec2c4a80-93c8-11eb-8807-ba7abeb11bb8.jpg)
`only glTF require`

* `Assets\UniGLTF\Runtime\UniGLTF\Format\GltfDeserializer.g.cs`
* `Assets\UniGLTF\Runtime\UniGLTF\Format\GltfSerializer.g.cs`

is generated.
