### ISSUE TITLE
Imported glTF model not rendered correctly

### ISSUE THREAD

**Issue by infosia** [vrm-c/UniVRM#821]
**Describe the bug**

Imported glTF model is not rendered correctly

**To Reproduce**

1. Download [readyplayerme-feminine.000.glb](https://github.com/infosia/readyplayerme-Tpose/blob/main/models/readyplayerme-feminine.000.glb)
2. Check if downloaded glTF model is valid (i.e https://gltf-viewer.donmccurdy.com/)
3. Drag & drop glb model into Unity
4. Imported glTF model rendered incorrectly

**Expected behavior**

![Capture2](https://user-images.githubusercontent.com/1661068/112416446-08950b00-8d69-11eb-8c00-152aaa9ad58f.PNG)

**Actual screenshot**

![Capture](https://user-images.githubusercontent.com/1661068/112416451-0af76500-8d69-11eb-90f5-c7352de65980.PNG)

**Environments (please complete the following information):**

 - OS: Windows 10
 - Unity version: Unity-2019.4.10f1
 - UniVRM version: v0.69.1

**Comment by ousttrue** [comment]
Issue:
`WEIGHTS_0` implemented only `float4`

TODO:
Implement UNSIGNED_BYTE and UNSIGNED_SHORT version.

**Comment by ousttrue** [comment]
`v0.70.0`
