### ISSUE TITLE
I try to export a glb at runtime and save it on the server, is that possible?

### ISSUE THREAD

**Issue by Tripl3Design** [vrm-c/UniVRM#824]
Is it possible to write a script to export a unity mesh to a .glb file and store it on the server using webGL?

**Comment by ousttrue** [comment]
UniVRM can perform vrm & glb RuntimeExport.

UniVRM-samples.unitypackage contains sample scene.

Assets/VRM.Samples/Scenes/VRMRuntimeExporterSample.unity
https://github.com/vrm-c/UniVRM/blob/master/Assets/VRM.Samples/Scripts/VRMRuntimeExporter.cs#L85

For glb, a little change is needed.
