### ISSUE TITLE
SpringBone mess up the hair

### ISSUE THREAD

**Issue by Amyzinq** [vrm-c/UniVRM#825]
So I've recently gotten into making my own character for VR and i use an outdated version of UNITY because of UniVRM as I need to use that, Before, I used UniVRM 0.53.0_6b07 and the hair didnt mess up this way, everything worked as it should! But whenever I exported the VRM file and tried using it in a Capture Software to see my character in action, the hairs didn't move as they should. And ive recently updated my UniVRM to 0.69.0_8739 and whenever I add springbones to the hairs and enter Play Mode the hair fucks up - and when i export this fucked up version, the hair moves but as you could imagine.. it fucks up there too!

**Does anyone have a solution to stop the hairs from doing this AND/OR get the hair to actually move whenever i export it!**

https://user-images.githubusercontent.com/81399164/112568685-243cf780-8de3-11eb-858d-2abfda07a37c.mp4

https://user-images.githubusercontent.com/81399164/112569035-c066fe80-8de3-11eb-8330-4fe11f652bc1.mp4

**Comment by ousttrue** [comment]
Yellow collision detection that does not overlap the hair indicates that the original model is not normalized.
Try setting the yellow sphere to overlap the hair in the inspector and re-export.

This issue may be related
https://github.com/vrm-c/UniVRM/issues/567

**Comment by ousttrue** [comment]
If you have any problems with the latest version, please report it again.
