### ISSUE TITLE
インポート後にコンパイルエラーが発生します。

### ISSUE THREAD

**Issue by ponpopon** [vrm-c/UniVRM#827]
**バグについて**
UniVRMインポート後、以下のエラーが発生します。

Assets/UniGLTF/UniHumanoid/Editor/Tests/BvhLoaderTests.cs(1,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)

Assets/UniGLTF/UniHumanoid/Editor/Tests/BvhLoaderTests.cs(127,10): error CS0246: The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets/UniGLTF/UniHumanoid/Editor/Tests/BvhLoaderTests.cs(127,10): error CS0246: The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)

**再現方法**
1. UniVRMをダウンロード
2. ダウンロードしたUniVRM-0.69.1_0ece.unitypackageをUnityのプロジェクト欄にドラッグ&ドロップ
3. パッケージをインポート

**期待する動作**
このエラーに伴い、Please fix compile errors before creating new state のエラーが起きるため、コンパイルエラーが起きないようにして欲しいです。

**環境情報**
 - OS: [MacOS BigSur 11.2.3]
 - Unity version: [Unity-2019.4.11f1]
 - UniVRM version: [0.69.1]

**Comment by ousttrue** [comment]
古い UniVRM を上書きしていないかご確認ください。
その場合、 アンインストールしてから import しなおしてみてください。
https://vrm.dev/docs/univrm/install/univrm_uninstall/ 

Unity では場所が変わったが同じと見なされるファイルを import する場合に、古い場所に残ります。
import 参照の解決ができなくなることがあります。
念のために一度削除してから import しなおすことをお勧めしております。
