### ISSUE TITLE
Blendshape error with VRM model

### ISSUE THREAD

**Issue by Amyzinq** [vrm-c/UniVRM#828]
Ok so i recently got into making my own VTuber Character, I used blendshapes from time to time in Unity and I haven't struggled with it before! But as I am currently changing my mind about my character all the time i try out different hairstyles ect - which makes me redo the work and put it into Unity again, i haven't changed ONE THING about the way i do it - I haven't pressed any buttons... but somehow everytime i go to configure the blendshapes this happened 

https://user-images.githubusercontent.com/81399164/112735878-d7762f80-8f4e-11eb-944b-6c4016df1333.mp4

this only happens when i change the levels of the blendshape, it doesn't start out like this! 

I thought it may be the hair i am using with the character, so i removed it and just uploaded a BASE model - but it still happens! Ive tried googling the solution and haven't found anything... Sorry if the solution is OBVIOUS! 

Please help!

xoxo

Amy!

**Comment by ousttrue** [comment]
Please Look at https://vrm.dev/en/docs/univrm/blendshape/check_blendshape_normal/

**Comment by PoChang007** [comment]
If the problem still exists, feel free to reopen this issue.

Thanks,

**Comment by PoChang007** [comment]
related to #415 #597

**Comment by blzq** [comment]
自分のモデルで試みたらエックスポート時に「Divide Vertex Buffer」をチェックするとこの問題は発生しませんけど、チェック外すと必ず発生します。

FBXインポートの「Legacy Blend Shape Normals」もこの様な問題は発生しないけれど、それは恐らく自分のFBXモデルはBlend Shape Normalsを含みません（Blenderで作ったので）。

**Comment by ousttrue** [comment]
エクスポート時にBlendShapeの法線が必用か不要かをデータから判断するのが難しいです(もともと無かったものでもデフォルト値や0値が詰められてデータとしては存在してしまう)。
`OnlyBlendshapePosition` (BlendShapeの法線を出力しない) も効くかもしれないので試してみてください。

**Comment by blzq** [comment]
申し訳ありません、前コメントで上手く説明いたしなかった気がします。

Blenderに作ったBlendShape (Shape key)をFBXとしてエックスポートすると、Blenderの制約によるBlendShapeの法線は共にエクスポートされていない（[ここのT46019](https://developer.blender.org/T68575)、BlendShapeの法線は「存在しない」か「０値」かはわかりません）。それで、UnityにFBXをインポートする際、BlendShapeの影を正しく表示できるためにCalculate Blend Shape Normalsを行うのほうが望ましいと思います。そうすると自分の試しの限り、FBXモデルのBlendShape法線は上手く表示されます。

そして、UniVRMで再エックスポートとインポートを行うと、最初コメントのような問題は発生します。でも、「Divide Vertex Buffer」をチェックすると問題は発生しません（元のFBXインポートのCalculate Blend Shape Normalsをチェックしても発生しません）。

ここからは勝手な推理ですが、恐らくLegacy Blend Shape NormalsをチェックするとBlendShapeの影がすこしおかしくなる原因は、Legacy Blend Shape Normalsによる０値のBlendShape法線がそのままキープしてしまっていますかな。そして０値の因果でバッグの発生はあっても見えないかもしれない。
