### ISSUE TITLE
UniVRM in Japanese

### ISSUE THREAD

**Issue by KetsukiAce** [vrm-c/UniVRM#832]
I have attempted to translate but I cannot is there any possible way to get a translated version of univrm?

**Comment by PoChang007** [comment]
Any picture attached here will help us better understand your question.

If you are talking about the language displayed in Meta/Export, you can switch between Japanese and English in vrm exporter dialog. 

Thanks,

**Comment by PoChang007** [comment]
language localization has been added since `0.73.0`.
feel free to reopen this issue if this solution is not you are looking for.

thanks,
