### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by Sagie15** [vrm-c/UniVRM#833]
NullReferenceException: Object reference not set to an instance of an object
VRM.VRMMetaEditor.OnInspectorGUI () (at Assets/VRM/Editor/Meta/VRMMetaEditor.cs:26)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <fc4e84dee5004858ad88e6706bb25889>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Qinoha** [comment]
I'm experiencing this issue as well, using v2019.4.19f1
Code listed in the error is as follows (line 26 markerd with a *):

 ```
using UnityEditor;


namespace VRM
{
    [CustomEditor(typeof(VRMMeta))]
    public class VRMMetaEditor : Editor
    {
        Editor m_Inspector;
        SerializedProperty m_VRMMetaObjectProp;

        private void OnDestroy()
        {
            UnityEditor.Editor.DestroyImmediate(m_Inspector);
        }

        private void OnEnable()
        {
            m_VRMMetaObjectProp = serializedObject.FindProperty(nameof(VRMMeta.Meta));
            m_Inspector = Editor.CreateEditor(m_VRMMetaObjectProp.objectReferenceValue);
        }

        public override void OnInspectorGUI()
        {
            EditorGUILayout.PropertyField(m_VRMMetaObjectProp);
*            m_Inspector.OnInspectorGUI();
        }
    }
}

```

**Comment by ousttrue** [comment]
`v0.71.0`

**Comment by pixelhustler** [comment]
I am still experiencing this error on export using 2020.3.18
