### ISSUE TITLE
ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by Rivaryn** [vrm-c/UniVRM#836]
Having trouble exporting the model with the following error using UniVRM 0.70.0:

ArgumentNullException: Value cannot be null.
UniGLTF.TextureExporter+ExportKey..ctor (UnityEngine.Texture src, UniGLTF.glTFTextureTypes type) (at Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/TextureExporter.cs:26)
UniGLTF.TextureExporter.ExportMetallicSmoothnessOcclusion (UnityEngine.Texture metallicSmoothTexture, System.Single smoothness, UnityEngine.Texture occlusionTexture) (at Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/TextureExporter.cs:163)
(I can provide the full error if needed but that's the first lines.)

I changed all of the materials on the model to use the VRM/MToon shader, but that didn't help solve the issue.  Any assistance would be much appreciated.

Thanks.

**Comment by ousttrue** [comment]
This issue occurs when the standard shader has only occurrenceTexture (no metallicSmoothTexture).

**Comment by phioalchemist** [comment]
Like Rivaryn, I get the following error and cannot export the VRM.
I am not using oclusionTexture for Material.

ArgumentNullException: Value cannot be null.
UniGLTF.TextureExporter+ExportKey..ctor (UnityEngine.Texture src, UniGLTF.glTFTextureTypes type) (at Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/TextureExporter.cs:26)

**Comment by ousttrue** [comment]
#838 で修正しました

|metallic|occlusion|error|
|-|-|-|
|null|null||
|〇|〇||
|〇|null|error|
|null|〇|error|

`v0.71.0` です。

**Comment by ousttrue** [comment]
Please try `v0.71.0`
