### ISSUE TITLE
SphereCollider ctor make lot of gc

### ISSUE THREAD

**Issue by Personuo** [vrm-c/UniVRM#843]
SphereCollider ctor use Mathf.Max(x,y,z), this function will generate a lot of gc,
pls Fix it to Mathf.Max(Mathf.Max(x,y),z);
thank you.

**Comment by Personuo** [comment]
Similarly, I found this problem in (VRMSpringBoneColliderGroup.UniformedLossyScale), but since this is not executed under update, it doesn't seem to have much effect

**Comment by ousttrue** [comment]
`public static float Max(params float[] values);` cause array GC

**Comment by ousttrue** [comment]
Fixed in `v0.72.0`
