### ISSUE TITLE
正規化を繰り返すと足が内側に移動する

### ISSUE THREAD

**Issue by m2wasabi** [vrm-c/UniVRM#87]
正規化エクスポートを繰り返すと足が内側・外向きに移動するようです

> 一次情報：https://twitter.com/mkt_/status/1067032357327134720

**Comment by ousttrue** [comment]
分かりにくいのですが、`繰り返し正規化` は避けてください。
一度だけ正規化し、以降は正規化せずにエクスポートしてください(2回目以降と判定された場合は、正規化のチェックボックスが外れるようになっている)。

ToDo: UIに直接説明を表示

**Comment by m2wasabi** [comment]
承知しました。

**本来想定されない** ユースケースですが、VRMモデルを改造する人がいると、
 `VRM` -(FBX Exporter)-> `FBX` -(Blender)-> `Blender` -(Blender)-> `FBX` -(UniVRM)-> `VRM`
とした場合、チェックボックスに関わりなく2回の正規化が適用される気がします。

このあたりの取り扱いについて、ドキュメントで保証外の動作と言及されるべきなのかと思います。

**Comment by ousttrue** [comment]
T-Pose正規化周りが情報不足なのでドキュメント強化します。

https://github.com/dwango/UniVRM/wiki/T-Pose%E3%81%A8%E3%83%A2%E3%83%87%E3%83%AB%E3%81%AE%E6%AD%A3%E8%A6%8F%E5%8C%96%E3%81%AE%E8%A9%B3%E7%B4%B0

ひとまずこちらで先に更新します。
