### ISSUE TITLE
[仕様要望]name属性全般の文字について

### ISSUE THREAD

**Issue by iCyP** [vrm-c/UniVRM#88]
jsonにおけるname属性全般において、半角英数字,アンダーバーのみに限定する制約仕様を希望します。
少なくとも、\  , . + ? / % $ | < > などの文字は除外されている方が扱いやすくなるのでないかと思います。
ご検討をお願いします。

**Comment by ousttrue** [comment]
既に存在してしまっているので変え辛いのですが、
実際問題、ファイルにする前にリネームせざるを得なかったりするのでなんらか検討したいと思います。
UIで非推奨文字列として警告するなど

**Comment by FMS-Cat** [comment]
GLTF本体のspecにおいては、これを特別禁止するような制限は存在しないため、難しいかと思います。
一方で、ASCIIセット以外の文字（日本語など）は禁止されていたりします…………
もちろん、VRM拡張部については我々がこのルールに必ず従う必要はないと思います。

See: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#json-encoding

**Comment by vyv03354** [comment]
> 一方で、ASCIIセット以外の文字（日本語など）は禁止されていたりします…………
> もちろん、VRM拡張部については我々がこのルールに必ず従う必要はないと思います。
> 
> See: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#json-encoding

JSON Encodingの節の 2. は、この仕様(glTF仕様)はプロパティ名やenumなどにASCII文字セットだけを使うと言っているだけで、ユーザーが(`"name"`属性の「値」などで)非ASCII文字を使うことを禁止しているわけではありません。

**Comment by FMS-Cat** [comment]
> Application-specific strings (e.g., values of "name" properties or content of extras fields) may use any symbols.

こちらですね。読み落としておりました。

**Comment by iCyP** [comment]
dup  #https://github.com/vrm-c/vrm-specification/issues/40
