### ISSUE TITLE
Bug on unity

### ISSUE THREAD

**Issue by DelduwathYT** [vrm-c/UniVRM#885]
## Describe the bug

When I want to export my avatar to VRM, some textures don't want to be exported which stops the whole export.

## To Reproduce

e.g. Steps to reproduce the behavior:

1. make the small modifications of the avatar
2. press the export mode of VRM0
3. make the 3 mandatory additions
4. click on export

## Expected behavior

the file should be exportable and recoverable

## Screenshots

![image](https://user-images.githubusercontent.com/82736297/115129411-e730e300-9fe5-11eb-9803-d49b66188fd7.png)

## Environments (please complete the following information):

 - OS: [e.g. `Windows 10`]
 - Unity version: [e.g. `Unity-2018.4`]
 - UniVRM version: [e.g. `0.70.0`]

## Additional context

no

**Comment by ousttrue** [comment]
This is fixed `v0.71.0`. 
#836
Please try `v0.72.0`
