### ISSUE TITLE
Model Export To VRChat

### ISSUE THREAD

**Issue by DemonRem** [vrm-c/UniVRM#907]
i using the feature of vrm to export it as unitypackage
but i have error say "Win32Exception: ApplicationName='git', CommandLine='rev-parse HEAD', CurrentDirectory='F:/VRChatSDK/Assets/VRM', Native error= The system cannot find the file specified

**Comment by PoChang007** [comment]
Hi,

It will be helpful if you can post the full error messages

**Comment by KanaFuyuko** [comment]
For VRM to VRChat, you can use this addon for that case: https://booth.pm/ja/items/1025226
You would package the prefab created by that addon (Along with any assets you wish to package) which you can share as a .unitypackage file. VRChat alone doesn't support VRM models.

**Comment by ousttrue** [comment]
If you have any problems with the latest version, please report it again.
