### ISSUE TITLE
v0.73.0 throws "Mesh not found." exception on export

### ISSUE THREAD

**Issue by oocytanb** [vrm-c/UniVRM#909]
## バグについて

以下のケースで、UniGLTF の Export を行うと、"Mesh not found." 例外が発生します。

- `Mesh Renderer` Component の `Material Size` が `0` のオブジェクトが含まれる場合。

- TextMesh Pro のオブジェクトが含まれる場合。
  (VCI で TextMesh Pro がサポートされていますが、新しい UniVRM を使用すると、VCI のエクスポート時エラーになります。)

## 再現方法

- シーンに上述のオブジェクトを配置し、メニューから `UniGLTF > Export UniGLTF` を実行します。

- 以下の場所で、例外が発生します。
	```
	Exception: Mesh not found.
	UniGLTF.gltfExporter.ExportNode (UnityEngine.Transform x, System.Collections.Generic.List`1[T] nodes, System.Collections.Generic.List`1[T] meshWithRenderers, System.Collections.Generic.List`1[T] skins) (at Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs:166)
	```

- [再現したシーンファイル](https://github.com/vrm-c/UniVRM/files/6366670/test_tmp_nomat.zip)を添付します。

## 期待する動作

正常にエクスポートできることです。

## 環境情報

- OS: Windows 10
- Unity version: 2019.4.14f1
- UniVRM version: 0.73.0

## 追加の状況・背景

UniVRM version 0.72.0 では、問題は発生しません。

**Comment by ousttrue** [comment]
再現確認しました 👀

**Comment by hiroj** [comment]
https://github.com/vrm-c/UniVRM/tree/v0.67.4
v0.73とv0.67.4に修正を入れました
https://github.com/virtual-cast/VCI/releases/tag/v0.32.1
VCIの対応しているUniVRMバージョンをv0.67.4に変更しました

**Comment by ousttrue** [comment]
`v0.74.0` で修正

**Comment by oocytanb** [comment]
対応ありがとうございます。
