### ISSUE TITLE
Blend Shapes not working if fbx to vrm export

### ISSUE THREAD

**Issue by Gigalots** [vrm-c/UniVRM#914]
I'm having this issue for a long time and haven't found a solution yet. this is why i hope someone can help me with this.

I'm exporting a model from vroid studio and importing it to blender to put in some more blendshapes. After that i export it as fbx and importing in into univrm. 

In skin mesh renderer the blendshapes are working just fine but if i export the model, and re- import it to unity the blend shapes dont work at all. they just working if i change the values i the skin mesh renderer.

also the window "blendshapes" in the exporter is blank if that means anything...
![why blank](https://user-images.githubusercontent.com/83218417/116074906-a181b380-a692-11eb-921b-65d75f55b57f.png)

Please help. I'm at the end of my knowledge.
![skinned mesh renderer](https://user-images.githubusercontent.com/83218417/116074568-3c2dc280-a692-11eb-8529-df4b66ea65a3.png)

![after reimport](https://user-images.githubusercontent.com/83218417/116074562-3afc9580-a692-11eb-8d13-301fd3f93495.png)

**Comment by ousttrue** [comment]
Perhaps the `BlendShapeAvatar` in the` VRM BlendShape Proxy` is null.
![avatar_null](https://user-images.githubusercontent.com/68057/116181036-dfdfa700-a754-11eb-9908-fb5193b30d82.gif)

You may be able to recover by setting a blend shape avatar from the asset

![set_avatar](https://user-images.githubusercontent.com/68057/116181565-cab74800-a755-11eb-904a-f46636869488.gif)

If you find out why the blend shape avatar is null, please report it.
https://vrm.dev/en/docs/univrm/

**Comment by Gigalots** [comment]
I am sorry but the blend shape avatar is not null. and it still doesn't move the face. do you have any other ideas what the issue could be?

**Comment by Gigalots** [comment]
I just found my problem. I thought the expressions would show on the model and not the little window on the lower right. 
![i am stupid](https://user-images.githubusercontent.com/83218417/116273557-213a7b80-a782-11eb-844e-1c35c74e57fa.png)
