### ISSUE TITLE
GLTF モデルの Import Setteings で Reverse Axis の設定が常に Preference の設定で上書きされてしまう

### ISSUE THREAD

**Issue by Santarh** [vrm-c/UniVRM#940]
## バグについて

GLTF モデルの Import Setteings で Reverse Axis の設定が常に Preference の設定で上書きされてしまう

## 再現方法

環境
- master branch ( https://github.com/vrm-c/UniVRM/commit/c6bdc4f4ee30017b3dbc0f2994ae607e58dd86c2 ) 

1. Preferences の UniGLTF で Reverse Axis が Z になっていることを確認する
2. GLTF ファイルの Import Settings で Reverse Axis を X にして Apply する
3. 設定が反映されず Z に戻り、モデルも反転しない。

**Comment by ousttrue** [comment]
2018 では動いているぽい？
2019 以降調査 👀

**Comment by ousttrue** [comment]
特に再現しなかった。

https://github.com/vrm-c/UniVRM/blob/master/Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporter.cs#L20-L25

の、 `asset` が常に null になっているぽい。
enum を unknown, z, x の３値にする手があるか。

**Comment by ousttrue** [comment]
`v0.75.0`
