### ISSUE TITLE
There is no consideration for texture mipmaps on exporting glTF.

### ISSUE THREAD

**Issue by Santarh** [vrm-c/UniVRM#947]
## バグについて

glTF 出力時、テクスチャのミップマップ設定が反映されない。

## 再現方法

1. モデルを Windows の 3D ビューワで表示すると [図. 1] のようにミップマップが適切に生成され、輪郭付近のスペキュラが綺麗
2. モデルをテキストエディタで開くと、LeatherPartsMat の Normalmap の `minFilter` が `LINEAR_MIPMAP_LINEAR` になっている

3. モデルを UniGLTF で Import し、そのまま再 Export する
4. 再 Export したモデルを Windows の 3D ビューワで表示すると [図. 2] のように輪郭付近のスペキュラがギザギザ
5. 再 Export したモデルをテキストエディタで開くと、LeatherPartsMat の Normalmap の `minFilter` が `LINEAR` になっている

glTF 2.0 Sample model - FlightHelmet
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/FlightHelmet

## 期待する動作

- Editor での入出力時、Texture Importer Settings の項目が反映される
    - Generate MipMaps が True かどうか
- Runtime での入出力時、`Texture2D` の状態が反映される
    - `Texture2D` の `mipmapCount` が `2` 以上かどうか

## スクリーンショット

[図. 1]
![image](https://user-images.githubusercontent.com/328204/118233867-80f88c80-b4cd-11eb-91cf-71a64b2c0e66.png)

[図. 2]
![image](https://user-images.githubusercontent.com/328204/118233922-94a3f300-b4cd-11eb-87ed-7d23c02aa355.png)

## 環境情報

 - OS: Windows 10
 - Unity version: Unity 2019.4.14f1
 - UniVRM version: ef81a6502cd79cf6dbcfb3ad16e7ce7a515a7740

**Comment by ousttrue** [comment]
| Unity                                              | glTF                                                    |
|----------------------------------------------------|---------------------------------------------------------|
| new Texture2D(mipChain=false).filterMode=Point     | samler.magFilter=NEAREST, minFilter=NEARREST            |
| new Texture2D(mipChain=false).filterMode=Bilinear  | samler.magFilter=LINEAR, minFilter=LINEAR               |
| new Texture2D(mipChain=false).filterMode=Trilinear | samler.magFilter=LINEAR, minFilter=LINEAR               |
| new Texture2D(mipChain=true).filterMode=Bilinear   | samler.magFilter=LINEAR, minFilter=LINEAR_MIPMAP_LINEAR |
| new Texture2D(mipChain=true).filterMode=Trilinear  | samler.magFilter=LINEAR, minFilter=LINEAR_MIPMAP_LINEAR |

🤔

**Comment by ousttrue** [comment]
| Unity =>                           | glTF.sampler =>                   | Unity                              |
|------------------------------------|-----------------------------------|------------------------------------|
| Texture2D.WrapModeU,V = Clamp      | sampelr.wrapS,T = CLAMP_TO_EDGE   | Texture2D.WrapModeU,V = Clamp      |
| Texture2D.WrapModeU,V = Mirror     | sampelr.wrapS,T = MIRRORED_REPEAT | Texture2D.WrapModeU,V = Mirror     |
| Texture2D.WrapModeU,V = Repeat     | sampelr.wrapS,T = REPEAT          | Texture2D.WrapModeU,V = Repeat     |
| Texture2D.WrapModeU,V = MirrorOnce | sampelr.wrapS,T = MIRRORED_REPEAT | Texture2D.WrapModeU,V = MirrorOnce |

glTF では MirrorOnce は無い。

**Comment by Santarh** [comment]
Trilinear は Bilinear へフォールバックしてしまって良いと考えます。
MirrorOnce は Mirror へフォールバックするか、Export 時にエラーとしてしまって良いと考えます。
また Unity は軸ごとに WrapMode を指定できますが、それもエラーとしてしまって良いと考えます。

**Comment by ousttrue** [comment]
修正完了 `v0.75.0`

**Comment by Santarh** [comment]
MipMap 絡む正確な対応関係はこちらっぽい
https://github.com/vrm-c/UniVRM/pull/969#issuecomment-846824582
