### ISSUE TITLE
Exporting VRM Model with FBX attachments resets Look At Bone Applier mapping values

### ISSUE THREAD

**Issue by PrettyFireNOI7** [vrm-c/UniVRM#948]
## Describe the bug

Attaching an fbx model to a vrm model which has been exported once will reset the mapping values in Look At Bone Applier.
## To Reproduce

__State__:
- A __test model__ which has been exported once, format changes from fbx to vrm, is waiting for the second time exporting to become a finished VRM model. 
- An __attachment model__ which is in fbx format and will be attached to the __test model__.

__Steps to repoduce__:
- 1.Open the Prefab of the test model. Drag and drop the attachment model into the hierarchy of the test model,making it a child of certain bone of the test model.
- 2.Set the mapping values in Look At Bone Applier then export the test model.
- 3.Import the finished test model,the reseting of the mapping values in Look At Bone Applier should be seeing.

## Expected behavior

In the case above, the mapping values in Look At Bone Applier shouldn't be reset.

## Files & Screenshots & Elaboration

__Unity Package__: 

[Test_Package.Zip](https://github.com/vrm-c/UniVRM/files/6489188/Test_Package.Zip)

- Contains: 
  - UniVRM 0.74
  - The test model mentiond above, and in different Unity scene it is in different exported state.
  - The test model with a blue attachment that is being a child of Head bone, and in different Unity scene it is in different exported state.

__Project Overview__:
![1](https://user-images.githubusercontent.com/81634162/118397128-1db15a80-b685-11eb-8da2-54bd750512a9.png)

__File Overview__: Model state in different scene is shown as the name of each scene.
![2](https://user-images.githubusercontent.com/81634162/118397188-6537e680-b685-11eb-969b-b139de324c53.png)

__Issue__: In the picture is the finished VRM model which is reimported back to Unity.Its mapping value was set to all 90 but as in the picture the value has been reset.While if now set the value again then export, the values will be reserved.
![3](https://user-images.githubusercontent.com/81634162/118397372-2fdfc880-b686-11eb-80d1-cd491b3b2f45.png)

## Environments :

 - OS: Windows 10
 - Unity version: Unity 2020.3.1f1c1
 - UniVRM version: 0.74

## Additional context

Nothing additional, but thanks for the work on UniVRM.

**Comment by ousttrue** [comment]
I confirmed the reproduction of the problem

**Comment by ousttrue** [comment]
It will be fixed in `v0.75.0`.

**Comment by ousttrue** [comment]
Perhaps the attachment model cause model normalization.
LookAt export bug with model normalization.
