### ISSUE TITLE
Fatal error when trying to import to vrm

### ISSUE THREAD

**Issue by beckwan** [vrm-c/UniVRM#951]
![87872640-14068a00-c9c3-11ea-876d-5b5e9bb5d2e2](https://user-images.githubusercontent.com/84330212/118501665-e09aa600-b720-11eb-88d1-c61dcdedf195.png)

I've been trying to convert to vrm. I'm kind of new to unity but have converted other avatars without this issue. 
I'm running unity 2018 with vrm0.70.0db1b on windows 10

the fatal error says it runs out of memory but I have plenty of available space. I have noticed there is a larger amount of blendshapes than my previous models. 

I have tried to import the vrm file to my desktop and drag into assets but gets the same result. 
 
I will add a link below with the relative files.

https://drive.google.com/drive/folders/1BfIdLMvQw8skAnHUA4S03wZtsC3gCByE?usp=sharing

**Comment by PoChang007** [comment]
Hi,

To avoid out of memory issue (there may be a memory leak in Unity 2018), switch Unity version to Unity 2019.4~

To reduce BlendShape size, apply BlendShape Size Reduction options in VRM export dialog or use MeshUtility (mesh separation).

Reference:
  * https://vrm.dev/en/docs/univrm/export/vrm_size/#options-for-blendshape-size-reduction
  * https://vrm.dev/en/docs/univrm/gltf/mesh_utility/

Related issues: #479 #438 

model test result: [#951_blendshape_size_reduction.zip](https://github.com/vrm-c/UniVRM/files/6494666/951_blendshape_size_reduction.zip)

**Comment by ousttrue** [comment]
If you have any problems with the latest version, please report it again.
