### ISSUE TITLE
[GLTF] Animation読み書き

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/UniVRM#96]
https://github.com/ousttrue/UniGLTF/issues/62

**Comment by hiroj** [comment]
ExporterはLINEARかSTEPのアニメーション出力だけ対応していて、それ以外の場合はLINEARでExportしているために起こっている現象だと思われます。
gltfとしてはCUBICSPLINEでの書き出しが可能なため、unityのAnimationCurveを変換する処理が必要。

**Comment by hiroj** [comment]
UniVRMではアニメーションサポートオプションであるためLINEARとSTEPしか対応していません、要望があれば v1.0で対応致します。
