### ISSUE TITLE
namespace MeshUtilityがUnityEditor.MeshUtility classと競合する

### ISSUE THREAD

**Issue by Narazaka** [vrm-c/UniVRM#973]
## バグについて

- namespace MeshUtilityがUnityEditor.MeshUtilityと競合し、UnityEditor.MeshUtility classを名前空間の修飾無く使っているコードがコンパイルエラーになる。

## 再現方法

- UniVRM 0.74.0をインポート
- UnityEditor.MeshUtilityを名前空間の修飾無く使っているコードを作る

`Assets/Editor/NewBehaviorScript.cs`

```csharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

public class NewBehaviourScript : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        UnityEditor.MeshUtility.Optimize(null);
        MeshUtility.Optimize(null); // error
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
```

![image](https://user-images.githubusercontent.com/1712548/119352441-a90d9a00-bcdc-11eb-8789-27927872c0f9.png)

- 製品の具体例としては Mantis LOD Editor https://assetstore.unity.com/packages/tools/modeling/mantis-lod-editor-professional-edition-37086?locale=ja-JP

![image](https://user-images.githubusercontent.com/1712548/119350050-d3118d00-bcd9-11eb-9b1f-e1135f381235.png)

## 期待する動作

- UnityEditor配下のクラスは修飾して使わないのが一般的であるため、修飾無しで競合するのは行儀が悪いと思います。
- 競合しないように異なる名前空間（`UniGLTF.MeshUtility`等）に切り出すべきだと思います。

## 環境情報

 - OS: `Windows 10`
 - Unity version: `Unity-2018.4`
 - UniVRM version: `0.74.0`

**Comment by ousttrue** [comment]
なるほど。
被りにくい namespace に入れないと優先順位で負けるのか・・・
namespace `MeshUtility` がよろしくない。

**Comment by ousttrue** [comment]
`v0.76.0` で立ち退き
