### ISSUE TITLE
Update 0.74 -> 0.75: namespace UniGLTF already contains definition for IAxisInverter

### ISSUE THREAD

**Issue by lyuma** [vrm-c/UniVRM#992]
## Describe the bug
I'm getting errors like "The namespace 'UniGLTF' already contains a definition for 'IAxisInverter'" after upgrading to UniVRM 0.75.0

It looks like the cause is in commit 22cb1372be04c84bade0b829b3b5de9a6aeba410 , UniGLTF/Runtime/UniGLTF/IO/Axises.cs was renamed to UniGLTF/Runtime/UniGLTF/IO/Axes.cs

At this time, the GUID in the old file was 5b3b7b9629a4da242bacf52f5ca0fd80, and the GUID of the new file is ec65074bc74907c4580348aa0b159411

The problem is, unitypackage does not know when a file is deleted, so my project now has both the old and the new copies of Axises.cs + Axes.cs

## To Reproduce

e.g. Steps to reproduce the behavior:

1. Import UniVRM 0.74
2. Then, import UniVRM 0.75
3. This error occurs while compiling scripts.

## Expected behavior

Ideally, package upgrades would be safe.

This issue might not be easy to fix now that both versions are in the wild. I'm not sure if unitypackages have a process for handling file renames.

For the user, the fix is simple: delete the Axises.cs file from the project. But the error message does not make this obvious.

## Screenshots

From Editor.log:
```
-----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/UniGLTF.dll
Microsoft (R) Visual C# Compiler version 2.9.1.65535 (9d34608e)
Copyright (C) Microsoft Corporation. All rights reserved.

Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(12,22): error CS0101: The namespace 'UniGLTF' already contains a definition for 'IAxisInverter'
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(20,19): error CS0101: The namespace 'UniGLTF' already contains a definition for 'ReverseZ'
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(43,19): error CS0101: The namespace 'UniGLTF' already contains a definition for 'ReverseX'
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(66,25): error CS0101: The namespace 'UniGLTF' already contains a definition for 'AxisesExtensions'
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(45,26): error CS0111: Type 'ReverseX' already defines a member called 'InvertMat4' with the same parameter types
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(50,27): error CS0111: Type 'ReverseX' already defines a member called 'InvertQuaternion' with the same parameter types
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(55,24): error CS0111: Type 'ReverseX' already defines a member called 'InvertVector3' with the same parameter types
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(60,24): error CS0111: Type 'ReverseX' already defines a member called 'InvertVector4' with the same parameter types
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(14,17): error CS0111: Type 'IAxisInverter' already defines a member called 'InvertVector3' with the same parameter types
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(15,17): error CS0111: Type 'IAxisInverter' already defines a member called 'InvertVector4' with the same parameter types
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(16,20): error CS0111: Type 'IAxisInverter' already defines a member called 'InvertQuaternion' with the same parameter types
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(17,19): error CS0111: Type 'IAxisInverter' already defines a member called 'InvertMat4' with the same parameter types
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(22,26): error CS0111: Type 'ReverseZ' already defines a member called 'InvertMat4' with the same parameter types
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(27,27): error CS0111: Type 'ReverseZ' already defines a member called 'InvertQuaternion' with the same parameter types
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(32,24): error CS0111: Type 'ReverseZ' already defines a member called 'InvertVector3' with the same parameter types
Assets\UniGLTF\Runtime\UniGLTF\IO\Axises.cs(37,24): error CS0111: Type 'ReverseZ' already defines a member called 'InvertVector4' with the same parameter types
-----CompilerOutput:-stderr----------
-----EndCompilerOutput---------------
```

## Environments (please complete the following information):

 - OS: Windows 10
 - Unity version: Unity 2018.4
 - UniVRM version: 0.75.0

## Additional context
I did not look for upgrade instructions, because I am lazy, so I just imported the new unitypackage over my existing install.

**Comment by dblatner** [comment]
I think you did not delete the previous package before re-importing/updating to 0.75 ? The AxisInverter C# files were renamed and you can solve it by deleting the old C# files with wrong naming.

**Comment by Santarh** [comment]
For the update, you first uninstall the previous version. And then install the version you want.

https://vrm.dev/en/docs/univrm/install/univrm_install/#before-installation

**Comment by Santarh** [comment]
Unfortunately, the UnityPackage ecosystem is not suitable for C# library updates. 😓
